### PR TITLE
 feat(bitbucket-server): add branch status handling

### PR DESCRIPTION
**Pull request by viceice**
This pr uses the bitbucket server build api to get and set branch states.

This pr superseeds pr #3246

### CODE REVIEW

**Comment by rarkins** [comment]
@ViceIce so should we close #3246 and merge this instead? Or merge #3246 first and then this?

**Comment by ViceIce** [comment]
if you are ok with this feature, we can close #3246, otherwise we should merge #3246 first.

**Comment by ViceIce** [comment]
I'll fix the codecov asap. 😃

**Comment by rarkins** [comment]
I'm fine with this one, let's move forward with it. Thanks!

**Comment by ViceIce** [comment]
Ok, Waiting for check done.

P.S.: I'm preparing a pr to implement comments to bb server.

**Pull request merged**
