### PR TITLE
refactor(autoreplace): set depIndex during flatten

### PR DESCRIPTION
**Pull request by rarkins**
## Context

Avoid needing `depIndex` typing during extract & lookup phases

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — APPROVED** [review]
we've managers which return deps out of order 😕

**Review by secustor — APPROVED** [review]

**Comment by setchy** [comment]
Should all of the `upgrade.depIndex=` be removed from `auto-replace.spec.ts` @rarkins ?

**Comment by rarkins** [comment]
> Should all of the `upgrade.depIndex=` be removed from `auto-replace.spec.ts` @rarkins ?

I didn't think so. They'll still be set prior to autoreplace.  Why do you think?

**Comment by setchy** [comment]
> > Should all of the `upgrade.depIndex=` be removed from `auto-replace.spec.ts` @rarkins ?
> 
> I didn't think so. They'll still be set prior to autoreplace. Why do you think?

all good - realized i misspoke this as soon as i hit enter 🙊 😅

**Pull request merged**
