### PR TITLE
docs(npm): do not use NPM_TOKEN with hostRules

### PR DESCRIPTION
**Pull request by viceice**
## Changes:

Change docs to make clear, `NPM_TOKEN` is not compatible with host rules.

## Context:

This is overriding any host rule, because the auth header is there before any hostrule can apply.
https://github.com/renovatebot/renovate/blob/606dd318816150805bd866c5678f14b7d8229dc4/lib/datasource/npm/get.ts#L121-L127

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by HonkingGoose — CHANGES_REQUESTED** [review]

**Comment by rarkins** [comment]
Should we check for it and log a warning at the start (eg in env parsing) and ideally link to a doc section for what they should do instead?

**Comment by viceice** [comment]
Ok, can try it tomorrow

**Comment by viceice** [comment]
> Should we check for it and log a warning at the start (eg in env parsing) and ideally link to a doc section for what they should do instead?

Can we defer this for another pr? as hostrules can be on shared presets too, so we will miss them on env validation.

**Review by rarkins — APPROVED** [review]

**Comment by viceice** [comment]
> Shared presets can't import from env though

Yes, but env `NPM_TOKEN` can override hostrule from shared preset.

**Pull request merged**
