### PR TITLE
fix: docker hosts

### LINKED ISSUE #3743: Multiple docker hosts in the config file is not supported
### Which Renovate are you using? CLI, App, or Pro
renovate cli

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
gitlab

### Have you checked the logs? Don't forget to include them if relevant
with this in my config.js:
```json
  hostRules: [
    {
      platform: 'docker',
      host:     'myregistry.internal:4567',
      username: 'piail',
      password: '<password>',
    },
    {
      platform: 'docker',
      host:     'docker.io',
    },
  ],
```

I end up with this in platforms object (used in host-rules, I added logs):
```json
       "platforms": {
         "docker": {"platform": "docker", "host": "docker.io"},
         "gitlab": {
           "gitlab.internal": {
             "name": "GitLab",
             "endpoint": "https://gitlab.internal/api/v4/",
             "platform": "gitlab",
             "username": null,
             "password": null,
             "token": "<TOKEN>",
             "default": true
           }
         }
       }
```

See [this discussion](https://github.com/renovatebot/config-help/issues/240) for more details

### PR DESCRIPTION
**Pull request by pyaillet**
Adds test and fix for multiple docker host in config file

Closes #3743

### CODE REVIEW

**Comment by rarkins** [comment]
I now recall that we wanted to be able to support `DOCKER_USERNAME` and `DOCKER_PASSWORD`. These were aimed to simplify things for people who need just one host. I wonder if we can make this fix still work with that approach too?

**Comment by pyaillet** [comment]
Ok, I tested it with `DOCKER_USERNAME=TEST DOCKER_PASSWORD=TEST node ../renovate/dist/renovate.js`
And the results are not good 😅 (see below).

1. Should we affect these credentials to all docker hosts that don't define ones ?
2. When no docker host is passed, should we default it to docker.io ?

```
       "platforms": {
         "docker": {
           "registry.docker.internal:1234": {
             "platform": "docker",
             "host": "registry.docker.internal:1234",
             "username": "internal-user",
             "password": "internal-password"
           },
           "docker.io": {"platform": "docker", "host": "docker.io"},
           "undefined": {"platform": "docker", "username": "TEST", "password": "TEST"}
         },
         "gitlab": {
           "gitlab.internal": {
             "name": "GitLab",
             "endpoint": "https://gitlab.internal/api/v4/",
             "platform": "gitlab",
             "username": null,
             "password": null,
             "token": "token"
           }
         }
       }
```

**Comment by rarkins** [comment]
We need to make a choice about backwards compatibility or not. It's probable that bot owners are using this variable for *either* docker.io *or* their own host (e.g. Artifactory) and we can't be sure which it is.

**Comment by rarkins** [comment]
I don't mind if we say "If you use these environment variables then no other docker host rules can be configured". Would that help?

**Comment by pyaillet** [comment]
Ok so the result would be:
1. some docker hosts are defined in the config file and the platforms structure is as this:
```
"platforms": {
  "docker": {
    "host1": { "host": "host1", ... },
    "host2": { "host": "host2", ... },
  },
}
2. env vars are passed to the cli and the structure is as this:
"platforms": {
  "docker": { "username":  ... },
}

If so, I can propose something :)

**Comment by pyaillet** [comment]
One question though, should one of these option overrides the other ?
Otherwise, the last call to `hostRules.update` will have the last word.

**Comment by rarkins** [comment]
I actually wrote a PR to fix this type of thing but it’s gone stale. I’m thinking of resurrecting it now because of this. Basically it could match more than one rule and the more specific one takes precedence (eg Docker+host beats docker-only)

**Comment by rarkins** [comment]
I think I'd better rewrite these hostRules now rather than us going further down this current path

**Comment by pyaillet** [comment]
Ok !
Is there anything I could do to help you with this ?
But anyway no hurry here.

**Comment by rarkins** [comment]
@pyaillet thanks for your help on this. I decided to rewrite hostRules to be fully flexible the way they should be, there's too much accumulated technical debt right now. I won't merge this PR and will instead include this feature as part of the rewrite, which is underway.

**Comment by pyaillet** [comment]
Thank you !
Let me know if I can help in anyway.

**Pull request closed without merging**
