### PR TITLE
fix(maven): Reject releases only for Maven Central repository

### LINKED ISSUE #32266: extractVersion with postProcessRelease (maven) causes rejected release
### Discussed in https://github.com/renovatebot/renovate/discussions/31886

<div type='discussions-op-text'>

<sup>Originally posted by **remal** October 10, 2024</sup>
### What would you like help with?

I would like help with my configuration

### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us which platform (GitHub, GitLab, etc) and which version of Renovate.

_No response_

### Please tell us more about your question or problem

**Miniumal reproduction repository**: https://github.com/remal/renovate-reproduction-intellij-ideaIC-build-range-eap

### Context
I'm developing an IntelliJ IDEA plugin and would like to configure Renovate to update `pluginUntilBuild` property in the `gradle.properties` file.

### Chosen approach to configure Renovate
1. Configure a RegEx custom manager that processes the `gradle.properties` file.
2. Renovate is supposed to replace a value for the `pluginUntilBuild` property.
3. An updated value should be the last `XXX-EAP-SNAPSHOT` version of `com.jetbrains.intellij.idea:ideaIC` dependency in https://www.jetbrains.com/intellij-repository/snapshots/
4. `XXX-EAP-SNAPSHOT` version should be converted to `XXX` (see `extractVersion`)

### Issue
The property is not updated. An unexpected message can be found in the logs: `DEBUG: Rejected release`

What's wrong? What would you suggest me to change?

### Logs (if relevant)

Full logs: https://developer.mend.io/github/remal/renovate-reproduction-intellij-ideaIC-build-range-eap/-/job/d8b53513-063b-42cc-9d75-400b0665247c

<details><summary>Relevant logs</summary>

```

DEBUG: Looking up com.jetbrains.intellij.idea:ideaIC in repository https://www.jetbrains.com/intellij-repository/snapshots/
DEBUG: hostRules: no authentication for www.jetbrains.com
DEBUG: Using queue: host=www.jetbrains.com, concurrency=16
DEBUG: Found 38 new releases for com.jetbrains.intellij.idea:ideaIC in repository https://www.jetbrains.com/intellij-repository/snapshots/
DEBUG: GET https://www.jetbrains.com/intellij-repository/snapshots/com/jetbrains/intellij/idea/ideaIC/243.19420.21-EAP-SNAPSHOT/maven-metadata.xml = (code=ERR_NON_2XX_3XX_RESPONSE, statusCode=404 retryCount=0, duration=294)
DEBUG: Content is not found for Maven url
{
  "url": "https://www.jetbrains.com/intellij-repository/snapshots/com/jetbrains/intellij/idea/ideaIC/243.19420.21-EAP-SNAPSHOT/maven-metadata.xml"
}

DEBUG: Rejected release
{
  "datasource": "maven"
  "packageName": "com.jetbrains.intellij.idea:ideaIC"
  "registryUrl": "https://www.jetbrains.com/intellij-repository/snapshots"
  "version": "243"
}

DEBUG: PackageFiles.add() - Package file saved for base branch
{
  "baseBranch": "main"
}

DEBUG: Package releases lookups complete
{
  "baseBranch": "main"
}

DEBUG: branchifyUpgrades
DEBUG: detectSemanticCommits()
DEBUG: getCommitMessages
DEBUG: semanticCommits: detected "unknown"
DEBUG: semanticCommits: disabled
DEBUG: 0 flattened updates found: 
DEBUG: Returning 0 branch(es)
DEBUG: config.repoIsOnboarded=true
DEBUG: packageFiles with updates
{
  "baseBranch": "main"
  "config": {
    "regex": [
      {
        "deps": [
          {
            "depName": "intellij-ideaIC-build-range-eap",
            "packageName": "com.jetbrains.intellij.idea:ideaIC",
            "currentValue": "242",
            "datasource": "maven",
            "registryUrls": [
              "https://www.jetbrains.com/intellij-repository/snapshots/"
            ],
            "replaceString": "\nplatformType = IC\nplatformVersion = 2023.3.8\n\n# Supported build number ranges and IntelliJ Platform versions -> https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html\n#pluginSinceBuild = XXX - loaded automatically from `platformVersion`\npluginUntilBuild = 242.*\n\n",
            "updates": [],
            "versioning": "maven",
            "warnings": [],
            "registryUrl": "https://www.jetbrains.com/intellij-repository/snapshots",
            "packageScope": "com.jetbrains.intellij.idea",
            "currentVersion": "242"
          }
        ],
        "matchStrings": [
          "(^|\\n)\\s*platformType\\s*=\\s*IC\\s*(\\n+|$)[\\s\\S]*?(^|\\n)\\s*pluginUntilBuild\\s*=\\s*(?<currentValue>\\d+)\\.\\*\\s*(\\n+|$)",
          "(^|\\n)\\s*pluginUntilBuild\\s*=\\s*(?<currentValue>\\d+)\\.\\*\\s*(\\n+|$)[\\s\\S]*?(^|\\n)\\s*platformType\\s*=\\s*IC\\s*(\\n+|$)"
        ],
        "depNameTemplate": "intellij-ideaIC-build-range-eap",
        "packageNameTemplate": "com.jetbrains.intellij.idea:ideaIC",
        "datasourceTemplate": "maven",
        "registryUrlTemplate": "https://www.jetbrains.com/intellij-repository/snapshots/",
        "packageFile": "gradle.properties"
      }
    ]
  }
}


```

</details>
</div>

### PR DESCRIPTION
**Pull request by zharinov**
## Context

- Closes: #32266

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
Does that mean that that repo didn't used to work at all when we used to eagerly check releases?

**Comment by zharinov** [comment]
Yes, I think it never worked to the full extent, though HTML page is good enough to extract the list of versions (i.e. without metadata)

**Comment by rarkins** [comment]
Might be better to make this logic configurable?
- never check (no timestamps possible)
- optional (use data if available)
- strict (enforce/filter)

**Comment by zharinov** [comment]
Isn't it overcomplication, though? Originally we only wanted to skip releases which were found in `metadata.xml` but don't have corresponding pom file, which breaks `maven` build. I'm not sure it makes sense outside of Maven Central.

**Comment by zharinov** [comment]
After all, `reject` is the strong tool, so we should limit its usage. I actually surprised why I didn't limited it to the Maven Central for the initial implementation.

**Comment by rarkins** [comment]
I'm pretty sure the problem which Pom checking solves was primarily in in maven central

**Comment by rarkins** [comment]
Wasn't the bug about extractVersion and not custom registries?

**Comment by zharinov** [comment]
I think `extractVersion` isn't relevant

**Review by rarkins — CHANGES_REQUESTED** [review]
This is not what we want. This feature was designed for private registries, not maven central

**Pull request closed without merging**
