### PR TITLE
fix(poetry): Fallback to PEP440 version scheme

### LINKED ISSUE #5011: Poetry versioning does not support pre-release identifiers
**What Renovate type are you using?**

We're using the GitHub App.

**Describe the bug**

Poetry versioning doesn't support pre-release versions because it's based on [npm versioning](https://github.com/renovatebot/renovate/blob/6684a95c6b/lib/versioning/npm/readme.md).

The reason seems to be that npm uses Semantic Versioning, which uses a different definition of a [pre-release version](https://semver.org/#spec-item-11) than [PEP 440](https://www.python.org/dev/peps/pep-0440/#pre-releases).

**Did you see anything helpful in debug logs?**

Renovate job 121953463 contains this:

```json
{
  "depName": "coverage",
  "depType": "dev-dependencies",
  "currentValue": "5.0b1",
  "managerData": {
    "nestedVersion": true
  },
  "datasource": "pypi",
  "skipReason": "unknown-version",
  "updates": []
}
```

**To Reproduce**

1. `poetry init`
1. `poetry add -D coverage=5.0b1`
1. `poetry lock`
1. Enable Renovate for the repository.

[Minimal repository with showcase](https://github.com/keimlink/renovate-poetry-versioning-showcase)

**Additional context**

### PR DESCRIPTION
**Pull request by zharinov**
Probably, this solution wouldn't work though tests are passing.
This is sort of request for further discussion.

Ref #5187
Closes #5011, #5506

### CODE REVIEW

**Comment by zharinov** [comment]
Example PR: https://github.com/zharinov/renovate-poetry-versioning-showcase/pull/1

**Comment by zharinov** [comment]
Looks like it doesn't affect existing poetry repos:
https://github.com/zharinov/micropy-cli/pulls
https://github.com/zharinov/headless-service/pulls
https://github.com/zharinov/xonshit/pulls
https://github.com/zharinov/Makehuman/pulls

**Comment by zharinov** [comment]
Need to refine tests and samples for npm & pep440, in order to combine them for poetry test suite

**Comment by zharinov** [comment]
The only problem I see for now is `getNewValue` function, where parameters are valid for both `npm` and `PEP440` schemes.

**Comment by zharinov** [comment]
The only incompatibility between both versions now is `==x.y.z` versions in PEP440 vs `x.y.z  in NPM when updating with `pin` strategy.

**Comment by rarkins** [comment]
> The only incompatibility between both versions now is `==x.y.z` versions in PEP440 vs `x.y.z in NPM when updating with `pin` strategy.

What are the "impacts" to that incompatibility? e.g. do we just miss an upgrade, or do we suggest an invalid upgrade?

**Comment by zharinov** [comment]
When pinning PEP440 range, the output will be `x.y.z` instead of `==x.y.z` as with PEP440. Should not be a big issue.

**Comment by rarkins** [comment]
OK, let's get this ready to merge.

**Comment by zharinov** [comment]
Planning to make separate PR with tests refactor

**Comment by viceice** [comment]
@zharinov any progress for this?

**Comment by zharinov** [comment]
It's complicated 😅I'm not sure about how to validate this implementation and how much problems can it bring in future, given it's pretty messy one

**Pull request closed without merging**
