### PR TITLE
docs: update node version in local-dev readme

### PR DESCRIPTION
**Pull request by drybalka**
## Changes

Update the required node version to only LTS versions in the local-dev readme.

## Context

The current version of node according to [release-schedule](https://github.com/nodejs/Release#release-schedule) is 19. 
However, with this version 19 the tests are failing on the main branch.
Switching back to version 18 (LTS) solves this issue.

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
Related: https://github.com/renovatebot/renovate/blob/0ce1d4daaef96b00041d77121b7e17aa351121fb/package.json#L129-L136

**Review by viceice — CHANGES_REQUESTED** [review]
i don't think we should do this, we allow all non-out-of-support node versions but minimal v16

**Comment by drybalka** [comment]
According to the document in its present state the allowed versions are 16, 18, and 19, of which the first two are LTS and the last one fails the tests. Or are they failing only for me?

But anyway, I just wanted with this PR to spare the newcomers (like me) some confusion. Besides, “Nodejs LTS” is what recommended in prerequisite section for Windows.

**Comment by rarkins** [comment]
So the question is whether Node 19 works or not. If it does not, we should not list it?

**Comment by rarkins** [comment]
I've just tested with 18.12.1 and 19.3.0 and both fully passed `yarn test` for me, so I don't think this is needed.

**Pull request closed without merging**
