### PR TITLE
refactor(hex): ensure strict null check

### LINKED ISSUE #12869: Enforce strict null checks for versioning schemes
### Describe the proposed change(s).

- [x] `aws-machine-image`
- [x] `cargo`
- [x] `composer`
- [x] `docker`
- [x] `git`
- [x] `gradle` #13554
- [x] `hashicorp`
- [x] `helm`
- [x] `hex` #13394
- [x] `ivy`
- [x] `loose` #13454
- [x] `maven` #13332
- [x] `node` #13404
- [x] `npm` #13404
- [x] `nuget`
- [x] `pep440` #13409
- [x] `poetry`
- [x] `regex`
- [x] `rez` #13334
- [x] `ruby` #13278
- [x] `semver-coerced` #13161
- [x] `semver` #13161
- [x] `swift` #12850 
- [x] `ubuntu` #12849

### PR DESCRIPTION
**Pull request by RahulGautamSingh**
## Changes:

- Fixed strict null errors.

## Context:

- Ref : #12869 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by RahulGautamSingh** [comment]
Blocked by #13334

**Review by viceice — COMMENTED** [review]
Please make npm versioning first, as you've made those changes in multiple Pr's now.

**Comment by RahulGautamSingh** [comment]
> Please make npm versioning first, as you've made those changes in multiple Pr's now.

Only a minor change was required  in the npm-versioining so I pushed it in #13334.

**Comment by RahulGautamSingh** [comment]
Ready for review and merge.

**Review by viceice — APPROVED** [review]

**Pull request merged**
