### PR TITLE
feat: update loopback monorepo

### PR DESCRIPTION
**Pull request by achrinza**
Signed-off-by: Rifa Achrinza <25147899+achrinza@users.noreply.github.com>

## Changes:

Added the new LoopBack 4 monorepo URL.

## Context:

As LoopBack becomes an OpenJS Foundation project, the repos were migrated from https://github.com/strongloop to https://github.com/loopbackio (see: https://github.com/loopbackio/loopback-next/issues/7595).

The new LoopBack 4 monorepo was added to the configuration, following the Next.js monorepo config.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — APPROVED** [review]

**Review by viceice — CHANGES_REQUESTED** [review]
Please run `yarn prettier-fix` to fix lint issue

**Comment by rarkins** [comment]
@achrinza as maintainers we don't have permissions to edit your branch so we can't do it for you

**Comment by achrinza** [comment]
Apologies, I missed the initial review; I've pushed the linted changed, PTAL.

**Review by viceice — APPROVED** [review]

**Comment by viceice** [comment]
@achrinza Please allow pr maintainer access, so we can update the pr, otherweise it will fall behind and isn't mergable until you pushed another update.

**Comment by achrinza** [comment]
Hi @viceice, unfortunately it seems GitHub only exposes this option for user-owned forks, not org-owned.

I've created https://github.com/renovatebot/renovate/pull/10988 as a replacement, with the maintainer edit access enabled.

**Pull request closed without merging**
