### PR TITLE
feat(proxy): lowercase proxy env

### LINKED ISSUE #9544: pass env to child process should pass lowercase proxy variables
`http_proxy` and `https_proxy` are more common than uppercase variants.

This functionality was initially included in the pr but was removed, could this be readded?
#4013

### PR DESCRIPTION
**Pull request by jose-ws**
## Changes:

Updated failing snapshots due to windows case sensitive environment vars.

Feature: Environment variables http_proxy and https_proxy are more common than uppercase variants so child processes receive both uppercase and lowercase vars of each.

## Context:

Closes #9544

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by viceice** [comment]
Looks like you have a wrong git author. So you need to fix it an force push. Maybe better to rebase then and /or squash commits.

**Comment by rarkins** [comment]
> Looks like you have a wrong git author. So you need to fix it an force push. Maybe better to rebase then and /or squash commits.

I can manually approve/merge this once we are happy. The problem is this seemed to fail snapshot tests on Windows last time, which we don't test in PRs. Maybe we add it to just this PR temporarily?

**Comment by rarkins** [comment]
Reproduced!

```
FAIL lib/util/exec/env.spec.ts (768 MB heap size)
232
  ● getChildProcess environment when trustlevel set to low › returns default environment variables
234

235
    expect(received).toMatchInlineSnapshot(snapshot)
236

233
    Snapshot name: `getChildProcess environment when trustlevel set to low returns default environment variables 1`
237

239
    - Snapshot  - 0
240
    + Received  + 3
241

242
    @@ -5,6 +5,9 @@
239
        "HTTP_PROXY": "HTTP_PROXY",
243
        "LANG": "LANG",
244
        "LC_ALL": "LC_ALL",
245
        "NO_PROXY": "NO_PROXY",
246
        "PATH": "PATH",
247
    +   "http_proxy": "HTTP_PROXY",
248
    +   "https_proxy": "HTTPS_PROXY",
249
    +   "no_proxy": "NO_PROXY",
250
      }
251

252
      22 |   });
253
      23 |   it('returns default environment variables', () => {
254
    > 24 |     expect(getChildProcessEnv()).toMatchInlineSnapshot(`
255
         |                                  ^
256
      25 |       Object {
257
      26 |         "DOCKER_HOST": "DOCKER_HOST",
258
      27 |         "HOME": "HOME",
259

260
      at Object.<anonymous> (lib/util/exec/env.spec.ts:24:34)
```

**Comment by viceice** [comment]
I'm pretty sure not wthat windows is case sensitiv and linux not for env vars

**Comment by rarkins** [comment]
I think this hopefully pass the `main` build now that the inline snapshot test has been updated

**Review by viceice — APPROVED** [review]
Works on windows for me

**Review by rarkins — APPROVED** [review]

**Comment by HonkingGoose** [comment]
@rarkins You need to merge in the latest `main` branch to get the actions to run again so that auto-merge can work.

**Comment by HonkingGoose** [comment]
@rarkins The CLA is not signed for one of the commits in the PR, so the PR will not get merged. Might be better to turn off auto-merge, and let the contributor squash the previous commits into one single clean commit, with the proper commit author?

**Pull request merged**
