### PR TITLE
feat(nuget): add version scheme

### LINKED ISSUE #4027: Nuget version with 4 components
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
In nuget there are packages with versions that have 4 components instead of the normal 3 in semver (like 1.2.3.4, ex: https://www.nuget.org/packages/IronPdf/5.2.0.1). But renovate doesn't update these dependencies because it doesn't understand it's an actual version number. It would be nice if renovate could handle this and keep updating them.

**Did you see anything helpful in debug logs?**
The logs indicated that the version found in the csproj is not a version and thus skipped.

**To Reproduce**

1.  Create c# project with the IronPdf dependency linked above, preferably one of the older versions like 5.0.5.2 or 5.1.1.2
2.  Run renovate on the project

**Expected behavior**
Renovate would see the version and try to update it like normal.

**Additional context**
None

### PR DESCRIPTION
**Pull request by mark-raymond**
NuGet packages sometimes use version numbers with more than 3 parts, which Renovate doesn't work with by default as they don't conform to SemVer. You can switch to the "loose" version scheme, as suggested in #4027, but that doesn't correctly differentiate between prerelease and stable packages.

This PR introduces a dedicated "nuget" version scheme, that follows closely how NuGet itself compares versions. I believe this more completely resolves #4027.

I hope that this can become the default version scheme for nuget, in `lib/manager/nuget/extract.ts`, but I didn't include changing the default in this PR in case that's too controversial!

### CODE REVIEW

**Comment by mark-raymond** [comment]
The one test failure is in code I didn't change; I guess that's spurious and needs rerunning?

**Comment by rarkins** [comment]
@mark-raymond thanks for the PR. I think let's merge it as-is for now (i.e. opt-in), then you can fully test it in production, and if after some weeks you are happy with it then we can evaluate whether to make it the default for nuget.

Perhaps also we can create a new issue to track implementing range support for NuGet versioning

**Comment by mark-raymond** [comment]
That all sounds good to me :slightly_smiling_face:

**Comment by nyctef** [comment]
What's the best way to use this version scheme? I've tried setting 
```
{
  "nuget": {
    "versionScheme": "nuget"
    ...
  }
  ...
}
```
but that didn't seem to work - I'm still seeing `"skipReason": "not-version"` on some nuget packages in the job log. I could try setting `versionScheme: nuget` at the top level config, but that'd probably be a bad idea for us since we're also using npm and other package types in the same repo.

**Comment by mark-raymond** [comment]
Yeah, I couldn't get it to work inside the "nuget" section; I just set it at the top level because the repos I was dealing with were nuget only.

**Comment by rarkins** [comment]
Please raise a new issue in the config-help repository instead, and you can link a reference back to this issue if you like. If it turns out to be impossible or a bug, we will then treat it as a new issue back in this repository.

**Pull request merged**
