### PR TITLE
ci: Split `lint` job

### PR DESCRIPTION
**Pull request by zharinov**
## Changes

Once sharding is implemented, `lint` job may become the longest-running one. This PR splits it into 4 separate jobs:
- `lint-types`
- `lint-eslint`
- `lint-prettier`
- `lint-other`

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — DISMISSED** [review]
@rarkins remember to change required jobs

**Comment by zharinov** [comment]
And seems like `lint` status needs to be removed from required list

**Comment by viceice** [comment]
> And seems like `lint` status needs to be removed from required list

yes

**Comment by zharinov** [comment]
- Waiting for: #22686

**Comment by HonkingGoose** [comment]
@zharinov the PR you were waiting for is now merged. 😉

**Pull request merged**
