### PR TITLE
fix(composer): add support for github vulnerability alerts

### PR DESCRIPTION
**Pull request by rarkins**
## Changes

Processes GitHub vulnerability alerts for Composer.

## Context

#14299

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by icanhazstring** [comment]
Nice. Thanks for the fix 👍

**Comment by icanhazstring** [comment]
How long does it normally take for the docker image release?

**Review by viceice — APPROVED** [review]

**Comment by viceice** [comment]
> How long does it normally take for the docker image release?

One to two hours, depends on renovate schedule. Checkout the `docker-renovate` and `docker-renovate-full` repo's.

**Comment by icanhazstring** [comment]
Sorry to bother. But the fix aint working 🤷

**Comment by viceice** [comment]
> Fix aint working, will open a new bug ticket.

This will only work on GitHub, so yes please open a new discussion first and provide information about your use case.

**Comment by icanhazstring** [comment]
Already moved: #14310

**Pull request merged**
