### PR TITLE
ci: run macOS, Windows, Java tests on `ci:fulltest` label

### PR DESCRIPTION
**Pull request by ylemkimon**
## Changes:

- Merged `build` and `build-pr` workflow to reduce repetition
- Run macOS, Windows, and Java tests on the `ci:fulltest` label

## Context:

Sometimes, there is a need to test the PR on other OSs and with Java, e.g., #12081. Furthermore, `build` and `build-pr` workflows were largely duplicated.

With this PR, the `build` workflow will run with the following configuration:

- `push` and `workflow_dispatch` (manually triggered)
  - OS: Ubuntu, macOS, Windows
  - Java tests: O
  - Release job: O
  - Example: https://github.com/ylemkimon/renovate/actions/runs/1323224239 and https://github.com/ylemkimon/renovate/actions/runs/1323346380
- `pull_request`
  - OS: Ubuntu
  - Java tests: X
  - Release job: X
  - Example: https://github.com/ylemkimon/renovate/actions/runs/1323226156
- `pull_request` with `ci:fulltest` label
  - OS: Ubuntu, macOS, Windows
  - Java tests: O
  - Release job: X
  - Example: https://github.com/ylemkimon/renovate/actions/runs/1323242236

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — COMMENTED** [review]
LGTM, but need to see it in action

**Comment by viceice** [comment]
I don't like labels with spaces, what about `ci:fulltest`? It would more align with our other labels.

@rarkins WDYT?

**Comment by rarkins** [comment]
I guess we'd need to change the branch protection required status checks now?

**Comment by ylemkimon** [comment]
@rarkins Yes, `test` -> `test (ubuntu-latest, 14, 3.9, 11)`. It's also possible to override the name.

**Comment by rarkins** [comment]
Can we make that name less specific so that it doesn't need to change every time we switch node/python/etc? Eg call it Ubuntu-latest?

**Comment by ylemkimon** [comment]
Job names are now `test (ubuntu-latest)`, `test (macos-11)`, and `test (windows-latest)`.

**Review by rarkins — APPROVED** [review]
Great PR, thanks

**Review by viceice — APPROVED** [review]

**Pull request merged**
