### PR TITLE
fix(leiningen): Don't extract deps from commented vectors

### PR DESCRIPTION
**Pull request by zharinov**
## Changes

- Handle common case of dependency commenting in Leiningen

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — DISMISSED** [review]
is this a preparation for a new parser?

**Comment by zharinov** [comment]
> is this a preparation for a new parser?

Just maintainance. Seems like this manager is about to become obsolete next couple years, so I don't think it's reasonable to rewrite parsing.

**Review by viceice — APPROVED** [review]
how did you found the issue?

**Comment by zharinov** [comment]
Tried to renovate an existing project: https://github.com/zharinov/zprint/pull/3/files

**Pull request merged**
