### PR TITLE
feat: travis.yml node_js versions support

### LINKED ISSUE #1208: Support Node.js versions in .travis.yml
I like to support all active/maintenance Node.js versions in many of my modules.

This currently results in the following .travis.yml:

```yaml
language: node_js
node_js:
  - '8'
  - '6'
  - '4'
```

I don't like to just add `'node'` (will test against latest Node.js) because if there is a breaking change in a new version of Node.js that shouldn't break PR builds for an unrelated reason or start breaking previously successful builds.

However it's a pain to keep this up to date manually across many repos and it would still be helpful to be notified of the break (just without breaking all builds on master).

This is something I had an idea to build a while ago but seems like it could be nicely integrated into Renovate. It would be great if you could specify which Node.js versions you wish to support (e.g `latest`/`active`/`maintenance`) and Renovate would open a PR to keep `.travis.yml` up to date when new Node.js versions are released.

Node.js/Travis is just my use case, could also support other CI environments and languages.

### PR DESCRIPTION
**Pull request by rarkins**
This PR adds support for renovating the `node_js` versions in `.travis.yml` configuration files. Important notes:
- Functionality is disabled by default and hence opt-in via configuration
- Added a new manager type `node` because it is anticipated to support more than just Travis in future, with mostly unified logic
- Added the config option "policy" with supported values: lts, active, current, lts_latest and lts_active
- Policy is actually an array, to allow additive combining, e.g. `["lts_latest", "current"]`
- Actual node versions are *hardcoded*. There is no perfect metadata source for this and they change infrequently enough that it is definitely not a problem for now (next change will be in April 2018)
- If node versions need updating, they are listed from newest to oldest
- Replacing function attempts to detect the indention (spacing) in file and use that

To enable, configure `node.enabled=true` and optionally `node.policy=["<policy>"]` if you want something other than `lts`.

Closes #1208

TODO:
- [x]  Documentation
- [x] Tests/coverage
- [x] Create issues for future improvements

### CODE REVIEW

**Comment by rarkins** [comment]
@lukechilds do you have any existing repositories that you would be able to use/test this feature on after this PR is merged? Or did you fix them all up by hand recently and your next updates would be in April 2018? If you have any then I can test with dry runs prior to merge too.

**Comment by lukechilds** [comment]
I'm sure I probably do, if they're up to date I wouldn't mind supporting LTS + Latest.

Gotta dash now but will have a look tomorrow for you.

**Comment by lukechilds** [comment]
Yeah I think all mine are up to date, but I would like to test against latest aswell, is that functionality in the PR?

**Comment by rarkins** [comment]
I'm using the term "current" instead of latest, as I believe that follows with the node.js terminology. So if you set `"policy": ["lts", "current"]` then it should result in 4,6,8,9. Is that what you want? I can test some of your repos for you as I was already using keyv as my text fixture

**Comment by lukechilds** [comment]
Yeah, that's perfect.

If you could that would be great, really tied up in some other projects atm. ❤️

**Pull request merged**
