### PR TITLE
feat: improved warning markdown

### LINKED ISSUE #24550: Use GitHub block quotes extension
### Discussed in https://github.com/renovatebot/renovate/discussions/24549

<div type='discussions-op-text'>

<sup>Originally posted by **uhthomas** September 20, 2023</sup>
### Tell us more.

GitHub has extended the blockquote syntax to include more visible messages. It would be nice if Renovate were to use these instead the existing style.

https://github.com/orgs/community/discussions/16925

Example:

> [!NOTE]  
> Highlights information that users should take into account, even when skimming.

> [!IMPORTANT]  
> Crucial information necessary for users to succeed.

> [!WARNING]  
> Critical content demanding immediate user attention due to potential risks.

Current:

Screenshot 2023-09-20 at 13 19 46

With proposed change:

Screenshot 2023-09-20 at 13 20 29
</div>

### PR DESCRIPTION
**Pull request by rarkins**
## Changes

Refactors markdown warnings plus adds a massage function to have them use GitHub's custom warning markdown approach.

## Context

Closes #24550

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
GitLab onboarding MR:

image

GitHub onboarding PR:

image

**Comment by rarkins** [comment]
Regular MR warning on GitLab:

image

Regular PR warning on GitHub:

image

**Comment by rarkins** [comment]
Dependency Dashboard warning GitLab:

image

GitHub:

image

**Review by viceice — DISMISSED** [review]

**Comment by rarkins** [comment]
@viceice sorry, decided to add one for Important too

**Review by viceice — APPROVED** [review]

**Pull request merged**
