### PR TITLE
feat(composer): ignorePlatformReqs

### PR DESCRIPTION
**Pull request by bytestream**
Config option to prevent `--ignore-platform-reqs` in composer package manager

### CODE REVIEW

**Comment by bytestream** [comment]
I'm not familiar with Typescript, so you'll have to point me in the right direction to fix those tests...

**Comment by JamieMagee** [comment]
@bytestream You need to update the snapshots. You can do that by running `yarn jest -u`.

**Comment by bytestream** [comment]
Thanks @JamieMagee should be OK now.

**Review by viceice — APPROVED** [review]

**Comment by rarkins** [comment]
@bytestream does this automatically close any of our existing issues? If so, please add `Closes #12345` to the PR description.

**Comment by bytestream** [comment]
No, it relates to #2355 and #4396 but it doesn't fix either of them.

**Comment by bytestream** [comment]
Thanks guys 👏

**Pull request merged**
