### PR TITLE
feat(manger/asdf): add argocd support

### LINKED ISSUE #19940: [ASDF] Support argocd plugin
### What would you like Renovate to be able to do?

Upgrade the `argocd` version in the `.tool-versions` file.

[beardix/asdf-argocd](https://github.com/beardix/asdf-argocd)

### If you have any ideas on how this should be implemented, please tell us here.

Other plugins were added via https://github.com/renovatebot/renovate/pull/18612

### Is this a feature you are interested in implementing yourself?

No

### PR DESCRIPTION
**Pull request by julianxhokaxhiu**
## Changes

Add argocd to the asdf manager

## Context

Closes #19940 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by rarkins — DISMISSED** [review]

**Comment by julianxhokaxhiu** [comment]
Actually I am not sure how this documentation here is updated: https://docs.renovatebot.com/modules/manager/asdf/#additional-information

If there's a way to do it already on this PR LMK and I'll be happy to add argocd to the list.

**Comment by rarkins** [comment]
It's auto-generated! So no need to do anything, the website will be updated automatically post-release

**Comment by julianxhokaxhiu** [comment]
I rebased the PR as GH was stating this branch was already out of date.

**Review by viceice — CHANGES_REQUESTED** [review]

**Review by viceice — APPROVED** [review]

**Comment by julianxhokaxhiu** [comment]
https://app.renovatebot.com/dashboard#github/julianxhokaxhiu/renovate-test/981559147 the `argocd` plugin still comes out as unsupported 🤔

```json
{
  "depIndex": 0,
  "depName": "argocd",
  "skipReason": "unsupported-datasource",
  "updates": []
}
```

Any idea why? Maybe this patch is not enough? Job is using this version:
```json
{
  "renovateVersion": "34.108.1"
}
```

**Comment by julianxhokaxhiu** [comment]
I added a test coverage of the new `argocd` plugin to make sure the `extract` logic works correctly and in fact it does. The test passes ( see mentioned PR above ), but it is still not clear to me why the bot is not picking it up for a bump and says unsupported.

**Comment by viceice** [comment]
please create a new discussion instead of commenting on released PR

**Pull request merged**
