### PR TITLE
feat(datasource): Rename `crate` datasource to `crates-io`

### PR DESCRIPTION
**Pull request by Turbo87**
## Changes

This PR renames the `crate` datasource to `crates-io`.

## Context

Other datasources are named after the official registry (e.g. `pypi` or `rubygems`), but for the Rust ecosystem the datasource was named `crate`, while the official registry is called "crates.io". One could argue that `crate` is more generic since the datasource also supports third-party cargo-compatible registries, but even in that case something like `cargo` or `cargo-registry` would make more sense.

Since an assumed 99% of cases will use crates.io instead of a custom third-party registry though, it seems best to use the least confusing term and rename the datasource to `crates-io` (I'm assuming a `.` character in the datasource name would cause all sorts of problems...).

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

Note that I've mostly followed the work in https://github.com/renovatebot/renovate/pull/21149 while implementing this change.

### CODE REVIEW

**Review by rarkins — CHANGES_REQUESTED** [review]
I don't think I prefer this rename. The _ideal_ for us is (a) different name to the manager to avoid confusion, and (b) to use a generic term instead of the default registry, so that it makes sense when used for private registries. e.g. using 'pypi' for python packages is not really correct, but we have no alternative. On the other hand using 'docker-hub' instead of 'docker' would be terrible, so we don't do that for the same reason we don't do 'crates-io' instead of 'crate'

**Comment by Turbo87** [comment]
would it be an option to have `crates-io` be an alias for "`crate` datasource with `crates-io` flavor"?

**Comment by rarkins** [comment]
> would it be an option to have `crates-io` be an alias for "`crate` datasource with `crates-io` flavor"?

We don't have a precedent for that (other than when we rename datasources and add migration code - but in this case they don't both exist). And generally speaking having aliases for the same thing leads to confusion

**Comment by viceice** [comment]
> I don't think I prefer this rename. The _ideal_ for us is (a) different name to the manager to avoid confusion, and (b) to use a generic term instead of the default registry, so that it makes sense when used for private registries. e.g. using 'pypi' for python packages is not really correct, but we have no alternative. On the other hand using 'docker-hub' instead of 'docker' would be terrible, so we don't do that for the same reason we don't do 'crates-io' instead of 'crate'

agreed

**Pull request closed without merging**
