### PR TITLE
fix(gradle): Support classifier and extension

### PR DESCRIPTION
**Pull request by ikesyo**
Try to port https://github.com/patrikerdes/gradle-use-latest-versions-plugin/pull/13 and https://github.com/patrikerdes/gradle-use-latest-versions-plugin/pull/22.

Details: https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.dsl.DependencyHandler.html#N17198

### CODE REVIEW

**Comment by ikesyo** [comment]
I can't sign the CLA due to https://github.com/cla-assistant/cla-assistant/issues/451.

**Comment by rarkins** [comment]
Is it possible to add a test for this case? Should fail on master but pass here.

**Comment by ikesyo** [comment]
Yes, I'll add a test for this!

**Comment by ikesyo** [comment]
@rarkins I added a test. Could you please review?

**Comment by ikesyo** [comment]
@rarkins Is there any chance to get this reviewed?

**Comment by ikesyo** [comment]
I really want the fix for Crashlytics: https://fabric.io/kits/android/crashlytics/install

 ```gradle
compile('com.crashlytics.sdk.android:crashlytics:2.10.1@aar')
```

**Comment by ikesyo** [comment]
Thanks @rarkins!

**Comment by ikesyo** [comment]
It appears that the regular expression does not support extension only forms such as `com.crashlytics.sdk.android:crashlytics:2.10.1@aar`. I'll send a follow-up pull request.

**Pull request merged**
