### PR TITLE
feat: environment proxy

### LINKED ISSUE #1411: Allow proxy configs
Currently it is impossible to run renovate behind a proxy. The tool should allow the user to configure proxy settings in one of two ways:

 1. pass proxy settings in via config (CLI or otherwise)
 1. read proxy environment variables with and apply them to requests

Personally, I prefer the latter. Depending if there's an appetite to add this I'm happy to open a PR that conforms to whichever method you prefer.

### PR DESCRIPTION
**Pull request by kayoub5**
Use work from #2686, with less code

Closes #2686, Closes #1411

### CODE REVIEW

**Comment by kayoub5** [comment]
@brokenmass could you check if this PR works well for you?

**Comment by rarkins** [comment]
@kayoub5 	does this support `NO_PROXY` ?

**Comment by kayoub5** [comment]
@rarkins yes, this PR uses `proxy-agent`, and it internally uses `proxy-from-env`

**Comment by rarkins** [comment]
I'm thinking if this should be released as a new major version, because although it's a "feature", it will result in a major "automatic" change in behaviour for anyone who already had these environment variables configured. Although we could make it opt-in for Renovate configuration, I prefer that it does this without requiring additional config. @hbetts 	do you have any opinion?

**Comment by rarkins** [comment]
@brokenmass can you confirm?

**Review by mikebryant — APPROVED** [review]
I've had to build a local image using this PR, as I'm behind a corporate proxy without direct access to the internet.

This seems to be working fine for me, thanks :)

**Pull request merged**
