### PR TITLE
feat(config): use onboardingConfig when rebasing onboarding PR

### LINKED ISSUE #4506: Update renovate.json in existing PRs when onboardingConfig is changed in config.js
**What would you like Renovate to be able to do?**
If I change the `onboardingConfig` option in config.js. On the next run, renovate does not update the renovate.json of any already open "Configure Renovate" PRs. 

**Describe the solution you'd like**
It would be nice for Renovate to recognize a difference in the `onboardingConfig` in config.js and `renovate.json` of any renovate/configure branch and open Configure PR, and if there is a difference, update the renovate.json on that branch

**Describe alternatives you've considered**
I think for `renovate/configure` branches that have been touched / committed to by someone else other than renovate could be ignored for this update.

**Additional context**
I am using the self-hosted renovate NPM package to keep several repositories up to date on a self-hosted GitLab. The reason for the change is we would like to change the name of the preset used in our onboardingConfig.

### PR DESCRIPTION
**Pull request by fullstackzach**
This is my first contribution to Renovate, so I'd love to hear if I'm doing this right!

This PR will have renovate use the `onboardingConfig` from config.js if the onboardingConfig changed to be different from the contents of renovate.json since the "Configure Renovate" PR was created. 

Note:

- [line 30](https://github.com/renovatebot/renovate/blob/master/lib/workers/repository/onboarding/branch/rebase.js#L30) already confirms the branch hasn't been modified
- [line 39](https://github.com/renovatebot/renovate/blob/master/lib/workers/repository/onboarding/branch/rebase.js#L39) already checks to see if onboardingConfig and the existing config in renovate.json match, if they do it returns before rebasing

I confirmed this change works by

1. Ran renovate locally against a test github repo first to open a "Configure Renovate" PR
1. I updated `onboardingConfig` in config.js and added an option (prConcurrentLimit: 2)
1. I ran renovate again against the same repository
1. I observed that updates the renovate.json in the `renovate/configure` branch adding the new option (prConcurrentLimit: 2).

Additonally, tests pass by running `yarn test`, and it is showing 100% line coverage

Closes #4506

### CODE REVIEW

**Comment by rarkins** [comment]
Thanks @fullstackzach. In the early days I had things these ways, and then there were some nasty edge cases that caused me to change my mind, but now I've forgotten them. It's entirely possible that other maturity in the code has eliminated them, but I'll need to think for a while about any unintended consequences!

**Comment by fullstackzach** [comment]
For sure, I totally understand since this has wide impact on all Onboarding PRs! I'd be happy to help and keep iterating on this if you can think of any problems.

**Comment by rarkins** [comment]
I think this is safe. There's one situation we can't detect - where users force push an updated config to the branch using Renovate as the author. In this case we see one commit and our own author so assume the PR is unmodified. However in that case users would need to force push under their own identity to avoid it, and it should be a rare case.

**Review by viceice — APPROVED** [review]
LGTM

A push to a renovate branch as renovate user is always a bad idea.

**Pull request merged**
