### PR TITLE
fix(bitbucket-server): includeForks setting

### PR DESCRIPTION
**Pull request by nikhil-zadoo**
## Changes:
Bitbucket server API response has 'origin' field in response instead of 'parent' if the repo is a fork

The api call https://<BITBUCKET_URL>/rest/api/1.0/projects//repos/ has no field called 'parent' but instead a 'origin' field.
Because of this issue, renovate is not able to identify if the repository is a fork which in turn breaks the 'includeForks': false setting.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — COMMENTED** [review]
Do you have a docs link for this?

**Review by viceice — DISMISSED** [review]
https://docs.atlassian.com/bitbucket-server/rest/5.3.0/bitbucket-rest.html#idm46551991063136
https://docs.atlassian.com/bitbucket-server/rest/5.3.0/bitbucket-rest.html#idm46551991024944

**Comment by rarkins** [comment]
@viceice is it documented there? I'm not seeing it on mobile. We need to verify this because if it's wrong then it could potentially break BBS functionality completely

**Comment by nikhil-zadoo** [comment]
The documentation for the bitbucket server is not the best one out there.
You can though see an example under: https://docs.atlassian.com/bitbucket-server/rest/7.14.0/bitbucket-rest.html#idp176
In this section you can look under 201 Http code example. There is no `parent` property but rather an `origin` property which points to the repo from where it was forked.

I am also copying the example text here
```
{
    "slug": "my-repo",
    "id": 1,
    "name": "My repo",
    "description": "My repo description",
    "hierarchyId": "e3c939f9ef4a7fae272e",
    "scmId": "git",
    "state": "AVAILABLE",
    "statusMessage": "Available",
    "forkable": true,
    "project": {
        "key": "PRJ",
        "id": 1,
        "name": "My Cool Project",
        "description": "The description for my cool project.",
        "public": true,
        "type": "NORMAL",
        "links": {
            "self": [
                {
                    "href": "http://link/to/project"
                }
            ]
        }
    },
    "public": true,
    "links": {
        "clone": [
            {
                "href": "ssh://git@<baseURL>/PRJ/my-repo.git",
                "name": "ssh"
            },
            {
                "href": "https://<baseURL>/scm/PRJ/my-repo.git",
                "name": "http"
            }
        ],
        "self": [
            {
                "href": "http://link/to/repository"
            }
        ]
    }
}

**Comment by nikhil-zadoo** [comment]
The documentation for the bitbucket server is not the best one out there.
You can though see an example under: https://docs.atlassian.com/bitbucket-server/rest/5.3.0/bitbucket-rest.html#idm46551991076064
In this section you can look under 201 Http code example for `POST`. There is no `parent` property but rather an `origin` property which points to the repo from where it was forked.
I am also copying the example text here

```
{
    "slug": "my-repo",
    "id": 2,
    "name": "My repo",
    "scmId": "git",
    "state": "AVAILABLE",
    "statusMessage": "Available",
    "forkable": true,
    "origin": {
        "slug": "my-repo",
        "id": 1,
        "name": "My repo",
        "scmId": "git",
        "state": "AVAILABLE",
        "statusMessage": "Available",
        "forkable": true,
        "project": {
            "key": "PRJ",
            "id": 1,
            "name": "My Cool Project",
            "description": "The description for my cool project.",
            "public": true,
            "type": "NORMAL",
            "links": {
                "self": [
                    {
                        "href": "http://link/to/project"
                    }
                ]
            }
        },
        "public": true,
        "links": {
            "clone": [
                {
                    "href": "ssh://git@<baseURL>/PRJ/my-repo.git",
                    "name": "ssh"
                },
                {
                    "href": "https://<baseURL>/scm/PRJ/my-repo.git",
                    "name": "http"
                }
            ],
            "self": [
                {
                    "href": "http://link/to/repository"
                }
            ]
        }
    },
    "project": {
        "key": "~JDOE",
        "id": 2,
        "name": "John Doe",
        "type": "PERSONAL",
        "links": {
            "self": [
                {
                    "href": "http://link/to/project"
                }
            ]
        }
    },
    "links": {
        "clone": [
            {
                "href": "https://<baseURL>/scm/JDOE/my-repo.git",
                "name": "http"
            },
            {
                "href": "ssh://git@<baseURL>/JDOE/my-repo.git",
                "name": "ssh"
            }
        ],
        "self": [
            {
                "href": "http://link/to/repository"
            }
        ]
    }
}

**Comment by rarkins** [comment]
Unfortunately it's not enough for us to merge, as it's just an example, it's for POST not GET, and it doesn't prove that origin is missing for other non-fork cases

**Comment by viceice** [comment]
I can't verify either, as i don't have a bitbucket-server. Migrated away some month ago.

@nikhil-zadoo Can you share some sample json by manual using `curl` against your bitbucket server? You can of cause remove unrelated fields and sanitize others.

**Comment by nikhil-zadoo** [comment]
Here is the response json I get from GET request `https://<SERVER_URI>/rest/api/1.0/projects/<PROJECT>/repos/<REPOSITORY>` to my bitbucket server
RESPONSE
```
{
    "slug": "<REPOSITORY_NAME>",
    "id": 25814,
    "name": "<REPOSITORY_NAME>",
    "hierarchyId": "3cefd41b18d898fa7ed4",
    "scmId": "git",
    "state": "AVAILABLE",
    "statusMessage": "Available",
    "forkable": true,
    "origin": {
      "slug": "<REPOSITORY_NAME_PARENT>",
      "id": 23864,
      "name": "<REPOSITORY_NAME_PARENT>",
      "hierarchyId": "3cefd41b18d898fa7ed4",
      "scmId": "git",
      "state": "AVAILABLE",
      "statusMessage": "Available",
      "forkable": true,
      "project": {
        "key": "<PROJECT>",
        "id": 4102,
        "name": "<PROJECT NAME>",
        "description": "<DESCRIPTION>",
        "public": false,
        "type": "NORMAL",
        "links": {
          "self": [
            {
              "href": "https://<REPO_URI>/projects/<PROJECT>"
            }
          ]
        }
      },
      "public": false,
      "links": {
        "clone": [
          {
            "href": "ssh://git@<REPO_URI>/<PROJECT>/<REPOSITORY_NAME>.git",
            "name": "ssh"
          },
          {
            "href": "https://<REPO_URI>/scm/<PROJECT>/<REPOSITORY_NAME>.git",
            "name": "http"
          }
        ],
        "self": [
          {
            "href": "https://<REPO_URI>/projects/<PROJECT>/repos/<REPOSITORY_NAME>/browse"
          }
        ]
      }
    },
    "project": {
      "key": "<PROJECT_NAME>",
      "id": 5233,
      "name": "<PROJECT NAME>",
      "public": false,
      "type": "NORMAL",
      "links": {
        "self": [
          {
            "href": "https://<REPO_URI>/projects/<PROJECT_NAME>"
          }
        ]
      }
    },
    "public": false,
    "links": {
      "clone": [
        {
          "href": "https://<REPO_URI>/scm/<PROJECT_NAME>/<REPOSITORY_NAME>.git",
          "name": "http"
        },
        {
          "href": "ssh://git@<REPO_URI>/<PROJECT_NAME>/<REPOSITORY_NAME>.git",
          "name": "ssh"
        }
      ],
      "self": [
        {
          "href": "https://<REPO_URI>/projects/<PROJECT_NAME>/repos/<REPOSITORY_NAME>/browse"
        }
      ]
    }
  }

**Comment by viceice** [comment]
Is this the normal or the fork? can you check the otherone too?

**Comment by nikhil-zadoo** [comment]
The one I pasted above was the forked repo.
The output for the parent repo is as below.
It does not have the `origin` property set.
```
{
    "slug": "<REPOSITORY_NAME>",
    "id": 23864,
    "name": "<REPOSITORY_NAME>",
    "hierarchyId": "3cefd41b18d898fa7ed4",
    "scmId": "git",
    "state": "AVAILABLE",
    "statusMessage": "Available",
    "forkable": true,
    "project": {
      "key": "<PROJECT>",
      "id": 4102,
      "name": "<PROJECT NAME>",
      "description": "<PROJECT DESCRIPTION>",
      "public": false,
      "type": "NORMAL",
      "links": {
        "self": [
          {
            "href": "https://BITBUCKET_SERVER_URI/projects/<PROJECT>"
          }
        ]
      }
    },
    "public": false,
    "links": {
      "clone": [
        {
          "href": "ssh://git@BITBUCKET_SERVER_URI/<PROJECT>/<REPOSITORY_NAME>.git",
          "name": "ssh"
        },
        {
          "href": "https://BITBUCKET_SERVER_URI/scm/<PROJECT>/<REPOSITORY_NAME>.git",
          "name": "http"
        }
      ],
      "self": [
        {
          "href": "https://BITBUCKET_SERVER_URI/projects/<PROJECT>/repos/<REPOSITORY_NAME>/browse"
        }
      ]
    }
  }

**Review by viceice — APPROVED** [review]

**Pull request merged**
