### PR TITLE
fix(bitbucket-server): get only writable repos.

### PR DESCRIPTION
**Pull request by viceice**
This pr uses the [repos api](https://docs.atlassian.com/bitbucket-server/rest/6.0.0/bitbucket-rest.html#idp354) to get writable repos. This will now find personal repos too.

Requires BitBucket Server 5.13 (the state flag)!

### CODE REVIEW

**Comment by ViceIce** [comment]
Additionally it improves the performance by removing the separate project requests.

**Comment by rarkins** [comment]
@ViceIce what would be the impact on someone running Bitbucket <5.13?

I see that 5.13 was [released in August 2018](https://confluence.atlassian.com/bitbucketserver/bitbucket-server-5-13-release-notes-953131455.html) but not able to locate Atlassian's official policies on which releases are still under support or not.

@iamstarkov is this release limitation OK with you, for example?

**Comment by ViceIce** [comment]
I can remove the state flag and defer it for a later version

**Comment by ViceIce** [comment]
Found eol's, version 5.0 is still supported.

 https://confluence.atlassian.com/support/atlassian-support-end-of-life-policy-201851003.html

**Comment by ViceIce** [comment]
Or simply check the server version ☺

https://docs.atlassian.com/bitbucket-server/rest/6.0.0/bitbucket-rest.html?utm_source=%2Fstatic%2Frest%2Fbitbucket-server%2Flatest%2Fbitbucket-rest.html&utm_medium=301#idp69

**Comment by rarkins** [comment]
It would be interesting to know if the state flag is just *ignored* in earlier versions. In that case wouldn't it be gracefully backwards compatible? I think we should have a general recommendation "don't add the bot to a repository unless it has write access" anyway.

**Comment by ViceIce** [comment]
Yes, but i use the autodiscover feature, which will currently try to use readonly repos. There is no archive function, so we simply made them readonly.

**Comment by ViceIce** [comment]
Maybe we should add a feature to detect the writable right on repo init and warn the user?

**Comment by ViceIce** [comment]
> It would be interesting to know if the state flag is just _ignored_ in earlier versions. In that case wouldn't it be gracefully backwards compatible? 

I'll try that with a [docker](https://hub.docker.com/r/atlassian/bitbucket-server). They have older versions there. 😄

**Comment by rarkins** [comment]
Detecting writeable at init is a good idea. I tried it with GitHub a while back but they have a bug where an *app* cannot detect writeable status while a *user* can, so I had to revert it. But otherwise it would be a good sanity check to add.

**Comment by ViceIce** [comment]
Ok, i'll send a pr.

As i fixed #3252, i first tryed to add a cachbusting parameter to the url `&_=${Date.now()}` with has worked.
BB has simply ignored the unknown parameter, so i think it will ignore state too on version below 5.13.

**Comment by rarkins** [comment]
Could you elaborate on exactly what the cache-busting problem/requirement was? I meant to ask before. e.g. is it PRs that are changed by a user mid-job and so gets out of sync? Or is it a case where Renovate itself changes the PR during the job and we need to refresh state?

When users change the repo mid-job, I prefer to simply detect and abort - because you can never tell just how much has changed. But we should explicitly handle cases where we Renovate itself has caused the cache to become out of date.

**Comment by ViceIce** [comment]
The pr version gets updated, when you push new commits to the branch. When renovate then trys to update the pr we get the cached pr version and the updated fails with confict.

Maybe we should completly rework the caching to be able to refresh the pr atfer git push.

**Comment by rarkins** [comment]
Maybe after each commitFilesToBranch we call getBranchPr with a cache bust option. That way it will refresh the cached PR (if exists) but still all the cache to be used for other operations where caching is fine.

**Comment by ViceIce** [comment]
> > It would be interesting to know if the state flag is just _ignored_ in earlier versions. In that case wouldn't it be gracefully backwards compatible?
> 
> I'll try that with a [docker](https://hub.docker.com/r/atlassian/bitbucket-server). They have older versions there. 😄

Works 👍  Bitbucket 5.2.6 is ignoring the `state`. This pr can be merged.

**Comment by rarkins** [comment]
Thanks for checking

**Pull request merged**
