### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by AdrienLemaire**
add date-fns changelog

Closes #

### CODE REVIEW

**Comment by rarkins** [comment]
@Fandekasp 	I don't think this manual setting is necessary. Renovate already finds and extracts the changelog entries: https://github.com/renovate-tests/datefns/pull/1

**Comment by Fandekasp** [comment]
@rarkins here is a screenshot of the PR I received from renovate this morning:

Release notes weren't shown, which is why I went looking for them. Not sure why :)

**Comment by rarkins** [comment]
That's weird. I just tried the same combination now and still got them:
image

It may be a bug in how changelogs are cached, but either way we shouldn't need this particularly PR. Sorry for the inconvenience

**Comment by Fandekasp** [comment]
Is it possible that they added the release notes after the release, and my
PR got built before the update ?
In which case, can you add a timer to check again at regular intervals ?

**Comment by Fandekasp** [comment]
A simple solution would be to always show the link to the github releases
page for github repos if release notes couldn't get parsed ?

**Comment by rarkins** [comment]
The bot should already cache existing Changelog files for up to an hour before checking/refreshing them and updating PRs if necessary. Of course, your particular repo may not run exactly after the refresh so maybe it's up to a 2 hour wait, worst-case.

And yes I was thinking the same thing. Even if we parse the notes, it could still be useful to include a "changelog" link in the main table.

**Comment by rarkins** [comment]
By the way, it looks like the v1.30.1 changelogs were only added around the time we were discussing this: https://github.com/date-fns/date-fns/commit/fa7a9731064ff466651c011394105e5b343540de#diff-4ac32a78649ca5bdd8e0ba38b7006a1e

So it makes sense that they were unavailable when you saw your PR and merged

**Pull request closed without merging**
