### PR TITLE
fix(gradle): support gradlePluginPortal()

### LINKED ISSUE #11893: `gradlePluginPortal()` is not supported
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Please select which platform you are using if self-hosting.

_No response_

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### Describe the bug

Renovate is not updating the Gradle plugin: `https://plugins.gradle.org/plugin/com.gradle.plugin-publish`

`repositories` block places:

```kotlin
// settings.gradle.kts

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        google()
        gradlePluginPortal()
    }
}
```

```kotlin
// buildSrc/build.gradle.kts

repositories {
    mavenCentral()
    google()
    gradlePluginPortal()
}
```

```toml
[versions]
gradlePublish = "0.13.0"


[libraries]
gradle-publish-pluginPublishPluginX = { module = "com.gradle.publish:plugin-publish-plugin", version.ref = "gradlePublish" }
```

Probably Renovate doesn't understand the fact that `gradlePluginPortal()` is the same as `maven("https://plugins.gradle.org/m2/")`

Additionally, `gradlePluginPortal()` is an official API, so it should be support as `mavenCentral()` and `google()` are supported.

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Looking up com.gradle.publish:plugin-publish-plugin in repository https://repo.maven.apache.org/maven2/
DEBUG: Content is not found for Maven url: https://dl.google.com/android/maven2/org/jsoup/jsoup/maven-metadata.xml
DEBUG: Looking up com.javiersc.gradle-plugins:android-library in repository https://repo.maven.apache.org/maven2/
DEBUG: Content is not found for Maven url: https://dl.google.com/android/maven2/com/diffplug/spotless/spotless-plugin-gradle/maven-metadata.xml
DEBUG: Looking up com.javiersc.gradle-plugins:all-projects in repository https://repo.maven.apache.org/maven2/
DEBUG: Content is not found for Maven url: https://dl.google.com/android/maven2/io/github/gradle-nexus/publish-plugin/maven-metadata.xml
DEBUG: Failed to look up dependency io.github.gradle-nexus:publish-plugin (io.github.gradle-nexus:publish-plugin)(packageFile="gradle/pluginLibs.toml", dependency="io.github.gradle-nexus:publish-plugin")
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

### PR DESCRIPTION
**Pull request by JavierSegoviaCordoba**
## Changes:

Fixes #11893 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — COMMENTED** [review]
Please do not force push, just push an new commit. We squash merge anyways. 😉

**Comment by JavierSegoviaCordoba** [comment]
@viceice ah sorry, I was fixing eslint issues, IntelliJ was conflicting the formatting automatically on commit.

**Review by viceice — COMMENTED** [review]
Needs snapshot updates

**Comment by JavierSegoviaCordoba** [comment]
@viceice what do you mean with snapshot updates?

**Comment by viceice** [comment]
Run `yarn jest -u`. 😉

**Comment by JavierSegoviaCordoba** [comment]
@viceice not sure if you were referring to add samples to `build.gradle.example1` and get the new snapshots.

**Review by zharinov — APPROVED** [review]
LGTM

**Review by rarkins — APPROVED** [review]

**Comment by JavierSegoviaCordoba** [comment]
Is there something blocking this one?

**Pull request merged**
