### PR TITLE
fix(host-rules): support matchHost with a dot prefix

### PR DESCRIPTION
**Pull request by straub**
## Changes:

`host-rules` will no longer double up on dot prefixes if the configured value of `matchHost`
already contains one.

## Context:

I found myself wishing the docs called this out when I added my own dot prefix out of what
I thought was an abundance of caution, and inadvertently made it impossible to match any
hostnames due to the one already there :) Hoping to help clarify this for posterity.

Open to suggestions on the wording! I'm not sure I phrased this as clearly as possible or
kept the voice of the docs consistently.

Edit: updated per recommendation below to correct the behavior, in addition to clarifying
in the docs.

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
Do you mean that we ended up with a "double dot" prefix when you first tried it?

**Comment by straub** [comment]
Exactly! I (incorrectly) configured ".docker.io" and `matchesHost` wound up trying to do `hostname.endsWith('..docker.io')` here:
https://github.com/renovatebot/renovate/blob/b8e36daa87e4275caa5b66bffa6fe3f4d5d8a77e/lib/util/host-rules.ts#L88

**Comment by rarkins** [comment]
We could/should probably fix that though

**Comment by straub** [comment]
Sounds good to me! Something like `rule.matchHost.startsWith('.') ? hostname.endsWith(rule.matchHost) : hostname.endsWith(`.${rule.matchHost}`)`?

Would we still want to have clarification in the docs that this happens?

Happy to PR this, with guidance on the desired approach. Also thanks for your time as always!

**Comment by rarkins** [comment]
I think that logic change sounds good. You're welcome to expand the explanation in the documentation too at the same time!

**Comment by straub** [comment]
@rarkins Updated! Please let me know what you think, at your convenience

**Review by rarkins — APPROVED** [review]

**Pull request merged**
