### PR TITLE
feat(datasource/html-links): add html-links datasource

### PR DESCRIPTION
**Pull request by amezin**
## Changes

Add `html-links` datasource.

This datasource extracts releases from hyperlinks in an HTML page.

The source HTML page URL is `registryUrl`.

`packageName` is the regex that the target URLs should match. Its first (and only) capture group becomes the package version.

URLs could point to files or directories, even non-existent, the datasource won't try to fetch the content or headers.

## Context

Sometimes there is no "package registry", only a website with download links, or just a directory listing generated by the server. This datasource, together with regex manager, enables use of Renovate in such cases.

This module is inspired by Debian's `uscan` tool.

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by amezin** [comment]
Had to add `url` to HTTP client's returned data to be able to resolve relative URLs correctly:

1) Renovate drops the trailing slash from `registryUrl`.

2) Even without the trailing slash, the URL can point to a directory. Better resolve this automatically instead of asking the users.

**Comment by amezin** [comment]
Also, it would be nice to provide digests for regex manager. Usually there's some form of checksum file stored alongside the downloads (md5sums, sha1sums, etc.). But this would require additional configuration (how to build the URL to the checksum file, and how to extract the checksum from the file). And I can't figure out how to provide additional configuration options to a datasource. Currently I have a script in `postUpgradeTasks` that updates those checksums, but it doesn't look like a good solution.

**Review by viceice — CHANGES_REQUESTED** [review]
I think this is better implemented as custom datasource, like the custom json datasource

@secustor  @JamieMagee @rarkins WDYT?

**Comment by secustor** [comment]
Sounds like a great addition to the custom datasource. 

What we would need to additionally is a way to describe a subset of the html document, maybe with XPATH. 
That way it should be usable for most scenarios.

**Comment by amezin** [comment]
Not sure how exactly to implement it in `custom` datasource.

> What we would need to additionally is a way to describe a subset of the html document, maybe with XPATH.

node-html-parser supports CSS selectors - but they only select elements, not attributes.

XPath (2.0) has [`matches()`](https://www.w3.org/TR/xpath-functions/#func-matches) function, which should work for selecting links by regex. But HTML is not XML. Maybe rebuilding DOM from node-html-parser as XML tree would work. Is there already an XML library in dependencies?

Also, should `transformTemplates` apply to XML - i.e. should they be XSLT?

And all of this looks complicated and requires a verbose config. In practice, I haven't seen a case where I needed something other than `href` attribute of `a`. "Downloads" page always has links. A directory listing always has links too.

**Comment by amezin** [comment]
Or maybe `extractVersion` is enough to filter links? Should I expect that versions not matching `extractVersion` will be silently discarded (and it is not an error)?

In this case, a `custom` datasource with `"format": "html-links"`, that simply converts all links into "versions" should be enough for my use cases.

Or maybe even `"format": "html"` - that, by default, extracts all links, and could be extended in future with additional config.

**Comment by secustor** [comment]
As first step it is fine to add a new `format` `html` to the custom manager and add an optional option to allow your regex filtering. 

I think `htmlLinkFilters` should be not too confusing.

**Comment by amezin** [comment]
https://github.com/renovatebot/renovate/pull/24403

**Pull request closed without merging**
