### PR TITLE
feat(package-rules): add datasources selector

### LINKED ISSUE #3335: Support "datasources" selector in packageRules
**What would you like Renovate to be able to do?**

Support applying package rules by datasource.

**Describe the solution you'd like**

Add a new field `datasources` to `packageRules` that can include values like `orb` and `github`.

**Describe alternatives you've considered**

Applying rules based on the `manager`, but that doesn't let you apply rules to just `orb` and not `docker` in `circleci`, for example.

### PR DESCRIPTION
**Pull request by Dmitry9**
Assumptions:
lib/util/package-rules.js -> applyPackageRules
This function ensures that [packagerules config part](https://renovatebot.com/docs/configuration-options/#packagerules) of configuration created by the user inside the renovate.json is valid and extracts configuration values like manager names or datasource names. Extracted values then merged into the object (mutable config) which like props in ReactJS world then passed to extract dependency function -> lookup function -> update dependency function. So at those three stages under the key of `datasources` of  the `mutable config` can be founded string-value which will define extract->lookup->update logic for this dependency. For example if user wants the Renovate-bot to update a Circleci-orb he can add:
```javascript
packagerule: {
  datasources: 'orb'
}
```
then extract function will find and parse .circleci.yaml file in the root folder of the repo of this user and add respective fields to the mutable config so that lookup function will be able to find wanted version for this orb on the [registry](https://circleci.com/orbs/registry/). I understand that changes made in this PR don't change anything because added field `datasources` has been never read.
This PR do not include any tests and extract->lookup->update logic because I want to understand whether I am on the correct way here.
@rarkins if all of that is close to the truth then, please, take a minute to correct (maybe cross out what is wrong), or drop a quick note about my first wrong assumption.

Closes #3335

### CODE REVIEW

**Comment by rarkins** [comment]
The code is right (so far), but some of the assumptions are wrong.

First of all, a way to save time would be to look up the history of the package-rules.js file via GitHub: https://github.com/renovatebot/renovate/commits/master/lib/util/package-rules.js

Then you can look at the `languages` commit as an example: https://github.com/renovatebot/renovate/commit/8c2cad0647ffa588bb95413ef63f70e4f4978517#diff-0b13f987e852b748b9f2c00f5db2c2ed

You can see some additional files/changes necessary that would apply here too. There is no need to change the lookup function at all.

And an example package rule once this feature is ready would look like this:

```json
{
  "packageRules": [{
    "datasources": ["orb"],
    "labels": ["circleci-orb!!"]
  }]
}
```

The above would apply the label `circleci-orb` only to Orb updates and not to any other (e.g. Docker updates, even if they're in the same circleci yml config file).

**Comment by rarkins** [comment]
Please also try to name your Pull Request title in a semantic style. You can check out previous PRs including 1-2 of your own that I've renamed.

**Comment by Dmitry9** [comment]
@rarkins please give me feedback on updated PR, so I can proceed to tests.

**Comment by rarkins** [comment]
Looks good thanks

**Comment by Dmitry9** [comment]
@rarkins please look into this PR I think it is ready to pass CI but cannot remove draft state from it.  I thought adding `feat` word to the PR's title was enough for conforming the semantic style requirements. Regardless of your title change I cannot see `Ready for review` [button](https://help.github.com/en/articles/changing-the-stage-of-a-pull-request).

**Comment by rarkins** [comment]
@Dmitry9 do you see this button I highlighted in your view?

image

I think if you click it then it will take off the draft status.

**Comment by Dmitry9** [comment]
no_btn
@rarkins Strangely enough I cannot see the button.

**Pull request merged**
