### PR TITLE
chore: fix yarn lock

### PR DESCRIPTION
**Pull request by viceice**
## Changes:
Not sure why i get these changes locally (ubuntu focal node v14)

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] Unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
Because of https://github.com/renovatebot/renovate/blob/46fda9790d21315053467f006a223bfdd8ffdd1a/lib/manager/npm/post-update/yarn.ts#L38

**Comment by viceice** [comment]
those deps are bundled in npm. 🤔

**Comment by viceice** [comment]
> Because of
> 
> https://github.com/renovatebot/renovate/blob/46fda9790d21315053467f006a223bfdd8ffdd1a/lib/manager/npm/post-update/yarn.ts#L38

so yarn would change the lockfile again, when running a full install? 🤔

**Comment by rarkins** [comment]
> > Because of
> > https://github.com/renovatebot/renovate/blob/46fda9790d21315053467f006a223bfdd8ffdd1a/lib/manager/npm/post-update/yarn.ts#L38
> 
> so yarn would change the lockfile again, when running a full install? 🤔

Yes, it probably does. But the lockfile we create passes `--frozen-lockfile`.

**Comment by viceice** [comment]
We should merge this, otherwise contributor will get this changes because tehy mostly don't use frozen lockfile (me included) 🙃

**Comment by viceice** [comment]
But next lockfile update will revert this ? 🤔

**Pull request merged**
