### PR TITLE
feat(pip_requirements): Extract flags from package files with no deps

### PR DESCRIPTION
**Pull request by mbudnek**
## Changes

The pip_requirements manager is used by the pip-compile manager for extracting info from requirements.in files.  This change makes pip_requirements return any flags it extracted from its input file even if there are no dependencies in the file.  This allows a user to provide a requirements.in file with nothing but `--extra-index-url` flags as a second input file when using pip-compile to compile dependencies in a setup.py file so that Renovate can look those index URLs up in its `hostRules` and pass appropriate credentials to pip-compile.

## Context

#28960 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — COMMENTED** [review]
I would prefer to extract a new function which always returns the results and leave this function as is.

all managers should return null when no deps are extracted.

**Comment by rarkins** [comment]
There are cases where we return the package file even with no deps (e.g. when it's the root npm package in workspaces)

**Comment by not7cd** [comment]
If this only concerns pip-compile manager, maybe it should handle this edge-case? Also, maybe extract function can have an optional flag to always return a package file object. A flag only used by pip-compile extract function. But this changes the interface.

**Review by rarkins — APPROVED** [review]

**Review by viceice — APPROVED** [review]
🤷‍♂️

**Pull request merged**
