### PR TITLE
feat(node): use node-version datasource

### PR DESCRIPTION
**Pull request by viceice**
## Changes
We should use `node-version` datasource instead of `github-tags` for NodeJS, so we ensure all binaries are already released.

## Context
- fixes #26579

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by rarkins — DISMISSED** [review]
This should be a performance improvement too as I anecdotally noticed the nodejs/node repo being heavily called

**Comment by secustor** [comment]
Needs snapshot updates

**Comment by viceice** [comment]
> This should be a performance improvement too as I anecdotally noticed the nodejs/node repo being heavily called

yes, we download a single json file. So only one request. 🙃

we can improve that datasource to include etag caching

```console
>curl -svX HEAD https://nodejs.org/dist/index.json
> HEAD /dist/index.json HTTP/2
> Host: nodejs.org
> user-agent: curl/7.81.0
> accept: */*
>
< HTTP/2 200
< date: Mon, 29 Jan 2024 13:45:20 GMT
< content-type: application/json
< content-length: 267011
< last-modified: Mon, 22 Jan 2024 19:23:49 GMT
< etag: "65aec0c5-41303"
< access-control-allow-origin: *
< cf-cache-status: HIT
< age: 2395
< accept-ranges: bytes
< strict-transport-security: max-age=31536000; includeSubDomains; preload
< x-content-type-options: nosniff
< server: cloudflare
< cf-ray: 84d1ea406aa18ffe-FRA
<
```

**Comment by viceice** [comment]
snapshot fixed 🙈

**Review by secustor — APPROVED** [review]

**Pull request merged**
