### PR TITLE
fix: support docker /library retry with abortOnError

### PR DESCRIPTION
**Pull request by ahippler**
## Changes

Before this change it was not possible to use official docker images from artifactory while enabling abortOnError.

## Context

`getReleases` for a docker image tries to make a second lookup using a /library prefix. This retry was not executed because `abortOnError` changes the error instance to `ExternalHostError` and throws immediately.  I unwrapped the error in case of `ExternalHostError` to allow the retry.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — CHANGES_REQUESTED** [review]
i don't think that this is right. I'm pretty sure the docker cli won't inject the library at that position.

**Comment by ahippler** [comment]
the test is a copy from the existing test right above...

**Comment by setchy** [comment]
I can confirm that this is how the JFrog Docker REST API behaves for official images.  The `library` is added after the jfrog virtual/remote registry name, and before the image name.

**Comment by ahippler** [comment]
I added a parameter instead of copying the test

**Comment by viceice** [comment]
> I can confirm that this is how the JFrog Docker REST API behaves for official images.  The `library` is added after the jfrog virtual/remote registry name, and before the image name. 
> 

I'm pretty sure the docker cli won't do that

**Comment by setchy** [comment]
> > I can confirm that this is how the JFrog Docker REST API behaves for official images.  The `library` is added after the jfrog virtual/remote registry name, and before the image name.
> 
> I'm pretty sure the docker cli won't do that

also correct ;)  https://github.com/renovatebot/renovate/pull/17925 was the PR that added special retry-logic for JFrog Artifactory and docker official image types

**Comment by viceice** [comment]
we should check what docker does and handle it that way, as it seems to work with artifactory.

i don't like the strange handling for artifactory.

**Comment by rarkins** [comment]
The question to answer: when Docker has a Dockerfile like `FROM some.host/some/path/theimage` how does it know if it should treat the image as `theimage`, `path/theimage`, or `library/theimage`?

**Comment by setchy** [comment]
> The question to answer: when Docker has a Dockerfile like `FROM some.host/some/path/theimage` how does it know if it should treat the image as `theimage`, `path/theimage`, or `library/theimage`?

or `path/library/theimage` which is the case for the JFrog REST API for official images

**Comment by ahippler** [comment]
seems like all root images (without `/`) are fetched from `library/<name>`

https://github.com/docker/cli/blob/master/vendor/github.com/docker/distribution/reference/normalize.go#L101
```
	if domain == defaultDomain && !strings.ContainsRune(remainder, '/') {
		remainder = officialRepoName + "/" + remainder
	}
```
officialRepoName is `library` here

**Comment by ahippler** [comment]
but all of this is not part of my PR. I just want to use the existing logic with `abortHostError:true`

**Comment by ahippler** [comment]
or should i try to remove the retry at all and do all requests for a image without `/` to `library/<image>`?

**Comment by setchy** [comment]
> or should i try to remove the retry at all and do all requests for a image without `/` to `library/<image>`?

this will not work for JFrog.  The convention they use is `FROM someorg.jfrog.io/some-jfrog-registry/some-image`, so you'll have a `/` but the JFrog REST API call format is `https://wfscorp.jfrog.io/v2/some-jfrog-registry/library/some-image/tags/list` - note that `library` is added between the jfrog virtual/remote registry and the image name

**Comment by viceice** [comment]
> > or should i try to remove the retry at all and do all requests for a image without `/` to `library/<image>`?
> 
> this will not work for JFrog.  The convention they use is `FROM someorg.jfrog.io/some-jfrog-registry/some-image`, so you'll have a `/` but the JFrog REST API call format is `https://someorg.jfrog.io/v2/some-jfrog-registry/library/some-image/tags/list` - note that `library` is added between the jfrog virtual/remote registry and the image name

we shouldn't try that fallback at all for those images, as docker wouldn't do that either.

**Comment by ahippler** [comment]
https://someorg.jfrog.io/v2/some-jfrog-registry/library/some-image/tags/list should no be thing since library woud only be added for https://someorg.jfrog.io/v2/some-jfrog-registry/library/some-image

**Comment by setchy** [comment]
> > > or should i try to remove the retry at all and do all requests for a image without `/` to `library/<image>`?
> > 
> > 
> > this will not work for JFrog.  The convention they use is `FROM someorg.jfrog.io/some-jfrog-registry/some-image`, so you'll have a `/` but the JFrog REST API call format is `https://someorg.jfrog.io/v2/some-jfrog-registry/library/some-image/tags/list` - note that `library` is added between the jfrog virtual/remote registry and the image name
> 
> we shouldn't try that fallback at all for those images, as docker wouldn't do that either.

docker-cli + jfrog will support either
* `someorg.jfrog.io/jfrog-remote-registry/image`
* `someorg.jfrog.io/jfrog-remote-registry/library/image`

Screenshot 2023-02-28 at 9 47 57 AM

however specifically the `tags/list` jfrog api does not.  hence https://github.com/renovatebot/renovate/pull/17925 resolved this.
Screenshot 2023-02-28 at 9 49 16 AM
Screenshot 2023-02-28 at 9 49 28 AM

as @ahippler suggested, can we please focus this issue on the retry + abortOnError logic, and move all this other discussion into another issue/discussion thread

**Review by viceice — APPROVED** [review]

**Pull request merged**
