### PR TITLE
feat(manager/mix): fix mix and git dependencies

### PR DESCRIPTION
**Pull request by 1oglop1**
## Changes

Fixes mix manager behaviour of Elixir git dependencies. 

## Context
Mix is manager is misbehaving with Git dependencies. 
See discussion: https://github.com/renovatebot/renovate/discussions/31778

This is a draft PR on purse, to help the discussion.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by 1oglop1** [comment]
@viceice Could you please prevent the bot from closing this so we can fix it? 
It has been dragging for a long time and as other contributors, I am reaching my limits.

**Comment by rarkins** [comment]
@1oglop1 the bot never closes PRs on its own. It closes it if we assign a label to the PR, which we do if a PR is unwelcome or unworkable.

If you're reached your limits and don't like how this project is run, then it's best for all if you abandon your efforts. We don't want any aggression or rudeness in an open source project like this. Please see https://github.com/renovatebot/renovate/blob/main/CODE_OF_CONDUCT.md#politeness

**Review by rarkins — APPROVED** [review]

**Comment by 1oglop1** [comment]
Tests are now passing but when I added more test cases I noticed a little bit of an unexpected behaviour
https://github.com/renovatebot/renovate/discussions/31778#discussioncomment-11414143

Shall we split this into 2 PRs and discussions or continue the same discussion?

**Review by rarkins — APPROVED** [review]

**Comment by rarkins** [comment]
Separate is better

**Pull request merged**
