### PR TITLE
feat(github): github enterprise vulnerability alerts

### LINKED ISSUE #4905: Enable vulnerability alerts on GitHub Enterprise Server
As of GitHub Enterprise Server (GHE) 2.17 vulnerability alerts are now supported. Currently we explicitly disable them [here](https://github.com/renovatebot/renovate/blob/master/lib/platform/github/index.ts#L1784-L1789).

It should be fairly safe to remove this check, as 2.17 is the oldest supported version of GHE, so any older version is unsupported anyway.

### PR DESCRIPTION
**Pull request by JamieMagee**
Add support for vulnerability alerts for GHE. Requires GHE 2.17.0 or higher. I think this is a fair requirement to assume, as [GHE 2.16.x went EOL on January 22, 2020.](https://help.github.com/en/enterprise/2.16/user/github)

This also allows us to remove the check for GHE version when gettings issues.

Closes #4905

### CODE REVIEW

**Review by viceice — APPROVED** [review]
Breaking change?

**Comment by JamieMagee** [comment]
> Breaking change?

Yeah, I'm still on the fence on this. Technically yes, but if you're not keeping your GitHub Enterprise instance up to date on patches, you probably have bigger issues. Is it on us to support a version of GitHub Enterprise, when even GitHub won't?

**Comment by viceice** [comment]
True, so I'm fine with minor version bump

**Comment by rarkins** [comment]
Split the issues and graphql into separate just in case?

**Pull request merged**
