### PR TITLE
fix(poetry): don't take `python` as a pypi deps

### PR DESCRIPTION
**Pull request by trim21**

### CODE REVIEW

**Review by viceice — COMMENTED** [review]
Why it should excluded? It should be return as separate dependency

**Comment by rarkins** [comment]
I guess we need a python version datasource?

**Comment by Trim21** [comment]
`"datasource": "pypi"` means it's a python package instead of python itself.

It has been considered as a separate dependency in `compatibility` part.

**Comment by viceice** [comment]
Can we use GitHub tags as datasource for python?

**Comment by Trim21** [comment]
I don't think it's a version need to be updated in poetry pyproject.toml file, at least not as a pypi package or git tag.

It's more like npm engines.

**Comment by rarkins** [comment]
We update npm engines too when applicable.

**Pull request merged**
