### PR TITLE
feat: use environment proxy config

### LINKED ISSUE #1411: Allow proxy configs
Currently it is impossible to run renovate behind a proxy. The tool should allow the user to configure proxy settings in one of two ways:

 1. pass proxy settings in via config (CLI or otherwise)
 1. read proxy environment variables with and apply them to requests

Personally, I prefer the latter. Depending if there's an appetite to add this I'm happy to open a PR that conforms to whichever method you prefer.

### PR DESCRIPTION
**Pull request by brokenmass**
This PR allow the usage of standard `HTTP_PROXY` , `HTTPS_PROXY` and `NO_PROXY` (or their lowercase counterparts) environment variable to configure proxy communication. This is useful for self hosted renovate deployed in air-gapped environment.

Closes #1411

### CODE REVIEW

**Comment by rarkins** [comment]
@brokenmass thanks very much for this PR. My thoughts so far:

1. This appears to support proxy for GitHub and GitLab connections but not any of the data sources, eg npmjs lookups. Wouldn’t you need all of them? I think for the rest we could add a `got` wrapper util that they require instead of `got` directly 

2. Have you been able to test this in a “real” scenario to verify it works with your proxy?

3. We should document this support somewhere

4. We should add later a way to configure this explicitly as a hostRule in addition to env

**Comment by kayoub5** [comment]
basically this PR could be simplified as:
```
var globalTunnel = require('global-tunnel-ng');
globalTunnel.initialize();
```
With one down side, that `global-tunnel` does not support `NO_PROXY`

**Comment by rarkins** [comment]
It seems like a reasonable compromise if it also means every registry/datasource we use is implicitly covered. @brokenmass what do you think?

**Comment by brokenmass** [comment]
@rarkins @kayoub5 : I’m sorry but I think it’s an unacceptable compromise. The typical use case scenario where a proxy configuration is needed involves an internally hosted GitHub enterprise (or other git solution) not reachable through the proxy (ignored by specifying it’s domani name in the no_proxy env) and the public GitHub.com reachable through the proxy. 

Because of this, Any solution that does not support no_proxy it’s , for me, not a valid solution.

**Comment by rarkins** [comment]
@brokenmass I'm a little confused though. I thought that this PR adds proxy support only for GitHub and GitLab, so part of the problem was that it was missing for lookups like npmjs, Docker, etc. What was the use case you were trying to solve - unproxied GHE and proxied github.com only?

**Comment by rarkins** [comment]
@kayoub5 another possibility is:

- Stop use of gh-got and gl-got and instead create our own got wrapper that all parts of the app uses
- The got wrapper adds `agent` config like in the example from got repo:

```
got('sindresorhus.com', {
	agent: tunnel.httpOverHttp({
		proxy: {
			host: 'localhost'
		}
	})
});
```

**Comment by brokenmass** [comment]
> @brokenmass I'm a little confused though. I thought that this PR adds proxy support only for GitHub and GitLab, so part of the problem was that it was missing for lookups like npmjs, Docker, etc. What was the use case you were trying to solve - unproxied GHE and proxied github.com only?

this PR aime to make renovate work in an airgapped environment (internal npm registry, internal docker registry, internal github enterprise) while still be able to connect to public github.com through a proxy

**Comment by rarkins** [comment]
@brokenmass thank you for the clarification - I understand your use case now.

I was also considering a fork/adaptation of `global-tunnel-ng` for this purpose, as you suggest. Were you thinking to embed it within Renovate or publish a separate module?

Thank you in advance for the GHE-hosted dependencies PR.

**Comment by rarkins** [comment]
@brokenmass we'll work on an embedded solution  like global-tunnel-ng that captures your use case (airgapped, NO_PROXY) as well as handles the general use case for others too (e.g. accessing npmjs.org, pypi.org, etc).

**Comment by iamstarkov** [comment]
how does NO_PROXY work?

**Comment by rarkins** [comment]
@iamstarkov these env variables are a convention but not a standard. We should operate the same way as described here: https://www.gnu.org/software/emacs/manual/html_node/url/Proxies.html

**Comment by iamstarkov** [comment]
@rarkins thanks

**Pull request closed without merging**
