### PR TITLE
feat: support node v14

### PR DESCRIPTION
**Pull request by viceice**
* build v14 on ci
* fix `::set-env` [deprecation](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/)
* do not support node v13 (ended on 2020-06-01)

should we be more strict, eg `^12.13.0 || >=14.15.0` , as `14.15.0` is first v14 lts ?

### CODE REVIEW

**Comment by rarkins** [comment]
> should we be more strict, eg `^12.13.0 || >=14.15.0` , as `14.15.0` is first v14 lts ?

I think so, because we sometimes depend on features which are added to the major releases prior to LTS, and we have no interest in chasing after pre-LTS versions to work out why something's failing.

**Comment by viceice** [comment]
maybe also time to raise yarn to 1.22.0 ?

**Comment by viceice** [comment]
should we skip v12 or v14 tests on windows? as we've done with v10 before?

**Comment by JamieMagee** [comment]
Does this require a major version bump?

**Comment by viceice** [comment]
> Does this require a major version bump?

Why? because we do not support node v13 anymore?

**Comment by viceice** [comment]
i can split this pr, so we first enable testing v14 only and later change the package.json node requirementes with a major bump, maybe dropping node support <14.15.0

**Comment by JamieMagee** [comment]
Yeah, it's technically breaking. Though now that I think about it, we drop unsupported versions of GHE without making a major release. This probably falls in the same category.

**Comment by rarkins** [comment]
I don't see why it's a major for us to add v14 support, although if we're taking anything away and it's deserving of a major then we could wait and combine it with others if it's not too inconvenient.

**Comment by viceice** [comment]
> Yeah, it's technically breaking. Though now that I think about it, we drop unsupported versions of GHE without making a major release. This probably falls in the same category.

so yes, i think it's ok to drop unsupported versions with a minor update

> I don't see why it's a major for us to add v14 support, although if we're taking anything away and it's deserving of a major then we could wait and combine it with others if it's not too inconvenient.

It's not because adding v14 support, it's because we explicit disallow node `^13  || <14.15`

**Pull request merged**
