### PR TITLE
feat(manager/npm): extract contraints again on post-update

### PR DESCRIPTION
**Pull request by viceice**
## Changes
- We now extract constraints again from `package.json` instead of using `extractedContraints`.
- User `constraints` are now consistently preferred after updates. 

Before this PR post-update has relyed on `extractedContraints` which comes from first update in PR.
So if you group different manager updates it can fail because the `extractedContraints` from wrong manager are used.
See linked PR and the history of it for working sample for yarn.

## Context
- https://github.com/renovate-reproductions/npm-extracted-constraint-lockfiles/pull/9

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by viceice** [comment]
@JamieMagee @secustor any chance to review this? this is blocking lockfile maintenance on some of my repos.

**Review by secustor — APPROVED** [review]
🤷

**Comment by bh** [comment]
Seems that this merge breaks my renovate bot integration for all new npm package update branches/PRs. The package-lock.json in packages/app/ is missing.

PR generated today:
Screenshot_2023-07-20_14-42-40
PR generated several days ago:
Screenshot_2023-07-20_14-43-10

I'm using lerna 7.x.x and there are no constraints. Node is pinned to 14.21.3 in .tools-version

**Comment by viceice** [comment]
please open a discussion

**Pull request merged**
