### PR TITLE
test(ts-jest): Migrate obsolete Jest config

### PR DESCRIPTION
**Pull request by zharinov**
## Context

```
Define `ts-jest` config under `globals` is deprecated
```

https://github.com/kulshekhar/ts-jest/blob/main/CHANGELOG.md?plain=1#L13

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by zharinov** [comment]
Code coverage still takes +10s even for simplest test like `lib/util/url.spec.ts`, though

**Review by viceice — COMMENTED** [review]
do you have some context link?

**Comment by zharinov** [comment]
https://github.com/kulshekhar/ts-jest/blob/main/CHANGELOG.md?plain=1#L13

**Comment by zharinov** [comment]
Also updated to the newer version, if you don't mind

**Review by viceice — APPROVED** [review]

**Pull request merged**
