### PR TITLE
chore: remove old TODO comment

### PR DESCRIPTION
**Pull request by HonkingGoose**
## Changes:

- Remove old TODO comment

## Context:

The issue the TODO comment refers to (#556) has been closed.

I don't know if we still need to do something here, if so, the comment should be updated instead of removed... 😄 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] Unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
Ideally we shouldn't have any TODO's unless they have an accompanying issue number written into the TODO

**Comment by HonkingGoose** [comment]
Ah okay, so do we care about cleaning up the TODO's then? Or do you just want to keep things as they are?

**Comment by rarkins** [comment]
It would be good, but it's a big task

**Comment by rarkins** [comment]
Added a new issue: #8358

**Pull request merged**
