### PR TITLE
fix(manager/sbt): group PRs by variable instead of variable+groupid together

### LINKED ISSUE #13929: [sbt] When a common variable is used for multiple dependencies, several PR are opened
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

31.38.4

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

13.6.2

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

In sbt project, consider the following _build.sbt_ file:

```scala
val kafkaVersion = "3.0.0"

libraryDependencies ++= Seq(
  "org.apache.kafka" % "kafka-clients" % kafkaVersion,
  "io.github.embeddedkafka" %% "embedded-kafka" % kafkaVersion % Test
)
```

When Renovate runs, it opens two distinct PR for each dependency:
- _chore(deps): update dependency io.github.embeddedkafka:embedded-kafka to v3.1.0_
- _chore(deps): update dependency org.apache.kafka:kafka-clients to v3.1.0_

I would expect Renovate to group all dependencies related to same variable in a single PR. I believe that's what happens with Maven for instance?

A drawback of the current mechanism is that if we setup automerge for dependencies with `"matchDepTypes": ["Test"]` (only test scoped dependencies), as the same variable is used for both a test dependency and a non test dependency, both PRs are automerged which is not desired at all.

### Relevant debug logs

_No response_

### Have you created a minimal reproduction repository?

https://github.com/gaeljw/renovate1799/pulls

### PR DESCRIPTION
**Pull request by PhilipAbed**
## Changes

currently the code groups PRs only if dependencies had the same groupId and used same variable at the same time.
now code will group PRs only if dependencies have the same variable, ignoring group id.

before:https://github.com/gaeljw/renovate1799/pulls
after: https://github.com/StinkyLord/renovate1799/pulls
i'm not sure if i break anything by doing this, so please advise

## Context

a request from the user to group PRs in SBT by the variable and not by the variable+groupId.

Closes https://github.com/renovatebot/renovate/issues/13929

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — COMMENTED** [review]
Needs test fixes

**Comment by PhilipAbed** [comment]
i'm not sure how is this related to my PR while i changed 1 line in code but it says module not found??? O.o
$ renovate --version && renovate-config-validator
internal/modules/cjs/loader.js:329
      throw err;
      ^

Error: Cannot find module '/home/runner/work/renovate/renovate/test/e2e/node_modules/@yarnpkg/libzip/lib/sync.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:321:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:534:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/runner/work/renovate/renovate/test/e2e/node_modules/@yarnpkg/core/lib/scriptUtils.js:7:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:[950](https://github.com/renovatebot/renovate/runs/5274418863?check_suite_focus=true#step:10:950):32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/runner/work/renovate/renovate/test/e2e/node_modules/@yarnpkg/core/lib/index.js:17:47)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/runner/work/renovate/renovate/test/e2e/node_modules/@yarnpkg/libzip/package.json',
  requestPath: '@yarnpkg/libzip'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.

**Comment by viceice** [comment]
Run `yarn install --force`

**Review by viceice — COMMENTED** [review]
LGTM, waiting for review from @zharinov

**Review by zharinov — APPROVED** [review]
LGTM

My original concern was about using same variable name between multiple files. If it's not the problem, I'm okay with the PR 👍

**Review by rarkins — APPROVED** [review]

**Pull request merged**
