### PR TITLE
chore(jenkins): Add Jenkins datasource

### PR DESCRIPTION
**Pull request by maxdanilov**
Closes #

### CODE REVIEW

**Comment by viceice** [comment]
@maxdanilov Why do you closed the pr?

**Comment by maxdanilov** [comment]
Opened it by a mistake, it's still a WIP.

**Comment by viceice** [comment]
you could also leave it open and mark as draft. so can can give easy feedback if requested

**Comment by maxdanilov** [comment]
Sure, I will do when the PR is more mature than it is now :) It's way too raw at the moment.

**Pull request closed without merging**
