### PR TITLE
docs: fix local development doc for python3 support

### PR DESCRIPTION
**Pull request by ViralRuparel**
Updates the local development document as the 'mock' library version '^4.0.0' and 'node-gyp' now supports python3 version '^3.6'.

### CODE REVIEW

**Comment by rarkins** [comment]
Thanks @ViralRuparel. I want to make sure that we don't want to leave in a mention of Python 2.7.

On one hand, Python 2.7 will work still. On the other hand, it's now officially unsupported so maybe we should not support it either, as this PR intends?

Cc @viceice

**Comment by viceice** [comment]
see #4426, this is already in our v20 pipeline.

**Comment by ViralRuparel** [comment]
okay @viceice , so where shall it be added in the v20 planning PR or it will be updated by the contributors working on v20 planning?

**Comment by viceice** [comment]
I think we should target the v20 branch. 

`requirements.txt` needs an update too.
https://github.com/renovatebot/renovate/blob/6c4892b59336ecb7bcb09ad1678f068f4ac11045/requirements.txt#L1

**Comment by ViralRuparel** [comment]
> I think we should target the v20 branch.
> 
> `requirements.txt` needs an update too.
> https://github.com/renovatebot/renovate/blob/6c4892b59336ecb7bcb09ad1678f068f4ac11045/requirements.txt#L1

Okay so shall I make change to requirement.txt and change the base branch to v20?

**Comment by ViralRuparel** [comment]
I have made changes to requirement.txt file, shall I change the base branch to v20 @rarkins , also as you said python 2.7 is already deprecated so no point to support it!

**Comment by viceice** [comment]
I would prefer to merge to v20, I'm prepare to finished it

**Review by viceice — APPROVED** [review]
LGTM (retargeted to v20)

**Comment by rarkins** [comment]
@ViralRuparel i recommend against force pushing to branches. Better to add commits on top to retain history

**Comment by ViralRuparel** [comment]
Okay, @rarkins will keep that in mind!

**Pull request merged**
