### PR TITLE
feat(composer): Detect TYPO3 extensions and Symfony bundles as libraries

### LINKED ISSUE #13795: Composer project type incorrectly detected (library or project)
### What would you like Renovate to be able to do?

I have composer project type defined as "bundle", which actually means it is a symfony bundle and should be considered as a library from dependencies point of view.

I did not find a way to indicate renovate that a project is a library or a project

Sadly, renovate by default pin its dependencies which does not work with composer.
It is fine to pin devdependencies though. I wanted to keep `rangeStrategy` to `auto` and not resort to `rangeStrategy: replace` for all dependency types (`dependencies`, `devdependencies`, `peerdependencies`)

### If you have any ideas on how this should be implemented, please tell us here.

For composer manager, project types can be anything you want. Maybe add a parameter to indicate which types should be considered as libraries by renovate.

for example: `projectDependencyType: library` for single project override
or for packageManager detected as composer, a list of types that should be detected as projects or library.
I think that renovate should default to `library`, and not the current way where only applies library type when `"type": "library"` in composer.json file.
```
{
   "packageManager": "composer",
   "libraryTypes": ["library", "bundle", "composer-plugin", "wp-plugin", ...],
   "projectTypes": ["project", "application", "cli", ...],
   "defaultDependencyManagementType": "library"
}
```

### Is this a feature you are interested in implementing yourself?

No

### PR DESCRIPTION
**Pull request by LeoniePhiline**
## Changes:

Detect TYPO3 extensions and Symfony bundles as libraries

###  feat(composer): detect typo3-cms-extension type

Detect composer.json `"type": "typo3-cms-extension"` as library,
and thus use `"rangeStrategy": "replace"` for TYPO3 extensions
by default.

See also:
https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/ComposerJson/Index.html#type

###  feat(composer): detect symfony-bundle type

Detect composer.json `"type": "symfony-bundle"` as library,
and thus use `"rangeStrategy": "replace"` for Symfony bundles
by default.

See also:
https://symfony.com/doc/current/bundles/best_practices.html#composer-metadata

## Context:

- Closes #13795

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — DISMISSED** [review]

**Comment by HonkingGoose** [comment]
Hi @LeoniePhiline!

Please do not force-push your branch for small changes, this makes it harder for us to review your work.

Quote from [our guide on contributing](https://github.com/renovatebot/renovate/blob/main/.github/contributing.md#do-not-force-push-to-your-pull-request-branch):

> ## Do not force push to your pull request branch
> 
> Please do not force push to your PR's branch after you have created your PR, as doing so forces us to review the whole PR again.
> This makes it harder for us to review your work because we don't know what has changed.
> PRs will always be squashed by us when we merge your work.
> Commit as many times as you need in your pull request branch.
> 
> If you are updating your PR branch from within the GitHub PR interface, then only use the default "Update branch" button.
> 
> Force pushing a PR is OK when:
> 
> - you need to make large changes on a PR which require a full review anyway
> - you need to bring the branch up-to-date with the target branch and incorporating the changes is more work than to create a new PR

**Review by viceice — APPROVED** [review]

**Comment by LeoniePhiline** [comment]
@HonkingGoose I know - but I was told otherwise here: https://github.com/renovatebot/renovate/pull/14136#issuecomment-1035110496

**Comment by HonkingGoose** [comment]
You're right!

I'm sorry for telling you off, when you got told to force push by the maintainer.

**Comment by mbrodala** [comment]
No idea about Symfony bundles but assuming a `typo3-cms-extension` as root, then `"rangeStrategy": "widen"` should be the default IMO.

This approach ensures that extensions get a update suggestion to support the next major release of dependencies (including TYPO3) instead of doing a hard cut. The latter makes upgrading said extension harder since it must be removed once and installed again after the TYPO3 upgrade.

Example with this change:

Prerequisite: Project uses TYPO3v10 and has extension `foo/bar` installed, extension `foo/bar` requires `typo3/cms-core` with `^10.4`

1. Renovate suggests a change to `^11.5` to the `foo/bar` extension which is applied and released
2. Project wants to update to TYPO3v11 and removes `foo/bar` since it is incompatible to TYPO3v11
3. Project updates to TYPO3v11
4. Project installs newer version of `foo/bar` (can include breaking changes, new features and new bugs)

Better approach:

1. Renovate suggests a change to `^10.4 || ^11.5` to the `foo/bar` extension which is applied and released
2. Project wants to update to TYPO3v11 and updates `foo/bar` since it is compatible to both TYPO3v10 and TYPO3v11
3. Project updates to TYPO3v11

**Comment by rarkins** [comment]
Please move it to a discussion or feature request so it doesn't get lost.

**Comment by mbrodala** [comment]
@rarkins You are right, see #14172

**Pull request merged**
