### PR TITLE
feat(swift): add xcode support

### LINKED ISSUE #9735: Support for Xcode project Swift PM Dependencies
**What would you like Renovate to be able to do?**

At present renovate doesn't help manage Swift dependencies from the perspective of an Xcode project. 
Large Xcode projects can have many dependencies and transitive dependencies. Annoyingly, Xcode projects don't handle these dependencies via a `Package.swift` file, like Swift packages themselves do.

**Did you already have any implementation ideas?**

Dependencies are tracked in `project.pbxproj`.

```
/* Begin XCRemoteSwiftPackageReference section */
               A74E51122637DA2D0018AC52 /* XCRemoteSwiftPackageReference "sqlite" */ = {
                       isa = XCRemoteSwiftPackageReference;
                       repositoryURL = "https://github.com/shareup/sqlite.git";
                       requirement = {
                               kind = upToNextMajorVersion;
                               minimumVersion = 15.0.1;
                       };
               };
/* End XCRemoteSwiftPackageReference section */
```

Resolved packages can be found in `app.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/`

### PR DESCRIPTION
**Pull request by Sherlouk**
## Status: Incomplete

As I have very little experience with Renovate, I'm opening this pull request prematurely in the hopes of getting some direction/feedback on certain areas. More information at the bottom.

## Changes

This pull request introduces support for Swift Package Manager dependencies through Xcode, useful for iOS (and other Apple platforms) developers.

## Context

Closes #9735

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

More unit tests will be provided as the implementation continues. A barebones repository has been created ([link](https://github.com/JamesSherlouk/renovate-xcode)) to test out this implementation.

### Pinning vs Resolved

There are really two options with regards to how we detect and update dependencies for Xcode.

1. Every dependency in the package definition file uses "exactVersion". We can use this to know what version Xcode is currently using, and we only need to read/update the package file. It would be solely up to Renovate to provide options around major/minor updates as Xcode will never attempt to update these dependencies.
2. We read the Package.resolved file in order to obtain the "currentVersion", and then update this file *and* the package definition when we apply changes (and open PRs). We would respect Xcode-level requirements (such as "up to next major").

The existing Swift manager currently always updates the definition file (not the resolved file) but this is incompatible with the Xcode IDE (which uses the resolved file as the source of truth). It feels although they should be very similar, the two managers are deviating more (and the Xcode solution may require it's own versioning solution, or at the very best a fair bit of work to make it more flexible to support both)

I believe that the default solution should be number two, as this alters the least of what Xcode provides by default and reduces confusion. Though number one is frankly simpler, and for many folks may be preferred - though this is why we have `rangeStrategy` to provide this as an option.

### Single `swift` manager or keep separate?

Do we believe it makes more sense to bloat the existing Swift manager to handle all scenarios of Swift Package Manager, or keep it separate since their implementation does require small nuances based on the source of the definition.

I believe it would make sense to merge it into one, but this will require quite a bit of rework with the existing solution to make it more compatible. Keeping it separate would allow us to do this more incrementally.

### CODE REVIEW

**Comment by viceice** [comment]
please move the long description to the issue.

**Comment by Sherlouk** [comment]
Unless any objections from people in the community, I think the pinning vs resolved argument makes sense to go with what I have suggested and what I believe most people would expect by default (to maintain Xcode ranges) and upgrade the resolved file.

I'd like to get some input on whether this should be a new manager though, or whether it should be an augmentation to the existing Swift one (despite their differences). I'm happy to make any changes suggested 👍 

Thanks :)

**Comment by viceice** [comment]
> Unless any objections from people in the community, I think the pinning vs resolved argument makes sense to go with what I have suggested and what I believe most people would expect by default (to maintain Xcode ranges) and upgrade the resolved file.
> 
> I'd like to get some input on whether this should be a new manager though, or whether it should be an augmentation to the existing Swift one (despite their differences). I'm happy to make any changes suggested 👍 
> 
> Thanks :)

let's discuss this in the issue.

**Comment by rarkins** [comment]
Let's close this for now due to staleness and conflicts. Very welcome to reopen or recreate at any time once you are able to work on it, thanks

**Pull request closed without merging**
