### PR TITLE
refactor(platform): Change signature types for "updatePr" method

### PR DESCRIPTION
**Pull request by zharinov**
Non-destructive changes cherry-picked from #6988.
Ref: #6986

### CODE REVIEW

**Review by viceice — COMMENTED** [review]
LGTM, but little strange naming: `BranchStatus` vs `PrState`. Should be unified?

**Comment by zharinov** [comment]
> LGTM, but little strange naming: `BranchStatus` vs `PrState`. Should be unified?

Hm, good question. I'll take a look tomorrow if `PrStatus` can be confused/conflicted with something like build statuses, etc.

**Comment by zharinov** [comment]
Well, I think `PrState -> PrStatus` rename can lead to further confusions, because the most of the PR APIs are using `state` field.

**Comment by viceice** [comment]
🤔  Maybe best is to rename `BranchStatus` to `BranchState` as that would be more meanigful.

[status vs state](https://english.stackexchange.com/questions/12958/status-vs-state)

@rarkins @JamieMagee What do you think?

**Comment by rarkins** [comment]
I would normally expect "status" to be like green/yellow/red or passing/pending/failing/etc, while "state" for a PR is open/closed/merged/etc.

**Review by viceice — APPROVED** [review]
Ok, so we leave it as is now

**Pull request merged**
