### PR TITLE
fix: add whitesource/renovate sourceUrl

### PR DESCRIPTION
**Pull request by rarkins**
## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — APPROVED** [review]
You should add it to the docker image like we do with oss renovate 😉

**Comment by viceice** [comment]
https://github.com/renovatebot/docker-renovate/blob/0e7b552f980b2f617ca3700a747d7802f678a198/Dockerfile#L9

**Comment by rarkins** [comment]
> You should add it to the docker image like we do with oss renovate 😉

The same Dockerfile is used for 3 different images via params, so this is easier for me

**Comment by viceice** [comment]
> > You should add it to the docker image like we do with oss renovate 😉
> 
> The same Dockerfile is used for 3 different images via params, so this is easier for me

Can also passed via build-arg 😝

**Pull request merged**
