### PR TITLE
fix: don’t assign if MR already has assignees or reviewers

### LINKED ISSUE #6375: Failing Builds leads to constant re-assigning of reviewers / assignees
#### This is a:

- [X] Bug report (non-security related)
- [ ] Feature request
- [ ] I'm not sure which of those it is

#### I'm using:

- [ ] The Renovate GitHub App
- [ ] Self-hosted GitHub
- [X] Self-hosted GitLab
- [ ] Self-hosted Azure DevOps

#### Please describe the issue:

Sorry for the bad title. It's late on Friday. But we have the following setup:

1. Updates with auto-merge
2. Sampling from a list of assignees/reviewers

This generally works fine, but we have now hit a problem when a Pr Build failed. Renovate was re-assigning a new sample of the people on every run:

https://gitlab.com/gitlab-org/gitlab-ui/-/merge_requests/1447

Traced back the problem to: https://github.com/renovatebot/renovate/blob/d9253ac742648c59340365f53be62fa0268fc251/lib/workers/pr/index.ts#L264-L267 which just triggers on every renovate run in the MR above.

Potential solution:
1. Do not re-assign if already assigned to someone

Workaround: Turned off automerge for now.

### PR DESCRIPTION
**Pull request by rarkins**
Adds new field `hasAssignees` to `Pr` interface, currently supported by GitLab platform only. PR worker then checks that hasAssignees is not `true` before assigning.

Closes #6375

### CODE REVIEW

**Comment by rarkins** [comment]
@leipert please review

**Review by viceice — COMMENTED** [review]
What about `hasReviewers` ?

**Comment by rarkins** [comment]
> What about `hasReviewers` ?

GitLab doesn't have reviewers and my intention was to make this for GitLab first to solve @leipert's problem. But if disabling automerge has taken the pressure off him then perhaps we should do a full solution (assignees, reviewers, all platforms) in the first go.

**Review by viceice — DISMISSED** [review]
🤔 Ok, but we should do it in near future for all platforms and reviewers.

**Comment by leipert** [comment]
@rarkins LGTM!

We have no need to re-enable automerge quickly, so you can fix it in one go 😄 

Automerge is still a bit broken for as, as we require Merge Request approvers. So we unfortunately still need human intervention (approval that is).

**Comment by leipert** [comment]
@rarkins / @viceice Minor bump on this 😉

**Comment by rarkins** [comment]
Ready for review

**Comment by leipert** [comment]
Looks good to me, @rarkins. Thanks!

@viceice ~~Wie schauts?~~ How does this MR look for you?

**Review by viceice — APPROVED** [review]

**Comment by viceice** [comment]
@rarkins i think this is ready for merge?

**Pull request merged**
