### PR TITLE
fix: move checkoutBranch after validation

### PR DESCRIPTION
**Pull request by RahulGautamSingh**
## Changes
- checkout branch only after validation is completed

## Context
- By logic we should only checkout a branch if we need to update it so the `checkoutBranch()` call should be made only after validation.
- `checkoutBranch()` takes around `~300-500ms`* so for repos with many dependencies we can save time during reruns

_PS: *  the time durations were calculated on local setup_

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
Can it be moved any later? e.g. I see

image

I'm guessing that next section would also return if the branch creation isn't scheduled?

**Comment by rarkins** [comment]
I would also like to see some tests on a real repo. e.g. take a repo with one or more updates pending creation but with a schedule which says weekly on monday mornings. In the existing Renovate, that would still clone the repo but with this change can that clone be skipped?

**Comment by RahulGautamSingh** [comment]
> I would also like to see some tests on a real repo. e.g. take a repo with one or more updates pending creation but with a schedule which says weekly on monday mornings. In the existing Renovate, that would still clone the repo but with this change can that clone be skipped?

https://github.com/RahulGautamSingh-testing/move-checkout-branch/pulls

**Comment by rarkins** [comment]
I'm not talking about branch creation (that already works before this PR). I'm talking about whether the run completes without cloning

**Comment by RahulGautamSingh** [comment]
> I'm not talking about branch creation (that already works before this PR). I'm talking about whether the run completes without cloning

I checked by running renovate consecutively on same repo and debugging. 
In local runs the repo was cloned once because my `cache.semanticCommits` is `undefined` . I think it won't be the case in hosted app and we will be able to go no-clone.

**Comment by RahulGautamSingh** [comment]
> I'm not talking about branch creation (that already works before this PR). I'm talking about whether the run completes without cloning

I debugged locally and discovered that cloning occurred in one of these calls: 'getRepoConfig()' and 'extract()' because no cache was present.
Both, I believe, will not occur in a rerun of the hosted app because a cache is present, and we can prevent cloning.

**Comment by rarkins** [comment]
You should test locally with repoCache=true to verify.

**Comment by viceice** [comment]
> You should test locally with repoCache=true to verify.

and do at least two runs 😉

**Comment by viceice** [comment]
> You should test locally with repoCache=true to verify.

i think it needs to be `enabled` instead

**Comment by rarkins** [comment]
Fixed above

**Comment by RahulGautamSingh** [comment]
It is `repositoryCache` 😅

[Here](https://gist.github.com/RahulGautamSingh/098da6ee2e761ccfb7e80ca6e97ec3fe) is the log for the second run.

**Comment by rarkins** [comment]
I'm confused though because it looks like the schedule check is done after the branch checkout, even in your PR. Have you pushed all local changes to GitHub?

**Comment by RahulGautamSingh** [comment]
> I'm confused though because it looks like the schedule check is done after the branch checkout, even in your PR. Have you pushed all local changes to GitHub?

No

**Review by viceice — APPROVED** [review]
🤞

**Pull request merged**
