### PR TITLE
fix(maven): Disable all parent packages by default

### PR DESCRIPTION
**Pull request by zharinov**
## Changes

In most cases (if not all), parent POM is used to define some common variables and isn't published to Maven.

This PR fixes lookups for 2 and more levels of POM parent files.

## Context

- Ref: #25758

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — APPROVED** [review]
so if required a user can enable if required?

**Comment by zharinov** [comment]
Yes, it's optional and can be reverted to current behavior

**Comment by zharinov** [comment]
But I think in reality nobody will want it

**Comment by Churro** [comment]
May I ask why the solution suggested in https://github.com/renovatebot/renovate/discussions/25758#discussioncomment-7574929 wouldn't be enough to solve this?

Disabling updates for all deps with `depType = "parent"` will also prevent updates to regular deps that are no locally defined. An example for this can be found [in the reproduction repo](https://github.com/rarkins/WebGoatNorman/blob/develop/pom.xml): 
```xml
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.6.2</version>
    </parent>
```

**Comment by zharinov** [comment]
Your solution is correct, maybe if these two presets work for everyone, we later could just remove `parent-root` dependency type and prevent lookups for all `parent` deps.

**Comment by zharinov** [comment]
Oh, I see actually some packages publish their parent POMs

**Comment by zharinov** [comment]
@Churro Now I'm not sure I understand your solution. The `if`-clause you propose to remove makes `depType = "parent-root"` from those deps which are already marked as parents. My premise is that parent packages generally aren't used outside of monorepo, so we don't need to lookup them. But in the monorepo, they're being used, but we can't use those versions which are published in Maven anyway. Therefore, both `parent` and `parent-root` could be safely disabled.

**Comment by Churro** [comment]
@zharinov, Yes, making them all `parent-root` also seemed a bit phishy to me and I agree that we wouldn't want to look up dependencies if they are defined locally in parent POMs. 

For others that are not locally defined, such as `spring-boot-starter-parent` in the example above, shouldn't it still be possible to receive updates out-of-the box? This seems to be a **very frequent use-case in practice**, see [here](https://github.com/search?q=spring-boot-starter-parent+path%3A**%2Fpom.xml&type=code&ref=advsearch).

Perhaps I'm overlooking something but isn't the root cause that the `maven` manager impl doesn't properly distinguish between locally and remotely defined parent POMs? It caused `org.owasp.webgoat.lesson:webgoat-lessons-parent` to be looked up, [even though it was defined locally](https://github.com/renovatebot/renovate/discussions/25758). This PR now disabled updates for any parent deps, regardless of where they are defined.

**Comment by breun** [comment]
If @Churro is correct that remotely defined parent POMs are now ignored by default, then I can think of many projects that will no longer get their frameworks updated by Renovate, like application that use Spring Boot for instance. That doesn't sound like a good idea.

**Comment by zharinov** [comment]
Now I think maybe we need to disable only known set of packages which are generating error messages

**Comment by zharinov** [comment]
@rarkins What do you think, should we stick to more targeted solution: https://github.com/renovatebot/renovate/issues/18117#issuecomment-1268548433?

**Pull request merged**
