### PR TITLE
feat(hapi-replacements): added replacements for hapi and joi

### PR DESCRIPTION
**Pull request by travi**
## Changes:

* defined a replacement for `hapi` to `@hapi/hapi`
* defined a replacement for `joi` to `@hapi/joi`
* defined a replacement for `@hapi/joi` to `joi`

## Context:

* hapi was renamed to include the organization scope
* joi was moved out of the hapi organization

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
Do you think we should try to including matchCurrentVersion with these sorts of replacements?

E.g. let's say the use is on v10 of joi and happy. They're probably not ready to migrate..?

If we did it this way, it means Renovate's first focus is on getting them to upgrade to the "latest" version of the existing package, and the second focus is on migrating over to the entry version of the new package.

Cc @JamieMagee

**Comment by JamieMagee** [comment]
Makes sense. So for `hapi` this would be `>=18.0.0` and for `@hapi/joi` this would be `>=17.0.0`?

**Comment by rarkins** [comment]
I think that's probably ok, although the safest option would be to only migrate from the "last" version of the old package.

**Review by viceice — DISMISSED** [review]

**Review by rarkins — CHANGES_REQUESTED** [review]
Let's add matchCurrentVersion to each so that the replacement is at least in the same major range and hopefully compatible. We should try to avoid any major version jumps during replacement migrations unless they're unavoidable/intentional.

**Comment by travi** [comment]
> Renovate's first focus is on getting them to upgrade to the "latest" version of the existing package, and the second focus is on migrating over to the entry version of the new package.

just hoping to understand the full goal. i agree with upgrading before replacing, but would this prevent the replacement PR from being created until the project is first upgraded?

i think there is value to the visibility that both tasks are outstanding, similar to how a PR is sent for an upgrade within the range of the current major and a second PR is also sent for the major bump in cases where both are possible. sometimes major upgrades are delayed because they require additional effort. 

when seeing a PR that would upgrade through multiple majors, that can be more motivating than a single major bump, at least because it becomes more clear how far out of date the project has become. i think similar can be true here. if a PR for a major bump is open, it might be ignored for a bit, but no additional major would ever come because the package has been renamed. if there were an open major bump PR _and_ a package rename PR, that could be more motivating to the project team.

am i overthinking this scenario? am i just misunderstanding the goal?

**Comment by rarkins** [comment]
> am i overthinking this scenario? am i just misunderstanding the goal?

Not necessarily but I don't think that the complexity of supporting major updates + replacement in one PR is worth it. If we propose major upgrades plus a migration then we *won't* be able to provide the necessary release notes, for example. Note: there's nothing stopping you creating your own replacement presets in a central config which override Renovate's default ones.

Perhaps a compromise is to migrate when it's a *compatible* release (same major) and not just wait for latest version of the current package.

One other relevant point is that migrated packages *should* also be marked as deprecated on npmjs and we *should* find a way to display this. We once did it with issues, but it was too noisy and error prone so got rolled back and never rolled forward again. I think displaying in the dashboard would be best, meaning from a visibility point of view the user would see:
- Notice that current package is deprecated (hopefully it says which package to update to)
- Pending update of current package

**Comment by travi** [comment]
> I don't think that the complexity of supporting major updates + replacement in one PR is worth it.

i was thinking that was the the existing behavior, so i was only advocating for not preventing it. if it has a meaningful complexity difference for you to manage, i certainly understand avoiding it.

> One other relevant point is that migrated packages _should_ also be marked as deprecated on npmjs and we _should_ find a way to display this.

i agree that this would be valuable. in the `hapi` case, the part of the deprecation message stating "This version contains severe security issues and defects and should not be used!" is a big part of my motivation for suggesting what i did. without the replacement PR, the team may not be aware of a deprecation like that, but making that visible in another way could certainly cover that desire. 

> I think displaying in the dashboard would be best,

i admit that i have not gotten in the habit of checking the dashboard when there arent github notifications associated with it. it often takes realizing that a PR hasnt come through for a specific dependency, likely because it was accepted and then rolled back at some point, before i seek out the dashboard. when managing many independent projects, it can be a while before this realization happens. i could see information like this being missed in many cases. i don't have a better idea other than some sort of account-level dashboard, but that would be my hesitation of this information only being on the dashboard.

> Note: there's nothing stopping you creating your own replacement presets in a central config which override Renovate's default ones.

i've already started doing this for replacements that arent relevant more globally, including for some cases where i've changed my own convention around which library i use (`check-engine` -> `ls-engines` or `markdownlint-cli` -> `remark-cli`, for example.). however, i think folks that are mature enough to go to this length are likely less in need of the notifications that they are as far behind because they are more likely to be doing the work to not grow so stale. this may be an uninformed assumption and there are certainly exceptions like my semi-abondoned side-projects where i've found some older deps that havent had proper attention.

> Let's add matchCurrentVersion to each so that the replacement is at least in the same major range and hopefully compatible.

i'll get this PR updated. the situation with `joi` becomes a little more complex following this approach, but probably proves your point further. it was originally named `joi`, but later gained the `@hapi` scope and later still went back from `@hapi/joi` to `joi` again. with this approach, we can capture both changes and guide folks through the most compatible upgrade path.

would you like me to follow this PR with another that updates existing replacements to follow this approach as well?

**Comment by rarkins** [comment]
> i was thinking that was the the existing behavior, so i was only advocating for not preventing it. if it has a meaningful complexity difference for you to manage, i certainly understand avoiding it.

Yes, Renovate can keep supporting large jumps in a replacement, but specifically I want our built-in presets to keep them to a minimum.
 
> i agree that this would be valuable. in the `hapi` case, the part of the deprecation message stating "This version contains severe security issues and defects and should not be used!" is a big part of my motivation for suggesting what i did. without the replacement PR, the team may not be aware of a deprecation like that, but making that visible in another way could certainly cover that desire.

I think once we surface deprecation messages again - which I consider to be related but a separate feature - then this will be largely solved.

> i admit that i have not gotten in the habit of checking the dashboard when there arent github notifications associated with it. 

Another idea would be noting in each PR that there's warnings which need checking (maybe deprecations can be considered their own first class concept though with their own count). Then you have a chance to see that in each PR you get, so then you only are unaware if you are not looking at the dashboard *or* getting PRs, so the chances are lower.

**Review by rarkins — APPROVED** [review]

**Comment by HonkingGoose** [comment]
> I think once we surface deprecation messages again - which I consider to be related but a separate feature - then this will be largely solved.

For reference, we're using issue #5098 to track this work. 😉

**Comment by travi** [comment]
> specifically I want our built-in presets to keep them to a minimum.

totally fair. makes sense to me. thanks for walking me through your reasoning

> would you like me to follow this PR with another that updates existing replacements to follow this approach as well?

still happy to do this if you'd like the others to follow the same approach

> Another idea would be noting in each PR that there's warnings which need checking (maybe deprecations can be considered their own first class concept though with their own count).

i like this idea. i think i would be more likely to spot the information there. while i do auto-merge almost everything that passes checks, i do still read my GH notifications to at least catch up on release notes.

**Comment by travi** [comment]
oops, looks like i didnt consider the range fully enough for that `joi` to `@hapi/joi` replacement: https://github.com/form8ion/javascript/pull/62. i'll get another PR up to narrow that soon

**Comment by travi** [comment]
#13205 is up

**Pull request merged**
