### PR TITLE
feat(ruby): Switch to @renovate/ruby-semver library

### PR DESCRIPTION
**Pull request by zharinov**

### CODE REVIEW

**Review by viceice — DISMISSED** [review]

**Comment by ViceIce** [comment]
@rarkins Anything blocking this?

**Review by viceice — APPROVED** [review]

**Review by viceice — CHANGES_REQUESTED** [review]
needs deconflicting

**Comment by JamieMagee** [comment]
@zharinov @viceice I fixed the conflicts. Looks like this is ready for merge.

**Review by viceice — DISMISSED** [review]

**Review by viceice — CHANGES_REQUESTED** [review]
needs `yarn.lock` deconflicting

**Pull request merged**
