### PR TITLE
feat: support template in labels

### LINKED ISSUE #8137: Support template in labels
**What would you like Renovate to be able to do?**

Support template in labels. https://docs.renovatebot.com/templates/
For example,

```json
{
  "labels": [
    "renovate:depName={{depName}}",
    "renovate:newVersion={{newVersion}}"
  ]
}
```

By supporting template in labels,

* We can search pull requests with label
  * This is especially useful if we split pull requests with `additionalBranchPrefix`
* We can change the behavior of CI by getting labels in CI

**Did you already have any implementation ideas?**

I have already implemented this feature, so I'll send a pull request.

### PR DESCRIPTION
**Pull request by suzuki-shunsuke**
## Changes:

* Add `addLabels` and `labels` to `exposedConfigOptions`
* When a pull request is created, compile labels with template

## Context:

Closes #8137 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] Unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — COMMENTED** [review]
Please create a test repo with sample pr

**Comment by suzuki-shunsuke** [comment]
Thank you for your review.

I have created a sample repo and prs.

* PRs
  * https://github.com/minimum-core/test-renovate/pull/8
  * https://github.com/minimum-core/test-renovate/pull/7
  * https://github.com/minimum-core/test-renovate/pull/6
* renovate.json: https://github.com/minimum-core/test-renovate/blob/b53eb5992a046e359e4d18baf9f434cbca5ffbc5/renovate.json 

```
~/repos/src/github.com/renovatebot/renovate feat/expose-labels
❯ git rev-parse HEAD
b4fae8252283ab0a8bb442e0b7571e6bab2ff405

~/repos/src/github.com/renovatebot/renovate feat/expose-labels
❯ yarn start minimum-core/test-renovate
yarn run v1.22.4
$ run-s generate:* 
$ node tmp/tools/generate-imports.js
generating imports
> data/extract.py
> data/node-js-schedule.json
> lib/datasource/
> lib/manager/
> lib/platform/
> lib/versioning/
$ babel-node --extensions ".ts,.js" -- lib/renovate.ts minimum-core/test-renovate
 INFO: Repository started (repository=minimum-core/test-renovate)
       "renovateVersion": "0.0.0-semantic-release"
 INFO: Dependency extraction complete (repository=minimum-core/test-renovate)
       "baseBranch": "main",
       "stats": {
         "managers": {"helmfile": {"fileCount": 1, "depCount": 3}},
         "total": {"fileCount": 1, "depCount": 3}
       }
 INFO: Branch created (repository=minimum-core/test-renovate, branch=renovate/helmfile-datadog-2.x)
       "commitSha": "e62b223"
 INFO: PR created (repository=minimum-core/test-renovate, branch=renovate/helmfile-datadog-2.x)
       "pr": 6,
       "prTitle": "Update Helm release datadog to v2.6.7 (helmfile)"
 INFO: Branch created (repository=minimum-core/test-renovate, branch=renovate/helmfile-ingress-nginx-3.x)
       "commitSha": "e8ed97c"
 INFO: PR created (repository=minimum-core/test-renovate, branch=renovate/helmfile-ingress-nginx-3.x)
       "pr": 7,
       "prTitle": "Update Helm release ingress-nginx to v3.17.0 (helmfile)"
 INFO: Branch created (repository=minimum-core/test-renovate, branch=renovate/helmfile-velero-2.x)
       "commitSha": "3906b71"
 INFO: PR created (repository=minimum-core/test-renovate, branch=renovate/helmfile-velero-2.x)
       "pr": 8,
       "prTitle": "Update Helm release velero to v2.14.4 (helmfile)"
 INFO: Repository finished (repository=minimum-core/test-renovate)
       "durationMs": 45903
✨  Done in 52.15s.
```

**Review by viceice — APPROVED** [review]
LGTM, waiting for second review to approve the approach.

**Review by dstiers11 — APPROVED** [review]
9

**Review by dstiers11 — APPROVED** [review]

**Pull request merged**
