### PR TITLE
feat(gitlab-releases): add gitlab-releases datasource

### LINKED ISSUE #7534: feat(gitlab): gitlab-releases
**What would you like Renovate to be able to do?**
Would be nice to have also gitlab-releases datasource

**Did you already have any implementation ideas?**
Should be similar to this:
- https://github.com/renovatebot/renovate/tree/master/lib/datasource/gitlab-tags
- https://github.com/renovatebot/renovate/tree/master/lib/datasource/github-releases

**Are there any workarounds or alternative ideas you've tried to avoid needing this feature?**
no

**Is this a feature you'd be interested in implementing yourself?**
no

Docs: https://docs.gitlab.com/ee/api/releases/

### PR DESCRIPTION
**Pull request by nejch**
## Changes:

Adds support for gitlab releases. This is embarrassingly similar to `gitlab-tags`, basically the endpoint and fields returned by the release API are different. But I saw that there's currently some refactoring going on in datasources so wasn't sure it was worth deduplicating only for it to be refactored again later (and github-tags/github-releases seemed to also have quite a bit of duplicate code).

Not sure how much value this has over gitlab tags since it seems like renovate will already fetch changelogs from release notes even for gitlab tags, but in the end it's possible some people might want to only update on releases, not on every tag.

Test MR on real repo:
https://gitlab.com/renovate-gitlab-releases/renovate-gitlab-releases/-/merge_requests/2

## Context:

Closes https://github.com/renovatebot/renovate/issues/7534.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — COMMENTED** [review]
I think this new datasource should directly be writen as class, so we don't need to refactor again.

**Comment by secustor** [comment]
@nejch Are you still working on this? If not, I would look into implementing it.

**Comment by rarkins** [comment]
@secustor I think you can branch off this PR's branch and submit as a superseding PR

**Comment by nejch** [comment]
> 
> 
> @secustor I think you can branch off this PR's branch and submit as a superseding PR

Sorry people, I've been busy so if you already start feel free, otherwise I can get back to it next week

**Comment by JamieMagee** [comment]
Closing this due to #11226

**Pull request closed without merging**
