### PR TITLE
docs(self-hosted): describe purpose and usage of privateKey option

### LINKED ISSUE #598: How to correctly generate public/private key pair
### Which Renovate are you using?
Renovate Open Source CLI

### Which platform are you using?

GitLab self-hosted

### What would you like to do?

We want to use Renovate's `encrypted` functionalty in our self-hosted setup (similar to what you mentioned in https://github.com/renovatebot/config-help/issues/331#issuecomment-522551925) and are struggling to generate a public/private key pair that works both for renvoate itself and also the encryption site.

Could you provide a snippet on how to generate the keys correctly? Once we got it working I'll open a PR against https://docs.renovatebot.com/self-hosted-configuration/#privatekey.

### PR DESCRIPTION
**Pull request by fgreinacher**
Closes https://github.com/renovatebot/config-help/issues/598

### CODE REVIEW

**Comment by JamieMagee** [comment]
@fgreinacher I updated your title to a semantic commit format.

**Comment by fgreinacher** [comment]
> @fgreinacher I updated your title to a semantic commit format.

Thanks!

> Also, It seems like current recommendations suggest key sizes of 2048-bit or above. [From Wikipedia](https://en.wikipedia.org/wiki/Key_size):
> 
> > RSA claimed that 1024-bit keys were likely to become crackable some time between 2006 and 2010 and that 2048-bit keys are sufficient until 2030. NIST recommends 2048-bit keys for RSA. An RSA key length of 3072 bits should be used if security is required beyond 2030.

Yeah, we used a 4096-bit key in our instance, so I document it like that :)

**Comment by JamieMagee** [comment]
Might also be worth including the command to encrypt secrets from the CLI. I think it is

```

**Comment by viceice** [comment]
What about adding a new page for encryption to the docs? so we have a single page with extended docu for creating keypairs and encrypting values.

**Comment by rarkins** [comment]
OK, but let's not let perfect be the enemy of good. I'm going to accept this PR for now and we can add a new page later dedicated to encryption (privateKey and gitPrivateKey I think?). I think I need to rename the latter variable anyway.

**Pull request merged**
