### PR TITLE
refactor: Remove depnameShort of terra* and kustomize

### PR DESCRIPTION
**Pull request by secustor**
## Changes:

Remove depNameShort of: 
- terraform
- terragrunt
- kustomize

## Context:

#8075

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added unit tests, or
- [ ] Unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — CHANGES_REQUESTED** [review]
This is possibly a breaking, becuase user configs can use `depNameShort`  which we don't know.

There is also no easy migration.

**Comment by viceice** [comment]
@rarkins  How should we handle the backward compability? Try to do some config migration? Migration in template processing?

**Comment by rarkins** [comment]
If want to do it in steps then we can do this:

1. Add logic somewhere around update flattening to set `dep.depNameShort ||= dep.depName` for backwards compatibility
2. Refactor managers progressively
3. Once they're all refactored, add migration logic to search/replace `{{depNameShort}}` to `{{depName}}`.
4. Additionally, add logic - maybe during compile step - to log a deprecation warning if we find `{{depNameShort}}` in any string being compiled
5. Remove `dep.depNameShort ||= dep.depName` in a future major release

**Review by viceice — APPROVED** [review]
Can be merge now as we already have #8401 merged

**Pull request merged**
