### PR TITLE
fix(cargo): default auto to update-lockfile

### PR DESCRIPTION
**Pull request by rarkins**
## Changes

rangeStrategy=auto should default to rangeStrategy=update-lockfile for Cargo

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — APPROVED** [review]

**Comment by yanns** [comment]
I'm still seeing the behavior of opened PR for minor versions when using https://www.mend.io/renovate/.
Is there something I can check? Ask https://www.mend.io/renovate/ to update?

**Comment by rarkins** [comment]
Please start a new discussion

**Comment by yanns** [comment]
> Please start a new discussion

https://github.com/renovatebot/renovate/discussions/29181

**Comment by yanns** [comment]
> Please start a new discussion

I've updated the discussion I've already started: https://github.com/renovatebot/renovate/discussions/28782#discussioncomment-9555622
Or do you really prefer a new one?

**Pull request merged**
