### PR TITLE
refactor: remove versioning destructuring

### PR DESCRIPTION
**Pull request by rarkins**

### CODE REVIEW

**Comment by rarkins** [comment]
It was hard to decide what naming to do here. `versioning` and `versionScheme` are already taken, e.g. `versioning.get(versionScheme)`. So that leaves `v` and `version`, both of which got used here and there. I decided to go with `version`, i.e. `const version = versioning.get(versionScheme)`, which meant needing to rename some filter/map functions to use `v` instead of `version`. WDTY?

**Comment by rarkins** [comment]
One other alternative: using the more vague `ver`, which would eliminate the need for renaming `version` => `v`

**Comment by rarkins** [comment]
I also wonder if `const v = versioning.get(versionScheme)` would also work and be low impact

**Review by viceice — APPROVED** [review]
Ok, i think the variable rename is ok for that to be consistent. `ver` sounds strange.

**Comment by ViceIce** [comment]
`v` schould only be used for small arrow functions, otherwise it would be difficult to understand bigger code

**Pull request merged**
