### PR TITLE
docs: shareable configs only work with JSON format

### PR DESCRIPTION
**Pull request by HonkingGoose**
## Changes:

- Document that shareable configs only work with the JSON format

## Context:

Based on end-user confusion about shareable configs not working with the JSON5 format (see discussion #10087).

For now we only support the normal JSON format until we implement feature request in issue #7674.

I did a search for `share` in the `*.md` files, and added the information that JSON is the only supported format if you want to use the shareable config.

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by rarkins — APPROVED** [review]

**Review by viceice — APPROVED** [review]
I think we can allow json5 in a future pr, as it won't open security concerns, it just allows some easier syntax. Eg inline comments.

**Comment by bmuenzenmeyer** [comment]
I'd be interested in giving a go at json5 support if you accept outside contributions.

**Comment by viceice** [comment]
> I'd be interested in giving a go at json5 support if you accept outside contributions.

Sure, shouldn't be hard, as we already have and use `json5` dependency.

**Review by JamieMagee — APPROVED** [review]

**Comment by bmuenzenmeyer** [comment]
> Sure, shouldn't be hard, as we already have and use `json5` dependency.

@viceice can you give me the shortest of clues as to what file(s) to start looking at? I am happy to put in the work, but an initial set of breadcrumbs is invaluable.

**Comment by viceice** [comment]
> > Sure, shouldn't be hard, as we already have and use `json5` dependency.
> 
> @viceice can you give me the shortest of clues as to what file(s) to start looking at? I am happy to put in the work, but an initial set of breadcrumbs is invaluable.

You need to check files `lib/config/presets/...` and the json methods in `lib/platform/...`, which are used to fetch local or hosted presets.

**Pull request merged**
