### PR TITLE
feat: apply package.json renovate config to whole repository

### LINKED ISSUE #1323: Apply package.json config globally in monorepos
Currently, if you have a monorepo then you have no choice but to use a `renovate.json` file. If you add your config to your project's root `package.json` then that config would apply only to that `package.json` instead of to the entire repository.

With this issue, I propose changing this behaviour so that `package.json` renovate config will be applied globally, unless overridden.

### PR DESCRIPTION
**Pull request by rarkins**
Changes the way Renovate treats renovate config inside `package.json` files. Before, config used to be applied only to that particular file, meaning that it was not applied for the rest of a monorepo, or for other package managers like Docker. Now, any `renovate` section inside the repository’s root `package.json` will be applied globally, just the sams as if it were contained within a `renovate.json` file. This means there is no longer any case where you *must* have a `renovate.json` file instead of `package.json`.

Closes #1323

BREAKING CHANGE: renovate config in `./package.json` is applied to whole repository, and renovate config inside non-root `package.json` is now ignored.

### CODE REVIEW

**Comment by rarkins** [comment]
@hbetts @destroyerofbuilds what do you think of this?

I did a check of logs from the 2500+ repositories managed by the GitHub App and not a single one of them has a `renovate` config section inside a `package.json` outside the root. I think for everyone else, it's unintuitive that the config *doesn't* currently apply to the whole app, because that's what every other app that offers `package.json` config does. The cases for this increases as the number of monorepos increases + multi-lang too (e.g. Docker).

Marking it as a breaking change naturally.

**Comment by destroyerofbuilds** [comment]
> This means there is no longer any case where you must have a renovate.json file instead of package.json.

I didn't realize there was an inconsistency there. I had assumed `renovate` configuration in `package.json` was applying to the entire repository (of a monorepo), so this change seems only to bring out the behavior that seemed intuitive to me.

**Comment by rarkins** [comment]
Heads-up @vvo and @Haroenv - this is now live in the app. Feel free to move any remaining `renovate.json` configs to `package.json>renovate`

**Comment by Haroenv** [comment]
Perfect!

**Pull request merged**
