### PR TITLE
fix: Azure DevOps (Service & Server)

### PR DESCRIPTION
**Pull request by jycouet**
Azure DevOps exists in two versions:
- Service (previously VSTS, the cloud version)
- Server (previously TFS, the on-premise version)

I was working a lot with the cloud version and renovate is working fine there.
But with the on-premise version, the way to clone the repo is a little bit different.

This PR is to get the clone cmd working on the two versions of DevOps.

### CODE REVIEW

**Comment by rarkins** [comment]
What's the logic behind the reordering and whitespace addition in the imports?

**Comment by jycouet** [comment]
It's my VSCode plugin **Beautify** who did this. He thinks it's "nicer", I didn't look more since **lint** didn't complain. But I can revert this styling part if you want.

**Comment by rarkins** [comment]
Yes, I prefer to leave things unchanged unless necessary

**Comment by rarkins** [comment]
Reference: https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops#use-your-personal-access-token

**Comment by JamieMagee** [comment]
I'm not sure that this change does anything. The documentation linked states that it applies to

>Azure DevOps Services | Azure DevOps Server 2019 | TFS 2018 | TFS 2017

Which includes the SaaS & on prem offering for Azure DevOps, and it explicitly says that anything can be used as the username

>See the following examples of using your PAT.
>
>Username: yourPAT
>Password: yourPAT
>or
>
>git clone https://anything:{yourPAT}@dev.azure.com/yourOrgName/yourProjectName/_git/yourRepoName

In fact it may actively be harmful if some string is expected in the username field. I haven't had a chance to test against Azure DevOps SaaS yet (And I don't have access to an on prem server to test that either)

**Comment by jycouet** [comment]
I'm struggling with this issue for the last few days... And yes depending on where you look you find different informations... (I also added a comment on a Feedback Microsoft site to help others) 

Fortunately, I do use daily the two environments and with my tests, this fix fixed my issue. 

Now both environments should work correctly

**Comment by JamieMagee** [comment]
Okay, if you've tested across both and it works then I'm happy

**Pull request merged**
