### PR TITLE
fix(npm): massage package-lock.json before update

### PR DESCRIPTION
**Pull request by rarkins**
## Changes:

Massages out `node_modules/` entries from `package-lock.json` before running `npm`.

## Context:

Closes #12442

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — COMMENTED** [review]
Looks very hacky to me 🤔

**Comment by rarkins** [comment]
Unfortunately npm@7 doesn't play very nice. Discussion here: https://github.com/renovatebot/renovate/discussions/12442#discussioncomment-1586348

**Comment by viceice** [comment]
i know, but is it fixed in npm v8? so we can suggest people to upgrade to npm v8?

**Comment by rarkins** [comment]
No, I tested with npm 8

**Pull request merged**
