### PR TITLE
feat: Add support for gitlab-ci include statements

### LINKED ISSUE #3932: Support for .gitlab-ci.yml include:file
**What would you like Renovate to be able to do?**
I'd like renovate to be able to renovate pinned versions of https://docs.gitlab.com/ee/ci/yaml/#includefile

e.g. a section in .gitlab-ci.yml like:
```
  - project: 'my-group/my-project'
    ref: v1.0.0
    file: '/templates/.gitlab-ci-template.yml'
```

**Describe the solution you'd like**
For renovate to update this to the latest tag of the referenced project

**Describe alternatives you've considered**
Haven't considered alternatives

### PR DESCRIPTION
**Pull request by mikebryant**
Support the include statement of .gitlab-ci.yml

Closes #3932

### CODE REVIEW

**Comment by mikebryant** [comment]
Testing locally generated https://gitlab.com/mikebryant/include-renovate-example/merge_requests/2/diffs

**Comment by mikebryant** [comment]
Tests are failing to do with the platform api change - I'm not sure if that's the right way to go yet, so haven't bothered trying to fix the test.

Also not sure about the new manager vs integrating into the gitlabci manager thing. (Haven't integrated at the moment because that means all of the messages are about docker, which isn't correct)

**Comment by rarkins** [comment]
Thanks, I’ll take a look soon and let you know. No need to worry about tests until we’re sure on the right approach.

**Comment by rarkins** [comment]
Hi @mikebryant, thanks again for the PR.

You're exactly right that our current approach of having the gitlabci manager inherit from "docker" is logically flawed. The same flaw applies to 1-2 other managers already too, so I've been trying to work out the best way to fix it. Essentially, these "parent" settings like `docker` should be tied to *datasources* now, not *managers*.

So if I fix that, it means we can unify the gitlabci managers. Maybe for now we leave as-is, as it doesn't really do any harm.

Next challenge is where to get the endpoint/repository info from. Right now you fetch that in datasource by querying platform, but I think we could consider doing this as part of the extract function. The extract function can actually take extra parameters:

```
async function extractPackageFile(content, packageFile, config) {

```

So the `endpoint` and current `repository` could be learned from that. This way result of the extract can be a fully specified repo and datasource doesn't need to query platform.

**Comment by mikebryant** [comment]
Thanks for the info, that's really helpful.

I'll continue with it as a separate manager, so I'm not blocked on that refactoring (and I don't feel up to that challenge right now).

On that config parameter, that's really useful, I will dig into that and make use of it, that definitely seems a better way.

**Comment by mikebryant** [comment]
@rarkins Have changed the way endpoint gets found, and added tests. :)

**Comment by mikebryant** [comment]
@rarkins Is there anything else I should be doing? :)

**Comment by rarkins** [comment]
@mikebryant sorry for the delay in merging. There was one thing else I wanted to change first but thought I’d do it myself rather than ask you.. and then time slipped away. I’ll try to get to it soon.

**Comment by mikebryant** [comment]
Ok, thanks for the update :)

**Comment by rarkins** [comment]
@mikebryant I've made the changes I wanted. Can you check it again to make sure it functions as you intend?

**Comment by mikebryant** [comment]
Will do, thanks!

**Comment by mikebryant** [comment]
@rarkins It's still working as I expect :)

**Comment by mikebryant** [comment]
So everything looks good and the tests are passing - would we be able to get this merged and I'll get some real-world usage going on it?

**Comment by rarkins** [comment]
@mikebryant fyi when I enabled this in the app, it hit a few cases where the YAML parsing resulted in a logger.error(). I have lowered this to warn so that I don't get alerts.

**Comment by mikebryant** [comment]
Interesting, thanks for the update. Makes sense :)

**Pull request merged**
