### PR TITLE
fix(preset): remove invalid reference

### LINKED ISSUE #8371: Renovates fails during config validation
**What Renovate type, platform and version are you using?**

I'm using renovate with a GitHub app. Logs say renovate version is `24.26.2`

**Describe the bug**

Renovated started failing during config validation without any changes on my end.

**Relevant debug logs**

```
DEBUG: Preset fetch error
{
  "preset": "workarounds:ignoreSbtLatestIntegration",
  "err": {
    "message": "Cannot convert undefined or null to object",
    "stack": "TypeError: Cannot convert undefined or null to object
  at Function.keys (<anonymous>)
  at getPreset (/home/ubuntu/renovateapp/node_modules/renovate/dist/config/presets/index.js:178:31)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (internal/process/task_queues.js:97:5)
  at async resolveConfigPresets (/home/ubuntu/renovateapp/node_modules/renovate/dist/config/presets/index.js:222:37)
  at async resolveConfigPresets (/home/ubuntu/renovateapp/node_modules/renovate/dist/config/presets/index.js:252:38)
  at async Object.resolveConfigPresets (/home/ubuntu/renovateapp/node_modules/renovate/dist/config/presets/index.js:252:38)
  at async mergeRenovateConfig (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/init/config.js:194:52)
  at async Object.getRepoConfig (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/init/config.js:231:14)
  at async Object.initRepo (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/init/index.js:19:14)
  at async Object.renovateRepository (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/index.js:60:18)
  at async renovateRepository (/home/ubuntu/renovateapp/app/worker/index.js:359:26)
  at async /home/ubuntu/renovateapp/app/worker/index.js:587:5"
  }
}
```

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [ ] I have provided a minimal reproduction repository
- [x] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

Linked repo https://github.com/erezrokah/2fa-with-slack-action/blob/92f87c4678a98999ba2e0a12d540ca2f42fa1c97/renovate.json

Issue https://github.com/erezrokah/2fa-with-slack-action/issues/237

### PR DESCRIPTION
**Pull request by viceice**
## Changes:

regression of #8363

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] Unit tests + ran on a real repository

### CODE REVIEW

**Comment by viceice** [comment]
@zharinov 😉

**Comment by zharinov** [comment]
😔

**Comment by zharinov** [comment]
BTW, how hard would it be to make simple smoke test to check such failures with CI? I mean, to test it can start and finish with non-error code in default mode with the simplest repo possible.

**Comment by viceice** [comment]
It would need a secret token, which makes it hard to test pr's

A simple solution will be to validate all internall presets with a unit test.

**Comment by rarkins** [comment]
Yes, we should validate the internal presets

**Comment by zharinov** [comment]
Okay, I'll figure it out

**Pull request merged**
