### PR TITLE
fix(versioning/hashicorp): allow v versions from npm

### PR DESCRIPTION
**Pull request by rarkins**
## Changes

Allows `v` versions instead of throwing

## Context

Errors thrown in the hosted app

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
@mcfedr I'm not sure if this is the best way to fix this, but at least it should stop it throwing for values like `v4.0.1`

**Comment by rarkins** [comment]
This may fix #19766 if the original fix didn't

**Review by viceice — APPROVED** [review]

**Comment by mcfedr** [comment]
Interesting that it happens, as npm2hashicorp is only called on the results of hashicorp2npm which ought to remove all "v"s - ice done this as npm spec doesn't allow them, although I notice the implementation of npm is very forgiving

**Comment by mcfedr** [comment]
Im now thinking throwing wasn't a great idea in a code base that doesn't expect it!

**Pull request merged**
