### PR TITLE
feat(gitlab): Allow using an OAuth2 token for authentication

### PR DESCRIPTION
**Pull request by julienp**
GitLab supports passing a Personal Access Token as an OAuth-compliant authorization header: https://docs.gitlab.com/ee/api/README.html#personalproject-access-tokens

This change allows using either a PAT or an OAuth2 token for GitLab.

### CODE REVIEW

**Review by viceice — COMMENTED** [review]
Does it work with all supported gitlab versions?

**Comment by rarkins** [comment]
This would be good to merge assuming it works with all supported GitLab versions. The `private-token` header always seemed like a weird hack

**Comment by julienp** [comment]
It looks like this was added in 12.2 a year ago. https://gitlab.com/gitlab-org/gitlab-foss/-/merge_requests/30277 

Which GitLab versions does renovate support? GitLab uses the token length to check if the Bearer token is a PAT or OAuth2 token. https://gitlab.com/gitlab-org/gitlab/-/blob/bd812df54f5b5363d39b55e537fc8bf1dc6991a7/lib/gitlab/auth/auth_finders.rb#L218
If we wanted to support versions older than 12.2 we could do the same and set the `Private-Token` header if the token has a length of 20 and use a Bearer otherwise.

**Comment by viceice** [comment]
I think it's ok to drop gitlab support for versions older than 12.2, because they are unsupported and have security issues fixed only in later versions.

gitlab only support last three minor versions, see https://docs.gitlab.com/ee/policy/maintenance.html#security-releases

btw: needs deconflicting

**Comment by julienp** [comment]
I fixe the conflicts. Not sure why the `license/cla` check is failing. I signed the CLA and it passed previously.

**Review by viceice — APPROVED** [review]

**Comment by thib3113** [comment]
just FYI, my company doesn't use the last version of gitlab, and hard to update the gitlab server .... 

So, I will need to fix my renovate version to 23.13.* .

**Comment by viceice** [comment]
@thib3113 Please open a new issue if you need support for older gitlab server version. Which version are you using?

**Comment by thib3113** [comment]
> @thib3113 Please open a new issue if you need support for older gitlab server version. Which version are you using?

11.10.1 .

In fact, I'm not asking for support, just to inform that some companies are always using old gitlab versions, and sometimes they can't upgrade it ( or need time ) .... 

For me, I will just set the renovate docker image version to 23.13

**Comment by rarkins** [comment]
Let's test if we can send both tokens at the same time. If old and new GitLab are ok with that, we can do it.

**Comment by viceice** [comment]
@thib3113 Hopefully you gitlab server is only accessible from your intranet, otherwise you have a highly vulnerable system on internet.

https://www.cvedetails.com/vulnerability-list/vendor_id-13074/Gitlab.html

**Comment by thib3113** [comment]
> @thib3113 Hopefully you gitlab server is only accessible from your intranet, otherwise you have a highly vulnerable system on internet.
> 
> https://www.cvedetails.com/vulnerability-list/vendor_id-13074/Gitlab.html

I doesn't have the access to update it .... I can just transmit the informations to another people ... And security is not really the first priority of most of company ... ( it need to be, but it's like backups ... before a problem, we don't saw it )

**Comment by viceice** [comment]
> It looks like this was added in 12.2 a year ago. https://gitlab.com/gitlab-org/gitlab-foss/-/merge_requests/30277
> 
> Which GitLab versions does renovate support? GitLab uses the token length to check if the Bearer token is a PAT or OAuth2 token. https://gitlab.com/gitlab-org/gitlab/-/blob/bd812df54f5b5363d39b55e537fc8bf1dc6991a7/lib/gitlab/auth/auth_finders.rb#L218
> If we wanted to support versions older than 12.2 we could do the same and set the `Private-Token` header if the token has a length of 20 and use a Bearer otherwise.

@julienp Are you able to send a pr to readd support for older gitlab versions?

**Comment by julienp** [comment]
@thib3113 I attempted to fix this here https://github.com/renovatebot/renovate/pull/7155 but I didn't have access to an old GitLab installation, could you test if it works with 23.14.4+ ?

**Comment by thib3113** [comment]
> @thib3113 I attempted to fix this here #7155 but I didn't have access to an old GitLab installation, could you test if it works with 23.14.4+ ?

works with 23.16.0 . Thank you

**Pull request merged**
