### PR TITLE
feat(presets): add monorepo weasel

### PR DESCRIPTION
**Pull request by Xzelsius**
## Changes

Adds monorepo preset for Weasel

## Context

Individual [Weasel](https://github.com/JasperFx/weasel) packages should be updated together

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by rarkins — DISMISSED** [review]

**Review by rarkins — APPROVED** [review]

**Comment by Xzelsius** [comment]
@rarkins Do I need to do something for the checks to run? Is it because the branch is out-of-date?
I don't want to cause you more work by constantly merge main in if it's not needed by your workflow.

**Review by rarkins — APPROVED** [review]

**Comment by rarkins** [comment]
There may be an unresolved conversation blocking it

**Comment by rarkins** [comment]
Merging won't help resolve a conversation

**Comment by rarkins** [comment]
It hopefully merges this time

**Pull request merged**
