### PR TITLE
refactor(gradle): Refactor manager test mocks

### PR DESCRIPTION
**Pull request by zharinov**
## Changes:

Simplify test mocks. Now it doesn't rely on temp dirs.

## Context:

Blocks #9932

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by zharinov** [comment]
@viceice Can you please run this test on Windows?

**Review by viceice — COMMENTED** [review]
Doesn't work as expected 
image

**Comment by viceice** [comment]
Pushed another commit to fully use our fs wrapper, you now need to fix the tests 😉

**Comment by zharinov** [comment]
Thanks, I'll try to test it on my own, using Virtual Box and Windows 10 developer images

**Comment by zharinov** [comment]
Now it should pass in Windows platform, I've made my own check

**Review by viceice — APPROVED** [review]

**Pull request merged**
