### PR TITLE
feat(automerge): recurse after automerge

### LINKED ISSUE #10239: Recurse after automerge
**What would you like Renovate to be able to do?**

Immediately run one more time after any automerge has completed, to rebase the remaining branches if necessary.

**Did you already have any implementation ideas?**

Recurse the `renovateRepository()` function.

### PR DESCRIPTION
**Pull request by rarkins**
## Changes:

Recurses renovateRepository up to 5 times after automerging.

## Context:

Automerging causes an early exit, now this recursion should allow branches to be rebased if necessary. Closes #10239

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — COMMENTED** [review]
I think we should start with max of three or two recursion. Otherwise we can create a log of rebase noise. 🤔

**Comment by rarkins** [comment]
> I think we should start with max of three or two recursion. Otherwise we can create a log of rebase noise. 🤔

Wouldn't that only happen if there were multiple automerges right after another, which could only be if there's `requiredStatusChecks=null`?

**Comment by viceice** [comment]
Right.

What about cached http requests for status checks? Can they interfere with a second run? Or any other cached platform http request? 🤔

**Comment by rarkins** [comment]
> Right.
> 
> What about cached http requests for status checks? Can they interfere with a second run? Or any other cached platform http request? 🤔

I think it's OK. `renovateRepository()` calls `initRepo()` which calls `initializeCache()` which: https://github.com/renovatebot/renovate/blob/ac613076047c9ffed2eba5a29c8747be9d9c7e80/lib/workers/repository/init/cache.ts#L8

I tested with a scenario with:
- Two minor updates, both set to automerge
- One of those two also has a major update

Run 1: Creates 3 PRs
Run 2: Automerges the minor-only dependency, recurses and rebases the other two
Run 3: Automerges the second minor update, recurses but fails to rebase the conflicted major update

I'm not sure why the rebase in run 3 didn't happen - the worker seems to think the PR is not conflicted. I added a 10s delay before recursing to let GitHub "catch up" but it didn't seem to help. I'll debug it to work out if it's a cache somewhere or definitely platform.

**Comment by viceice** [comment]
Ok, i can maybe test it on self-hosted gitea or gitlab to how it works there on Monday

**Comment by rarkins** [comment]
Marking as ready for review. I don't think if any problem exists with conflict detection that it's caused by these changes.

**Review by viceice — APPROVED** [review]

**Pull request merged**
