### PR TITLE
feat: gemstash compatibility added

### LINKED ISSUE #6787: Gemstash server integration
**What would you like Renovate to be able to do?**

Renovate should be able to fetch gems in a private [Gemstash server](https://github.com/rubygems/gemstash). It should be able to handle credentials for this server.

AFAIK, the url `/api/v1/gems` seems implemented in Gemstash but only for pushing gems https://github.com/rubygems/gemstash/blob/9d0e45d80e70f7e2d3987e5e1cdef68cd1119a91/lib/gemstash/web.rb#L48

It seems that urls used to fetch gems are `/api/v1/dependencies`. That's what fetched when I use `bundle lock -V`.

For instance, here fetching ffi and nokogiri gems:

```
HTTP GET https://username:password@INTERNALDOMAIN/private/api/v1/dependencies
HTTP 200 OK https://username:password@INTERNALDOMAIN/private/api/v1/dependencies
Fetching gem metadata from https://INTERNALDOMAIN/private/
Query List: ["ffi", "nokogiri"]
Query Gemcutter Dependency Endpoint API: ffi,nokogiri
HTTP GET https://username:password@INTERNALDOMAIN/private/api/v1/dependencies?gems=ffi%2Cnokogiri
HTTP 200 OK https://username:password@INTERNALDOMAIN/private/api/v1/dependencies?gems=ffi%2Cnokogiri
```

### PR DESCRIPTION
**Pull request by micheelengronne**
This PR adds a check to use the `api/v1/dependencies.json` endpoint if `api/v1/versions` does not exist.

It is currently the case for the Gemstash repository.

Closes #6787

### CODE REVIEW

**Comment by micheelengronne** [comment]
`prettier --list-different "**/*.{ts,js,mjs,json,md}"` does not output anything. I don't know what to modify.

**Comment by rarkins** [comment]
Try running `yarn lint` locally.

But also, doesn't this solution try/fail for *every* dependency? i.e. if you need to look up 20 dependencies, it will result in 20 * 404 errors in addition to the 200 * 200 OK?

**Comment by micheelengronne** [comment]
Indeed. But a Gemfile can contain gems from multiple sources. We canno't know in advance if the gem can be fetched from `api/v1/versions` or not.

I will do more tests locally as the unit tests broke.

**Comment by rarkins** [comment]
I'd wondered if we could detect when a particular registryUrl does not support the traditional endpoint and then "remember" that for subsequent requests

**Comment by micheelengronne** [comment]
Maybe via a `hostRules` settings ?

**Comment by rarkins** [comment]
I think it's ok to try/fail but I prefer we only do it *once* per run instead of once per dependency.

**Pull request closed without merging**
