### PR TITLE
feat(replacements): fakerjs to scoped

### PR DESCRIPTION
**Pull request by ST-DDT**
## Changes

Created a replacement rule to replace the unmaintained [faker](https://www.npmjs.com/package/faker) with the community driven replacement [@faker-js/faker](https://www.npmjs.com/package/@faker-js/faker)

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by Shinigami92 — APPROVED** [review]

**Review by viceice — COMMENTED** [review]
why so many rules?

**Comment by Shinigami92** [comment]
> why so many rules?

I don't really understand your question :thinking:
Each rule serves different purposes. If someone is e.g. on v4, then switching the npm scope directly to v5.5.3 would result in breaking changes.
The new home kept the whole history and released backward-compatible legacy versions that were not changed.

**Comment by ST-DDT** [comment]
> why so many rules?

I thought this was some kind of requirement:

https://github.com/renovatebot/renovate/blob/15ac0b35e55812788acb1596bb9f635e9041c9fc/docs/development/creating-editing-renovate-presets.md?plain=1#L36-L38

I can change them to all point to 5.5.3 if you want.

**Comment by Shinigami92** [comment]
> I can change them to all/only point to 5.5.3 if you want.

I would suggest to NOT do that, because it violates:

```
Replacement PRs should ideally propose a replacement only once the user is on a compatible version, by specifying a compatible `matchCurrentVersion` constraint
```

**Review by rarkins — DISMISSED** [review]

**Review by rarkins — APPROVED** [review]

**Review by secustor — APPROVED** [review]

**Pull request merged**
