### PR TITLE
feat: skip gitlab disabled and empty repos

### PR DESCRIPTION
**Pull request by arsdehnel**
GitLab projects can have the repo portion disabled which causes the current `initRepos()` to fail.  This will now skip projects in this configuration as they have no code or dependencies to update.  I'm also adding a check for the `empty_repo` property as another way to check for the repo being empty which could also cause Renovate to hit errors.

Closes # 5080

### CODE REVIEW

**Comment by arsdehnel** [comment]
Sorry for the extra commit under the wrong username that confused the CLA bot, I think things are good now.

**Comment by arsdehnel** [comment]
I see it failed in some Travis CI check for `getPackageUpdates` but I'm not at all sure how my changes would've impacted that.  If that is something I need to fix on my PR I think I'm going to need help knowing what to do with that.

**Comment by JamieMagee** [comment]
@arsdehnel Yeah, looks like your changes were unrelated, and there is a fix in master (25215644fd777d19f75696123cf88083fda55675 and 1300075a72fce1eb75990db3dc5a9d674d6301f1). I merged the latest master into your PR, which should fix the build issues.

I wonder is it also worth checking for `merge_requests_access_level` as well? If MRs are disabled Renovate will fail later in the process.

**Comment by arsdehnel** [comment]
Yeah good call, I'll add that check as well.

**Comment by arsdehnel** [comment]
Added that check and CI seems to be happy now!

**Review by JamieMagee — APPROVED** [review]

**Pull request merged**
