### PR TITLE
refactor: Use GraphQL variables instead of string templates

### PR DESCRIPTION
**Pull request by zharinov**
## Changes:

String templates and query string manipulation are too fragile and prevent further refactoring.
It's more convenient to use variables.

## Context:

Ref #8386

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by rarkins — COMMENTED** [review]
How risky is this refactor? And are we sure there aren't graphql libraries to abstract some of this?

**Comment by zharinov** [comment]
I've checked query results and pagination, everything works same. I don't know about abstraction, we're mostly just using plain GraphQL in not so many places. The only abstraction is the pagination, but we already solved it (kind of).

**Comment by rarkins** [comment]
What about the variables used here. Is that your own abstraction or part of graphql?

**Comment by zharinov** [comment]
They're part of GraphQL specification and transported with the query in the same JSON object

**Comment by JamieMagee** [comment]
Nice! https://github.com/octokit/graphql.js/issues/2 is also a good summary of why this is a good idea.

**Review by JamieMagee — APPROVED** [review]

**Pull request merged**
