### PR TITLE
support docker version openjdk:8u131-jre-alpine

### PR DESCRIPTION
**Pull request by ivan-meridianbanc-com**
This PR fixes docker parse of version like openjdk:8u131-jre-alpine by replacing from (Number)u(Number) to Number.Number. 8u131-jre-alpine becomes 8.131-jre-alpine

I signed CLA.
Please, let me know if I need to do anything else so this could be merged.

### CODE REVIEW

**Comment by rarkins** [comment]
This could potentially be solved using the new regex-based versionScheme. @TheKevJames @ViceIce what do you think?

**Comment by ivan-meridianbanc-com** [comment]
> This could potentially be solved using the new regex-based versionScheme. @TheKevJames @ViceIce what do you think?

@rarkins : Could you provide example how to configure such "regex-based versionScheme" for docker?

**Comment by ViceIce** [comment]
@ivan-meridianbanc-com You have to configure the [versionScheme](https://docs.renovatebot.com/configuration-options/#versionscheme) with a [packageRule](https://docs.renovatebot.com/configuration-options/#packagerules) to something like

```json

{
  "packageRules": [
    {
    "packageNames": ["openjdk"],
    "managers": ["dockerfile"],
    "versionScheme": "regex:^(?<major>\\d+)u(?<minor>\\d+)(-(?<compatibility>.*))?$"
    }
  ]
}
```

**Comment by ivan-meridianbanc-com** [comment]
> @ivan-meridianbanc-com You have to configure the [versionScheme](https://docs.renovatebot.com/configuration-options/#versionscheme) with a [packageRule](https://docs.renovatebot.com/configuration-options/#packagerules) to something like
> 
> ```json
> {
>   "packageRules": [
>     {
>     "packageNames": ["openjdk"],
>     "managers": ["dockerfile"],
>     "versionScheme": "regex:^(?<major>\\d+)u(?<minor>\\d+)(-(?<compatibility>.*))?$"
>     }
>   ]
> }
> ```

@ViceIce Thank you for your reply.
I tried with this configuration.

I get this error:
WARN: Config Warning 
       "configError": {
         "configFile": "^(?<major>\\d+)u(?<minor>\\d+)(-(?<compatibility>.*))?$",
         "validationError": "Invalid regex versionSheme found"
       },
       "res": "created"

I am not very good with regular expression. 
Could you please point me in the right direction how to generate it, validate it ?
I do not know if <major>, <minor>, <compatibility> are standard regexp or renovate specific ?

**Comment by rarkins** [comment]
@ivan-meridianbanc-com these are called "named capture groups" in regex and supported since Node.js 10. Can you try the exact regex string for versionScheme that @ViceIce suggested to you?

**Comment by ivan-meridianbanc-com** [comment]
> @ivan-meridianbanc-com these are called "named capture groups" in regex and supported since Node.js 10. Can you try the exact regex string for versionScheme that @ViceIce suggested to you?

I tried it as described:

Here it is:
```
{
    "assignees": ["ivan-meridianbanc"],
    "packageRules": [
    {
        "packageNames": ["openjdk"],
        "managers": ["dockerfile"],
        "versionScheme": "regex:^(?<major>\\d+)u(?<minor>\\d+)(-(?<compatibility>.*))?$"
    }]
}
```

**Comment by ViceIce** [comment]
@ivan-meridianbanc-com Can you please doubble check your config, run again with debug level and post the log

**Comment by ivan-meridianbanc-com** [comment]
> @ivan-meridianbanc-com Can you please doubble check your config, run again with debug level and post the log

The problem is that the module re2 is not installed.
The regexp is working if re2 module is installed.

Dockerfile
```
FROM node:8
USER root
```

```
$ npm install -g renovate
/usr/local/bin/renovate -> /usr/local/lib/node_modules/renovate/dist/renovate.js
/usr/local/bin/renovate-config-validator -> /usr/local/lib/node_modules/renovate/bin/config-validator.js

> dtrace-provider@0.8.8 install /usr/local/lib/node_modules/renovate/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

gyp WARN EACCES user "undefined" does not have permission to access the dev dir "/root/.node-gyp/8.16.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/renovate/node_modules/dtrace-provider/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/renovate/node_modules/dtrace-provider/.node-gyp'
gyp ERR! System Linux 4.19.23-coreos-r1
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/renovate/node_modules/dtrace-provider
gyp ERR! node -v v8.16.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

> re2@1.10.0 install /usr/local/lib/node_modules/renovate/node_modules/re2
> node-gyp rebuild

gyp WARN EACCES user "undefined" does not have permission to access the dev dir "/root/.node-gyp/8.16.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/renovate/node_modules/re2/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/renovate/node_modules/re2/.node-gyp'
gyp ERR! System Linux 4.19.23-coreos-r1
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/renovate/node_modules/re2
gyp ERR! node -v v8.16.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

> core-js@3.2.1 postinstall /usr/local/lib/node_modules/renovate/node_modules/core-js
> node scripts/postinstall || echo "ignore"

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: re2@1.10.0 (node_modules/renovate/node_modules/re2):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: re2@1.10.0 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ renovate@19.34.4
added 751 packages from 1053 contributors in 26.674s
$ renovate --platform gitlab --endpoint https://gitlab.com/api/v4 $(cat repositories.txt | xargs)
 WARN: RE2 not usable, falling back to RegExp
       "err": {
         "code": "MODULE_NOT_FOUND",
         "message": "Cannot find module 're2'",
         "stack": "Error: Cannot find module 're2'\n    at Function.Module._resolveFilename (module.js:548:15)\n    at Function.Module._load (module.js:475:25)\n    at Module.require (module.js:597:17)\n    at require (internal/module.js:11:18)\n    at RegEx (/usr/local/lib/node_modules/renovate/dist/util/regex.js:7:21)\n    at Object.<anonymous> (/usr/local/lib/node_modules/renovate/dist/util/regex.js:17:3)\n    at Module._compile (module.js:653:30)\n    at Object.Module._extensions..js (module.js:664:10)\n    at Module.load (module.js:566:32)\n    at tryModuleLoad (module.js:506:12)"
       }
```

**Comment by rarkins** [comment]
You need node 10.

**Comment by ViceIce** [comment]
@ivan-meridianbanc-com  You can also use the new slim image.

**Comment by ivan-meridianbanc-com** [comment]
> You need node 10.

Thank you @rarkins .

This Dockerfile is working.
```
FROM node:10
USER root
RUN npm_config_user=root npm install -g renovate
```
@ViceIce The slim is missing python.

**Comment by rarkins** [comment]
Great, we don't need this PR then.

**Pull request closed without merging**
