### PR TITLE
fix(maven)!: set RegistryStrategy = 'hunt'

### LINKED ISSUE #22744: Maven datasource: use hunt registryStrategy
### Describe the proposed change(s).

Renovate should fetch packages using registryStrategy=hunt.

It's important though that we have the registries listed in the right order whenever possible.

### Describe why we need/want these change(s).

This is to align with https://maven.apache.org/guides/mini/guide-multiple-repositories.html#repository-order

### PR DESCRIPTION
**Pull request by fredrondina**
## Changes

set maven RegistryStrategy = 'hunt'

## Context

Closes #22744 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
We need to first make sure that the registry Urls are in the best order. @Churro any thoughts?

**Comment by Churro** [comment]
Correct registry order is definitely not warranted in `gradle` and `maven` managers (at least). The existing `merge` strategy isn't fitting to how these two behave either but I'm clueless how many releases we'd miss by switching to `hunt`.

**Comment by rarkins** [comment]
@Churro I think we maybe need to make the change and then be responsive for fixing afterwards if necessary?

**Comment by Churro** [comment]
You're probably right.

I think with the `maven` manager it should be feasible to extract + re-order `registryUrls` according to the official docs ([here](https://maven.apache.org/guides/mini/guide-multiple-repositories.html#repository-order)). With `gradle`, it's way more intricate but I'd hope that `hunt` resolve at least as realiable as `merge` in that case.

**Comment by rarkins** [comment]
Are we sure Gradle does hunt too?

**Comment by Churro** [comment]
> Are we sure Gradle does hunt too?

Generally, it does. This is also stated in the [official docs](https://docs.gradle.org/current/userguide/dependency_management_for_java_projects.html):
> A project can have multiple repositories. Gradle will look for a dependency in each repository in the order they are specified, stopping at the first repository that contains the requested module.

I'm not sure about deps with dynamic versions (e.g. `com.squareup.okttp3:okhttp:4.9.+`) though - see [here](https://docs.gradle.org/current/userguide/dependency_resolution.html#discovering_versions):
> Each repository is inspected, Gradle does not stop on the first one returning some metadata. When multiple are defined, they are inspected in the order they were added.

**Comment by rarkins** [comment]
Replaced by #24588

**Pull request closed without merging**
