### PR TITLE
fix(npm): replace pnpm overrides in right position

### PR DESCRIPTION
**Pull request by viceice**
## Changes
Replace pnpm overrides deps on right position
- regression of #28199

## Context
- #28605

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
Can we wait for a reproduction repo to verify it against?

**Comment by viceice** [comment]
> Can we wait for a reproduction repo to verify it against?

https://github.com/containerbase/base/blob/b95329c58c0437b23424da896e3df463b6d9a7a6/package.json#L34

will convert to `pnpm.overrides` to validate after forking 🤗

**Comment by viceice** [comment]
working sample with this PR
- https://github.com/renovate-reproductions/base/pull/2

**Comment by viceice** [comment]
failing on app
- https://github.com/renovate-reproductions/28605-pnpm-overrides/issues/3

**Comment by karlhorky** [comment]
> working sample with this PR
> 
> * [build(deps): update dependency esbuild to v0.20.2 (viceicebot) renovate-reproductions/base#2](https://github.com/renovate-reproductions/base/pull/2)

Oh TIL that there's a `renovate-reproductions/base` repo, this looks very useful 👀 ❤️

- https://github.com/renovate-reproductions/base/

Would be great to have this as a part of the open source issue / discussion creation process, to make it super easy to create good reproductions for Renovate

**Review by rarkins — APPROVED** [review]

**Review by secustor — APPROVED** [review]

**Comment by HonkingGoose** [comment]
> > working sample with this PR
> > 
> > * [build(deps): update dependency esbuild to v0.20.2 (viceicebot) renovate-reproductions/base#2](https://github.com/renovate-reproductions/base/pull/2)
> 
> Oh TIL that there's a `renovate-reproductions/base` repo, this looks very useful 👀 ❤️
> 
>     * [github.com/renovate-reproductions/base/](https://github.com/renovate-reproductions/base/)
> 
> 
> Would be great to have this as a part of the open source issue / discussion creation process, to make it super easy to create good reproductions for Renovate

See this discussion:

- https://github.com/renovatebot/renovate/discussions/28614

**Pull request merged**
