### PR TITLE
feat: support corepack + yarn

### LINKED ISSUE #14797: Yarn lock file maintenance using wrong version
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### Please select which platform you are using if self-hosting.

_No response_

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

When Yarn 2+ is used in a project, but not embedded in the repository via `yarnPath`, lock file maintenance will fall back to Yarn 1 and replace the whole `yarn.lock`.

An example can be seen here: https://github.com/jgraichen/renovate-corepack-yarn/pull/4/files

When dependencies are bumped, the `yarn.lock` is correctly updated: https://github.com/jgraichen/renovate-corepack-yarn/pull/3/files

I'd love to have all updates and lock file maintenance use the correct Yarn version.

### Relevant debug logs

_No response_

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

### PR DESCRIPTION
**Pull request by jgraichen**
This PR fixes the yarn post-update handle to use the correct yarn version. Previously, any constraints for Yarn 2+ were ignored, as only Yarn 1 is installable via NPM.

## Changes

This PR changes the post-update handler to use `corepack` to install and use a matching Yarn 2+ version. The correct version is already detected based on `packageManager`, `engines`, the lock file, or any user constraint specified in the renovate config.

An additional fix is needed for the code extracting the valid Yarn version from the lock file, which did override any, likely more specific, constraint from the user or the `package.json`.

## Context

This fixes use-cases when Yarn 2+ is used, but the binary bundle not embedded in the repository. Previously, a Yarn 1 lock file would have been generated.

It also fixes runs that would just fail, e.g. when a Yarn engine > 1 is defined.

Closes #14797

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
"Lazy" checking of packageManager field would be better because it may itself be upgraded as part of the PR. However it looks like the actual version doesn't matter to us here so the approach is OK.

**Review by viceice — COMMENTED** [review]
yes, please detect that in post update. so if a user already has set some manual constraints, that should be respected.

**Comment by jgraichen** [comment]
As far as I know, the post-update is run on an updated `package.json`. The new code does not extract any version, or installs a specific yarn version, or anything else.

It does take the updated `package.json`, and corepack uses whatever yarn version is specified there. I'd assume that, when renovate updates the `packageManager` field, it actually does write it into the `package.json` to run post-update commands, does it not? Then, the new version will already be used by corepack.

It definitely does that to package updates, otherwise updating the lock files would never work correctly. Am I missing something?

**Comment by rarkins** [comment]
@jgraichen what we are hoping for is to remove any extract code changes and instead put it all in post-update. Do you think that refactor is possible?

**Comment by viceice** [comment]
we recently did something like that for pnpm (constraints)

- #14660

so i would expect this should work like that.

**Review by viceice — COMMENTED** [review]
see other comment

**Comment by jgraichen** [comment]
First, I was looking at the `upgrades` list argument too, but it only contains a `packageManager` record when the field itself is updated too, which isn't working for the use case.

I added the flag because I wanted to avoid read the file, parsing JSON, and parsing the package.json structure and field again. It felt somewhat redundant, duplicated, and harder to test, especially as the `managerData` already contained things like a flag for e.g. detecting lerna or yarn zero installs. I also thought about exposing the actual field value there (`managerData?.packageManager: string`) but tried to keep it small.

If a solution similar to the linked PR is preferred, reading the file again, I will try to do that here too.

**Comment by jgraichen** [comment]
Shall I try to skip corepack and extract a constraint for yarn when installing? It could work, but feels like reimplementing corepack, which supports pnpm too.

**Comment by jgraichen** [comment]
I tried to look at what the PNPM module is doing, but thing didn't work out. I started also parse the `packageManager` field and using it as a yarn constraint:

```ts
    const yarnCompatibility: string = yarnUpdate
      ? yarnUpdate.newValue
      : config.constraints?.yarn ?? (await getYarnConstraint(cwd));
```

This will work for all the checks defining which features are available, such as `isYarnDedupeAvailable` and `isYarnModeAvailable`. This was ignored before and will be a good addition.

When actually running the code in a debugger, I noticed that [`lib/modules/manager/npm/extract/index.ts#L203`](https://github.com/renovatebot/renovate/blob/4ff728d72c2b06e77a1d6ebaa0f94a65f13be5d0/lib/modules/manager/npm/extract/index.ts#L203) is already extracting constrains from the `packageManager` and `engines` fields. Indeed, when debugging the actual code running, `config.constraints.yarn` was always set to `^3.0.0`. The `(await getYarnContraint(cwd))` is never called (outside of tests). I didn't debug the PNPM code if the same happens there.

Something along the way seems to transform the exact version from `packageManager` into a more relaxed range. I tried running on different repositories, with different `packageManager` versions:

| `packageManager` | ``` |
| --- | --- |
| `yarn@3.1.0` | `^3.0.0` |
| `yarn@2.2.0` | `^2.2.0` |

It seems to be relaxed to include possible latest patch releases.

While debugging, I also tried a few different scenarios:

1) `config.constraints.yarn` is also set when an [engine for yarn](https://github.com/jgraichen/renovate-yarn-engine-v3/blob/b049c1f49fab928bddc0a05e9e5d0e874c340b5e/package.json#L7-L9) is specified. Runs currently will just fail with an error: [The engine "yarn" is incompatible with this module](https://github.com/jgraichen/renovate-yarn-engine-v3/pull/1#issuecomment-1107651158).

2) [`constraints` in `renovate.json`](https://github.com/jgraichen/renovate-yarn-constraint-v3/blob/6acf3a3aa7d16bbdb07878e94d3baaa8a5ff27e9/renovate.json#L3-L5) are basically ignored.

I tried to work with the given constraints, but unfortunately `corepack` does not accept ranges, only exact versions. 

The best way I found up until now is this:

```
    if (minYarnVersion) {
      if (isYarn1) {
        preCommands.push(`npm i -g yarn@${quote(yarnCompatibility)}`); # (2)
      } else {
        preCommands.push(`npm i -g corepack`);
        preCommands.push(`corepack prepare --activate yarn@${minYarnVersion.version}`) # (3)
      }
    } else {
      preCommands.push('npm i -g yarn');  # (1)
    }
```

1. When there is no constraint found anywhere, `minYarnVersion` will be blank, and yarn 1.x is installed as before.

2. When a `1.x` constraint is given, `yarn@1.x` will be installed as before.

3. When any non-1.x constraint is present, be it `renovate.constrains.yarn`, `packageManager`, `engines`, or any other mechanism where renovate identified a version, `corepack` is installed and the smallest possible `yarn` version is installed.

This isn't optimal yet, but covers many cases:

1. `engines.yarn` greater than `1.x` do no [longer fail](https://github.com/jgraichen/renovate-yarn-engine-v3/pulls), but an older version of yarn will be used.

2. `renovate.constraints.yarn` greater than 1.x are not [ignored anymore](https://github.com/jgraichen/renovate-yarn-constraint-v3/pulls). They use an old but correct version of yarn.

3. `packageManager` fields are working correctly too, but possibly two versions of yarn are download and installed. For example, when `packageManager` is set to `yarn@3.1.0`, renovate will pass `config.constraints.yarn: "^3.0.0"`. The post-update hook will invoke `corepack prepare yarn@3.0.0`, which will install yarn 3.0.0. When the actual `yarn` call is executed, the shim will read the `packageManager` field on its own and install yarn `3.1.0`, which will then be used to update the lock file.

My open questions are:

1) Why are constraints transformed into ranges? Would it be possible to keep specific constraints such as from `packageManager`?

2) Would it be possible to not use `minYarnVersion`, but look up the latest yarn version matching the constraint somehow?

**Comment by jgraichen** [comment]
Are the constraints extracted by NPM maybe overridden here? https://github.com/renovatebot/renovate/blob/868ebbef636de7a78b719dc607001e3de391f32c/lib/modules/manager/npm/extract/locked-versions.ts#L24-L37

I'll try to take a look next time.

**Comment by viceice** [comment]
you should probably create a new PR for refactoring yarn constraints handling. it should ideally only done in Post-Update.

so any constraints set in extract phase should be removed.

**Comment by jgraichen** [comment]
The current changes only fix using the correct constraints for yarn. There isn't any refactoring yet.

All that is needed is to look up the last available @yarnpkg/yarn package version if the constraint is a range because `corepack` needs a specific version. I'd really like to have this fixed first before refactoring where constraints are parsed or not.

Do you have any example on how the NPM data source can be used to look up a package version?

**Review by rarkins — CHANGES_REQUESTED** [review]
PR title should represent what's changed, right now it's too broad

**Comment by jgraichen** [comment]
@rarkins Just updated.

I also added a lookup for the latest yarn release, if the user specified a range constraint somewhere (e.g. `engines` or renovate config constraints).

**Comment by rarkins** [comment]
Didn't the majority of Yarn 2+ cases already work fine before this? Isn't this PR solving the case where corepack is in use and the Yarn 2 binary is not checked into the repo?

This PR's title still implies that Yarn 2+ versions were incorrect before, and I don't think that is accurate.

**Comment by jgraichen** [comment]
@rarkins The only case that does work is when a yarn binary has been embedded into the repository.

Everything else fails:

* When a yarn engine > 1 is configured in `package.json`, renovate will just fail: https://github.com/jgraichen/renovate-yarn-engine-v3/pull/1

* When a yarn constraint in `renovate.json` is defined, renovate just ignores it and creates a yarn v1 lock file: https://github.com/jgraichen/renovate-yarn-constraint-v3/pull/3/files

* When a `packageManager` field is defined, renovate just ignores it and creates a yarn v1 lock file: https://github.com/jgraichen/renovate-yarn-corepack-v3/pull/3/files

The reason why embedding a yarn 2+ binary into the repository works is that yarn v1 will pick that up and re-run itself with the embedded binary.

Only yarn 1.x constraints (from renovate constraints, `packageManager`, or `engine`) are correctly used when installing yarn v1. Every other constraint is ignored.


This PR basically does add any constraint extraction method. They all are already present. It only extends the yarn post-update hook to actually do something with any v2+ constraints.

The only change to an extraction method is a fix to the existing code to not override a more specific constraint with the broad ones from the lock file scanning.

I am open to better title, but struggling to find anything precise.

**Comment by viceice** [comment]
@rarkins i think I'll send a refactoring PR tomorrow morning, where all constraint handling will be done in Post-Update. then this PR can add the corepack handling in a more easy and wanted way.

**Comment by rarkins** [comment]
> The only case that does work is when a yarn binary has been embedded into the repository.

..which was the *only* way Yarn 2+ worked prior to corepack, and it's still the way in Yarn's [migration guide](https://yarnpkg.com/getting-started/migration) (installation guide has been updated to recommend corepack).

> I am open to better title, but struggling to find anything precise.

I have updated it, including reclassified this as a feature not fix. Corepack did not exist when we first supported Yarn 2, so it's wrong to consider this was a *bug*, which means it's not a *fix*.

**Comment by viceice** [comment]
https://github.com/renovatebot/renovate/blob/868ebbef636de7a78b719dc607001e3de391f32c/lib/modules/manager/npm/extract/locked-versions.ts#L8-L10

That code is creating the new yarn range constraints, working on refactor now

**Pull request closed without merging**
