### PR TITLE
feat(config): parse json files as json5

### LINKED ISSUE #7674: Support json5 for Shared Configs
**What would you like Renovate to be able to do?**

We'd like to be able to add comments to make it clear why certain config settings are the way they are. This is especially important with a shared, collaborative configuration. Currently this is not possible with json. Either `yaml` or `json5` would solve this.

**Did you already have any implementation ideas?**

From reading the code, two things would need to happen: A consumer would need to explictly specify the file extension (already possible today?) and the config fetcher would need to know how to parse it by toggling off the extension. An even better exp would probably try the various paths and only fail if no matching extension is found. Likely would be expensive and noisy though.

### LINKED ISSUE #15186: config-validator ignores parsing errors
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.26.3

### Please select which platform you are using if self-hosting.

GitHub Enterprise Server

### If you're self-hosting Renovate, tell us what version of the platform you run.

3.3.5

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

If there is a json parser error in the renovate.json file then it gets silently ignored.
This is the code causing it
https://github.com/renovatebot/renovate/blob/868ebbef636de7a78b719dc607001e3de391f32c/lib/config-validator.ts#L56-L68
Presumably it was written like that to silently ignore missing files, but it has the side effect that it also ignores malformed files.
In our case we run the validator during PRs that modify the renovate.json in our repos, but any parsing error gets ignored so it's pretty easy to land changes that breaks it.

We could trivially make our own custom step that validates that the renovate.json parses, but for the sake of providing value to the general community I wonder:

Does it make sense to change this to be silent when the file does not exist, and log an error when it fails to parse instead?

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste any log here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

### PR DESCRIPTION
**Pull request by viceice**
## Changes
- parse all json config files as `JSON5`. It doesn't harm and make life easier.
- Log more validation errors

## Context
- closes #7674
- fixes #15186

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
How to handle the impending config migration PRs? We were planning to JSON.stringify the migrated config and maybe limit it to JSON files only or have a warning when it's .json5

**Comment by viceice** [comment]
we can probably document that only the JSON part is left on migration. we don't see the comments after parsing, so it would pretty hard to retain all JSON5 stuff.

**Review by JamieMagee — DISMISSED** [review]
Approved, but it looks like you gave yourself merge conflicts with strict null checks 😅

**Comment by viceice** [comment]
> Approved, but it looks like you gave yourself merge conflicts with strict null checks 😅

fixed 😅

**Review by rarkins — APPROVED** [review]

**Pull request merged**
