### PR TITLE
fix: rename turbo repo

### PR DESCRIPTION
**Pull request by moltar**
## Changes

Renames Vercel Turbo monorepo.

Turbo was added in #22393.

But since then Vercel must have renamed their repo, because that URL redirects to the one in this PR.

## Context

The side effect of having the wrong URL, is that packages are not grouped correctly.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
How long ago was the renaming done? Should we have both for a period?

**Comment by moltar** [comment]
> How long ago was the renaming done?

Don't know, tried to find this out, but didn't find any conclusive information.

I just observed on my repos that all of the packages were merged separately recently, but could have been for a while too, and I just didn't once.

> Should we have both for a period?

That I cannot answer, as I am not too familiar with the Renovate ways.

How would that be done? An array of URLs? Or just under a different name?

**Comment by moltar** [comment]
This PR seems to change the URLs: https://github.com/vercel/turborepo/pull/8965

**Comment by rarkins** [comment]
Then we need to have both repo URLs as part of this rule

**Comment by moltar** [comment]
> Then we need to have both repo URLs as part of this rule

How to do that?

**Comment by moltar** [comment]
> Then we need to have both repo URLs as part of this rule

✅ Fixed

**Review by rarkins — APPROVED** [review]

**Pull request merged**
