### PR TITLE
Fix `git-tags` datasource to not modify repo tags

### PR DESCRIPTION
**Pull request by jakauppila**
Updates the `git-tags` datasource so that it does not modify the repo tags it pulls back.

There are currently two consuming managers `swift` and `composer`:

Swift
- Swift documentation dictates that repo versioning [needs to conform to semantic versioning](https://developer.apple.com/documentation/xcode/publishing_a_swift_package_with_xcode) presumably without the leading `v` which would lead me to believe that no action needs to be taken in the `swift` manager as there should be no need to strip the `v` off.

Composer
- Composer supports verison references with `v` in the name as [it strips it out internally](https://getcomposer.org/doc/articles/versions.md#tags), so I'm not sure if updates to the manager are actually warranted?

Related to https://github.com/renovatebot/renovate/issues/5228

### CODE REVIEW

**Comment by rarkins** [comment]
@zharinov do you remember this from when you added Swift?

**Comment by zharinov** [comment]
> @zharinov do you remember this from when you added Swift?

We probably should not remove `v`-prefixes in the datasource level, while still filtering obviously invalid values like `1.2.3^{}`.

Though, I'm not sure how these two managers can handle it. I would add additional tests cases for their `extract.ts` code.

**Comment by zharinov** [comment]
Initially, I wrote code that removes it because Swift's version scheme can't sort arrays like `['v0.0.1', 'v0.0.2']`

**Comment by rarkins** [comment]
@zharinov can you branch off this PR work to update any Swift files necessary (extract, update, versionScheme) so that it can use the raw v-prefixed tags if given? e.g. if we need to enhance the version scheme to be able to sort the tags, we do that.

**Comment by zharinov** [comment]
Okay

**Comment by rarkins** [comment]
Superseded by #5251

**Pull request closed without merging**
