### PR TITLE
chore(test): fixes jest oom

### LINKED ISSUE #5527: JavaScript heap out of memory on Actions Test CI
Maybe signs of a memory leak in our tests?

```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x8fa090 node::Abort() [/opt/hostedtoolcache/node/10.19.0/x64/bin/node]
 2: 0x8fa0dc  [/opt/hostedtoolcache/node/10.19.0/x64/bin/node]
 3: 0xb0052e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/opt/hostedtoolcache/node/10.19.0/x64/bin/node]
 4: 0xb00764 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/opt/hostedtoolcache/node/10.19.0/x64/bin/node]
 5: 0xef4c72  [/opt/hostedtoolcache/node/10.19.0/x64/bin/node]
 6: 0xef4d78 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/opt/hostedtoolcache/node/10.19.0/x64/bin/node]
 7: 0xf00e52 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/opt/hostedtoolcache/node/10.19.0/x64/bin/node]
 8: 0xf01784 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/opt/hostedtoolcache/node/10.19.0/x64/bin/node]
 9: 0xf043f1 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/opt/hostedtoolcache/node/10.19.0/x64/bin/node]
10: 0xecd874 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/opt/hostedtoolcache/node/10.19.0/x64/bin/node]
11: 0x116d9fe v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/opt/hostedtoolcache/node/10.19.0/x64/bin/node]
12: 0x30128705be1d 
```

### PR DESCRIPTION
**Pull request by viceice**
Workaround for jest oom.

Closes #5527

### CODE REVIEW

**Comment by rarkins** [comment]
Why are the tools necessary in the Dockerfiles?

**Comment by viceice** [comment]
image
 🙈

**Comment by viceice** [comment]
yarn postinstall

**Comment by viceice** [comment]
`prepare` will only be called on `yarn install` and not on `yarn install --production`. I can call it manually on `yarn jest`

**Comment by rarkins** [comment]
Hmm, when running it on OSX I get lots of these messages:

```
$ cross-env NODE_ENV=test LOG_LEVEL=fatal node --expose-gc node_modules/jest/bin/jest.js
Patching module not allowed fs close
Patching module not allowed fs closeSync
Patching module not allowed fs close
Patching module not allowed fs closeSync
Patching module not allowed stream PassThrough
Patching module not allowed fs close
Patching module not allowed fs closeSync
Patching module not allowed fs close
Patching module not allowed fs closeSync
Patching module not allowed fs close
Patching module not allowed fs closeSync
Patching module not allowed stream PassThrough
Patching module not allowed stream PassThrough
Patching module not allowed stream PassThrough
Patching module not allowed stream PassThrough
Patching module not allowed fs close
Patching module not allowed fs closeSync
Patching module not allowed stream PassThrough
```

Not sure if I should revert.

Also execution time went up from 35s to 53s

**Comment by viceice** [comment]
logging, which i forgot to remove 🙈

**Comment by viceice** [comment]
https://github.com/renovatebot/renovate/blob/1dd4414baef5eaad1d90f7fa656172df588cc861/tools/prepare.js#L56

**Comment by viceice** [comment]
image

**Comment by sibelius** [comment]
isn't better to use patch-package for this?

**Comment by viceice** [comment]
Hav not known that, thanks, i'll try that. https://www.npmjs.com/package/patch-package

**Pull request merged**
