### PR TITLE
fix(presets): include 'google-auth-library' in googleapis group

### PR DESCRIPTION
**Pull request by wereHamster**
## Context

I'm using the group:googleapis preset but <del>dependabot</del> renovatebot created a separate PR for google-auth-library. Group those together.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — COMMENTED** [review]
I'm not sure if this will make any difference to dependabot. this repo is for renovatebot.

**Review by rarkins — APPROVED** [review]

**Comment by wereHamster** [comment]
Replace dependabot with renovatebot in the description… finger memory :-/

**Comment by viceice** [comment]
> Replace dependabot with renovatebot in the description… finger memory :-/ 

ok 😏

can you sign the cla please?

**Comment by rarkins** [comment]
For a submission like this there's no "intellectual property" claim possibility so I can override the requirment

**Pull request merged**
