### PR TITLE
fix(github): Paginate open and closed PR lists

### LINKED ISSUE #7999: Add pagination to github.getOpenPrs()
**What would you like Renovate to be able to do?**

Paginate all open PRs

**Did you already have any implementation ideas?**

I don't know if it's enough to just add `paginate: true` to the graphql query? I am not sure why we set it to false in the first place but it seems to trace back to https://github.com/renovatebot/renovate/pull/6203/files

### PR DESCRIPTION
**Pull request by zharinov**
## Changes:

- [x] Remove any constraints on pagination for `getOpenPrs` and `getClosedPrs` functions.
- [x] Update tests
- [x] Test on real repo with >1 PR pages

## Context:

Closes #7999

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added unit tests, or
- [x] Unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
Maybe you can reduce the page size to a lower number for the purposes of local testing

**Comment by zharinov** [comment]
Well, it worked fine for little pages

**Review by viceice — APPROVED** [review]

**Comment by rarkins** [comment]
Does this limit to 1000 like in rest? We aren't able to filter by PR creator so there are some repos where this would return 10s of thousands of closed PRs

**Comment by zharinov** [comment]
Ready for review/merge

**Pull request merged**
