### PR TITLE
docs: move manager docs out of config options

### PR DESCRIPTION
**Pull request by rarkins**
I plan to implement this eventually for all dynamically-loaded components like version schemes, datasources and managers.

Removed all manager entries from the config definitions file and copied their contents into `readme.md` files in their respective directories.

### CODE REVIEW

**Comment by rarkins** [comment]
Seeking everyone's feedback on how far we should take this. I am thinking that if we go to the effort to implement a manager, the least we can do is a short readme for each - i.e. enforce it. And if so, which headings should be mandatory?

Within the docs website (source: https://github.com/renovatebot/docs.renovatebot.com), I am thinking of breaking this into a separate markdown file rather than embedding them back into the configuration-options doc. In future there can be a page each for managers, datasources and version schemes.

Our auto-generating docs could do things like extract the `fileMatch` field from `index.ts` and format it into a section, avoiding the need to explicitly duplicate that data into markdown.

If we enforce (lint) a mandatory URL within each manager then that could also be used in documentation to point people to whatever is the canonical or best URL for that manager (e.g. npm home page, poetry home page, etc).

**Review by viceice — DISMISSED** [review]
I think the homepage Generator can assemble the new configs back to one file or better to multiple files by type. Eg managers, datasources, ...

**Comment by ViceIce** [comment]
I think a single primary heading should be the first row in `readme.md`, so it is clear what this manager, datasource, ... is.

This cam be removed by docs generator.

**Comment by ViceIce** [comment]
what if we also generate and store the json schema on the docs page.

then we can download it for tests, and notify for required homepage updates?
and we do not have a possible conflicting schema file on pr's.

**Comment by rarkins** [comment]
It would be good that the schema file is not in source control

**Comment by rarkins** [comment]
See #5411

**Pull request merged**
