### PR TITLE
feat(versioning): add perl versioning

### PR DESCRIPTION
**Pull request by ikesyo**
## Changes

Add `perl` versioning and tests.

## Context

- #15172

I'd like to use this versioning over the `loose` versioning for updating Perl's `cpanfile`.

https://metacpan.org/pod/version

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by secustor — CHANGES_REQUESTED** [review]
The name of the readme file has a typo, but else LGTM

**Comment by ikesyo** [comment]
@secustor Thanks for your review, just fixed!

**Review by secustor — APPROVED** [review]

**Comment by secustor** [comment]
Please do not force push. All commits will be squashed any on merge anyway, but it makes it harder to review subsequent changes.

**Review by viceice — APPROVED** [review]

**Comment by ikesyo** [comment]
Sorry for the inconvenience. I'll avoid force push from now on.

**Pull request merged**
