### PR TITLE
test: feature support for prs rarer than 1 month

### LINKED ISSUE #6222: open PRs rarer than monthly
I see in https://docs.renovatebot.com/presets-schedule/ that I can configure Renovate to open PRs daily, weekly, or monthly.

However, in some repos, I'd like rarer than monthly like every 2 months, quarterly, every 6 months, yearly.

### PR DESCRIPTION
**Pull request by JamieMagee**
I've had this bug pinned in my notifications for a while. Finally got around to resolving it :smile: 

fixes #6222

### CODE REVIEW

**Review by viceice — DISMISSED** [review]

**Comment by rarkins** [comment]
Does it work though? Can we add documentation?

**Comment by JamieMagee** [comment]
@rarkins Yes, it works. Where should I add documentation? In `configuration-options.md`? Should I add a preset for `schedule:quarterly`, `schedule:annually`, etc. as well?

**Comment by rarkins** [comment]
So as this is only tests, does it mean it's *always* worked, just now we're testing it works?

**Review by viceice — DISMISSED** [review]

**Comment by JamieMagee** [comment]
> So as this is only tests, does it mean it's _always_ worked, just now we're testing it works?

Yes, it's always worked. `later` also supports schedules defined in years, but Renovate doesn't implement it.

**Comment by rarkins** [comment]
So the string is first parsed by later, and then we kind of interpret later's parsed result. Do we interpret that correctly?

**Comment by JamieMagee** [comment]
Yes, so here's where we parse the schedule text: https://github.com/renovatebot/renovate/blob/591a7604a20117ef32f4c2f5c1beceddc99aed4d/lib/workers/branch/schedule.ts#L51-L58

And here's where we check if the current time fits the schedule (for months)

https://github.com/renovatebot/renovate/blob/591a7604a20117ef32f4c2f5c1beceddc99aed4d/lib/workers/branch/schedule.ts#L122-L132

`schedule.M` is an array of the month's number, and we check if it contains the current month's number.

**Comment by rarkins** [comment]
Great, thanks for confirming. I couldn't remember adding that

**Comment by JamieMagee** [comment]
Added a sample of a schedule longer than a month to the docs, and added a preset for `quarterly`. Is there any benefit to adding longer schedules?

**Pull request merged**
