### PR TITLE
refactor(git): avoid direct force push

### PR DESCRIPTION
**Pull request by hazendaz**
--force plush can be blocked for direct usage (also prevented by + operation during push).  For such systems, it is necessary to perform a force push via a two step operation of first running delete then running the push without the force option.

The current code base does use raw delete in one case.  So this usage is not entirely new here.  The only occurances of force with push found were within the index.ts.

This will prevent case where renovate discovers force push is blocked and then is unable to update branches.  This results in physical user needed to cancel open pull requests and delete branches normally before renovate can work again.

### CODE REVIEW

**Comment by hazendaz** [comment]
This issue is related to #5718.  Many bitbucket corporate instances have half disabled force push options.  Force push is still readily acheivable in this situation by first running a deletion from the remote followed by push without a force option.  I think this will fix the majority of what issue #5718 was discussing while retaining renovate behaviour.

**Comment by rarkins** [comment]
Thanks for the PR. This needs further discussion of the implications plus testing on each platform. For example, GitHub is known to close Pull Requests if you delete the underlying branch.

**Comment by hazendaz** [comment]
@rarkins Great point!  Bitbucket does the same.  I presume all do.

**Comment by rarkins** [comment]
So this code change would potentially close all PRs on all platforms any time Renovate needs to update the branch?

**Comment by hazendaz** [comment]
Hi @rarkins That sounds correct, it should close the PR in flight.  Is there logic in renovate now that can simply reopen it again (same PR)?  This might I suspect cause unnecessary email alerts so it probably needs a flag to accept this condition.  I was hoping to avoid an extra property but maybe a flag is needed here for this type of behavour change?

**Comment by rarkins** [comment]
It's not possible to reopen PRs again on every platform once you delete the underlying branch, but even if it were then it would be highly undesirable to 99.9% of users because of the notifications noise increase it would cause (and also be unintuitive/confusing).

Let's close this PR for now, please now create an issue to discuss your requirements the proposed solution and we can try to work out an elegant way to achieve it for your use case.

**Comment by viceice** [comment]
@hazendaz You can use a more fine grained permissions to allow renovate user to force-push for the `renovate/**` branches only.

You can also use the free `Control Freak` to control even more.

**Comment by hazendaz** [comment]
@rarkins Thanks, I'll do a bit more research into this.  @viceice Thanks for the pointers.

**Pull request closed without merging**
