### PR TITLE
chore: migrate to jest v27

### LINKED ISSUE #10159: Migrate Jest to v27
Might be a good idea to update our `jest monorepo` and `jest-ts` test stuff once that hits 7 `stabilityDays`.

For easy reference, here's the blog post from Jest themselves explaining the changes.

https://jestjs.io/blog/2021/05/25/jest-27

_Originally posted by @HonkingGoose in https://github.com/renovatebot/renovate/issues/2958#issuecomment-848531328_

### PR DESCRIPTION
**Pull request by viceice**
## Changes:

Migrates to Jest v27

## Context:
 closes #10159

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by HonkingGoose** [comment]
@viceice I was thinking if we could switch to a lighter weight `node` environment? Maybe we don't need a full `JSDOM` environment? We might be able to speed up the tests even more... 😄 

If it turns out we still need the full fat `JSDOM` environment for some tests, we could use docblocks comment to mark the parts of the tests that can run in the `node` environment. That way we could use the lightweight env where possible, and use the full fat env where needed.

Link to Jest blog post: https://jestjs.io/blog/2021/05/25/jest-27 search for the string `Running tests in a JSDOM environment` to see what Jest has to say about this.

**Comment by HonkingGoose** [comment]
@viceice does your commit fixing the memory leak maybe also fix issue #5647?

**Comment by viceice** [comment]
> @viceice I was thinking if we could switch to a lighter weight `node` environment? Maybe we don't need a full `JSDOM` environment? We might be able to speed up the tests even more... 😄
> 
> If it turns out we still need the full fat `JSDOM` environment for some tests, we could use docblocks comment to mark the parts of the tests that can run in the `node` environment. That way we could use the lightweight env where possible, and use the full fat env where needed.
> 
> Link to Jest blog post: https://jestjs.io/blog/2021/05/25/jest-27 search for the string `Running tests in a JSDOM environment` to see what Jest has to say about this.

We already use node env 😏 
https://github.com/renovatebot/renovate/blob/9209fade5ed521f8c88627d9b5c7158b26f7f33d/jest.config.ts#L31

**Comment by HonkingGoose** [comment]
> We already use node env 😏

That was a quick fix! 🤣

**Comment by viceice** [comment]
> @viceice does your commit fixing the memory leak maybe also fix issue #5647?

Nope, i can see it when not running with `--logHeapUsage` 😕

**Comment by viceice** [comment]
I think this is ready

**Review by rarkins — APPROVED** [review]

**Pull request merged**
