### PR TITLE
fix(config): add missing `globalOnly` flags

### PR DESCRIPTION
**Pull request by viceice**
## Changes
add missing `globalOnly` flag for some global renovate options.

## Context
- #16183

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
Are there any differences between stage=global and globalOnly=true now? And if so then can we pick one and remove the other?

**Comment by viceice** [comment]
> Are there any differences between stage=global and globalOnly=true now? And if so then can we pick one and remove the other?

not sure. i only found this relevant usage
https://github.com/renovatebot/renovate/blob/c3acca8877287419a415f7ed68b40eadbfba3c2a/lib/config/index.ts#L37-L58

`filterConfig` is called two times
https://github.com/renovatebot/renovate/blob/e5c6f38d750383538bab95a40184058fec5bf0e0/lib/workers/global/index.ts#L42
https://github.com/renovatebot/renovate/blob/0cf4f48842183cf0a4ad95485009775c9a7afff9/lib/workers/repository/updates/flatten.ts#L193

**Comment by viceice** [comment]
`globalOnly` is only used in tests

**Comment by rarkins** [comment]
My original goal of stages was to trim the config a little at each stage to make it manageable when logging or debugging. Ie it was essentially cosmetic and not functional

**Review by rarkins — APPROVED** [review]

**Pull request merged**
