### PR TITLE
refactor: invert default for "gitLabAutomerge" option

### PR DESCRIPTION
**Pull request by fgreinacher**
## Changes:

This MR changes the default of the `gitLabAutomerge` option from `false` to `true`.

This is a breaking change, so users running Renovate against GitLab versions before 12.7 should consider explicitely disabling this option to prevent potential problems.

## Context:

The [GitLab issue that forced us to make this opt-in](https://gitlab.com/gitlab-org/gitlab/issues/26293) is now fixed for several months. See the [original MR](https://github.com/renovatebot/renovate/issues/3265#issuecomment-536056784) for some more background.

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] Unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — COMMENTED** [review]
I don't like this enabled by default.

**Comment by fgreinacher** [comment]
> I don't like this enabled by default.

You're too quick 😁 I added my reasoning, maybe that helps?

**Comment by viceice** [comment]
sure, but not all users (eg me 🙃 ) want to use that feature by default.

**Comment by fgreinacher** [comment]
> sure, but not all users (eg me 🙃 ) want to use that feature by default.

Why would you not want to use that? Note that this just controls whether Renovate uses GitLabs "merge when pipeline succees" feature.

**Comment by rarkins** [comment]
As 12.7 was only released in January, I'd prefer not to have this on by default. I'm undecided anyway if it's good to enable by default anyway, but this compatibility aspect seals it. It's just one line in your bot config to enable it for all repos, right?

**Comment by fgreinacher** [comment]
> As 12.7 was only released in January, I'd prefer not to have this on by default. I'm undecided anyway if it's good to enable by default anyway, but this compatibility aspect seals it. It's just one line in your bot config to enable it for all repos, right?

OK, we'll do it on our instance config then. Thanks for the honest feedback!

**Pull request closed without merging**
