### PR TITLE
fix: ensure git.hasDiff will not compare against files

### PR DESCRIPTION
**Pull request by felipecrs**
## Changes

This fixes a situation in which git.hasDiff may try to compare against a remote branch but there is a file with the same name. The fix resolves such ambiguity, so that git will always treat the argument as a revision spec and not a potential file.

## Context

```
❯ git diff HEAD origin/master
[works]
❯ mkdir -p origin && touch origin/master
❯ git diff HEAD origin/master
fatal: ambiguous argument 'origin/master': both revision and filename
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
> git diff HEAD origin/master --
[works]
```

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by rarkins — DISMISSED** [review]

**Review by viceice — COMMENTED** [review]
needs lint fix

**Comment by felipecrs** [comment]
Ops, my bad!

**Comment by JamieMagee** [comment]
This must have been a painful bug to find 😅

**Review by JamieMagee — DISMISSED** [review]

**Comment by felipecrs** [comment]
Prettier fixed!

**Comment by felipecrs** [comment]
The failure seems unrelated this time.

**Review by JamieMagee — APPROVED** [review]

**Pull request merged**
