### PR TITLE
fix(poetry): lockFileMaintenance

### LINKED ISSUE #9231: poetry.lock can't get updated
**What Renovate type, platform and version are you using?**
github app

**Describe the bug**

when `lockFileMaintain` is enabled, `poetry.lock` should update but renovate can't create correct PR

**Relevant debug logs**

```text
}
DEBUG: getBranchPr(renovate/lock-file-maintenance)(branch="renovate/lock-file-maintenance")
DEBUG: findPr(renovate/lock-file-maintenance, undefined, open)(branch="renovate/lock-file-maintenance")
DEBUG: branchExists=false(branch="renovate/lock-file-maintenance")
DEBUG: Branch has 0 upgrade(s)(branch="renovate/lock-file-maintenance")
DEBUG: recreateClosed is true(branch="renovate/lock-file-maintenance")
DEBUG: Checking schedule(before 5am on monday, null)(branch="renovate/lock-file-maintenance")
DEBUG: Checking 1 schedule(s)(branch="renovate/lock-file-maintenance")
DEBUG: Checking schedule "before 5am on monday"(branch="renovate/lock-file-maintenance")
{
  "parsedSchedule": {
    "schedules": [
      {
        "t_b": [
          18000
        ],
        "d": [
          2
        ]
      }
    ],
    "exceptions": [],
    "error": -1
  }
}
DEBUG: Does not match schedule because 6 is not in 1(branch="renovate/lock-file-maintenance")
DEBUG: Package not scheduled(branch="renovate/lock-file-maintenance")
DEBUG: Skipping branch creation as not within schedule(branch="renovate/lock-file-maintenance")
```

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [X] I have provided a minimal reproduction repository
- 
https://github.com/Trim21/poetry-lock-cannot-update

**Additional context**

### PR DESCRIPTION
**Pull request by trim21**
## Context:

close #9231
## Documentation (please check one with an [x])

- [X] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [X] No new tests but ran on a real repository
https://github.com/Trim21/poetry-lock-cannot-update/pull/18

### CODE REVIEW

**Review by viceice — APPROVED** [review]
@rarkins Backport to v24?

**Comment by rarkins** [comment]
We use `config.isLockFileMaintenance` elsewhere. I was thinking that `is<updateType>` should be automatically populated. Is the problem because multiple updates are in one config?

**Comment by Trim21** [comment]
I logged the config object，updatedDeps is empty when lock file maintenance

**Comment by rarkins** [comment]
> @rarkins Backport to v24?

Not until I understand if or why other config.isLockFileMaintenance references in our code base work

**Comment by Trim21** [comment]
what's blocking this? Is there anything else I need to do?

**Comment by viceice** [comment]
@Trim21 we need to find the cause why `config.isLockFileMaintenance` is not working as expected.

Your pr is a workaround and not a fix for the root cause.

**Comment by rarkins** [comment]
I've created #9728 so I'm ok to merge this in the meantime

**Pull request merged**
