### PR TITLE
feat(github): Support multiple auto-merge types

### PR DESCRIPTION
**Pull request by zharinov**
## Changes:

Ref #12363

## Context:

Pick up particular `automergeStrategy`, or at least prefer `REBASE` over `SQUASH` and `MERGE`, depending on repository settings.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by rarkins — CHANGES_REQUESTED** [review]

**Review by viceice — APPROVED** [review]

**Review by rarkins — APPROVED** [review]

**Comment by glasser** [comment]
How does an end user choose a preferred merge method? Is this automergeStrategy, whose docs seem to still say is only supported by Bitbucket?

**Comment by rarkins** [comment]
@zharinov could you update any docs necessary?

**Comment by zharinov** [comment]
We should add support for `automergeStrategy` for GitHub, and GitLab and Azure as well (separate PRs).

**Comment by zharinov** [comment]
For now, it falls back from `REBASE` to `SQUASH` and then to `MERGE` for GitHub

**Comment by glasser** [comment]
I'm not sure I follow — what falls back? Is there configurability?

**Comment by zharinov** [comment]
For now, only with repository settings, as it was wite Renovate own automerge mechanism.

**Pull request merged**
