### PR TITLE
fix(gitlab): skipped jobs are ignored

### PR DESCRIPTION
**Pull request by alexkvak**
## Changes:

Skipped GitLab pipeline jobs are ignored.
If GitLab pipeline has only skipped jobs — the result is y ellow.
Otherwise standard rules are applied.

## Context:

I have succeeded pipeline with one skipped job. This job only runs when one of previous jobs fail.
Renovate thinks that pipeline is red and falls back to create an MR.

But it should merge branch while skipped job is OK.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by alexkvak** [comment]
@rarkins  could you review this PR?

**Comment by rarkins** [comment]
Important question: Should a repo with *only* skipped tests be considered as green/ready to merge? I would have thought not but that's the test case you have. I would have expected to be green, a commit must have 1 or more passing tests and no pending or failing tests. (skipped tests kind of get treated as not counting at all, instead of counting as green)

**Comment by alexkvak** [comment]
> Should a repo with only skipped tests be considered as green/ready to merge?

I guess question is not pretty correct. This PR is about skipped pipeline steps (jobs). Job isn't always the test. In our case skipped job is the slack notification sender. It should run only if the one of the previous jobs fail.

**Comment by rarkins** [comment]
I think we can defensively handle this situation though. You never know when a GitLab bug or an unforeseen edge cases could cause it. Possibly just filter out skipped checks first and then evaluate the remaining checks? That way a job with all skipped checks does not show up as green, but a job with only passing + skipped does.

**Comment by alexkvak** [comment]
@rarkins please take a look

**Review by rarkins — APPROVED** [review]

**Pull request merged**
