### PR TITLE
fix: Master issue GitLab MR links broken

### LINKED ISSUE #2615: Master issue has wrong PR links
**What Renovate type are you using?**
Renovate Docker

**Describe the bug**
When Renovate's master issue links to GitLab MRs, the link is incorrect.

It generates: `https://gitlab.com/<project>/pull/<#>`

When it should be: `https://gitlab.com/<project>/merge_requests/<#>`

**To Reproduce**

1.  Setup a renovate project in GitLab with `:masterIssueApproval` with some outdated dependencies
2.  Run renovate
3.  Open new master issue and tick the dependency to get renovate to open a PR
4.  Run renovate again
5.  See open PR link is now incorrect in GitLab issue.

**Expected behavior**
Link leads to correct PR instead of 404.

### PR DESCRIPTION
**Pull request by Jamesking56**
Fixes MR links in GitLab for Master Issue.

Not sure how to test this so please test in review.

Closes #2615

### CODE REVIEW

**Comment by Jamesking56** [comment]
Not sure why Travis failed here.

**Comment by rarkins** [comment]
@Jamesking56 it's just a formatting problem:

> The command "yarn prettier --list-different" exited with 1.

I'll fix it up as I want to make a small change anyway.

**Comment by Jamesking56** [comment]
Has this released to the Docker container? This change isn't actually working for me even though I'm using the latest image

**Comment by rarkins** [comment]
It should have been, but I tightened the regex to try to reduce false positives and may have made a mistake before merging. I’ll test it again soon

**Pull request closed without merging**
