### PR TITLE
fix(repository): It should not create / update / delete any master issue in dry run mode.

### LINKED ISSUE #3966: Renovate CLI with dry run creates master issue
**What Renovate type are you using?**
CLI

**Describe the bug**
It should not create the master issue in dry run mode.

**Did you see anything helpful in debug logs?**
-

**To Reproduce**
Master issue is enabled on the repository :
```
{
  masterIssue: true
}
```
Renovate runs with `--dry-run=false`

**Expected behavior**
It should not create / update / delete any issue.

**Additional context**
I think we should modify master-issue.js and any `await platform.xxxx()` calls like this
```
      if (config.dryRun) {
        logger.info('DRY-RUN: Would close Master Issue ' + config.masterIssueTitle);
      } else {
        await platform.ensureIssueClosing(config.masterIssueTitle);
      }
```

### PR DESCRIPTION
**Pull request by jgarec**
Closes #3966

### CODE REVIEW

**Comment by ViceIce** [comment]
@jgarec Please add tests to fix coverage.

**Comment by jgarec** [comment]
Yes of course
But i think a refactoring is necessary. ensureMasterIssue() has too much complexity

**Comment by ViceIce** [comment]
Yes, but refactoring should be done on separate pr

**Comment by rarkins** [comment]
@jgarec it would be fantastic if you are able to refactor the function to reduce complexity. Would you prefer to do that step first and then fix the dry run, or first fix the dry run and then do the refactoring? I don't mind either way.

**Comment by rarkins** [comment]
Thanks @jgarec !

**Pull request merged**
