### PR TITLE
fix: use correct manager config for fileMatch

### PR DESCRIPTION
**Pull request by srueg**
Use correct manager config for fileMatch. Otherwise the language overwrites won't be merged correctly.

### CODE REVIEW

**Comment by JamieMagee** [comment]
Hi @srueg! Thanks for your contribution. I merged the current master into your branch, which kicked off the CI again.

Is there a test you could add to verify this behaviour? And have you tested this change locally?

**Comment by srueg** [comment]
I'm in the process of adding a new language with two managers and I set the `fileMatch` on the language level. I then realized the config is not properly merged and it failed. With my change the merged config is used and it will honor the `fileMatch` option on language leve.

**Comment by rarkins** [comment]
I think that this fix is probably correct, *however* I think that it's probably not correct to define `fileMatch` at the `language` level. Normally managers would look into different file names. So I think we can merge this but I'd caution in case you maybe shouldn't be configuring that way. @srueg can you elaborate on your use case?

**Comment by srueg** [comment]
Yeah, giving it a second thought, I probably don't need a new language. A manager can return dependencies of different types, right? I.e. my manager handles Docker images and Helm charts.
I implemented this with two managers (one for Docker, one for Helm) but one should probably do it.

**Comment by rarkins** [comment]
A manager can return dependencies with different datasources, yes. For example `circleci` returns both `docker` and `orb` types. If it's the same file then usually it should be a single `manager` and with no `language` parent.

**Pull request merged**
