### PR TITLE
 fix: resolve repoConfig.packageRules.extends with repo config

### LINKED ISSUE #14974: repoConfig.packageRules.extends no longer works
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.11.3

### Please select which platform you are using if self-hosting.

github.com

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

When using `packageRules` with `expands` in the `config.js`, it no longer expands the presets.

Reproduction repo is https://github.com/anomiex/renovate-test/

It seems the patch that originally fixed this bug was reverted because it broke some other feature that seems to be completely undocumented (#14827)?

### Relevant debug logs

<details><summary>Logs</summary>

The config in the reproduction repo sets `separateMajorMinor` for `monorepo:wordpress`. The update record for packages in that monorepo should show "bucket" as "latest", as here with 32.9.3:

```
2022-04-05T20:15:38.0862720Z                {
2022-04-05T20:15:38.0862959Z                  "depType": "dependencies",
2022-04-05T20:15:38.0863320Z                  "depName": "@wordpress/i18n",
2022-04-05T20:15:38.0863576Z                  "currentValue": "4.4.0",
2022-04-05T20:15:38.0863818Z                  "datasource": "npm",
2022-04-05T20:15:38.0864089Z                  "prettyDepType": "dependency",
2022-04-05T20:15:38.0864325Z                  "depIndex": 0,
2022-04-05T20:15:38.0864565Z                  "updates": [
2022-04-05T20:15:38.0864771Z                    {
2022-04-05T20:15:38.0864987Z                      "bucket": "latest",
2022-04-05T20:15:38.0865232Z                      "newVersion": "4.5.0",
2022-04-05T20:15:38.0865456Z                      "newValue": "4.5.0",
2022-04-05T20:15:38.0865829Z                      "releaseTimestamp": "2022-03-23T13:52:36.437Z",
2022-04-05T20:15:38.0866095Z                      "newMajor": 4,
2022-04-05T20:15:38.0866323Z                      "newMinor": 5,
2022-04-05T20:15:38.0866554Z                      "updateType": "minor",
2022-04-05T20:15:38.0866931Z                      "branchName": "renovate-sh/wordpress-monorepo"
2022-04-05T20:15:38.0867195Z                    }
2022-04-05T20:15:38.0867388Z                  ],
2022-04-05T20:15:38.0867590Z                  "warnings": [],
2022-04-05T20:15:38.0867819Z                  "versioning": "npm",
2022-04-05T20:15:38.0868125Z                  "sourceUrl": "https://github.com/WordPress/gutenberg",
2022-04-05T20:15:38.0868448Z                  "sourceDirectory": "packages/i18n",
2022-04-05T20:15:38.0868713Z                  "currentVersion": "4.4.0",
2022-04-05T20:15:38.0868968Z                  "isSingleVersion": true,
2022-04-05T20:15:38.0869215Z                  "fixedVersion": "4.4.0"
2022-04-05T20:15:38.0869431Z                },
```

With 32.11.3, we instead get "bucket" set to "non-major", indicating that the `separateMajorMinor` was not applied.
```
2022-04-05T20:18:57.4826676Z            {
2022-04-05T20:18:57.4826894Z              "packageFile": "package.json",
2022-04-05T20:18:57.4827111Z              "deps": [
2022-04-05T20:18:57.4827302Z                {
2022-04-05T20:18:57.4827516Z                  "depType": "dependencies",
2022-04-05T20:18:57.4827770Z                  "depName": "@wordpress/i18n",
2022-04-05T20:18:57.4828003Z                  "currentValue": "4.4.0",
2022-04-05T20:18:57.4828239Z                  "datasource": "npm",
2022-04-05T20:18:57.4828545Z                  "prettyDepType": "dependency",
2022-04-05T20:18:57.4828787Z                  "depIndex": 0,
2022-04-05T20:18:57.4829081Z                  "updates": [
2022-04-05T20:18:57.4829279Z                    {
2022-04-05T20:18:57.4829556Z                      "bucket": "non-major",
2022-04-05T20:18:57.4829794Z                      "newVersion": "4.5.0",
2022-04-05T20:18:57.4830005Z                      "newValue": "4.5.0",
2022-04-05T20:18:57.4830355Z                      "releaseTimestamp": "2022-03-23T13:52:36.437Z",
2022-04-05T20:18:57.4830614Z                      "newMajor": 4,
2022-04-05T20:18:57.4830829Z                      "newMinor": 5,
2022-04-05T20:18:57.4831050Z                      "updateType": "minor",
2022-04-05T20:18:57.4831410Z                      "branchName": "renovate-sh/wordpress-monorepo"
2022-04-05T20:18:57.4831656Z                    }
2022-04-05T20:18:57.4831839Z                  ],
2022-04-05T20:18:57.4832030Z                  "warnings": [],
2022-04-05T20:18:57.4832255Z                  "versioning": "npm",
2022-04-05T20:18:57.4832549Z                  "sourceUrl": "https://github.com/WordPress/gutenberg",
2022-04-05T20:18:57.4832863Z                  "sourceDirectory": "packages/i18n",
2022-04-05T20:18:57.4833118Z                  "currentVersion": "4.4.0",
2022-04-05T20:18:57.4833362Z                  "isSingleVersion": true,
2022-04-05T20:18:57.4833603Z                  "fixedVersion": "4.4.0"
2022-04-05T20:18:57.4833808Z                },
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

### PR DESCRIPTION
**Pull request by anomiex**
## Changes

Redo #14688, working around the undocumented setting thing from #14827.

## Context

Closes #14974

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — CHANGES_REQUESTED** [review]
needs test case(s) to validate that the bug for `sourceUrl` never happen again.

**Comment by anomiex** [comment]
It turns out that's easier said than done, because the tests for the merge module unconditionally mock the migrate-validate module that's responsible for actually throwing the error.

I've added a test that checks that the mocked migrateAndValidate function wasn't passed the packageRules. If you know of a better way to test it, feel free to contribute.

**Review by viceice — COMMENTED** [review]
I'm not sure here 🤷‍♂️

**Review by viceice — COMMENTED** [review]
@rarkins I'm still not sure about side effects here.

**Comment by rarkins** [comment]
Same here. Let's try to step back:

The problem here is that an `extends` array within `packageRules` within `config.js` doesn't get resolved. If it's present within a `renovate.json` then it does.

This happens because:
- `extends` values are "lazily" resolved, meaning not during global init but instead waiting until repo init
- we are resolving `extends` within repo config before merging it with global config, meaning they are missed out

We already have a bit of a hack to copy `extends` from the root of global config into the repo config before resolving it, but `extends` within `packageRules` - or anywhere else non-root will be missed out.

So would this change work instead?

```
diff --git a/lib/workers/repository/init/merge.ts b/lib/workers/repository/init/merge.ts
index 1ead00699..4ad24befa 100644
--- a/lib/workers/repository/init/merge.ts
+++ b/lib/workers/repository/init/merge.ts
@@ -249,6 +249,7 @@ export async function mergeRenovateConfig(
     delete resolvedConfig.hostRules;
   }
   returnConfig = mergeChildConfig(returnConfig, resolvedConfig);
+  returnConfig = await presets.resolveConfigPresets(returnConfig, config);
   returnConfig.renovateJsonPresent = true;
   // istanbul ignore if
   if (returnConfig.ignorePaths?.length) {
```

**Comment by anomiex** [comment]
> So would this change work instead?

It does for my use case. Updated the PR to use that.

**Review by rarkins — APPROVED** [review]

**Review by viceice — APPROVED** [review]
🤷‍♂️

**Pull request merged**
