### PR TITLE
fix(git): support setting file mode

### PR DESCRIPTION
**Pull request by ylemkimon**
## Changes:

Support setting the file mode (`chmod`) in `git.commitFiles()`

## Context:

Sometimes, there is a need to set the file mode in committed files, e.g., executables.

This is a blocking issue for #11368.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by rarkins — APPROVED** [review]

**Comment by rarkins** [comment]
Ok, let's revert and make sure to test using Windows CI for this feature specifically

**Comment by rarkins** [comment]
@ylemkimon Could you restore this branch and create a new PR? Then we can add multi platform tests until we've verified it works 

@viceice maybe we could reserve a certain branch pattern or other technique to trigger cross platform tests without us needing to manually edit workflows per-PR?

**Comment by viceice** [comment]
I think we can use a manual dispatch trigger for this.

I think this can be easily handled, with multiple workflows and composite actions to reduce duplicate code.

**Comment by ylemkimon** [comment]
One way I use to trigger the workflow on PRs is to use a label and `labeled` event.

**Comment by viceice** [comment]
Sounds good, can you make a small sample?

https://github.community/t/manually-triggering-checks-for-a-pr/134054

**Comment by viceice** [comment]
No, but it makes it easier, because of less duplicate workflow code. 😉

**Pull request merged**
