### PR TITLE
feat(github): reuse autoclosed PRs

### LINKED ISSUE #3982: Check for existing autoclosed PR before opening new PR
**What would you like Renovate to be able to do?**

Reuse autoclosed PRs

**Describe the solution you'd like**

Before Renovate opens new PRs check in case there previously existed a PR with same branch name and matching PR title (including " - autoclosed" suffix). If so, then attempt to reopen and update that old closed PR instead of creating a new one. This would reduce the impact of "flapping" of autoclosed PRs.

**Describe alternatives you've considered**

Today the bot just opens new PRs

**Additional context**

See #3981

### PR DESCRIPTION
**Pull request by rarkins**
## Changes:

Adds logic to look for an autoclosed PR for the same branch as called for `getBranchPr()`. If found then an attempt to restore the branch and reopen the PR is made, so that it can be reused.

## Context:

Closes #3982 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by zharinov** [comment]
`getPr` may use obsolete cache, as I can remember, but not sure

**Comment by rarkins** [comment]
getPr looks in the graphql lists first, then queries it directly by number using REST if not found. By deleting it from the closed graphql list it causes it to be fetched from REST, which should not have been called previously (it's a closed PR..).

Would be good to make it a bit more explicit though.

**Review by viceice — COMMENTED** [review]
Looks good, needs tests.

**Review by viceice — DISMISSED** [review]

**Comment by rarkins** [comment]
I've reverted it due to finding some noisy logging when it tries to reopen more than once in a run. Although it's working and the logged errors can be ignored, I'd like to clear those up.

**Pull request merged**
