### PR TITLE
fix(onboarding): force branch creation to prevent diff-check

### LINKED ISSUE #21109: Git function thrown when pushing onboarding branch
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us what version of Renovate you run.

Latest/source

### If you're self-hosting Renovate, select which platform you are using.

github.com

### Was this something which used to work for you, and then stopped?

I am trying to get this working for the first time

### Describe the bug

A git error is logged during the process of creating the onboarding branch, but it does not seem to create an impact.

I'm not sure yet whether this is 100% reproducible or only in certain circumstances.

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Creating onboarding branch (repository=renovate-tests/pip8)
DEBUG: Preparing files for committing to branch renovate/configure (repository=renovate-tests/pip8)
DEBUG: Setting git author name: Renovate Testing (repository=renovate-tests/pip8)
DEBUG: Setting git author email: renovate-tests@redgc.com (repository=renovate-tests/pip8)
DEBUG: git commit (repository=renovate-tests/pip8)
       "deletedFiles": [],
       "ignoredFiles": [],
       "result": {
         "author": null,
         "branch": "renovate/configure",
         "commit": "777eba6cbd0ca4800a7c78662dbc7e2ddde6a0a9",
         "root": false,
         "summary": {"changes": 1, "insertions": 3, "deletions": 0}
       }
DEBUG: Git function thrown (repository=renovate-tests/pip8)
       "err": {
         "task": {
           "commands": ["diff", "HEAD", "origin/renovate/configure"],
           "format": "utf-8",
           "parser": "[function]"
         },
         "message": "fatal: ambiguous argument 'origin/renovate/configure': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n",
         "stack": "Error: fatal: ambiguous argument 'origin/renovate/configure': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n\n    at Object.action (/Users/rhys/src/github/renovatebot/renovate/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:42:29)\n    at PluginStore.exec (/Users/rhys/src/github/renovatebot/renovate/node_modules/simple-git/src/lib/plugins/plugin-store.ts:29:29)\n    at /Users/rhys/src/github/renovatebot/renovate/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:127:42\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/Users/rhys/src/github/renovatebot/renovate/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:124:14)\n    at GitExecutorChain.<anonymous> (/Users/rhys/src/github/renovatebot/renovate/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:100:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/Users/rhys/src/github/renovatebot/renovate/node_modules/simple-git/dist/cjs/index.js:55:24)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
       }
DEBUG: Pushing refSpec renovate/configure:renovate/configure (repository=renovate-tests/pip8)
DEBUG: git push (repository=renovate-tests/pip8)
       "result": {
         "pushed": [
           {
             "deleted": false,
             "tag": false,
             "branch": true,
             "new": true,
             "alreadyUpdated": false,
             "local": "refs/heads/renovate/configure",
             "remote": "refs/heads/renovate/configure"
           }
         ],
         "ref": {"local": "refs/remotes/origin/renovate/configure"},
         "remoteMessages": {
           "all": [
             "Create a pull request for 'renovate/configure' on GitHub by visiting:",
             "https://github.com/renovate-tests/pip8/pull/new/renovate/configure"
           ],
           "pullRequestUrl": "https://github.com/renovate-tests/pip8/pull/new/renovate/configure"
         }
       }
 INFO: Branch created (repository=renovate-tests/pip8, branch=renovate/configure)
       "commit": "777eba6cbd0ca4800a7c78662dbc7e2ddde6a0a9",
       "onboarding": true```

</details>


### Have you created a minimal reproduction repository?

I have explained in the description why a minimal reproduction is impossible

### PR DESCRIPTION
**Pull request by RahulGautamSingh**
## Changes

- Add `force:true` option to the `commitAndPush` fn call when creating an onboarding branch.
https://github.com/renovatebot/renovate/blob/39493b715ba06881111fb6df65766905a51f78a1/lib/workers/repository/onboarding/branch/create.ts#L36-L49
- This is necessary so that we don't perform a diff-check with the remote onboarding branch which in this case won't exist.
https://github.com/renovatebot/renovate/blob/39493b715ba06881111fb6df65766905a51f78a1/lib/util/git/index.ts#L1005-L1011
- I found that we do the same when creating update branch so basically just adding the option here as well.
https://github.com/renovatebot/renovate/blob/39493b715ba06881111fb6df65766905a51f78a1/lib/workers/repository/update/branch/commit.ts#L53-L61

## Context
- Closes: https://github.com/renovatebot/renovate/issues/21109

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
Please describe what this changes and why this works

**Comment by rarkins** [comment]
So then in which cases do we _not_ force?

**Comment by RahulGautamSingh** [comment]
The cases in which we force:
1. User requested a rebase
2. Branch doesn't exist (ie. we are creating new branch)
3. Branch is conflicted

In the remaning cases we do not force ie. behind-base
- For onboarding branches currently we never force

**Review by viceice — APPROVED** [review]

**Comment by RahulGautamSingh** [comment]
> So then why do we need to force for onboarding? Does it "skip" today?

To prevent the diff-check which causes the error each time a onboardingbranch is created.

**Pull request merged**
