### PR TITLE
feat(github): add PR suffix to automerge commit titles

### LINKED ISSUE #3116: Add PR suffix to automerge commit titles
**What would you like Renovate to be able to do?**
When automerging a PR, add the PR # at the end of the commit message

**Describe the solution you'd like**
For [this commit](https://github.com/artsy/reaction/commit/59e805223d54dca29bf013ba42a0be892d5c92af) the message would be be 

```
Update dependency @artsy/palette to v2.35.0 (#1964)
```

**Additional context**

This just makes it a little easier to trace back to the original PR.

### PR DESCRIPTION
**Pull request by AhmedAbdraboh**
Add PR suffix to automerge commit titles

Closes #3116

### CODE REVIEW

**Comment by rarkins** [comment]
To test this, set up a test repo with a renovate config like this:

```
{
  "requiredStatusChecks": null,
  "automerge": true
}
```

This tells Renovate to skip tests, so it should automerge right away. The easiest package file to test with would be a `.nvmrc` file, e.g. with value `10.15.0`. Then you should see it automerge updated to `10.15.1`.

**Comment by rarkins** [comment]
Also, I'd like to test it with different merge types - merge commit, squash merge, rebase merge. I'm not sure if this `commit_message` param works for all 3.

**Comment by zephraph** [comment]
@rarkins, `commit_message` should work with all three types. The merge api exposes that as well as `merge_type` as a first class option. 

https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button

**Comment by zephraph** [comment]
Oh, one thing though. I don't think this is gonna be exactly what we want. @AhmedAbdraboh, this sets the commit message to ` (#123)`. We _do_ want the to be appended to commit_message, but unless commit_message is being set somewhere else this will just set the commit message to be the number.

**Comment by zephraph** [comment]
Is there a way to get the PR title here?

**Comment by rarkins** [comment]
Isn’t the commit message field *appended* according to documentation?

**Comment by rarkins** [comment]
I've tested this and the solution doesn't work. Happy to accept any PR that has tested/verified a way that works.

**Pull request closed without merging**
