### PR TITLE
feat: Clean up change logs

### PR DESCRIPTION
**Pull request by illay1994**
## Context

- #23139

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by rarkins — CHANGES_REQUESTED** [review]
There are many changes here which seem unrelated to the issue this is meant to close

**Comment by illay1994** [comment]
> There are many changes here which seem unrelated to the issue this is meant to close

https://github.com/illay1994/renovate/pull/2

I added the next changes in a separate PR.

**Comment by illay1994** [comment]
Hi @rarkins 
Thanks for review.
I plan to contribute a lit bit more.

I would like after this PR add Azure DevOps Change Logs Source and review 
lib/workers/repository/update/pr/changelog/release-notes.ts to migrate to Change log source

**Review by viceice — COMMENTED** [review]
please split this PR. it's far to big. especially the code move on changelogs should be done in a separate PR.

**Comment by illay1994** [comment]
#25364 - First pr

**Comment by rarkins** [comment]
I think it would be cleaner to create a new PR. Closing due to inactivity and conflicts

**Pull request closed without merging**
