### PR TITLE
docs: use proper capitalization for noun JavaScript

### PR DESCRIPTION
**Pull request by HonkingGoose**
## Changes:

- Capitalize the word JavaScript in the documentation.

## Context:

Words like Docker, JavaScript, GitHub, GitLab, CircleCI, Travis, look better if they are capitalized properly, I have noticed some inconsistencies in the capitalization of these kinds of words.

This pull request only changes the word JavaScript, to test the waters.

I know that there's more stuff like this that I can fix for you, if you want. Let me know if you like/hate this idea, and want me to proceed/stop. :+1: 

I'm not 100 % sure if I should change the `title:` and `description:` metadata fields in the Markdown files? Does that affect the docs building process if I change the metadata? :confused:

### CODE REVIEW

**Review by viceice — APPROVED** [review]
I'm okay with those changes. The `title` and `descriptsion` metadata is only for visual context, so should also ok.

**Review by rarkins — APPROVED** [review]

**Comment by HonkingGoose** [comment]
Do you prefer one big pull request to update all those words in one go or do you want one pull request per word?

**Comment by viceice** [comment]
how you like, as long as this are only docs changes 🙃

**Comment by HonkingGoose** [comment]
Ah nice, it's merged into `master`.
I'll go do the rest of the words then in one big pull request.
I'll keep my changes limited to the `docs/` folder.

**Pull request merged**
