### PR TITLE
feat(gomod): Update source import paths on major upgrade

### LINKED ISSUE #3348: Go modules: update source code after major updates
**What would you like Renovate to be able to do?**

Update Go's import references after major updates

**Describe the solution you'd like**

Whenever doing a major update in `go.mod`, Renovate should find and update all "old" references from within source code, e.g.

image

I'm not sure yet about exactly what logic Renovate should use or if it's as simple as a global grep/search/replace through `*.go` files.

**Describe alternatives you've considered**

Otherwise users need to add these changes themselves to a PR.

**Additional context**

This is an example PR from Renovate today: https://github.com/hairyhenderson/github-responder/pull/82

Here is a manual/human PR that replaced it: https://github.com/hairyhenderson/github-responder/pull/90 (Cc @hairyhenderson)

Something also strange is that the replacement PR has vendored modules updated while Renovate's did not. I'm suspecting it could be related to Renovate's failure to update the references in source code, but not 100% sure.

### PR DESCRIPTION
**Pull request by 56KBs**
## Changes:

Add gomodUpdateImportPaths postUpdateOption to update source code import paths when major updates occur.

Uses [marwan-at-work/mod](https://github.com/marwan-at-work/mod) to complete the source code update

## Context:

Closes #3348

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by 56KBs** [comment]
A point to discuss from this PR is the interaction & effective requirement for running the `gomodTidy` post update option alongside this newly introduced option.

An example PR using just `gomodUpdateImportPaths` postUpdateOption can be seen here - https://github.com/56KBs/renovate-bug-mrr/pull/2. 

You can see both imports exist in the `go.mod` file, this is due to the ordering of events that occur. `go get` runs, adding the dependency and re-adding the old import, `marwan-at-work/mod` then runs, updating the import paths. Nothing is run to remove the un-needed imports, I can see two ways to resolve this:

1. All users of `gomodUpdateImportPaths` must also enable `gomodTidy` to get the real value from it
2. Following `gomodUpdateImportPaths` making changes, the `go get` runs **again**, which should, in theory, remove the unneeded import

The ordering implemented in this PR is the only order it can be completed in, `marwan-at-work/mod` cannot occur before the `go get` is issued as it will fail, see here for the error: https://github.com/56KBs/renovate-bug-mrr/pull/1

**Comment by rarkins** [comment]
I have considered whether to run `goModTidy` by default before, and we could consider it again.

Alternatively, running it implicitly if it's a major update, but then the behavior would be inconsistent between major and non-major updates.

We should also consider whether to make this PR's functionality default too, if we are generating incorrect PRs without it anyway.

Running `go get` twice seems ok too though.

**Comment by 56KBs** [comment]
Having tested the double `go get` functionality, it sadly doesn't work as I expected - This makes it more complicated to resolve, without the `goModTidy` being default behaviour, or implicitly run too.

I personally am not sure why you wouldn't run `goModTidy` by default, but perhaps there are some edge cases I've not considered.

**Comment by rarkins** [comment]
@56KBs let's start by running `goModTidy` for all major updates, as part of the PR you're preparing. It sounds like we'll probably switch to running it by default for non-major updates too, but for now we can limit it to major-only, which are currently "partly broken" anyway.

FYI the main reason for not running tidy all the time was because initially it wasn't part of go modules, and the modules creator thought people shouldn't focus on "cleaning up" their modules definitions too obsessively. So if it was optional for go mod, we kept it as optional for Renovate. But from my point of view, it makes sense to run.

**Comment by 56KBs** [comment]
I've made `goModTidy` implicitly enabled on all major updates. For now however I've left `gomodUpdateImportPaths` as optional - I'm happy to remove this postUpdateOption and make it default behaviour on major updates if desired.

**Review by rarkins — COMMENTED** [review]
This looks good to me, I think best to leave it behind a feature flag like 
you've done until a few people have validated it in practice. Before approving, can you point to some example PRs where it's working?

**Comment by 56KBs** [comment]
Having ran it over some larger examples, it flagged up a bug when going from v0 -> v1 (It shouldn't update any source code) - I've pushed a fix for it and here are some example PRs:

1. https://github.com/56KBs/renovate-bug-mrr/pull/4 - Using a fork of the reproduction repo from https://github.com/renovatebot/renovate/issues/9127
1. https://github.com/56KBs/github-responder/pull/7 - Using a fork of the repository from https://github.com/renovatebot/renovate/issues/3348
   1. https://github.com/56KBs/github-responder/pull/8 - Shows a v0 to v1 upgrade

**Review by rarkins — APPROVED** [review]

**Pull request merged**
