### PR TITLE
fix: add @types/eslint to packages:eslint

### PR DESCRIPTION
**Pull request by keeganwitt**
## Changes:

Add [`@types/eslint`](https://www.npmjs.com/package/@types/eslint) to the [`packages:eslint`](https://docs.renovatebot.com/presets-packages/#packageseslint) preset.

## Context:

I think it makes sense to group these dependencies together, particularly since there's already TypeScript ESLint dependencies in this preset.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — APPROVED** [review]
@rarkins I'm not sure, but shouldn't this automatically grouped? 🤔

**Review by viceice — CHANGES_REQUESTED** [review]
Needs snapshot updates

**Comment by keeganwitt** [comment]
> Needs snapshot updates

Ah, I see. Thank you.

**Comment by rarkins** [comment]
> @rarkins I'm not sure, but shouldn't this automatically grouped? 🤔

`@types/eslint` gets kind of "impicitly grouped" with `eslint` (we drop the `@types-` part from the branch name) but won't "follow" it into explicit groups.

**Comment by keeganwitt** [comment]
> > @rarkins I'm not sure, but shouldn't this automatically grouped? 🤔
> 
> `@types/eslint` gets kind of "impicitly grouped" with `eslint` (we drop the `@types-` part from the branch name) but won't "follow" it into explicit groups.

In cases like this, has it been preferred to rely on the implicit grouping rather than changing the preset? If so, how would the user be aware of this?

**Review by viceice — APPROVED** [review]
As @rarkins mentioned we need this to properly group to eslint.

**Pull request merged**
