### PR TITLE
ci(dependency review): create allow-licenses list

### LINKED ISSUE #16106: Configure new options for `dependency-review-action`
### Describe the proposed change(s).

The new major version of the `dependency-review-action` has some new features that we _may_ want to use.

I'm opening an issue to discuss which, if any, of these features we want to use.

Relevant quote: [^quote]

> Major version update! We are introducing a few configuration options to make the action more useful in a broader set of scenarios:
> 
> - `fail-on-severity`: Specify the minimum security vulnerability threshold before failing workflow runs.
> - `allow-licenses`: An allowlist for dependency licenses.
> - `deny-licenses`: A blocklist for dependency licenses.
> 
> You can read more about these options in the ["Configuration" section of the README](https://github.com/actions/dependency-review-action/#configuration).

Update PR:

- #16101

[^quote]: [`dependency-review-action v2` release notes](https://github.com/actions/dependency-review-action/releases/tag/v2.0.0)

### PR DESCRIPTION
**Pull request by HonkingGoose**
## Changes

- Create `allow-licenses` list [^docs]

## Context

We have a `dependency review` action. The goal of this action is to warn us if we're taking on new dependencies that have known vulnerabilities. The action recently gained a new feature, it can now check the license of new dependencies.

I don't know what licenses are compatible with our `AGPL-3.0-only` license, so I'm only putting the `AGPL-3.0-only` and the `AGPL-3.0-or-later` licenses in the allow list.

The allow-list uses SPDX license identifiers. [^spdx]

Closes #16106.

### Upstream docs

> ### Licenses
> 
> You can set the action to fail on pull requests based on the licenses of the dependencies
> they introduce. With `allow-licenses` you can define the list of licenses
> your repository will accept. Alternatively, you can use `deny-licenses` to only
> forbid a subset of licenses. These options are not supported on GHES.
> 
> You can use the [Licenses API](https://docs.github.com/en/rest/licenses) to see the full list of supported licenses. Use the `spdx_id` field for every license you want
> to filter. A couple of examples:
> 
> ```yaml
> # only allow MIT-licensed dependents
> - name: Dependency Review
>   uses: actions/dependency-review-action@v2
>   with:
>     allow-licenses: MIT
> ```
> 
> ```yaml
> # Block Apache 1.1 and 2.0 licensed dependents
> - name: Dependency Review
>   uses: actions/dependency-review-action@v2
>   with:
>     deny-licenses: Apache-1.1, Apache-2.0
> ```
> 
> **Important**
> 
> * Checking for licenses is not supported on GHES.
> * The action will only accept one of the two parameters; an error will
> be raised if you provide both.
> * By default both parameters are empty (no license checking is
> performed).
> * We don't have license information for all of your dependents. If we
> can't detect the license for a dependency **we will inform you, but the
> action won't fail**.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

[^docs]: https://github.com/actions/dependency-review-action/#licenses
[^spdx]: https://spdx.org/licenses/

### CODE REVIEW

**Comment by JamieMagee** [comment]
Is the `allow-list` option an explicit list of allowed licenses, or is it for listing compatible licenses? The documentation isn't very clear on this.

**Comment by rarkins** [comment]
I would like to be warned before we add any additional GPL-licensed dependencies to this repo

**Comment by HonkingGoose** [comment]
> Is the `allow-list` option an explicit list of allowed licenses, or is it for listing compatible licenses?

@JamieMagee I think its an explicit list of allowed licenses. So if a PR introduces a dependency with a license that's _not_ on the `allow-licenses` list, the action will throw an error.

Quote from the docs:

> You can set the action to fail on pull requests based on the licenses of the dependencies
> they introduce. With `allow-licenses` you can define the list of licenses
> your repository will accept.

To know what to put in the `allow-licenses` list, we first need to know/decide what licenses are compatible with our license.

---

> I would like to be warned before we add any additional GPL-licensed dependencies to this repo

Unfortunately, we can't mix-and-match by using both `allow-licenses` _and_ `deny-licenses`.

**Comment by rarkins** [comment]
Unfortunately this doesn't seem to suit our needs

**Pull request closed without merging**
