### PR TITLE
fix(gitlab): follow pagination in getbranchstatus for gitlab

### LINKED ISSUE #4340: Renovate ignores status of later steps in large pipelines
#### This is a:

- [x] Bug report (non-security related)
- [ ] Feature request
- [ ] I'm not sure which of those it is

#### I'm using:

- [ ] The Renovate GitHub App
- [ ] Self-hosted GitHub
- [x] Self-hosted GitLab
- [ ] Self-hosted Azure DevOps

#### Please describe the issue:
I have a long pipeline of checks that all builds need to pass before being merged into master.
It seems that renovate uses gitlab's commit-status api to test if the checks have passed, see
https://docs.gitlab.com/ee/api/commits.html#commit-status
However that result is paginated and renovate seems to only check the first page (default is 20 steps) meaning renovate isn't aware if one of the later steps fails so will automerge (if nothing else prevents it).

### PR DESCRIPTION
**Pull request by eddarmitage**
There are cases where the first page of results is not representative of the entire branch's status, so we need to follow all pages in the result.

I _think_ this should be sufficient to fix the issue, but I don't really know enough node/jest to understand how the tests should work. Maybe something like the following?

```typescript
describe('Paginated getBranchStatus(branchName, requiredStatusChecks)', () => {
  beforeEach(() => {
    api.get.mockReturnValueOnce({
      headers: {
        Link: '<URL&page=2&per_page=1>; rel="next", <URL&page=1&per_page=1>; rel="first", <URL&page=2&per_page=1>; rel="last"',
      },
      body: [{ status: 'success' }],
    } as any);
    api.get.mockReturnValueOnce({
      headers: {
        Link: '<URL&page=1&per_page=1>; rel="first", <URL&page=2&per_page=1>; rel="last"',
      },
      body: [{ status: 'success' }],
    } as any);
  });
  it('returns success if all pages contain success', async () => {
    const res = await gitlab.getBranchStatus('somebranch', null);
    expect(res).toEqual('success');
  });
});
describe('Paginated getBranchStatus(branchName, requiredStatusChecks)', () => {
  beforeEach(() => {
    api.get.mockReturnValueOnce({
      headers: {
        Link: '<URL&page=2&per_page=1>; rel="next", <URL&page=1&per_page=1>; rel="first", <URL&page=2&per_page=1>; rel="last"',
      },
      body: [{ status: 'success' }],
    } as any);
    api.get.mockReturnValueOnce({
      headers: {
        Link: '<URL&page=1&per_page=1>; rel="first", <URL&page=2&per_page=1>; rel="last"',
      },
      body: [{ status: 'failed' }],
    } as any);
  });
  it('returns failed if any page contains failed', async () => {
    const res = await gitlab.getBranchStatus('somebranch', null);
    expect(res).toEqual('failed');
  });
});
```

Closes #4340

### CODE REVIEW

**Comment by ViceIce** [comment]
Tests looks good, you can move the `beforeEach` content to the `it` and then move both ìt` to one `describe`.

**Comment by rarkins** [comment]
@leipert could you review?

**Comment by eddarmitage** [comment]
@ViceIce: Test doesn't seem to pass, so I presume there's something wrong with the Link header, but I'm not quite sure what...

```console
 FAIL  test/platform/gitlab/index.spec.ts
  ● platform/gitlab › Paginated getBranchStatus(branchName, requiredStatusChecks) › returns failed if any page contains failed

    expect(received).toEqual(expected) // deep equality

    Expected: "failed"
    Received: "success"

      454 |       } as any);
      455 |       const res = await gitlab.getBranchStatus('somebranch', null);
    > 456 |       expect(res).toEqual('failed');
          |                   ^
      457 |     });
      458 |   });
      459 |   describe('getBranchStatusCheck', () => {

      at Object.toEqual (test/platform/gitlab/index.spec.ts:456:19)
```

**Comment by ViceIce** [comment]
@eddarmitage you should use `mockResolvedValueOnce`, because all `api` functions are async. An please push your tests, then ich can have look and provide a fix.

Don't worry about failing CI checks. We can fix them later.

**Comment by ViceIce** [comment]
Header: `Link` -> `link` (must be lowercase) 😅

**Comment by ViceIce** [comment]
See here for exanple paging:
https://github.com/renovatebot/renovate/blob/6be9ee0418b2b1f9be8313b2211cad65a75c3ccb/test/platform/gitlab/gl-got-wrapper.spec.ts#L19-L41

**Comment by eddarmitage** [comment]
@ViceIce: Failing tests pushed :)

**Comment by ViceIce** [comment]
@eddarmitage you can't test it there, because the gitlab-wrapper is mocked, so the paging is overwritten by the mocked function. 

@rarkins do we need a test for this? because paging should work.

**Comment by rarkins** [comment]
We don't need to add a new test if we already have 100% coverage

**Comment by ViceIce** [comment]
ok, so @eddarmitage you can remove the tests 👼

**Comment by eddarmitage** [comment]
Pushed with tests removed.

**Review by viceice — APPROVED** [review]
LGTM

**Comment by rarkins** [comment]
Thanks @eddarmitage !

**Comment by leipert** [comment]
Thanks, sorry for the late review (or non-existent 😆 ) Great work 🎉

**Pull request merged**
