### PR TITLE
fix(versioning/composer): support range versions normalization

### PR DESCRIPTION
**Pull request by Lctrs**
## Changes

With composer versioning, you can specify range versions in the form of eg. `^7.4|^8`. Actually, `composer2npm()` function does not normalize this to the valid semver equivalent `||`. This PR fixes this.

## Context

Ref https://github.com/renovatebot/renovate/pull/20217#discussion_r1113157711

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — COMMENTED** [review]
please add a test

**Comment by Lctrs** [comment]
> please add a test

@viceice Done.

**Review by viceice — APPROVED** [review]

**Comment by Lctrs** [comment]
@viceice Don't know why this doesn't get merged. I signed the CLA.

**Comment by viceice** [comment]
PR was outdated, I've updated now. it should automerge after ci checks succeeds

**Pull request merged**
