### PR TITLE
refactor(versioning/ubuntu): Postpone offering new releases

### PR DESCRIPTION
**Pull request by Gabriel-Ladzaretti**
## Changes
Postpone offering new releases by one week.

22.04 jammy is around the corner, should we be on the safe side and postpone updates?
currently we will start offering updates on the 21th, local time. delaying it might be a good idea.
 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — DISMISSED** [review]

**Comment by Gabriel-Ladzaretti** [comment]
> This pull request will squash and merge automatically when all requirements are met

just curious, what are these so called requirements? obviously required changes and approval.
any thing else? 
thought pending review requests  was preventing this from being merged, guess not...

**Comment by viceice** [comment]
branch is out of date, which is blocking automerge 😉

**Review by viceice — COMMENTED** [review]
this should probably use UTC instead of local time compare, so we're independent of time zone

**Review by viceice — COMMENTED** [review]
@rarkins I'm not longer sure if we should defer the update here. 🤔

**Comment by rarkins** [comment]
It's both future and current here: https://wiki.ubuntu.com/Releases

**Comment by rarkins** [comment]
I think one day is conservative enough. I'll merge this so that we can get tests to pass

**Review by rarkins — APPROVED** [review]

**Pull request merged**
