### PR TITLE
docs(platform/bitbucket): update requiring implementation section

### PR DESCRIPTION
**Pull request by setchy**
## Changes

Update non-implemented section for Bitbucket Cloud.  
## Context

Bitbucket Cloud Issues are currently implemented

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by rarkins — COMMENTED** [review]
Can this section be removed?

**Comment by setchy** [comment]
> Can this section be removed?

sure can.  i took a gamble and matched what the [gitea docs](https://docs.renovatebot.com/modules/platform/gitea/#features-awaiting-implementation) had.  i prefer it being removed too

**Comment by setchy** [comment]
Removed.  It does look like every other [platform subpage](https://docs.renovatebot.com/modules/platform) has this section though 🤔

**Comment by rarkins** [comment]
So maybe instead it's incomplete?

**Review by viceice — APPROVED** [review]

**Review by rarkins — APPROVED** [review]

**Pull request merged**
