### PR TITLE
fix(pypi): fallback to simple lookup on 403

### PR DESCRIPTION
**Pull request by Kakadus**
## Changes

This adds 403 to the simple index fallback check, so that pytorch index urls are correctly resolved by renovate.

## Context

See #26383 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by viceice** [comment]
🤔 this can cause a lot confusion when people try to get authentication to work with custom pypi registries.

**Comment by sorgfresser** [comment]
Right now the PyTorch dependency lookup fails with their private registry - while this might be an issue with torch's behaviour, renovate could fix this by defaulting to simple on 403s. I get that this could be confusing though. 

Could this retry be achieved using hostRules in the renovate config defaulting to the old behaviour, i.e. no retry? This way we could fix the PyTorch-issue while still not confusing the setup of private registries.

**Comment by rarkins** [comment]
Can we just restrict it to the pytorch domain for now?

**Comment by rarkins** [comment]
This would be a harder but better long term solution: https://github.com/renovatebot/renovate/issues/26483

**Comment by Kakadus** [comment]
I've tried to implement this in #26505. Closing this in favor of it for now.

**Pull request closed without merging**
