### PR TITLE
feat(composer): Read provided COMPOSER_AUTH (#12586)

### LINKED ISSUE #12586: Read COMPOSER_AUTH environment variable
### What would you like Renovate to be able to do?

The composer manager does not use the provided 

After reading [getting started docs on private composer packages](https://docs.renovatebot.com/getting-started/private-packages/) I was expecting that providing a `COMPOSER_AUTH` variable works, as described in [the composer documentation](https://getcomposer.org/doc/articles/authentication-for-private-packages.md#authentication-using-the-composer-auth-environment-variable).

When reading the code, I saw that a provided `COMPOSER_AUTH` environment variable would be overwritten by `extraEnv: { ..., COMPOSER_AUTH: getAuthJson() }` in [lib/manager/composer/artifacts.ts](https://github.com/renovatebot/renovate/blob/53e3cb17fef44032c11ac2ae33e94ccd1131fb3b/lib/manager/composer/artifacts.ts#L113)

### If you have any ideas on how this should be implemented, please tell us here.

When a `COMPOSER_AUTH` environment variable is provided, use that as the `AuthJson` values. 

Then if (as described in [renovatebot PHP documentation about Private packages](https://docs.renovatebot.com/php/)) `hostRules` values are provided, they will either overwrite (if exists) or appended (if not exists) to the `AuthJson` configuration.

When an invalid COMPOSER_AUTH is provided, an error will be thrown as this is not expected.

### Is this a feature you are interested in implementing yourself?

Yes

### PR DESCRIPTION
**Pull request by ruudvanderweijde**
## Changes:

Read `COMPOSER_AUTH` environment variable when provided.
The provided `hostRules` will overwrite provided `COMPOSER_AUTH` values when defined.
An `Error` will be thrown on an invalid `COMPOSER_AUTH` variable.

## Context:

Closes #12586

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by ruudvanderweijde** [comment]
@rarkins is there anything I should do on this pull request?

**Comment by rarkins** [comment]
@ruudvanderweijde branch needs de-conflicting, but also I'm curious how you address the problem that Renovate itself also needs access to the same registry credentials to do its lookups. Do you duplicate the credentials in both the environment variable as well as `hostRules` config?

**Comment by ruudvanderweijde** [comment]
I have resolved the conflict.

> also I'm curious how you address the problem that Renovate itself also needs access to the same registry credentials to do its lookups. Do you duplicate the credentials in both the environment variable as well as hostRules config?

In the previous/current version it's impossible to provide an external `COMPOSER_AUTH` environment variable because it would be always overwritten in [lib/manager/composer/artifacts.ts#L113](https://github.com/renovatebot/renovate/blob/main/lib/manager/composer/artifacts.ts#L113).
```js
111      extraEnv: {
112        COMPOSER_CACHE_DIR: await ensureCacheDir('composer'),
113        COMPOSER_AUTH: getAuthJson(),
114      },
```

As we have multiple projects using the `COMPOSER_AUTH`, we have it defined as JSON. So it's not easy to do a trick like using `process.env.XXX` to inject passwords. Obviously plaintext passwords are not wanted here.

The change that I did was just to pre-fill the `AuthJson` object with values from the `COMPOSER_AUTH` environment variable. All values provided by `hostRules` will then append or overwrite the values given by the `COMPOSER_AUTH` environment variable. This will make the `hostRules` always leading.

The relevant change: parse the `COMPOSER_AUTH` JSON and use it as default values before setting the `hostRules` values.
```js
  let authJson: AuthJson = {};

  if (process.env.COMPOSER_AUTH) {
    try {
      authJson = JSON.parse(process.env.COMPOSER_AUTH);
    } catch (err) {
      throw new Error(
        `Failed to parse COMPOSER_AUTH: ${err.message as string}`
      );
    }
  }
```

I hope this answers your question.

**Comment by rarkins** [comment]
Unfortunately that doesn't answer it. If it's just an env variable, Renovate itself won't parse/understand it. Therefore if Renovate attempts to look up any dependencies which require authentication, it will fail. If the lookups fail, you won't even get `composer` running.

So what is your solution for ensuring Renovate itself also has access to the credentials, not just Composer? Have you tested your branch against in a real setup with private packages and had Renovate be able to update them?

**Comment by ruudvanderweijde** [comment]
Thanks for the answer. Considering that, I will close the pull request, and will just use the `hostRules` instead.

Thank you for the help.

**Pull request closed without merging**
