### PR TITLE
fix(exec): Whitelist LC_ALL and LANG

### PR DESCRIPTION
**Pull request by zharinov**
Ref #5062

### CODE REVIEW

**Comment by zharinov** [comment]
https://docs.docker.com/network/proxy/

**Comment by rarkins** [comment]
Can you explain this more? We need to pass end vars to child process but not to Docker itself via `-e`

**Comment by zharinov** [comment]
I thought, pipenv pass them to Docker already and we should do for all. Well, here we have two options: (1) extend basic vars with `LANG` and `LC_ALL`, passing it to Docker explicitly when needed or (2) pass it always as done in this PR.

**Comment by rarkins** [comment]
Thanks, I understand better. I wonder if they’re only needed for child process when using global binary source. In which case, they should be safe to include on the default whitelist. If they’re needed inside the container then we should build them into the container if not already

**Comment by zharinov** [comment]
By the way, I doubt `LC_ALL` and `LANG` actually needed for pipenv. This is the only place we pass basic vars into container.

**Comment by rarkins** [comment]
> By the way, I doubt `LC_ALL` and `LANG` actually needed for pipenv. This is the only place we pass basic vars into container.

I suspect there were only needed for binarySource=global. Let's add them to our whitelisted env vars for child process and not pass them into the container itself.

**Pull request merged**
