### PR TITLE
docs: Documented Bunyan log levels

### PR DESCRIPTION
**Pull request by rmtsrc**
Added documentation on available log levels from [the Bunyan docs](https://github.com/trentm/node-bunyan#levels).

### CODE REVIEW

**Comment by rarkins** [comment]
Thanks. Are you using the schema to validate your bot/admin config too? I was actually wondering if the schema should be simplified by including user-configurable settings only (ie what you can configure in `renovate.json`).

**Comment by sebflipper** [comment]
@rarkins I was looking to update the [Self-Hosted Configuration Options docs](https://renovatebot.com/docs/self-hosted-configuration/#loglevel) this was the only reference I found, but looks like I may have edited the wrong file, as this schema file seems to be automatically generated and failed on [Travis CI](https://travis-ci.org/renovatebot/renovate/builds/510882749?utm_source=github_status&utm_medium=notification).

**Comment by rarkins** [comment]
Yes the schema file needs to be generated based on the lib/config/definitions.js contents

**Comment by rarkins** [comment]
If you update that file the online docs will also be updated automatically right after it’s merged :)

**Pull request closed without merging**
