### PR TITLE
feat(migrations): versionStrategy

### PR DESCRIPTION
**Pull request by pret-a-porter**
## Changes:

1. One more migration from previously huge PR https://github.com/renovatebot/renovate/pull/12957

## Context:

1. https://github.com/renovatebot/renovate/issues/11459
2. Part of https://github.com/renovatebot/renovate/pull/12957 

## Documentation

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — APPROVED** [review]
Are you able to make the migrations safe for strict null checks? Should be next PR. So we don't need to change code again.

**Comment by pret-a-porter** [comment]
> Are you able to make the migrations safe for strict null checks? Should be next PR. So we don't need to change code again.

Could you elaborate the question please, I did not get it

**Comment by viceice** [comment]
Add migration files to `tsconfig.strict.json` and run the corresponding script from `package.json`.

Then try to fix compiler errors. You can draft a PR before any fixes, so we can see errors in ci and guide you to fix.

**Comment by pret-a-porter** [comment]
Thanks, I see. Let's merge this PR and I will fix null checks for migrations in separate PR

**Pull request merged**
