### PR TITLE
feat(config): make force push optional for bitbucket-server

### LINKED ISSUE #5718: Renovate requires force push capabilities
**What Renovate type are you using?**

Selfhosted Bitbucket Server

**Describe the bug**

Renovate created a first PR successfully for a new version of dependency `x` but it is not merged before the next version of the same dependency `x` happens.

**Did you see anything helpful in debug logs?**

```
...
DEBUG: Branch does not need rebasing ...
...
INFO: Need to update package file so will rebase first ...
...
DEBUG: Updated 1 package files ...
DEBUG: No updated lock files in branch ...
DEBUG: 1 file(s) to commit ...
...
DEBUG: Error commiting files ...
...
remote: Rewriting history is not allowed for branch ...
```

**To Reproduce**

Sorry don't have a public Bitbucket repo / account.

### LINKED ISSUE #8239: Add alternative to force push for updating Renovate branches
**What would you like Renovate to be able to do?**

In instances where force push is disabled by git administrators (typically enterprises), the Renovate process errors when attempting to update branches. If an alternative to force push is in place as an opt-in config that can get user around this challenge.

**Did you already have any implementation ideas?**
Initial thought was to create a new config option, gitDeleteBeforePush, that can be enabled to switch from force push to delete branch and push branch. Initial PR impl: https://github.com/renovatebot/renovate/pull/8233

Initial comments for discussion:

> With this change you won't get any further updates after the pr is closed. So you will get a lot of noise because of renovate ignore pr comments. An you need to reopen the pr manually.

Agree on the noise but this would be a trade off some may be willing to take. For manual reopen that you mentioned, would that be related to how Renovate will ignore PRs that are closed? From my small test on git hub, it seems to have been OK since the initial PR was updated to include "autoclosed" in the title. Does Renovate update the autoclosed PR for every platform?

>It makes no sense to block force push for branches when you can delete and recreate them. 

Do not disagree but there are instances where this set up is in place with limited ability to change.

>Which particular platform is this for? 

My personal need would be Bitbucket server but would think this would be applicable for all supported platforms.

>And how does it behave when the branch is deleted? Most of them close the associated MR/PR, so I don't think this code alone is enough. 

From my limited testing the branch delete closes the open PR and the same PR was able to be recreated in a future Renovate run (same in the sense to the same final version, but different initial versions i.e. PR1 16.3.0 ->17.0.1, PR2 16.4.0 -> 17.0.1). I was not able to test a conflict scenario. What additional logic do you think would be required, or might there be another option other than delete/push?

### PR DESCRIPTION
**Pull request by jparnone**
## Changes:

Adds new a config option for Bitbucket-Server only to delete and push a new branch for changes vs using force push. Force push remains the default behavior for all platforms. 

## Context:

Since force push can be blocked in many enterprises, this update enables a delete and push in lieu of a force push to mitigate that challenge.

Closes #8239 
Closes #5718

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added unit tests, or
- [x] Unit tests + ran on a real repository

### CODE REVIEW

**Comment by danez** [comment]
Out of curiosity, why are force pushes disallowed in your org? I do get that some branches should be protected and rewrite of history should be disallowed, but why for all branches?

**Comment by jparnone** [comment]
Sorry, that's a question I don't have an answer for.

**Comment by hazendaz** [comment]
@danez Sometimes corporate decisions are not the most well thought out.  Clearly global block of force push has no valid rational.  However, this PR helps make some rationality out of a badly imposed rule.

**Comment by jparnone** [comment]
@rarkins do you have any other questions or concerns or can this be reviewed?

**Comment by rarkins** [comment]
@jparnone unfortunately this is a lot of code to be added to the codebase and needing maintaining, for what is potentially just one single user (i.e. yourself).

If this functionality could be added in a more elegant way, or affected more users, then it would be much easier to say yes to. Let's keep chatting in the issue in case there's an alternative solution.

**Pull request closed without merging**
