### PR TITLE
refactor: throw error if issue with git

### LINKED ISSUE #16614: Error checking last author for isBranchModified
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### Please select which platform you are using if self-hosting.

_No response_

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Multiple repositories in the hosted app report this error

### Relevant debug logs

<details><summary>Logs</summary>

```
Error: fatal: not a git repository (or any parent up to mount point /mnt)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

    at Object.action (/home/ubuntu/renovateapp/node_modules/simple-git/dist/cjs/index.js:1194:25)
    at PluginStore.exec (/home/ubuntu/renovateapp/node_modules/simple-git/dist/cjs/index.js:1229:29)
    at /home/ubuntu/renovateapp/node_modules/simple-git/dist/cjs/index.js:1590:43
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (/home/ubuntu/renovateapp/node_modules/simple-git/dist/cjs/index.js:1588:16)
    at GitExecutorChain.<anonymous> (/home/ubuntu/renovateapp/node_modules/simple-git/dist/cjs/index.js:1572:44)
    at Generator.next (<anonymous>)
    at fulfilled (/home/ubuntu/renovateapp/node_modules/simple-git/dist/cjs/index.js:55:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

### PR DESCRIPTION
**Pull request by RahulGautamSingh**
## Changes
 -  add if-block which throws error if error detected

## Context
 - Closes #16614 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by RahulGautamSingh** [comment]
Should we throw error for all instances where we execute git commands these changes suffice?

**Review by rarkins — CHANGES_REQUESTED** [review]
If you're going to wrap in a catch then you need to throw again after

**Comment by rarkins** [comment]
Instead of so much error handling I think let's just add a git status command after clone and hope that it is enough to trigger the error early.

**Comment by RahulGautamSingh** [comment]
> Instead of so much error handling I think let's just add a git status command after clone and hope that it is enough to trigger the error early.

🤞

**Review by rarkins — APPROVED** [review]

**Pull request merged**
