### PR TITLE
fix(manager/git-submodule): use appropriate hostType for auth

### LINKED ISSUE #16561: [Bug] Git-submodule checkout om Gitlab stopped working with 32.110.2
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.111.0

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

GitLab Enterprise Edition 15.1.2-ee

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

Git submodule extraction worked with version 32.110.1:
```
INFO: Repository started (repository=foo)
       "renovateVersion": "32.110.1"
 INFO: Dependency extraction complete (repository=foo)
       "baseBranch": "master",
       "stats": {
         "managers": {
           "dockerfile": {"fileCount": 1, "depCount": 2},
           "git-submodules": {"fileCount": 1, "depCount": 35},
           "gitlabci": {"fileCount": 2, "depCount": 8},
           "pip_requirements": {"fileCount": 1, "depCount": 5}
         },
         "total": {"fileCount": 5, "depCount": 50}
       }
 INFO: Repository finished (repository=foo)
       "durationMs": 35989
```

With version 32.110.0 (and 32.110.2) it fails (everytime and reproducably):

```
INFO: Repository started (repository=foo)
       "renovateVersion": "32.111.0"
 WARN: Error mapping git submodules during extraction (repository=foo)
       "err": {
         "task": {
           "commands": [
             "ls-remote",
             "--symref",
             "https://**redacted**@example.com/foo/bar/hosts.git",
             "HEAD"
           ],
           "format": "utf-8",
           "parser": "[function]"
         },
         "message": "fatal: could not read Password for 'https://**redacted**@example.com'/: No such device or address\n",
         "stack": "Error: fatal: could not read Password for 'https://**redacted**@example.com'/: No such device or address\n\n    at Object.action (/usr/src/app/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:38:28)\n    at PluginStore.exec (/usr/src/app/node_modules/simple-git/src/lib/plugins/plugin-store.ts:24:29)\n    at /usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:114:40\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:111:14)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:88:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/node_modules/simple-git/dist/cjs/index.js:55:24)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
       }
```

Changes between the versions: https://github.com/renovatebot/renovate/compare/32.110.1...32.111.1
I guess the reason is the update of the git-parse-url module: https://github.com/renovatebot/renovate/commit/210695c1a0580c18d6a2be81cabc0fce2984c856
And maybe this issue has something to do with it: https://github.com/IonicaBizau/git-url-parse/issues/140

### Relevant debug logs

When running renovate on the cli with debug-log activated, I get the following output with a password-prompt at the end.
This does not happen with 32.110.1.

<details><summary>Logs</summary>

```

 INFO: Repository started (repository=foo)
       "renovateVersion": "32.111.1"

DEBUG: Repo is onboarded (repository=foo)
DEBUG: Found renovate.json config file (repository=foo)
DEBUG: Repository config (repository=foo)
       "fileName": "renovate.json",
       "config": {
         "$schema": "https://docs.renovatebot.com/renovate-schema.json",
         "extends": ["config:base"],
         "git-submodules": {"enabled": true},
         "packageRules": [
           {
             "matchManagers": ["git-submodules"],
             "groupName": "ansible_submodules",
             "automerge": true
           }
         ]
       }


Password for 'https://oauth2@git.mms-support.de':

```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

### PR DESCRIPTION
**Pull request by viceice**
## Changes
- detect platform on `sub-module` manager and fallback to `git-refs`
- default branch works with platform host-rule works
- there are still issues:
  - if platform is detected, fetching  updates doesn't work, as we always use `git-refs` host-type.

## Context
- fixes #16561

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by viceice** [comment]
@rarkins should we propably need to change this

https://github.com/renovatebot/renovate/blob/a5b9ad096bc8ec5706849218de332deb4b983b2f/lib/util/git/url.ts#L42

So if `hostType=git-ref` and we don't find auth, try to detect platform and use platform specific hostrule? 
Or just always use `git-refs` and document on `sub-modules` manager, that we need a `git-refs` host-type or no host-type?

**Comment by astellingwerf** [comment]
Don't you agree the same fix could apply to the GitRefsDatasource and GitTagsDatasource?

**Comment by viceice** [comment]
> Don't you agree the same fix could apply to the GitRefsDatasource and GitTagsDatasource?

that's not so easy, as they use static http classes, which passes the Host-Type via constructors

**Comment by viceice** [comment]
@rarkins WDYT?

**Comment by rarkins** [comment]
I really don't know, sorry. Haven't written or used this section of code

**Comment by viceice** [comment]
@JamieMagee WDYT?

**Comment by JamieMagee** [comment]
This looks reasonable, though from your description it might just push the issue to when updates are fetched?

**Review by JamieMagee — DISMISSED** [review]

**Comment by viceice** [comment]
> This looks reasonable, though from your description it might just push the issue to when updates are fetched?

🤷‍♂️ not sure about a better solution

**Review by secustor — APPROVED** [review]

**Comment by ribtoks** [comment]
What is preventing this PR from being merged?

**Review by JamieMagee — APPROVED** [review]

**Pull request merged**
