### PR TITLE
feat(jenkins-plugins): Add Jenkins Plugins datasource

### LINKED ISSUE #6710: Jenkins plugin datasource
**What would you like Renovate to be able to do?**

Support the Jenkins plugin registry as a datasource

**Did you already have any implementation ideas?**

Work already done by @maxdanilov in https://github.com/renovatebot/renovate/pull/6668

As discussed there in comments:

- We should fetch https://updates.jenkins.io/current/update-center.actual.json once per day to store a mapping of plugin -> sourceUrl (I did not notice any other data in it that we need). Work for this is mostly done already in the other PR

- fetch https://updates.jenkins.io/current/plugin-versions.json hourly and store a mapping of plugin -> [version, buildDate]. We probably need to record it as a proper timestamp so use 00:00 UTC with whatever date they record

### PR DESCRIPTION
**Pull request by maxdanilov**
Adds a datasource for enabling Renovate to be able to upgrade Jenkins plugins.

- Datasource is fetching data from the Jenkins [upgrade center](https://updates.jenkins.io/)

Closes #6710

### CODE REVIEW

**Comment by rarkins** [comment]
@maxdanilov this looks really great. I think that your cache functions could perhaps be turned into "generic" ones to be shared with any other datasource that needs to fetch and transform files, but I'm happy to leave that refactoring until later.

Have you verified this caching logic locally in practice? I'm not sure of the best way to confirm that it's only fetching/transforming once.

**Comment by viceice** [comment]
Does this supersedes #6668?

**Comment by rarkins** [comment]
> Does this supersedes #6668?

Only the datasource of that

**Comment by maxdanilov** [comment]
> @maxdanilov this looks really great. I think that your cache functions could perhaps be turned into "generic" ones to be shared with any other datasource that needs to fetch and transform files, but I'm happy to leave that refactoring until later.
> 
> Have you verified this caching logic locally in practice? I'm not sure of the best way to confirm that it's only fetching/transforming once.

Thank you!
I've improved the tests a bit in https://github.com/renovatebot/renovate/pull/6848/commits/2e05f771b6d8d76f38cd33642d9b9d89827b7935 to test caching by making a consecutive call to `getPkgReleases` to ensure it does not make new HTTP calls when caches are not expired yet.

**Comment by maxdanilov** [comment]
> Does this supersedes #6668?

I plan to amend #6668 to only include a manager and so it can be merged later once this PR merged.

**Review by rarkins — APPROVED** [review]

**Comment by maxdanilov** [comment]
@rarkins can this be merged? Asking since that would be a prerequisite to finishing https://github.com/renovatebot/renovate/pull/6668 (the manager part)

**Pull request merged**
