### PR TITLE
fix(git): gracefully handle remote ref lock error

### PR DESCRIPTION
**Pull request by viceice**
## Changes:

gracefully handle `remote: error: cannot lock ref` git errors as `ExternalHostError`

## Context:

I've had a corrupt git repo and renovate silently failed  to push an update

```
Pushing to https://git.some.org/some/repo.git
POST git-receive-pack (711 bytes)
remote: error: cannot lock ref  'refs/heads/renovate/docker-renovate-renovate-23.26.x': unable to resolve reference 'refs/heads/renovate/docker-renovate-renovate-23.26.x': reference broken        
    error: failed to push some refs to https://git.some.org/some/repo.git
```

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] Unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
Won't this just platform-failure forever?

**Comment by viceice** [comment]
yes, until manually fixed, but this should also give some more visibillity. currently renovate silently fails without any error and no updates at all.

**Comment by rarkins** [comment]
Perhaps you could make it so that it only fails for that one branch, and continues with others? And is it possible to delete the remote branch to recover on the next run?

**Review by rarkins — DISMISSED** [review]

**Comment by viceice** [comment]
It won't recover automatically, you need to manually fix it by removing the ref file on remote repo.

currently we throw repo changed error, so renovate stops processing repo (not sure why it is silent, maybe we should log this specific type as error?). should we throw a new message type, so we can simply pass branch error up?

**Comment by rarkins** [comment]
If the problem is isolated to the branch then we should try to catch and log it there and continue

**Comment by viceice** [comment]
maybe a better solution is to add a new condition here
https://github.com/renovatebot/renovate/blob/04c3b30d8d5301320a00c288609ebc7c57457449/lib%2Futil%2Fgit%2Findex.ts#L652-L664

so we log that as error ( so renovate exits with 1)  and throw a new error `commit-failed` ?

**Comment by viceice** [comment]
Ok. moved the check. Renovate should log an error and continue now

**Comment by viceice** [comment]
@rarkins Ready for a new review

**Review by rarkins — APPROVED** [review]

**Pull request merged**
