### PR TITLE
feat(presets)!: drop `renovate.json` fallback

### PR DESCRIPTION
**Pull request by viceice**
## Changes
Remove the fallback to `renovate.json` preset when `default.json` is not found.

**NOTE**: Review with ignore whitespace changes. 😉 

**TODO**
- [ ] fix conflicts
- [ ] throw config error when fallback found

## Context
- #22212
- #23419
- #24263
- #27992

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by secustor — COMMENTED** [review]
Outside of coverage LGTM

Also not approving as it targeted at the main branch ;)

**Review by rarkins — CHANGES_REQUESTED** [review]
@nabeelsaabna can you find out how many `Fallback to renovate.json file as a preset is deprecated, please use a default.json file instead.` log messages we see daily in the hosted app?

@viceice we may want to upgrade this to a WARN for a longer period of time first

**Comment by nabeelsaabna** [comment]
in the last 7 days we have 4234 unique repositories with this message

**Comment by viceice** [comment]
ok I've created another PR to warn now, so we can drop later
- #24263

**Comment by rarkins** [comment]
I don't think we can do this yet

**Review by rarkins — COMMENTED** [review]
I think we have too many still using this in the Renovate app.

**Comment by viceice** [comment]
> I think we have too many still using this in the Renovate app.

so what's the next step to get existing users to change their settings?

**Comment by rarkins** [comment]
We could improve our efficiency by remembering these fallbacks in repositoryCache: https://github.com/renovatebot/renovate/issues/28008

**Comment by rarkins** [comment]
I'm not sure we can merge this for a long time, certainly not in v38. So let's close this PR but keep the branch in place

**Pull request closed without merging**
