### PR TITLE
feat(self-hosted)!: convert `ignorePrAuthor` to self-hosted option

### PR DESCRIPTION
**Pull request by RahulGautamSingh**
## Changes
- Convert `ignorePrAuthor` option to self-hosted option

## Context
Ref: https://github.com/renovatebot/renovate/discussions/29497

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by RahulGautamSingh** [comment]
I am not sure about the breaking label. Because even if someone may have added the option inside repo config, it would be meaningless.

**Comment by rarkins** [comment]
There is probably a use case for repo config ignorePrAuthor (e.g. someone was running their own bot, then migrated to the hosted app), however if it _doesn't work_ today then I think we can make it global only for now

**Review by viceice — COMMENTED** [review]
if you think we should merge it as breaking, then please target v38 branch

**Comment by RahulGautamSingh** [comment]
I will do it in a new PR, targeting v38

**Pull request closed without merging**
