### PR TITLE
fix(ts): convert worker/repository/init to typescript

### PR DESCRIPTION
**Pull request by viceice**
#1261

### CODE REVIEW

**Comment by rarkins** [comment]
@ViceIce sorry, I broke you with some changes to the original JS. Let me know if you need my help resolving

image

**Review by rarkins — CHANGES_REQUESTED** [review]
Resolve conflicts

**Comment by ViceIce** [comment]
@rarkins resolved 😅

**Review by JamieMagee — APPROVED** [review]

**Comment by JamieMagee** [comment]
Sorry for the long wait. LGTM :smile:

**Pull request merged**
