### PR TITLE
ci: Switch to `lcov` output format

### PR DESCRIPTION
**Pull request by zharinov**
## Changes

This enable `change` percentage column to show some values

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by zharinov** [comment]
If I understand correctly, this `-0.65%` are caused by report format switching and will be okay once this PR is merged to `main`

**Comment by zharinov** [comment]
I have hypothesis that we should reset all data in codecov and start it fresh, testing it in my local fork

**Comment by rarkins** [comment]
How is that done?

**Comment by zharinov** [comment]
image

**Comment by rarkins** [comment]
I got the impression that it's different?

**Comment by zharinov** [comment]
I'm not sure this PR makes any difference. Two hypotheses:
- `json` format is not well-suited for multi-file upload
- we broke data consistency when switched from one-file upload to multifile upload

**Comment by zharinov** [comment]
And I think the second is more realistic

**Pull request merged**
