### PR TITLE
chore: run devcontainer as root

### LINKED ISSUE #12156: Cannot build in devcontainer
### Describe the bug

When opening this repository in a devcontainer config, e.g. in GitHub Codespaces `yarn install` fails due to missing permissions for `/tmp`. To me it looks like `/tmp` has incorrect permissions for the non-root user:

image

### Have you created a minimal reproduction repository?

No reproduction repository, but here are the steps:

1. Create a new codespace for this repository: Screen Shot 2021-10-14 at 10 41 14
2. Wait for the codespace to open.
3. Switch to the Terminal panel and run `yarn install`: image

### PR DESCRIPTION
**Pull request by viceice**
## Changes
explicitly set container user

## Context
- fixes #12156

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by viceice** [comment]
Works for me on WSL v2 and Windows 11. Don't have access to codespaces, so can't test there

/cc @fgreinacher

**Comment by fgreinacher** [comment]
Sorry, still the same problem in Codespaces:

image

**Comment by viceice** [comment]
@fgreinacher Can you test again?

**Comment by fgreinacher** [comment]
> @fgreinacher Can you test again?

Sure! Same problem with `root` in the `Dockerfile`. It's working though when I change `remoteUser` to `root`.

**Comment by viceice** [comment]
So the `/tmp` is still missing the writable flag for others?

**Comment by fgreinacher** [comment]
No unix permissions pro, but the permissions don't seem to work:

image

**Comment by viceice** [comment]
> It's working now with a fresh Codespace!

With root or the version before?

**Comment by fgreinacher** [comment]
With the recent version, root in the Dockerfile

**Comment by rarkins** [comment]
Does this mean Codespaces will work out of the box?

**Comment by viceice** [comment]
> Does this mean Codespaces will work out of the box?

Yes. @fgreinacher tested it.

**Comment by fgreinacher** [comment]
Yes, it works flawlessly with newly created Codespaces 🎉

image

**Comment by JamieMagee** [comment]
> Works for me on WSL v2 and Windows 11. Don't have access to codespaces, so can't test there

I thought codespaces was open to everyone now?

**Review by JamieMagee — APPROVED** [review]

**Pull request merged**
