### PR TITLE
fix(pip_setup): Allow setup.py to import stuff from their own package

### LINKED ISSUE #6544: setup.py importing stuff from its own package
**What Renovate type are you using?**

Tested with latest Docker image & source code version.

**Describe the bug**
Renovate fail to parse a `setup.py` file if it contains a line like `from the_pkg_itself import ...`

**Did you see anything helpful in debug logs?**
```
Error: Command failed: python3.8 "/usr/src/app/node_modules/renovate/data/extract.py" "setup.py"
/usr/src/app/node_modules/renovate/data/extract.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "/usr/src/app/node_modules/renovate/data/extract.py", line 30, in <module>
    invoke()
  File "/usr/local/python/3.8.3/lib/python3.8/unittest/mock.py", line 1325, in patched
    return func(*newargs, **newkeywargs)
  File "/usr/src/app/node_modules/renovate/data/extract.py", line 24, in invoke
    imp.load_source('_target_setup_', sys.argv[-1])
  File "/usr/local/python/3.8.3/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "setup.py", line 3, in <module>
    from testpkg import __version__
ModuleNotFoundError: No module named 'testpkg'

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:482:12)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
```

**To Reproduce**
Example minimal `setup.py` to reproduce the issue:
```
from setuptools import setup, find_packages
from testpkg import __version__
setup(
    name="testpkg",
    version=__version__,
    packages=find_packages(),
)
```

**Additional context**
I am working on a PR to fix this

### PR DESCRIPTION
**Pull request by Lucas-C**
Closes #6544

### CODE REVIEW

**Comment by Lucas-C** [comment]
I do not understand while the new test triggers this error:
```thrown: "Exceeded timeout of 30000 ms for a test.```

I have the same error on my computer with:
```$ yarn jest lib/manager/pip_setup/extract.spec.ts```

But I think I need some help here to figure out what is the issue...

The call to `exec` times out, however I can successfully execute the Python command:
```
$ python3 data/extract.py lib/manager/pip_setup/__fixtures__/setup-3.py
{
  "name": "testpkg",
  "version": "1.0",
  "packages": []
}
```

**Comment by rarkins** [comment]
Is it timing out all tests or just the new one you added?

**Comment by Lucas-C** [comment]
Only the one I added

**Review by viceice — CHANGES_REQUESTED** [review]
Needs  deconflicting. Also we never call `python` in tests, because we mock `child_process`. So you can't really test your changes.

If we want to test real extraction, you need to add a new test file (eg: `extract-real.spec.ts`) and implement the test there.

**Comment by Lucas-C** [comment]
Could you give me pointers on how to make the commit message more semantic ?
I see that the bot is not pleased, but I see no mention of it in [.github/contributing.md](../blob/master/.github/contributing.md).

**Comment by viceice** [comment]
Yes, coverage needs to be fixef

**Comment by Lucas-C** [comment]
I still have this timeout issue that I don't know how to resolve... :(

**Comment by rarkins** [comment]
@viceice should we skip the test?

**Comment by viceice** [comment]
Should be ok to skip

**Comment by rarkins** [comment]
@Lucas-C can you remove the problematic test and ignore the code block instead?

**Comment by Lucas-C** [comment]
Done !

**Comment by rarkins** [comment]
@Lucas-C do you have - or can you provide - any public repos that you've run this new code against to ensure no regression problems?

**Comment by Lucas-C** [comment]
Nope I haven't tested it on any public repo.
I had the issue with a repo on a privately-hosted Gitlab

**Review by rarkins — COMMENTED** [review]
Change looks simple but we need to test it against some real examples to ensure it doesn't error

**Comment by rarkins** [comment]
@zharinov can you do a sanity check of this against some real-world `setup.py` project?

**Comment by zharinov** [comment]
Can confirm it worked identically to `master` on this example: https://github.com/zharinov/mitmproxy
To the another hand, I wasn't able to reproduce original issue once `testpkg/__init__.py` is present: https://github.com/zharinov/renovate-test-setup-py

**Comment by rarkins** [comment]
@Lucas-C how would you recommend to reproduce?

**Comment by Lucas-C** [comment]
Thanks for merging this.

As for a reproduction example, there was one in the initial commit:
https://github.com/renovatebot/renovate/pull/6545/commits/85a587e8e223eecc8b71d9eec67e9f23930146b3

**Pull request merged**
