### PR TITLE
fix(versioning)!: bump short ranges to version

### LINKED ISSUE #20488: Cargo: tilde bump does not bump if satisfying existing range
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

34.145.0

### If you're self-hosting Renovate, select which platform you are using.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

15.8.1

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Reproduction repository: https://github.com/JMLX42/cargo-renovate-tilde-test

```toml
[package]
name = "cargo-renovate-tilde-test"
version = "0.1.0"
edition = "2021"

[dependencies]
semver = "~1"
```

The `Cargo.toml` above should trigger an upgrade/PR/MR considering:

- the `semver` crate version is currently `1.0.16`
- as per [the Cargo documentation on the `~` operator](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#tilde-requirements):

> Tilde requirements specify a minimal version with some ability to update. If you specify a major, minor, and patch version or only a major and minor version, only patch-level changes are allowed. If you only specify a major version, then minor- and patch-level changes are allowed.
> 
> `~1.2.3` is an example of a tilde requirement.
> 
> ```
> ~1.2.3  := >=1.2.3, <1.3.0
> ~1.2    := >=1.2.0, <1.3.0
> ~1      := >=1.0.0, <2.0.0
> ```

Even with `"rangeStrategy": "bump"`, there is no upgrade/PR/MR:

```json
{
  "extends": [
    "config:base",
    ":semanticCommits",
    ":semanticCommitTypeAll(chore)"
  ],
  "rangeStrategy": "bump"
}
```

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Found 1 package file(s) (repository=aerys/test/cargo-renovate-tilde-test)
 INFO: Dependency extraction complete (repository=aerys/test/cargo-renovate-tilde-test, baseBranch=main)
       "stats": {
         "managers": {"cargo": {"fileCount": 1, "depCount": 1}},
         "total": {"fileCount": 1, "depCount": 1}
       }
DEBUG: PackageFiles.add() - Package file saved for base branch (repository=aerys/test/cargo-renovate-tilde-test, baseBranch=main)
DEBUG: Package releases lookups complete (repository=aerys/test/cargo-renovate-tilde-test, baseBranch=main)
DEBUG: branchifyUpgrades (repository=aerys/test/cargo-renovate-tilde-test)
DEBUG: 0 flattened updates found:  (repository=aerys/test/cargo-renovate-tilde-test)
DEBUG: Returning 0 branch(es) (repository=aerys/test/cargo-renovate-tilde-test)
DEBUG: config.repoIsOnboarded=true (repository=aerys/test/cargo-renovate-tilde-test)
DEBUG: packageFiles with updates (repository=aerys/test/cargo-renovate-tilde-test, baseBranch=main)
       "config": {
         "cargo": [
           {
             "packageFile": "Cargo.toml",
             "deps": [
               {
                 "depName": "semver",
                 "depType": "dependencies",
                 "currentValue": "~1",
                 "managerData": {"nestedVersion": false},
                 "datasource": "crate",
                 "depIndex": 0,
                 "updates": [],
                 "warnings": [],
                 "versioning": "cargo",
                 "sourceUrl": "https://github.com/dtolnay/semver",
                 "registryUrl": "https://crates.io",
                 "dependencyUrl": "https://crates.io/crates/semver",
                 "currentVersion": "1.0.0"
               }
             ]
           }
         ]
       }
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

### PR DESCRIPTION
**Pull request by rarkins**
## Changes

Bumps short ranges to full version ranges

## Context

Closes #20488

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — APPROVED** [review]
isn't this a breaking change?

**Review by Turbo87 — APPROVED** [review]
this seems more correct to me than before. I agree that it's probably a breaking change even though it could be considered a bug fix as well. to avoid surprised users it might be best to ship this with a major version bump.

**Comment by rarkins** [comment]
Majority of users don't really have a choice now to opt in though. But sure, v35 is nearly ready to go

**Comment by Turbo87** [comment]
you mean because they're using it via GitHub app? makes sense, but even just for communication purposes it might be better to clearly mark it as a breaking change :)

**Comment by secustor** [comment]
LGTM, I will approve when the target branch has been changed

**Pull request merged**
