### PR TITLE
feat(preset): add dependencyDashboardWithLabel

### PR DESCRIPTION
**Pull request by ykzts**
## Changes:

It would be useful to be able to assign an arbitrary label at the same time when creating a Dependency Dashboard.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by JamieMagee — APPROVED** [review]

**Review by Caglar1881 — APPROVED** [review]

**Review by viceice — COMMENTED** [review]
I don't see a real benefit here. 🤔

**Comment by rarkins** [comment]
> I don't see a real benefit here. 🤔

Same here. Does it really solve much of a pain point except for 1 config line instead of 2?

**Comment by ykzts** [comment]
There is already an enableVulnerabilityAlertsWithLabel paired with enableVulnerabilityAlerts. I think it would be useful to have a dependencyDashboardWithLabel as well.

Is the dependencyDashboard different from enableVulnerabilityAlerts in nature?

**Comment by viceice** [comment]
`dependencyDashboard` is enabled by default in `config:base`

**Comment by ykzts** [comment]
Hmm... I was assuming that :dependencyDashboardWithLabel would be used from shareable presets created from scratch without extending `config:base`. I didn't know that you always need to extend `config:base` in any case.

**Comment by viceice** [comment]
You don't need to extend `config:base`, but it's recommend for most users.

**Pull request closed without merging**
