### PR TITLE
ci(build): Remove Python from Renovate dependencies

### PR DESCRIPTION
**Pull request by zharinov**
## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by zharinov** [comment]
Let's see if it would work or not

**Comment by HonkingGoose** [comment]
If this works properly, you'll need to change this file as well:

https://github.com/renovatebot/renovate/blob/c98b79b11a40d3997f658cd92d432c2da3c2d440/docs/development/local-development.md?plain=1#L9-L18

**Comment by zharinov** [comment]
> If this works properly, you'll need to change this file as well:

Yes, though I'm not 100% sure if we don't depend on Python in any platform anymore

**Comment by rarkins** [comment]
I think python can be required for `node-gyp`? Not sure

**Review by viceice — DISMISSED** [review]
This is ok, as python is always installed on github runner.

We also no longer depend on a specific python versin since the js based extraction.

`node-gyp` is happy with any python v3+

**Comment by HonkingGoose** [comment]
Do we still need Python when developing then?

**Comment by viceice** [comment]
i don't think so

**Review by rarkins — APPROVED** [review]

**Pull request merged**
