### PR TITLE
chore(npm): log hostRules npmrc logic

### PR DESCRIPTION
**Pull request by rarkins**
## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by secustor** [comment]
needs linting fix

**Review by secustor — COMMENTED** [review]
LGTM, but needs eslint fix.

**Review by viceice — COMMENTED** [review]
a lot logging, shouldn't we move some to trace?

**Comment by rarkins** [comment]
@viceice I found these useful/necessary for debugging .npmrc problems from logs

**Review by viceice — APPROVED** [review]

**Pull request merged**
