### PR TITLE
fix(pip_setup): dump only install_requires and extras_require setup args

### LINKED ISSUE #3377: Error parsing setup.py
Here's the file:

```py
#!/usr/bin/env python

from distutils.core import setup, Extension

module_RF24 = Extension('RF24',
            libraries = ['rf24-bcm', 'boost_python'],
            sources = ['pyRF24.cpp'])

setup(name='RF24',
    version='1.0',
    ext_modules=[module_RF24]
      )
```

The error is: `TypeError: Object of type Extension is not JSON serializable`

### PR DESCRIPTION
**Pull request by adamko147**
## Changes:

Extract only `install_requires` and `extras_require` arguments when parsing setup.py

## Context:

Closes #3377

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or 
- [ ] Newly added unit tests, or
- [x] Unit tests + ran on a real repository

real repository at https://github.com/adamko147/renovate-python

### CODE REVIEW

**Comment by viceice** [comment]
Instead of removing problematic objects we should only serialize value we need.

**Comment by viceice** [comment]
we only need `extras_require` and `install_requires` 

https://github.com/renovatebot/renovate/blob/6da2f1d2f0a96986eeb9d3d04f43c8767a28b486/lib/manager/pip_setup/util.ts#L24-L28

**Review by rarkins — CHANGES_REQUESTED** [review]
Opt for allow-list approach instead of deny-list as suggested by @viceice

**Comment by adamko147** [comment]
@rarkins @viceice
- the report.json should now include only `install_requires` and `extras_require`
- `extract.py` won't fail if `setup` is not called within `setup.py`

**Review by viceice — APPROVED** [review]

**Pull request merged**
