### PR TITLE
chore(lint): optimize linting

### PR DESCRIPTION
**Pull request by viceice**
This pr updates the eslint config. Most of the manual configs are included by the extends.

**Questions:**
- [ ]  Should we enable [`@typescript-eslint/interface-name-prefix`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/interface-name-prefix.md) as recommend ?
- [ ] Should we extend `eslint:recommended` ?

### CODE REVIEW

**Comment by rarkins** [comment]
I guess it can make sense to use the `I` prefix if that's considered best practice.

I'm not too familiar with `eslint:recommended`. It was a long time ago that I settled on the airbnb presets anyway.

**Comment by ViceIce** [comment]
So i will reenable `@typescript-eslint/interface-name-prefix`.

I can find some projects extending `eslint:recommended` before `airbnb` and some not. On the `airbnb` samples they don't use `eslint:recommended`, so we shouldn't do that too.

**Comment by ViceIce** [comment]
🤔  now i've enabled the rule and read the docu again. the default recommend setting is to never use the prefix. so i would recommend that too.

**Comment by rarkins** [comment]
Whoops, I misread that "never prefix" recommendation. Agreed.

**Comment by rarkins** [comment]
Ready for merge?

**Comment by ViceIce** [comment]
no, just a few moments

**Comment by ViceIce** [comment]
using ` --cache` flag for eslint will speedup lining alot 

if ci run is successful it is ready for merge

**Pull request merged**
