### PR TITLE
feat(nuget): Add range support

### LINKED ISSUE #4898: NuGet: Support for exact version references
**What would you like Renovate to be able to do?**

Renovate should be able to update NuGet `PackageReference`s that use exact version syntax (part of the [version range syntax](https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#version-ranges-and-wildcards), i.e.

```xml
<PackageReference Include="MyPackage" Version="[1.2.3]" />
```

**Describe the solution you'd like**

The NuGet versioning scheme https://github.com/renovatebot/renovate/blob/master/lib/versioning/nuget/index.ts needs to handle the exact version syntax with the brackets around the version number.

### PR DESCRIPTION
**Pull request by fgreinacher**
Closes #4898

### CODE REVIEW

**Comment by fgreinacher** [comment]
@sieukrem As discussed, please fix author and title of the commit via amend and force push to this branch.

**Comment by rarkins** [comment]
@fgreinacher did you notice the [nuget versionScheme](https://github.com/renovatebot/renovate/tree/master/lib/versioning/nuget) added by @mark-raymond recently? I'd like to make sure any changes here still work with that, as we had thought about making `nuget` the default versionScheme for the `nuget` manager.

**Comment by fgreinacher** [comment]
Ah, didn't notice that, thanks! 

Maybe we could just call https://github.com/renovatebot/renovate/blob/master/lib/versioning/nuget/index.ts#L6 on `line`?

**Comment by sieukrem** [comment]
@rarkins  Thanks for advice!

The changes in pull request are versioning schema independent and would match also referenced nuget versioning (SemVer 2.0.0), so that the versionScheme.parse will provide additional benefit. Furthermore the pull request is about semantics of boundaries and their update effect.

**Comment by rarkins** [comment]
Here's where I have a doubt/concern: Shouldn't we be considering the extracted "currentValue" to be `[1.2.3]` and not `1.2.3`? e.g. that's how we work with Maven.

I'm guessing that this PR is an incremental improvement on our current lack of support - so maybe it's ok to merge - but should we be aiming for full support/awareness of this range syntax within our nuget versionScheme?

**Comment by mark-raymond** [comment]
Yes, I think handling the ranges should be within the nuget versionScheme itself.

**Comment by rarkins** [comment]
I'd consider @fgreinacher and @mark-raymond to be the main stakeholders in this decision as past contributors to the nuget functionality. If you both think that the current PR is a good incremental idea regardless of whether we should "one day" support the full version ranges, then I'll be happy to merge this PR as-is.

**Comment by fgreinacher** [comment]
I wasn’t aware of the manager-specific versioning schemes. Looking at what is done elsewhere (e.g. for maven) I agree that we should move the new range handling to the NuGet scheme as part of this PR.

**Comment by fgreinacher** [comment]
I discussed this offline with @sieukrem. We would like to keep this as-is as a first step. Implementing the full versioning scheme for NuGet needs some more thoughts and work and can be done later, hopefully based on user feedback.

**Review by viceice — APPROVED** [review]
I like this, because in one project i have to pin a nuget package too. And yes, we can support even more versioning with changes. I'm happe to help with that.

So i think we can remove WIP and merge this.

@fgreinacher Did you do live tests, maybe some we can see?

**Comment by fgreinacher** [comment]
@sieukrem is the one who did all the work, I just created the PR 😃

**Comment by rarkins** [comment]
Thanks all. I added a new issue #5016 to capture the requirement for full range support in the NuGet versionScheme

**Pull request merged**
