### PR TITLE
fix(gomod): avoid duplicating "incompatible" metadata

### LINKED ISSUE #17089: Golang parse 'incompatible' component of semver
### What would you like Renovate to be able to do?

Ref: https://github.com/renovatebot/renovate/discussions/17079

Golang dependencies that aren't v2 module compatible (i.e. don't have a `go.mod` in their source) but have a valid semver get tagged as `<semver>+incompatible` in `go.mod`. Renovate cannot currently parse this but should as the dependency is still eliglbe for upgrade, it's just a signifier that the dependency doesn't comply with [go modules v2](https://go.dev/blog/v2-go-modules). 

Example repo: https://github.com/sp3nx0r/renovate-golang-incompatible

### If you have any ideas on how this should be implemented, please tell us here.

Just strip the `+incompatible` component of the semver and treat it as standard semver, without the need for users to create a custom version regex rule. This doesn't affect the underlying capability of the dependency

### Is this a feature you are interested in implementing yourself?

No

### PR DESCRIPTION
**Pull request by maxbrunet**
## Changes

Avoid adding `+incompatible` if it is already in the new value.

## Context

Spotted on PR parca-dev/parca-agent#818

```diff
diff --git a/go.mod b/go.mod
index d67bb1a09..706b3900b 100644
--- a/go.mod
+++ b/go.mod
@@ -8,7 +8,7 @@ require (
 	github.com/cenkalti/backoff/v4 v4.1.3
 	github.com/cespare/xxhash/v2 v2.1.2
 	github.com/common-nighthawk/go-figure v0.0.0-20210622060536-734e95fb86be
-	github.com/docker/docker v20.10.17+incompatible
+	github.com/docker/docker v20.10.18+incompatible+incompatible
 	github.com/dustin/go-humanize v1.0.0
 	github.com/go-kit/log v0.2.1
 	github.com/goburrow/cache v0.1.4
```

Fixes #17089

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — APPROVED** [review]

**Comment by maxbrunet** [comment]
@rarkins @viceice could you click "Update branch" to get it merged, please?

**Comment by viceice** [comment]
> @rarkins @viceice could you click "Update branch" to get it merged, please?

you can do it yourself on your PR's 😉 shouldn't remove the approval

**Comment by maxbrunet** [comment]
> you can do it yourself on your PR's :wink: shouldn't remove the approval

Since I am not a maintainer / do not have write access, it will disable auto-merge, so you might have to click that then, let me give it a try :grin:

**Comment by maxbrunet** [comment]
Never mind, looking good, either GitHub changed something or it depends on the branch protection rule

**Pull request merged**
