### PR TITLE
feat(platform/codecommit): add token support in config_js and update docs

### PR DESCRIPTION
**Pull request by PhilipAbed**
## Changes
Added the option to put AWS_SESSION_TOKEN into the `token` param in config.js
and patched the `index.mx` for codecommit

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — APPROVED** [review]
wrong PR title otherwise LGTM

**Comment by PhilipAbed** [comment]
@viceice can you please merge this? rhys is sick today, the logic has been approved by him, the docs fix too we have problem in numbering in docs which is important

**Comment by viceice** [comment]
> @viceice can you please merge this? rhys is sick today, the logic has been approved by him, the docs fix too we have problem in numbering in docs which is important

I know, i already approved and enabled automerge now 😉 Couldn't do that before because of the non semantic PR title before 🙃

**Comment by PhilipAbed** [comment]
@viceice  thank you

**Pull request merged**
