### PR TITLE
test: use swc compiler

### PR DESCRIPTION
**Pull request by viceice**
## Changes

Use swc for compiling typescript for local debug and jest tests.
This should speedup tests and reduce memory footprint.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by viceice** [comment]
@rarkins swc seems to make our tests a lot faster, but has a bug.

the comments for Istanbul are missing, when I'm enable them, the compilation fails. I'll file a upstream bug soon

**Comment by viceice** [comment]
> What speedup percentage for `yarn jest` is?

for node v14 i see ~ half time. node v16 seems to have some issue with jest

**Review by rarkins — DISMISSED** [review]

**Review by rarkins — DISMISSED** [review]

**Comment by JamieMagee** [comment]
Are you planning to migrate compilation to SWC? Or use SWC for local development, and keep using tsc for compilation?

**Comment by viceice** [comment]
> Are you planning to migrate compilation to SWC? Or use SWC for local development, and keep using tsc for compilation?

no decision yet, maybe I'll start with esm compilation, as the normal typescript Compiler can't do this very well yet. i previously tests esm compilation with esbuild.

**Review by JamieMagee — DISMISSED** [review]

**Comment by rarkins** [comment]
Closing due to staleness and conflicts

**Pull request closed without merging**
