### PR TITLE
feat: improve xunit monorepo

### PR DESCRIPTION
**Pull request by NatMarchand**
## Changes

I've added all the repositories for xUnit monorepo.

## Context

xUnit monorepo is missing some repositories (see [docs](https://xunit.net/#projects)) 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — COMMENTED** [review]
we usually only group multiple repos if they have same release numbers.

**Comment by NatMarchand** [comment]
Yeah, I understand, I can remove some repos but usually at least xunit/visualstudio.xunit and xunit/xunit are released together.

**Comment by viceice** [comment]
> Yeah, I understand, I can remove some repos but usually at least xunit/visualstudio.xunit and xunit/xunit are released together.
> 

do they have the same versions?

do they need to merged together?

**Comment by NatMarchand** [comment]
I can't vouch for the maintainer but from what I can see, for all the releases (excepts pre-release packages) since 2015 they have been published the same day under the same version. 

xunit:
Version | Last updated
-- | --
2.5.0 | 25 days ago
2.4.2 | 8/1/2022
2.4.1 | 10/29/2018
2.4.0 | 7/17/2018
2.3.1 | 10/27/2017
2.3.0 | 10/6/2017
2.2.0 | 2/20/2017
2.1.0 | 9/27/2015
2.0.0 | 3/16/2015

xunit.runner.visualstudio
Version | Last updated
--|--
2.5.0 | 25 days ago
2.4.5 | 5/5/2022
2.4.3 | 8/3/2020
2.4.2 | 6/2/2020
2.4.1 | 10/29/2018
2.4.0 | 7/17/2018
2.3.1 | 10/27/2017
2.3.0 | 10/6/2017
2.2.0 | 2/20/2017
2.1.0 | 9/27/2015
2.0.1 | 7/13/2015
2.0.0 | 3/16/2015

There's no strict need for xunit.runner.visualstudio to be upgraded (as there is no explicit strict dependency between packages) but one embed the other's dll and not keeping them in sync might have some unexpected behavior.

**Review by rarkins — DISMISSED** [review]

**Review by rarkins — APPROVED** [review]

**Pull request merged**
