### PR TITLE
feat: stabilityDays

### LINKED ISSUE #3564: [feature request]Auto merge after ? days’ no-version bumping.
Thanks for your tools! Love it!

**What would you like Renovate to be able to do?**
Here is my workflow:

2019/4/10:
Lib author bump version from 1.29.8–1.30.0

Auto merge daily happens.
But I find sth wrong about this(not catch by CI) , go to issues to find the answer, find others are also suffered this. Author find a solution to fix.

4/11: 
Bump version to 1.30.1

Auto merged. Problem is solved.

**Describe the solution you'd like**
Could it possible to set a hook before auto merge? Like, auto merge only happens when the PR did not update(no lib version bump) in some days.

Then I can escape from the problem I said before!

Auto merge after ? days’ no PR update.

**Describe alternatives you've considered**
NO

**Additional context**

### LINKED ISSUE #3897: Feature Request: Option to always stay X weeks out of date
**What would you like Renovate to be able to do?**
I don't want my repo on the very bleeding edge but only to consider bumps for packages that are >4 weeks old and thus have any bugs/kinks worked out in the event of a bad release.

**Describe the solution you'd like**
A way to configure the acceptable delay delta of considered bumps.

**Describe alternatives you've considered**
Can't find a way to do this currently other than manually evaluating bumps.

### PR DESCRIPTION
**Pull request by rarkins**
Closes #3564, Closes #3897

### CODE REVIEW

**Comment by ViceIce** [comment]
Will it work when i'm using `autoMergeType=branch` ?

**Review by viceice — CHANGES_REQUESTED** [review]
Coverage missing

**Comment by rarkins** [comment]
> Will it work when i'm using `autoMergeType=branch` ?

I think so. If you add a setting for `stabilityDays` then it won't prevent the branch from being created, but once it is created then the status check will be set to "pending" initially before being updated to "success" later. I think branch automerge should therefore behave nicely with it.

**Review by viceice — APPROVED** [review]
LGTM

**Pull request merged**
