### PR TITLE
feat(bitbucket-cloud): Default reviewers

### PR DESCRIPTION
**Pull request by puug**
Addresses Cloud variant of #3579

### CODE REVIEW

**Comment by puug** [comment]
Tests to come

**Review by viceice — COMMENTED** [review]
@puug Have you done some real tests? Is it working as expected?

**Comment by puug** [comment]
> @puug Have you done some real tests? Is it working as expected?

Yes, tested in the real world, raises PRs with the default reviewers (or none if none configured for that repo)

**Review by viceice — APPROVED** [review]
LGTM

**Pull request merged**
