### PR TITLE
chore(ci): add azure pipelines

### PR DESCRIPTION
**Pull request by viceice**
This pr adds a working azure pipeline.

You have to add a azure devops organization and project, from there you can enable it.

### CODE REVIEW

**Comment by rarkins** [comment]
@ViceIce do you have any updated figures for build/test speed of Azure vs Circle?

**Comment by ViceIce** [comment]
Not really. macos needs ~10min too, only linux is fast with ~5min.

https://dev.azure.com/viceice/test/_build/results?buildId=35

**Comment by ViceIce** [comment]
I'll try to adapt some config from [jest](https://github.com/facebook/jest/blob/1b38e11c17c71999a53f8e00527276daaa6722da/.azure-pipelines.yml)

**Comment by ViceIce** [comment]
Strange, macos ist faster with inband and no-cache now.

https://dev.azure.com/viceice/test/_build/results?buildId=36

trying with cache next

**Comment by ViceIce** [comment]
https://status.dev.azure.com/_event/136223684 🙈

**Comment by ViceIce** [comment]
OK, i think the windows defender is slowing down. 🙈 

Trying to disabled while running build.

**Comment by ViceIce** [comment]
nope, defender already disabled.

But jest seems to have a windows problem: https://github.com/facebook/jest/issues/7811

**Comment by ViceIce** [comment]
using `--link-duplicates` speeds up `yarn install` about 30sec

**Comment by ViceIce** [comment]
here is appveyor: https://ci.appveyor.com/project/ViceIce/renovate

~8min to build, 2min saved by caching.

Finally we can say that windows builds are a lot slower.

**Comment by rarkins** [comment]
Thanks for all the research. In that case, what do you think if we run Azure CI tests against `master` branch only, so at least we can more quickly catch windows regression test failures in future, assuming there is an alerting mechanism for an admin like me to be notified by email of CI failures? That way we're not doubling the testing time of each PR.

**Comment by ViceIce** [comment]
Yes you can add notifications for different events, like a failed pipeline

**Comment by rarkins** [comment]
@ViceIce do you think we should add just Azure then? If we add files, then we need to maintain them, so I'm not sure about Appveyor

**Comment by ViceIce** [comment]
i will remove appveyor. we can enable azure as not required, so you can merge without waiting for azure to finish.

**Comment by ViceIce** [comment]
So i've added `master` and pr only filter. I would run azure on pr too, but let it as optional checks.

**Pull request merged**
