### PR TITLE
fix: Redirect help links to new location

### PR DESCRIPTION
**Pull request by leifjones**
## Changes:

- Correct instances of an old URL to point to the new URL

## Context:

Corrects the link that people may click when reading the following on a Pinned dependencies PR:
`👻 Immortal: This PR will be recreated if closed unmerged. Get config help if that's undesired.`

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] Unit tests + ran on a real repository

_Sidebar: I appreciate that you seek input on the template!_

### CODE REVIEW

**Comment by mrsegen** [comment]
Closing because of a commit without matching email address.

**Comment by mrsegen** [comment]
Replaced by #8084

**Comment by viceice** [comment]
@mrsegen Next time simply force push a new commit instead of opening a new pr 😉

**Comment by mrsegen** [comment]
My attempts to fix were on a different machine from the original commit.

**Comment by viceice** [comment]
Next time configure author, then `git commit --amend --reset-author`, then `git push --force`.

Or do the commit on other machine and do the force push there, it will overwrite the previous commit.

**Comment by mrsegen** [comment]
Thanks!

**Pull request closed without merging**
