### PR TITLE
fix(github): Support skipped state for Workflows

### LINKED ISSUE #5956: GitHub: Automerge blocked due to skipped build step
**What Renovate type are you using?**

GitHub

**Describe the bug**

Over here: https://github.com/NullVoxPopuli/ember-jsqr/pull/6
I have a skipped build step (using a condition), and I think this may be holding up the auto-merge on success.

The build is successful, but not every step ran / needed to run.

**Did you see anything helpful in debug logs?**

I could not find anything in the logs related to the dependency `@ember/optional-features` and the branch `renovate/ember-autional-features-1.x` idk if the search is broken.. but no results came up.

**To Reproduce**

Clone this repo?: https://github.com/NullVoxPopuli/ember-jsqr/pull/6

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
Hopefully Resolves #5956

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
Doesn't look like there is a way to reword a commit in the GH UI. :(

**Review by viceice — CHANGES_REQUESTED** [review]
Don't worry about commit message, we will squash merge anyways.

Needs test case.

`skipped` is not documented 🤔

https://developer.github.com/v3/checks/runs/#create-a-check-run

**Comment by NullVoxPopuli** [comment]
How to do test case?

**Review by viceice — CHANGES_REQUESTED** [review]
Please run `yarn prettier-fix`

**Comment by NullVoxPopuli** [comment]
doesn't look like I can, because python is a depedency, and I don't have python installed. I'm on windows.

```
$ yarn && yarn prettier-fix
yarn install v1.16.0
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.2: The platform "win32" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "eslint-config-airbnb-typescript > eslint-config-airbnb@18.0.1" has unmet peer dependency "eslint-plugin-jsx-a11y@^6.2.3".    
warning "eslint-config-airbnb-typescript > eslint-config-airbnb@18.0.1" has unmet peer dependency "eslint-plugin-react@^7.14.3".      
warning "eslint-config-airbnb-typescript > eslint-config-airbnb@18.0.1" has unmet peer dependency "eslint-plugin-react-hooks@^1.7.0". 
warning " > jest-mock-extended@1.0.8" has incorrect peer dependency "jest@^24.0.0".
[5/5] Building fresh packages...
[1/4] ⠠ dtrace-provider
[-/4] ⠠ waiting...
[3/4] ⠠ husky
warning Error running install script for optional dependency: "C:\\Users\\Preston\\Documents\\Development\\NullVoxPopuli\\renovate\\node_modules\\re2: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: C:\\Users\\Preston\\Documents\\Development\\NullVoxPopuli\\renovate\\node_modules\\re2
Output:
C:\\Users\\Preston\\Documents\\Development\\NullVoxPopuli\\renovate\\node_modules\\re2>if not defined npm_config_node_gyp (node \"C:\\Users\\Preston\\AppData\\Local\\Volta\\tools\\image\\node\\12.16.1\\6.13.4\\node_modules\\npm\\bin\\node-gyp-bin\\\\..\\..\\node_modules\\node-gyp\\bin\\node-gyp.js\" rebuild )  else (node \"\" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@12.16.1 | win32 | x64
gyp ERR! find Python
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if \"python\" can be used
gyp ERR! find Python - \"python\" is not in PATH or produced an error
gyp ERR! find Python checking if \"python2\" can be used
gyp ERR! find Python - \"python2\" is not in PATH or produced an error
gyp ERR! find Python checking if \"python3\" can be used
gyp ERR! find Python - \"python3\" is not in PATH or produced an error
gyp ERR! find Python checking if the py launcher can be used to find Python 2
gyp ERR! find Python - \"py.exe\" is not in PATH or produced an error
gyp ERR! find Python checking if Python is C:\\Python27\\python.exe
gyp ERR! find Python - \"C:\\Python27\\python.exe\" could not be run
gyp ERR! find Python checking if Python is C:\\Python37\\python.exe
gyp ERR! find Python - \"C:\\Python37\\python.exe\" could not be run
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python=\"C:\\Path\\To\\python.exe\"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python \"C:\\Path\\To\\python.exe\"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (C:\\Users\\Preston\\AppData\\Local\\Volta\\tools\\image\\node\\12.16.1\\6.13.4\\node_modules\\npm\\node_modules\\node-gyp\\lib\\find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (C:\\Users\\Preston\\AppData\\Local\\Volta\\tools\\image\\node\\12.16.1\\6.13.4\\node_modules\\npm\\node_modules\\node-gyp\\lib\\find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\\Users\\Preston\\AppData\\Local\\Volta\\tools\\image\\node\\12.16.1\\6.13.4\\node_modules\\npm\\node_modules\\node-gyp\\lib\\find-python.js:225:16)
gyp ERR! stack     at PythonFinder.execFileCallback (C:\\Users\\Preston\\AppData\\Local\\Volta\\tools\\image\\node\\12.16.1\\6.13.4\\node_modules\\npm\\node_modules\\node-gyp\\lib\\find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:310:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:322:5)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:469:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command \"C:\\\\Users\\\\Preston\\\\AppData\\\\Local\\\\Volta\\\\tools\\\\image\\\\node\\\\12.16.1\\\\6.13.4\\\\node.exe\" \"C:\\\\Users\\\\Preston\\\\AppData\\\\Local\\\\Volta\\\\tools\\\\image\\\\node\\\\12.16.1\\\\6.13.4\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js\" \"rebuild\"
gyp ERR! cwd C:\\Users\\Preston\\Documents\\Development\\NullVoxPopuli\\renovate\\node_modules\\re2
gyp ERR! node -v v12.16.1
$ run-s prepare:*
yarn run v1.16.0
$ patch-package
patch-package 6.2.2
Applying patches...
@jest/types/chalk@3.0.0 ✔
jest-runtime@25.3.0 ✔
Done in 1.31s.
yarn run v1.16.0
$ tsc -p tools
Done in 3.07s.
yarn run v1.16.0
$ node --experimental-modules tools/check-re2.mjs
(node:2060) ExperimentalWarning: The ESM module loader is experimental.
Checking re2 ... error.
Error: Cannot find package 're2' imported from C:\Users\Preston\Documents\Development\NullVoxPopuli\renovate\tools\check-re2.mjs      

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "prepare:re2" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

feel free to commit to this branch though.

**Comment by NullVoxPopuli** [comment]
ah, this worked:
```
$ node node_modules/prettier/bin-prettier.js lib/platform/github/index.ts -c --write
```

**Comment by NullVoxPopuli** [comment]
@viceice requested changes applied ;)

**Pull request merged**
