### PR TITLE
fix(pr): fix broken markdown when version contains '|'

### LINKED ISSUE #5397: renovate-bot open a PR with wrong Markdown table rendering result
**What Renovate type are you using?**

Hosted GitHub App.

**Describe the bug**

I use `"rangeStrategy": "widen"` in my renovate configuration. So Renovate will upgrade my dependency from `^24.0.0` to `^24.0.0 || ^25.0.0`. 

In the PR Renovate generated for this upgrade, Renovate wrote something like below in the PR description:

```
| Package | Type | Update | Change |
|---|---|---|---|
| jest | dependencies | major | [`^24.0.0` -> `^24.0.0 || ^25.0.0`](https://url.io/) |
```

This table will be rendered as the HTML below:

| Package | Type | Update | Change |
|---|---|---|---|
| jest | dependencies | major | [`^24.0.0` -> `^24.0.0 || ^25.0.0`](https://url.io/) |

image

The `|| ^25.0.0` part is gone because of the Markdown table syntax.

**Did you see anything helpful in debug logs?**

N/A

**To Reproduce**

https://github.com/ocavue/jest-puppeteer-istanbul/pull/17#issue-371959702

**Additional context**

This rendering error can be fixed by adding a `\` before `|`.

```
| Package | Type | Update | Change |
|---|---|---|---|
| jest | dependencies | major | [`^24.0.0` -> `^24.0.0 \|\| ^25.0.0`](https://url.io/) |
```

| Package | Type | Update | Change |
|---|---|---|---|
| jest | dependencies | major | [`^24.0.0` -> `^24.0.0 \|\| ^25.0.0`](https://url.io/) |

### PR DESCRIPTION
**Pull request by djcsdy**
Fixes broken markdown in PRs caused by version ranges containing `|`.

For an example of what I mean, see this PR: https://github.com/softwareventures/tslint-rules/pull/25

Notice that the table markup is broken because the target version range is `^1.9.3 || ^2.0.0`, and `|` is interpreted by markdown as a table cell delimiter.

Closes #5397

### CODE REVIEW

**Review by rarkins — COMMENTED** [review]
We need to check how this impacts the various platforms we support. If they handle this differently then we may need to move this massaging logic into each platform's markdown massage logic.

**Comment by viceice** [comment]
See here: https://github.com/renovatebot/renovate/issues/3799#issuecomment-510762831
I've tested almost all our supported platforms

**Comment by rarkins** [comment]
Can we fix this using our `getPrBody()` functions for each platform? They are a bit misnamed these days - should maybe be `massagedMarkdown()` or something similar

**Comment by viceice** [comment]
Should be doable, I think bitbucket server is now fixed too, so we can use the escaped variant there too.

**Comment by rarkins** [comment]
So we default to the "correct" way (that gitea supports) and then massage it to escaped on other platforms?

**Comment by viceice** [comment]
@djcsdy @rarkins I want to summarize what needs to be done here.

* All platforms (excerpt gittea) are render the pipes wrong (current state).
* with this change only bitbucket cloud will render the pipes wrong (as before).
* this change is not nessessary for gittea but works there too.


So what shpould we do here?  replacing it in `getPrBody` of platfrom can be difficult, can be replace additional places where not appropriate.

**Comment by rarkins** [comment]
@viceice let's leave bitbucket cloud broken for now then, so that we can move forward with the others.

**Review by rarkins — CHANGES_REQUESTED** [review]
Please add a test or two though

**Comment by rarkins** [comment]
@djcsdy @viceice I'm a bit confused as to the status of this. Does this PR still fix things?

**Comment by viceice** [comment]
Yes, escaping is more standard and fixes bitbucket server. Bitbucket cloud is broken with both. Other platforms work before and after.

**Comment by rarkins** [comment]
From a virus code review, I can't work out what difference this PR makes

**Comment by viceice** [comment]
It escapes the pipe in version ranges. See linked or for broken GitHub PR. So this will fix GitHub pr's too

**Comment by viceice** [comment]
I try to add a test PR for current state tomorrow, so we can see this pr failing and fix text afterwards.

**Comment by rarkins** [comment]
@viceice I'm confused because I don't notice any change to the **escaping**:

image

**Comment by djcsdy** [comment]
The important part of this PR was https://github.com/renovatebot/renovate/pull/6235/files#diff-464116b52af741627d80e2939c215721L65, which someone has already implemented in master. So this PR is redundant now.

**Comment by viceice** [comment]
Here an actual pr with broken markdown
image

**Comment by viceice** [comment]
already fixed in #6514

**Pull request closed without merging**
