### PR TITLE
fix: add `remark-html` to `monorepo:remark`

### PR DESCRIPTION
**Pull request by karlhorky**
`monorepo:remark` in docs https://docs.renovatebot.com/presets-monorepo/#monoreporemark

## Changes

Add `remark-html` to the `monorepo:remark` preset

## Context

It seems that upgrading `remark-html` to the major version `16.0.1` caused breakages in the types, which are mitigated by also upgrading `remark`

@wooorm would you suggest any other package repos be added as part of Renovate's `monorepo:remark`?

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required (I believe the docs page is autogenerated)

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
These repos don't appear to have common release versions though, so there is a downside to doing this

**Comment by karlhorky** [comment]
Oh, I see. So this PR should be closed? Or is there any other way of automating these upgrades (or even just communicating this linkage to users)?

**Comment by karlhorky** [comment]
@wooorm I guess synchronizing the version numbers of `remark` and `remark-html` would probably not be an option, right? (I'm assuming it's disruptive)

**Comment by rarkins** [comment]
In a true monorepo you'd usually see something like "Update remark monorepo to v12". But when you mix versions, you end up with "Update remark monorepo" which then becomes an "immortal" PR.

**Comment by karlhorky** [comment]
Ah yeah, I think the Gatsby monorepo is currently like this, I've had problems getting rid of those PRs

**Comment by wooorm** [comment]
Some plugins are maintained by “us”. Some aren’t. This changes over time. Some are in our orgs, or in one repo, others aren’t. I don’t think using same versions, or maintaining in one repo, has significant benefits.

I have no opinion on what should be done in renovate. But perhaps it might be nice to have some “clustering”, where a release to a package is added onto an existing PR if there is one?

**Comment by rarkins** [comment]
If you're still interested, this would be better as an opt-in grouping definition in https://github.com/renovatebot/renovate/blob/main/lib/config/presets/internal/group.ts

It does not seem correct to make it a default monorepo definition

Thanks

**Comment by karlhorky** [comment]
Ok I opened the following PR for an opt-in grouping definition for `remark`, does that look correct?

- https://github.com/renovatebot/renovate/pull/25969

@wooorm in case you would have any further packages to add to the group (eg. should `rehype-` packages also be included?) then happy to make those changes

**Comment by wooorm** [comment]
Could be, perhaps? I don’t exactly know of the consequences.

But, note that unified packages have had majors many times without consequences to each other. This time was mainly a small/breaking type change in the AST, which is used everywhere, which meant everything had to update. Most unified packages actually do work across these version bumps, if you `@ts-expect-error`.

**Pull request closed without merging**
