### PR TITLE
fix(cocoapods): Add repo update option

### PR DESCRIPTION
**Pull request by funzin**
I tried to update the library managed by cocoapods with renovate, but the following error occurred
```
Analyzing dependencies
[!] Unable to find a specification for `GoogleUtilities/ISASwizzler (= 6.7.1)`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

The cause of this error is solved by adding `--repo-update`, so I added the option

### CODE REVIEW

**Comment by rarkins** [comment]
Thanks for the PR. Can you link to the documentation for this option, so we can confirm if it's appropriate to run in every scenario?

**Comment by funzin** [comment]
@rarkins 
There's an explanation of the options in this document, so check it out.
See Also: https://guides.cocoapods.org/terminal/commands.html#pod_install

**Comment by rarkins** [comment]
From https://guides.cocoapods.org/terminal/commands.html#pod_install:

image

From https://guides.cocoapods.org/terminal/commands.html#pod_repo_update:

image

I wonder if this is incorrectly documented, because a fixed path of `/home/travis` seems strange. I'm not sure from this that we want to run this 100% of the time.

**Comment by rarkins** [comment]
From a StackOverflow Q&A:

image

Isn't that repo pretty large?

**Comment by rarkins** [comment]
Next question: is this something we should attempt to cache (a) within the current repo only, or (b) globally for all repos?

**Comment by funzin** [comment]
@rarkins 

 >I wonder if this is incorrectly documented, because a fixed path of /home/travis seems strange. I'm not sure from this that we want to run this 100% of the time.

I think you're right, this document is wrong.
The correct path is `~/.cocoapods/repo`.

You can install it here and check it out.
https://guides.cocoapods.org/using/getting-started.html

>Isn't that repo pretty large?

The actual contents of `~~/.cocoapods/repo` is https://github.com/CocoaPods/Specs repository, so it's big.

>Next question: is this something we should attempt to cache (a) within the current repo only, or (b) globally for all repos?

I think "b" is enough.
If it affects performance, you can change it to a.
I'll leave it to you.

**Comment by rarkins** [comment]
As the Cocoapods spec is large, then it's not something we ideally want to do automatically for every repo as proposed in this PR. The questions to answer are:

1. Will every single repo fail if we don't do this? In which case we probably need to do it, but think about how to do it efficiently and not overload or get blocked by GitHub.

2. Can we automatically detect/predict in advance which repos will need it and insert it?

3. If not (2), can we detect the failure and retry?

4. Is (3) efficient enough or should we have a way to configure it in repo configs? And if we do, is there a problem that every Cocoapods user will add it because there is no downside, but meanwhile Renovate and GitHub suffer from the extra load?

**Review by rarkins — CHANGES_REQUESTED** [review]
Do not merge, needs research first

**Comment by funzin** [comment]
@rarkins 

>Will every single repo fail if we don't do this?

The current local spec (~/.cocoapods/repo) isn't up-to-date enough to cause this problem.
So it's going to continue to fail.

Rather than cloning the spec(https://github.com/CocoaPods/Specs) from scratch, `pod install` won't work unless the specs are cached beforehand, so you can think of it as `git pull`.

Summary: The current `~/.cocoapods/repo` itself still exists, but it's not up to date.

**Comment by viceice** [comment]
@funzin Which cocoapods version are you using? The big git repo shouldn't be directly used since version 1.7.2

Please try to update to the cdn source, see https://blog.cocoapods.org/CocoaPods-1.7.2/

ref #6613

**Comment by viceice** [comment]
see https://github.com/asoneji/sample-ios-project-cocoapods-renovate-debug-source/blob/2b86dd218c4a15e3026b646dc9ed7c068b432056/sample-ios-project/Podfile#L5 for sample cdn usage

**Comment by funzin** [comment]
cocoapods version is 1.9.3. but we have used old cdn.
I will check it new cdn:pray:

**Comment by massto** [comment]
.gitignore

**Comment by funzin** [comment]
I replaced source from `https://github.com/CocoaPods/Specs` to `https://cdn.cocoapods.org/`.
so I have got it working right.

This pr will be closed.

**Pull request closed without merging**
