### PR TITLE
feat!: drop BUILDPACK env support

### PR DESCRIPTION
**Pull request by viceice**
## Changes
Remove old `BUILDPACK` env support

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by rarkins — DISMISSED** [review]

**Comment by viceice** [comment]
@zharinov any idea why coverage changed so much? 🤔

**Comment by zharinov** [comment]
I don't know

**Review by zharinov — APPROVED** [review]

**Comment by rarkins** [comment]
@viceice lots of conflicts now unfortunately

**Comment by JamieMagee** [comment]
Rebased on top of latest `v36` and resolved conflicts.

**Review by JamieMagee — DISMISSED** [review]

**Comment by viceice** [comment]
> Rebased on top of latest `v36` and resolved conflicts.

failed tests, probably needs more changes now

**Comment by rarkins** [comment]
I've replaced this with a commit directly to v36 branch

**Pull request closed without merging**
