### PR TITLE
chore(lookup): increase log level of "Found no results ..." message

### PR DESCRIPTION
**Pull request by amezin**
## Changes

Add a warning when no valid package versions can be found in the datasource.

## Context

This is almost always a configuration error. It happened to me multiple times when I configured versioning or extractVersion incorrectly. And the issue is hard to notice when there are no updates available immediately, because logs and reports only show newer versions from lookup results.

There is a debug-level log message already, which I currently remap to warning. But I'm a bit afraid that it'll change or disappear.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by secustor** [comment]
@nabeelsaabna Do you use the warn level for telemetry in the App? 
This will potentially raise a lot of additional warnings.

**Comment by rarkins** [comment]
My instinct is that although this seems like a good idea, similar things have bitten us in the past. Let's keep in mind that users can use logLevelRemap to raise logs to WARN if they want

**Comment by nabeelsaabna** [comment]
> @nabeelsaabna Do you use the warn level for telemetry in the App? This will potentially raise a lot of additional warnings.

nope

**Review by secustor — COMMENTED** [review]
Based on the discussion above please reduce it to an info log message

**Review by secustor — APPROVED** [review]

**Pull request merged**
