### PR TITLE
feat(manager): support kustomize

### LINKED ISSUE #5467: Support for Kustomize Image Tags and Remote Bases
**What would you like Renovate to be able to do?**
We are looking to integrate renovatebot into our flow for all version-related functionality.

To do this we need to tackle one key piece of functionality which is support Kustomize.

**Describe the solution you'd like**
We would like to support two pieces of functionality for Kustomize:

1. Kustomize remote bases
2. Kustomize Image Tags

implemented as two separate managers (similar to how the terraform managers are implemented).

**Describe alternatives you've considered**
The current kubernetes plugin doesn't support this filetype, I considered adding it there, but opted to keep it separate as they are orthogonal. Kustomize aims to fill the same niche as helm.

**Additional context**
I have started work on implementing the above integration and wanted to get early feedback on if this is the correct direction to be going with it as there seems to be a fair amount of internal restructuring going on at the moment.

I aim to have a working PR up by the end of the week that anyone is welcome to play around with & provide feedback.

If you have any thoughts about things that I should definitely be avoiding, or I should avoid implementing this completely, please let me know.

All feedback is welcome.

Thanks!

### PR DESCRIPTION
**Pull request by moredhel**
This adds the following functionality:

- support for git-tag based datasources for remote bases
- support for docker based datasource for images

Closes #5467

### CODE REVIEW

**Comment by rarkins** [comment]
Thanks @moredhel, I made some small changes to the meta part of this PR - doc location and language. Could you check it for anything left failing the tests?

**Comment by moredhel** [comment]
Hi @rarkins, no problem. There are a few type errors that I'll get to on Monday as I need to review and understand how to pass information from the extract to the update functions.

I'll post a more detailed question then when I have had more time to formulate my question

**Comment by moredhel** [comment]
Thanks @rarkins,

Please have another look through the code & If you're happy then I'm happy.

Thanks

**Comment by lukasmrtvy** [comment]
@moredhel  
Would be nice to support also ChartInflator plugin
https://github.com/kubernetes-sigs/kustomize/blob/master/plugin/someteam.example.com/v1/chartinflator/ChartInflator

Its not released yet afaik

**Comment by rarkins** [comment]
@lukasmrtvy sounds like it should be a new feature request

**Pull request merged**
