### PR TITLE
refactor(datasource/go): Enable strict null checks

### PR DESCRIPTION
**Pull request by zharinov**
## Changes:

- Enable strict null checks

## Context:

- Ref: #7154
- Blocked by: #13558

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
Needs deconflicting

**Comment by viceice** [comment]
@zharinov what's the state of this PR? i skipped go on my refactor PR because of this PR. 🤗

**Comment by viceice** [comment]
- Superceeded by #15144

**Comment by zharinov** [comment]
Yeah, let's close it. Sorry for not responding you 😅

**Pull request closed without merging**
