### PR TITLE
fix: don't try to install yarn 2 from npm

### PR DESCRIPTION
**Pull request by christophehurpeau**
as yarn 2 is local in the project and should be started by yarn 1 via yarn config file.
When using yarn2, installing latest yarn (v1) should work best

### CODE REVIEW

**Comment by christophehurpeau** [comment]
related issue: #5230

**Comment by christophehurpeau** [comment]
Example of failed install: https://github.com/christophehurpeau/babel-preset-modern-browsers/pull/66#issuecomment-680006677

**Review by viceice — APPROVED** [review]

**Comment by rarkins** [comment]
So we'd run yarn 1 but with yarn 2's options?

**Comment by christophehurpeau** [comment]
@rarkins yes, in that case yarn1 is just here to call yarn 2, you can find a more detailed explanation here https://github.com/renovatebot/renovate/pull/6045#issuecomment-661030364 :)

**Comment by rarkins** [comment]
And what if yarn 2 is not committed to the repo?

**Comment by christophehurpeau** [comment]
I guess a way to make sure would be to check if .yarnrc.yml exists and has a valid yarnPath ?

**Comment by christophehurpeau** [comment]
Another way is to call `${yarnPath} --version`

**Comment by rarkins** [comment]
Is there a scenario where the repo doesn't have Yarn 2 committed and therefore Renovate's artifact updating fails?

**Comment by christophehurpeau** [comment]
Only if there is a .gitignore ignoring .yarn folder, but that's not supposed to happen

> Yarn 2 and later are meant to be managed on a by-project basis

https://yarnpkg.com/getting-started/install

> .yarn/*
> !.yarn/releases

https://yarnpkg.com/advanced/qa#which-files-should-be-gitignored

**Pull request merged**
