### PR TITLE
feat: abortOnError / abortIgnoreStatusCodes

### PR DESCRIPTION
**Pull request by rarkins**
This PR adds the ability for users to customize which hosts throw `DatasourceError`s and for which HTTP status codes. `abortOnError` can be used to opt-in certain host types or specific hosts such that they throw `DatasourceError` and abort the run, while `abortStatusCodes` allows for the list of status codes to be customized.

Sets groundwork for #5557

### CODE REVIEW

**Comment by rarkins** [comment]
TODO:

- [ ] throw for http errors too (ETIMEOUT, etc)
- [ ] Convert hardcoded datasource error throwing into hostRules
- [ ] Ensure default abortStatusCodes are added to hostRules

**Comment by rarkins** [comment]
@JamieMagee @viceice what do you think about this approach? I think it achieves the flexibility necessary without being too confusing. Even the basic examples given in documentation can be turned into in-built presets to make it simpler still.

**Review by viceice — DISMISSED** [review]
I'm fine with this approach. 👍

**Comment by JamieMagee** [comment]
Yeah, also sounds good to me. I like the composability we gain with `hostRules`

**Comment by rarkins** [comment]
Waiting on #6563

**Pull request merged**
