### PR TITLE
docs: update renovate/renovate tags

### PR DESCRIPTION
**Pull request by HonkingGoose**
## Changes:

- Update `renovate/renovate` DockerHub tags

## Context:

This was due an update. 😄 

It's odd that the minor/patch version numbers are reasonably up to date, while the major version is lagging behind.
I think we have a custom RegEx manager that updates these references, but maybe it's not updating the major version (by design or accident)?

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by HonkingGoose** [comment]
> It's odd that the minor/patch version numbers are reasonably up to date, while the major version is lagging behind.
> I think we have a custom RegEx manager that updates these references, but maybe it's not updating the major version (by design or accident)?

The current `default.json` over on the `renovate/.github` repo says:

```json 
   {
      "description": "Update references to Docker tags for renovate/renovate in Markdown files weekly",
      "matchPackageNames": ["renovate/renovate"],
      "matchPaths": [".md"],
      "extends": ["schedule:weekly"],
      "automerge": true,
      "stabilityDays": 0,
      "commitMessageTopic": "references to {{{depName}}}",
      "semanticCommitType": "docs",
      "semanticCommitScope": null,
      "additionalBranchPrefix": "docs-"
    },
```

I'm not sure if this config would pick up a new major version or not.

https://github.com/renovatebot/.github/blob/main/default.json

**Review by viceice — CHANGES_REQUESTED** [review]
@HonkingGoose The braqnch is here: https://github.com/renovatebot/renovate/commit/b345e6f0bc3ff0939f25d96efcf7729afe36d308

I'm checking the logs why it won't open a pr

**Comment by viceice** [comment]
image

🤔

**Comment by viceice** [comment]
```
DEBUG: Checking if we can automerge branch(branch="renovate/docs-renovate-renovate-25.x")
DEBUG: mergeStatus=no automerge(branch="renovate/docs-renovate-renovate-25.x")
DEBUG: Ensuring PR(branch="renovate/docs-renovate-renovate-25.x")
DEBUG: There are 0 errors and 0 warnings(branch="renovate/docs-renovate-renovate-25.x")
DEBUG: getBranchPr(renovate/docs-renovate-renovate-25.x)(branch="renovate/docs-renovate-renovate-25.x")
DEBUG: findPr(renovate/docs-renovate-renovate-25.x, undefined, open)(branch="renovate/docs-renovate-renovate-25.x")
DEBUG: findPr(renovate/docs-renovate-renovate-25.x, undefined, closed)(branch="renovate/docs-renovate-renovate-25.x")
DEBUG: Checking branch combined status(branch="renovate/docs-renovate-renovate-25.x")
DEBUG: getBranchStatus(renovate/docs-renovate-renovate-25.x)(branch="renovate/docs-renovate-renovate-25.x")
DEBUG: branch status check result(branch="renovate/docs-renovate-renovate-25.x")
{
  "state": "pending",
  "statuses": []
}
DEBUG: No check runs found(branch="renovate/docs-renovate-renovate-25.x")
{
  "result": {
    "total_count": 0,
    "check_runs": []
  }
}
DEBUG: getBranchStatus() result(branch="renovate/docs-renovate-renovate-25.x")
{
  "branchStatus": "yellow",
  "branchName": "renovate/docs-renovate-renovate-25.x"
}
DEBUG: Branch status is "yellow" - checking timeout(branch="renovate/docs-renovate-renovate-25.x")
DEBUG: Branch is 2 hours old - skipping PR creation(branch="renovate/docs-renovate-renovate-25.x")
```
Missing ci job?

**Comment by viceice** [comment]
yes, missing github actions jobs https://github.com/renovatebot/renovate/branches/active

image

**Comment by viceice** [comment]
OK, it's because we don't build renovate branches, so `"prCreation": "not-pending",` will block pr creation forever 😕

**Comment by HonkingGoose** [comment]
Do we want to keep this PR around? I think the best way to proceed is to fix our GitHub Action setup so the auto-update works properly again.

I made a new issue to track our work on the CI fix (#10789).

I'll mark this PR as a draft for now, so we don't accidentally merge it.

**Comment by HonkingGoose** [comment]
@viceice I notice have a branch for the `v24` and `v25` versions of the `renovate/renovate` tag. I would have expected only a branch for the `v25` tag. Maybe we have misconfigured something?


To see what I mean, check out the Renovate bot commit on each branch, note that it affects the same files, but one updates the references to 24 and the other to 25.

**Comment by viceice** [comment]
> @viceice I notice have a branch for the `v24` and `v25` versions of the `renovate/renovate` tag. I would have expected only a branch for the `v25` tag. Maybe we have misconfigured something?
> 
> To see what I mean, check out the Renovate bot commit on each branch, note that it affects the same files, but one updates the references to 24 and the other to 25.

image

There are some missing v24 updates too 😏

**Comment by viceice** [comment]
forced pr now #10795

**Comment by HonkingGoose** [comment]
The GitHub PR diff is empty now I've merged the latest `main` which has the changes from #10795.

I'll close this PR as there's no point in having it open anymore.

**Pull request closed without merging**
