### PR TITLE
fix(docker): incorrect variable used during refactor

### PR DESCRIPTION
**Pull request by rajatagarwal**
## Changes:
https://github.com/renovatebot/renovate/issues/10535

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by rajatagarwal** [comment]
Ran locally and executed tests as mentioned here: https://github.com/renovatebot/renovate/blob/main/docs/development/local-development.md#fork-and-clone

**Review by JamieMagee — APPROVED** [review]

**Comment by JamieMagee** [comment]
For reference, here's the diff from where this bug was introduced https://github.com/renovatebot/renovate/commit/cd078e73bde134eb6359c95684e3911c6329e348#diff-922b65de7866726a28ede70241c7f637072005518289aa3755070398bc5b1db7L112

**Comment by viceice** [comment]
@JamieMagee Next time we should check the pr descrioption, so it auto closes the mentioned issue 😉

**Comment by JamieMagee** [comment]
Whoops! I saw that it #-mentioned an issue, but didn't check carefully enough

**Pull request merged**
