### PR TITLE
fix(ci): Restrict template expressions

### PR DESCRIPTION
**Pull request by zharinov**
## Changes

At the moment, there is no way to genuinely fix template expression warnings of possible `undefined` values, so these annotations only annoy us during code review. The feeling of helplessness is quite harmful for the psyche, so let's just turn it off for now.

## Context

- #7154

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by rarkins — DISMISSED** [review]

**Review by viceice — COMMENTED** [review]
there are a lot issues we now simply suppress

**Comment by viceice** [comment]
especially when urls are created from string templates

**Comment by zharinov** [comment]
But having these warnings in every PR (mostly unrelated) doesn't address this problem.
Would you like to make it strict and suppress current occurrences with type assert like we did for strict null checks?

**Comment by zharinov** [comment]
This won't solve it as well, though at least we'll have more control over new occurrences.

**Comment by viceice** [comment]
i already fixed a lot of them, we should fix the remaining or mark them with the existing todo

**Comment by zharinov** [comment]
Okay, then I'll suppress them line-by-line and mark as todo.

**Review by viceice — APPROVED** [review]

**Pull request merged**
