### PR TITLE
feat(preset): group all Octokit packages together

### PR DESCRIPTION
**Pull request by astorije**
## Changes

See https://github.com/octokit

Screenshot 2023-06-16 at 5 45 32 PM

## Context

Octokit are the official clients for the GitHub API. We use individual packages, composed together. They don't get updated often, but when they do, they are typically released at the same time and require to be upgraded together. Event when they do not, package names conflict so it would be nicer to group them together.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by rarkins — DISMISSED** [review]

**Review by viceice — COMMENTED** [review]
😕 those should be grouped by source url Like Most of the other mono repos.

**Review by viceice — CHANGES_REQUESTED** [review]
see other comment

**Comment by astorije** [comment]
> 😕 those should be grouped by source url Like Most of the other mono repos.

@viceice are you sure? I tried to follow existing conventions and it seemed to me that sets of packages were relying on the prefix more than the URL (8 occurrences in this file vs. 2), as @octokit packages are not a monorepos.
I don't mind either way of course, just figured I'd confirm before making the change.

Thanks!

**Comment by viceice** [comment]
https://github.com/renovatebot/renovate/blob/2d43e576b352935052f440049847f242506ee8d1/lib/config/presets/internal/monorepo.ts#L6

they should be in this list.

**Comment by viceice** [comment]
or this

https://github.com/renovatebot/renovate/blob/2d43e576b352935052f440049847f242506ee8d1/lib/config/presets/internal/monorepo.ts#L272

or 

https://github.com/renovatebot/renovate/blob/2d43e576b352935052f440049847f242506ee8d1/lib/config/presets/internal/monorepo.ts#L283

**Comment by rarkins** [comment]
I don't mind org group vs by scope

**Comment by astorije** [comment]
Done!

**Review by viceice — APPROVED** [review]

**Comment by astorije** [comment]
Apparently our self-hosted bot is stuck in v35.120.0 so unfortunately I'll have to wait until our DevOps team can help figure it out before getting the change 😅
Thanks for the quick turnaround as usual!

**Pull request merged**
