### PR TITLE
feat: support retrieving changelog from ghe hosted repositories

### PR DESCRIPTION
**Pull request by brokenmass**
This PR provides the ability to retrieve changelog from packages hosted on the same github enterprise of the 'target' project being renovated.

### CODE REVIEW

**Comment by brokenmass** [comment]
@rarkins

**Comment by rarkins** [comment]
@brokenmass I’ll need some time to understand and review this. Could you add a few inline comments explaining the logic?

**Comment by brokenmass** [comment]
I think it can be easily summarised as:
If we are using Github enterprise (GITHUB_ENDPOINT is configured) and the dependencies we are retrieving the changelog for is hosted on that github (verified by comparing GITHUB_ENDPOINT hostname with the pkg.repositoryUrl hostname) then preserve the credentials for Github enterprise.
In this way ghGot will make the requests to the private Github.
if that's the case then use the github enterprise hostname as baseurl when building the changelog summary links.

If the hostname are different instead revert to the previous behaviour of trying to retrieve the changelog from the public Github.com

**Comment by brokenmass** [comment]
@rarkins is there anything I can do to help you get this merged ?

**Comment by rarkins** [comment]
Visual review looks good. I need to run it against some test repositories first and then hopefully merge it tomorrow so I can deploy to the app and watch for any problems.

**Comment by rarkins** [comment]
Thanks for the excellent PR, btw. I’m impressed that you stitched it all together

**Comment by brokenmass** [comment]
@rarkins does the app clear the cache when is updated ? if that's not the case than the issue might be cause by this line [here](https://github.com/brokenmass/renovate/blob/b6824606e714c8eef76a5ba9edbb2406555a944f/lib/workers/pr/changelog/index.js#L41) as if the res retrieved from cache does not contain `res.project.githubBaseURL` (cache value from a previous version for example) it will be handled as a github enterprise repo.

**Comment by rarkins** [comment]
Thanks for taking a look. Can you reopen or raise a new PR when done? And yes let’s make sure it handles “old” caches too.

**Pull request merged**
