### PR TITLE
feat: official Dockerfile

### LINKED ISSUE #1609: Provide official docker image on DockerHub for self-hosted renovate
It would be awesome if there was an official, always up-to-date, guaranteed-to-work , properly tagged Docker image on Docker hub for self-hosted renovate that could just be dropped into an infrastructure.

### PR DESCRIPTION
**Pull request by rarkins**
Adds a Dockerfile for building with Docker Hub

Design choices:
- Use alpine node for size reduction
- Keep npm and yarn globally installed in final build
- Keep this "behaving" like the npm binary, e.g. runs and exits, no cron, etc

Closes #1609

### CODE REVIEW

**Comment by rarkins** [comment]
Current image size is 269MB. It will reduce to 200MB after the next major release where I move `npm` and `yarn` to be peer dependencies rather than production dependencies.

**Comment by rarkins** [comment]
Cc @hulkish @felixfbecker

**Comment by rarkins** [comment]
To be done in future issues:
- [ ] Remove `node` and `yarn` as `dependencies` so they are not duplicated within the image
- [ ] Add a post-publish hook to add major and minor tags

**Comment by rarkins** [comment]
@destroyerofbuilds please also review

**Comment by felixfbecker** [comment]
Nice and simple. Will work perfectly with [Kubernetes cronjobs](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/)

**Pull request merged**
