### PR TITLE
docs: Add Debug configuration for VSCode

### PR DESCRIPTION
**Pull request by praveshtora**
Closes #

### CODE REVIEW

**Comment by rarkins** [comment]
@praveshtora thanks. So there's no way to use the VSCode debugger while using "normal" CLI arguments or normal system env? Also, does defining token in `config.js` work?

**Comment by praveshtora** [comment]
VSCode was not able to read the system environment variables, thus we need to declare them explicitly in launch.json. Though passing repo name can be optional and debugger would still work and hit the breakpoint.

**Comment by rarkins** [comment]
@praveshtora can you check if it's possible to set token in `config.js` rather than the custom env? The `config.js` should be located in the pwd and would look something like this:

```js
module.exports = {
  token: 'abc123',
}
```

or this:

```js
module.exports = {
  token: process.env.GITHUB_TOKEN,
}
```

**Comment by praveshtora** [comment]
@rarkins token in config.js works. Please review the updated PR.

**Comment by ViceIce** [comment]
you can also add the repository to `config.js`

**Comment by praveshtora** [comment]
@ViceIce Just checked. It works by adding repositories in config.js. @rarkins What would be an ideal place to put repository name then?

**Comment by rarkins** [comment]
@praveshtora I think I prefer recommending people use `config.js` (`repositories` field) rather than the VSCode config file, because `config.js` is not checked into the repo and won't be flagged by git as a modified file. So can you rewrite the recommendation/PR to reflect that users should enable VSCode debugging by defining both `token` and `repositories` within `config.js`?

**Comment by praveshtora** [comment]
@rarkins I have updated the PR with required changes.

**Comment by ViceIce** [comment]
You can something like this to `config,js`add environment variables for renovate:
```javascript
Object.assign(process.env, {
  TEMP: 'C:\\tmp',
  GITHUB_COM_TOKEN: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
});
```

I use this for vscode, because i use bitbucket server or gitlab as backend.

**Comment by praveshtora** [comment]
But config file is the same for all platform. Right? So that would be the more generalized configuration. Just adding `platform` in config.js works for me.

**Comment by ViceIce** [comment]
yes, you can only use a single platform at a time. I use the gh token to not get blocked by github api (request limit).

**Comment by rarkins** [comment]
FYI this is how I use my `config.js` locally:
image

This way I just need to comment/uncomment lines to switch platforms.

**Pull request merged**
