### PR TITLE
feat(npm): support updating `packageManager` field and Yarn binary

### LINKED ISSUE #11368: Support updating Yarn binary
### What would you like Renovate to be able to do?

Update the Yarn (JavaScript package manager) binary to the latest version.

### If you have any ideas on how this should be implemented, please tell us here.

The current version can be detected from `.yarnrc.yml`:
```yml
yarnPath: .yarn/releases/yarn-3.0.1.cjs
```
(However, the version cannot be detected if upgraded from Yarn 1:
```yml
yarnPath: ".yarn/releases/yarn-berry.cjs"
```
In this case, I think it should always run. )

The version data can be fetched from the npm [`@yarnpkg/cli` package](https://www.npmjs.com/package/@yarnpkg/cli?activeTab=versions) (npm datasource).

It can be updated by running:
```sh
yarn set version <version>
yarn install # update lockfile and cache
```

Afterwards, following paths should be commited:
```sh
.yarn/releases
.yarn/cache # if zero-installs is used
.pnp.cjs # if zero-installs is used
.yarnrc.yml
package.json
yarn.lock
```

### Is this a feature you are interested in implementing yourself?

Yes

### PR DESCRIPTION
**Pull request by ylemkimon**
## Changes:

- Set `constraints` based on [the `packageManager` field](https://nodejs.org/api/packages.html#packages_packagemanager), simulating the behavior of Corepack
- Support updating the `packageManager` field in `package.json`
  - Update lockfile with the new version
  - Update the Yarn 2+ binary checked in to the repo

## Context:

Node v16.9.0+ includes a new tool called [Corepack](https://nodejs.org/api/corepack.html) (formerly pmm), to help with managing versions of package managers. It uses the `packageManager` field in `package.json`, which is in the form of `{yarn,pnpm}@<exact version>`.

I've tried to create a new manager, but the logic is too intertwined, e.g., the lockfile depends on the version of the package manager. I agree that the `npm` manager is too complex and I see a lot of opportunities to refactor, but it'd be out of scope for this PR.

Fixes #11368 if the `packageManager` is set.

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository:

* pnpm `5.18.9` -> `5.18.10`: https://github.com/ylemkimon/renovate-corepack/pull/5
* pnpm `5.18.9` -> `6.16.1`: https://github.com/ylemkimon/renovate-corepack/pull/7
* Yarn `1.22.11` -> `1.22.15`: https://github.com/ylemkimon/renovate-yarn-update/pull/5
* Yarn `2.3.3` -> `2.4.3`: https://github.com/ylemkimon/renovate-yarn-3/pull/178
* Yarn `2.3.3` -> `3.0.2`: https://github.com/ylemkimon/renovate-yarn-3/pull/181

/cc @arcanis (core maintainer of Yarn and Corepack)

### CODE REVIEW

**Review by rarkins — CHANGES_REQUESTED** [review]

**Review by rarkins — DISMISSED** [review]

**Review by viceice — COMMENTED** [review]
looks good so far, but i like to move the contraints extraction after update phase right before lockfile update binary call is happen

**Comment by viceice** [comment]
I'm not sure, in other managers we prefer to extract the contraints in `updateArtifacts`, but `npm` manafer is a bit special, so i'm not sure about the right place.

But the place right before the yarn / npm / pnpm call would be the right place

**Comment by ylemkimon** [comment]
I think refactor can be done in another PR, to reduce complications.

**Comment by ylemkimon** [comment]
@rarkins Could you let me know what changes are required?

**Comment by rarkins** [comment]
@ylemkimon I thought you planned to do some refactoring first and then resume this PR?

**Comment by ylemkimon** [comment]
@rarkins Nope, I was planning to do it after this PR gets merged 😄

**Comment by rarkins** [comment]
@viceice wdyt?

**Comment by viceice** [comment]
> @rarkins Nope, I was planning to do them after this PR gets merged 😄

LGTM, please don't forget 😉

**Review by viceice — APPROVED** [review]

**Pull request merged**
