### PR TITLE
feat: add changelog url for eslint-plugin-react-etc

### PR DESCRIPTION
**Pull request by AdrienLemaire**
## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — CHANGES_REQUESTED** [review]
Needs cla signing, otherwise LGTM

**Comment by AdrienLemaire** [comment]
@viceice interesting that you'd require a CLA on my 14th PR... done.

**Review by viceice — APPROVED** [review]

**Comment by viceice** [comment]
btw: you won't get any futher feedback if you leave the pr as is. We do not mark it as ready, nor do a new review if not requested 😉

**Comment by rarkins** [comment]
> interesting that you'd require a CLA signature on my 14th PR... done.

The CLA bot we use requires contributors to re-agree if any of the wording changes. So you had completed the previous CLA through the same means, it's just there were some changes since related to change of ownership.

**Comment by AdrienLemaire** [comment]
A CHANGELOG file is quite a recurrent pattern across repositories. It'd save us a lot of time if renovate could auto-detect these.

**Comment by rarkins** [comment]
It does autodetect them usually. Do you have a reproduction of it failing to find this one we can look at?

**Comment by AdrienLemaire** [comment]
@rarkins the package for this PR is an example.
We see this in our private repo:


Maybe your CHANGELOG check is skipped because a github release was done, even though it doesn't have notes in it ?

**Comment by rarkins** [comment]
Yes, it's possible that the GitHub Release is taking precedence. If you can create a minimal reproduction repo (e.g. one dependency, one PR) then I'll try debugging it

**Comment by rarkins** [comment]
Closing this until we work out if it is needed or not

**Comment by AdrienLemaire** [comment]
@rarkins I wish you had merged it instead of closed it. We are overwhelmed by tasks, but still took the time to create this PR...

**Comment by rarkins** [comment]
@AdrienLemaire it's appreciated that you created the PR, but even if it's one line we're not going to merge it if it's a pointless addition.

**Comment by viceice** [comment]
Yes, we should work out, why renovate isn't able to find this file by default.

**Pull request closed without merging**
