### PR TITLE
feat: Support multiple assignees in Gitlab

### LINKED ISSUE #3745: Support multiple GitLab assignees
Seems the assignee_id field may be replaced by assignee_ids: https://gitlab.com/gitlab-org/gitlab-ee/merge_requests/10161

### PR DESCRIPTION
**Pull request by praveshtora**
* According to their offical docs -https://docs.gitlab.com/ee/api/merge_requests.html#update-mr , with the new release , assignee_ids is supported.
Closes #3745

### CODE REVIEW

**Comment by praveshtora** [comment]
@rarkins I have verified in the official docs and have tested as well. It seems to be working.

**Comment by rarkins** [comment]
@praveshtora we need to also make sure we don't "break" any Renovate users who are using still-supported versions of GitLab but which don't have `assignee_ids` support. So we need to check:

1. Is this GitLab EE only, or also GitLab CE?
2. Which version of each was this feature introduced?
3. What's the minimum version of GitLab CE/EE that GitLab themselves still consider "supported"?

**Comment by praveshtora** [comment]
I could find it in releases- https://about.gitlab.com/2017/05/22/gitlab-9-2-released/.  I am still trying to find whats the minimum version till its supported.

**Comment by rarkins** [comment]
Let’s make sore we don’t mix up issues and MRs too. Normally we don’t assign issues to anyone - only MRs. that announcement mentions Issues specifically.

**Comment by praveshtora** [comment]
I went through changelogs for both ce and ee and could find it only for the enterprise edition. It was released in version 11\.11.0 (2019-05-22).  The issue which introduced this feature https://gitlab.com/gitlab-org/gitlab-ee/merge_requests/10161. 
Do we deal differently for `ce` and `ee`?

**Comment by rarkins** [comment]
Our idea is to support all versions of CE and EE that GitLab themselves support. In this case it means we must be gracefully backwards compatible with CE or EE that *don't* support this feature. I'm not sure of the best way to do that

**Comment by rarkins** [comment]
Sorry, let's skip this one until there's demand. And then we investigate if/how we can support multiple versions of CE/EE if still required.

**Pull request closed without merging**
