### PR TITLE
fix(platform): Filter out non-Renovate PRs with same branch

### LINKED ISSUE #5188: getBranchPr gets confused by other PRs
**What Renovate type are you using?**

Hosted app

**Describe the bug**

1. Renovate creates a PR in the repo
2. Someone else creates a PR to that PR's branch, keeping the exact same branch name
3. Renovate is then confused, and getBranchPr returns the second PR not the first

**Did you see anything helpful in debug logs?**

### PR DESCRIPTION
**Pull request by zharinov**
Closes #5188

### CODE REVIEW

**Comment by rarkins** [comment]
@zharinov what tests have you been able to do so far? e.g. were you able to reproduce the problem in old code then see it's fixed in new?

**Comment by ViceIce** [comment]
Shouldn't we try to fetch only our PR's? Then we don't need that check.

**Comment by rarkins** [comment]
Right now we fetch all open ones in case one is a Renovate reconfiguration PR that we need to validate

**Comment by rarkins** [comment]
I’m tempted to deprecate that capability and make it a separate module to keep core renovate simpler

**Comment by zharinov** [comment]
> @zharinov what tests have you been able to do so far? e.g. were you able to reproduce the problem in old code then see it's fixed in new?

I tested on [this example](https://github.com/zharinov/renovate-npm/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc), it updates different PRs depending on master vs fix branch. I also validated this result with debugger run.

**Comment by rarkins** [comment]
- [ ] Need to check that this doesn't break "forkMode" because Renovate's PRs come from another repo

**Comment by zharinov** [comment]
Okay, seems like it's ready for review

**Pull request merged**
