### PR TITLE
fix(maven): registryUrls from parent hierarchy

### LINKED ISSUE #4281: Renovate doesn't use maven repositories from parent pom
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
In a maven module project Renovate does not check repositories defined in a parent pom for dependencies defined in a sub module.
E.g.
Parent pom in root directory:
```
...
    <groupId>com.example</groupId>
    <artifactId>some-parent</artifactId>
    <version>1.2.3</version>
    <packaging>pom</packaging>
...
    <repositories>
        <repository>
            <id>xyz</id>
            <name>xyz</name>
            <url>http://example.com/nexus/xyz</url>
        </repository>
    </repositories>
...
```
Module pom in sub directory
```
...
    <parent>
        <groupId>com.example</groupId>
        <artifactId>some-parent</artifactId>
        <version>1.2.3</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
...
    <dependencies>
        <dependency>
            <groupId>com.example</groupId>
            <artifactId>some-library</artifactId>
            <version>4.5.6</version> <!-- only hosted at http://example.com/nexus/xyz -->
        </dependency>
...
```

**Did you see anything helpful in debug logs?**
(Adjusted to match the example)
```
{
 "datasource": "maven",
 "depName": "com.example:some-library",
 "currentValue": "4.5.6",
 "fileReplacePosition": 1066,
 "registryUrls": ["https://repo.maven.apache.org/maven2"],
 "groupName": "some-library.version"
},

```

`registryUrls` should include `http://example.com/nexus/xyz`

**To Reproduce**

1.  Create repository with a parent pom in the root, a submodule in a directory.
2.  Define repositories in the parent and dependencies in the module as the example
3.  Run renovate with maven enabled
4.  It will fail to check the private repo

**Expected behavior**
Renovate should check the dependencies in the module against the repositories defined in the parent pom.

**Screenshots**
n/a

**Additional context**
I'm actively working on a fix for this

### PR DESCRIPTION
**Pull request by zharinov**
Closes #4281
Replaces #4282 to handle nested parents

### CODE REVIEW

**Comment by rarkins** [comment]
@RoamingKiwi can you confirm if this PR also solves your needs?

**Comment by RoamingKiwi** [comment]
Yeah it does

**Comment by rarkins** [comment]
Thanks, added you as co-author of this PR and merged

**Comment by RoamingKiwi** [comment]
Awesome, thanks for your help

**Comment by rarkins** [comment]
This unfortunately caused a regression error so needed to be rolled back. Lots of warnings like `No repositories defined for org.apache.commons:commons-io` and autoclosed PRs.

**Pull request merged**
