### PR TITLE
Update dependency-pinning.md

### PR DESCRIPTION
**Pull request by ithinkihaveacat**
Improve explanation of what `package-lock.json` does and doesn't do.

### CODE REVIEW

**Comment by ithinkihaveacat** [comment]
Can that CircleCI test failure be ignored (doc-only change)? I'm not sure what it's complaining about.

**Comment by rarkins** [comment]
I don't mind clarifying the text but I'd prefer to reword it. The heading is "What a lock file does for you" and I'd prefer not to lead with "What a lock file does is very confusing". If it's confusing, let's make it clear - rather than risk being seen to criticize the lock files/tools.

The failure is due to enforcing prettier formatting on the file. We can fix that up once the final text is decided.

**Comment by rarkins** [comment]
See #4073

**Comment by ithinkihaveacat** [comment]
Fair point re tone. Will add comment to #4073.

**Pull request closed without merging**
