### PR TITLE
feat(presets): add Forge monorepo

### PR DESCRIPTION
**Pull request by koterpillar**
## Changes

Add a monorepo preset for Atlassian Forge platform.

## Context

Forge has several packages developers might use: [`@forge/cli`](https://developer.atlassian.com/platform/forge/cli-reference/), [`@forge/api`](https://developer.atlassian.com/platform/forge/runtime-reference/product-fetch-api/), [`@forge/ui`](https://developer.atlassian.com/platform/forge/ui-kit/), etc. Makes sense to update them together.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — COMMENTED** [review]
please try to group them via sourceUrl, like most of the other mono repos

**Comment by koterpillar** [comment]
Unfortunately Forge packages don't have a publicly accessible source code repository, so matching by source URL won't work.

**Comment by viceice** [comment]
we don't like to add package rules for closed source

**Comment by koterpillar** [comment]
Fair enough, I like FOSS as well but unfortunately don't have enough control here.

Does "don't like" mean "this will not be merged" or can I do something to get it in (as IMO this will improve the maintenance for users of Forge)?

**Comment by viceice** [comment]
@rarkins WDYT?

**Comment by rarkins** [comment]
I'm ok to add it

**Review by rarkins — APPROVED** [review]

**Pull request merged**
