### PR TITLE
fix(gomod): GOPROXY with slash doesnt work

### PR DESCRIPTION
**Pull request by PhilipAbed**
## Changes

trimm slash while parsing GOPROXY

## Context

some customer run failed with this error
`DEBUG: Goproxy error: trying next URL provided with GOPROXY`

the URL in the error had 2 slashes // after go.
`"url": "https://{XYZ.ARTIFACTORY}/go//x/y/z/v3/@v/list",`

when i checked code for this i found the slash is hardcoded into this

https://github.com/renovatebot/renovate/blob/4bea95b2d005b2d661405a3e4f3bca7861266fc5/lib/modules/datasource/go/releases-goproxy.ts#L132

the simple solution is to trim the slash from GOPROXY in the parser before it, as it is not necessary.

let me know if you think otherwise.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by rarkins — COMMENTED** [review]
Why is a trailing slash a problem if parsed with it? It's valid in URLs obviously

**Review by rarkins — CHANGES_REQUESTED** [review]
I think that this approach to fixing it is not robust. It's done in a separate _file_ to where the problem occurs. We should either use a better way of joining URLs, or do the trailing slash trimming at the point of static joining

**Comment by PhilipAbed** [comment]
so you are saying the issue is with 
 const url = `${baseUrl}/${this.encodeCase(packageName)}/@v/list`; 
 its kind of hardcoded, we should use some URL joiner here

**Comment by viceice** [comment]
> so you are saying the issue is with 
>  const url = `${baseUrl}/${this.encodeCase(packageName)}/@v/list`; 
>  its kind of hardcoded, we should use some URL joiner here

yes, that's better

**Comment by PhilipAbed** [comment]
im afraid to use url joiner since the url.parser and joiner are broken for protocols
https://github.com/renovatebot/renovate/pull/31008/files
https://github.com/renovatebot/renovate/discussions/30295

**Review by rarkins — APPROVED** [review]

**Review by viceice — APPROVED** [review]

**Pull request merged**
