### PR TITLE
fix(gradle-wrapper): skip artifacts update if no gradlew command found

### PR DESCRIPTION
**Pull request by rarkins**

### CODE REVIEW

**Comment by rarkins** [comment]
I think our tests need updating. Currently we see some warnings in the app because we attempt to run `null ......` which clearly won't work.

**Review by viceice — COMMENTED** [review]
Yes needs test updates. Do you need help for it?

**Comment by rarkins** [comment]
> Yes needs test updates. Do you need help for it?

If you don't mind, because I skip Java tests locally still. The existing tests started failing because they were based on `null` gradlew

**Comment by viceice** [comment]
ok, will do after lunch 🙃

**Comment by viceice** [comment]
So tests are working, now i add some mock tests too, so we always have 100% coverage for the java tests too (even without real gradle tests)

**Pull request merged**
