### PR TITLE
fix: lerna with useWorkspaces: true

### LINKED ISSUE #7726: Support lerna with yarn 2 (berry)
**What Renovate type, platform and version are you using?**

Hosted App, on github

**Describe the bug**

The yarn install in post-update is broken:
https://github.com/renovatebot/renovate/blob/master/lib/manager/npm/post-update/yarn.ts#L53-L60

as renovate is trying to run: `npm i -g yarn@'>= 2.2.0'`

https://github.com/christophehurpeau/nightingale/pull/95#issuecomment-727179668

**Relevant debug logs**

```
DEBUG: Executing command(branch="renovate/pin-dependencies")
{
  "command": "docker run --rm --name=renovate_node --label=renovate_child -v \"/mnt/renovate/gh/christophehurpeau/nightingale\":\"/mnt/renovate/gh/christophehurpeau/nightingale\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -v \"/home/ubuntu/.npmrc\":\"/home/ubuntu/.npmrc\" -e NPM_CONFIG_CACHE -e npm_config_store -w \"/mnt/renovate/gh/christophehurpeau/nightingale\" docker.io/renovate/node:15.2.0 bash -l -c \"npm i -g yarn@'>= 2.2.0' && sed -i 's/ steps,/ steps.slice(0,1),/' /home/ubuntu/.npm-global/lib/node_modules/yarn/lib/cli.js && npm i -g lerna@3.22.1 && yarn install --ignore-scripts --ignore-engines --ignore-platform && lerna bootstrap --no-ci --ignore-scripts -- --ignore-scripts --ignore-engines --ignore-platform\""
}
DEBUG: lock file error(branch="renovate/pin-dependencies")
{
  "cmd": [
    "yarn install --ignore-scripts --ignore-engines --ignore-platform",
    "lerna bootstrap --no-ci --ignore-scripts -- --ignore-scripts --ignore-engines --ignore-platform"
  ],
  "err": {
    "killed": false,
    "code": 1,
    "signal": null,
    "cmd": "docker run --rm --name=renovate_node --label=renovate_child -v \"/mnt/renovate/gh/christophehurpeau/nightingale\":\"/mnt/renovate/gh/christophehurpeau/nightingale\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -v \"/home/ubuntu/.npmrc\":\"/home/ubuntu/.npmrc\" -e NPM_CONFIG_CACHE -e npm_config_store -w \"/mnt/renovate/gh/christophehurpeau/nightingale\" docker.io/renovate/node:15.2.0 bash -l -c \"npm i -g yarn@'>= 2.2.0' && sed -i 's/ steps,/ steps.slice(0,1),/' /home/ubuntu/.npm-global/lib/node_modules/yarn/lib/cli.js && npm i -g lerna@3.22.1 && yarn install --ignore-scripts --ignore-engines --ignore-platform && lerna bootstrap --no-ci --ignore-scripts -- --ignore-scripts --ignore-engines --ignore-platform\"",
    "stdout": "",
    "stderr": "npm ERR! code ETARGET\nnpm ERR! notarget No matching version found for yarn@>= 2.2.0.\nnpm ERR! notarget In most cases you or one of your dependencies are requesting\nnpm ERR! notarget a package version that doesn't exist.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /tmp/renovate-cache/others/npm/_logs/2020-11-14T10_25_13_983Z-debug.log\n",
    "message": "Command failed: docker run --rm --name=renovate_node --label=renovate_child -v \"/mnt/renovate/gh/christophehurpeau/nightingale\":\"/mnt/renovate/gh/christophehurpeau/nightingale\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -v \"/home/ubuntu/.npmrc\":\"/home/ubuntu/.npmrc\" -e NPM_CONFIG_CACHE -e npm_config_store -w \"/mnt/renovate/gh/christophehurpeau/nightingale\" docker.io/renovate/node:15.2.0 bash -l -c \"npm i -g yarn@'>= 2.2.0' && sed -i 's/ steps,/ steps.slice(0,1),/' /home/ubuntu/.npm-global/lib/node_modules/yarn/lib/cli.js && npm i -g lerna@3.22.1 && yarn install --ignore-scripts --ignore-engines --ignore-platform && lerna bootstrap --no-ci --ignore-scripts -- --ignore-scripts --ignore-engines --ignore-platform\"\nnpm ERR! code ETARGET\nnpm ERR! notarget No matching version found for yarn@>= 2.2.0.\nnpm ERR! notarget In most cases you or one of your dependencies are requesting\nnpm ERR! notarget a package version that doesn't exist.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /tmp/renovate-cache/others/npm/_logs/2020-11-14T10_25_13_983Z-debug.log\n",
    "stack": "Error: Command failed: docker run --rm --name=renovate_node --label=renovate_child -v \"/mnt/renovate/gh/christophehurpeau/nightingale\":\"/mnt/renovate/gh/christophehurpeau/nightingale\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -v \"/home/ubuntu/.npmrc\":\"/home/ubuntu/.npmrc\" -e NPM_CONFIG_CACHE -e npm_config_store -w \"/mnt/renovate/gh/christophehurpeau/nightingale\" docker.io/renovate/node:15.2.0 bash -l -c \"npm i -g yarn@'>= 2.2.0' && sed -i 's/ steps,/ steps.slice(0,1),/' /home/ubuntu/.npm-global/lib/node_modules/yarn/lib/cli.js && npm i -g lerna@3.22.1 && yarn install --ignore-scripts --ignore-engines --ignore-platform && lerna bootstrap --no-ci --ignore-scripts -- --ignore-scripts --ignore-engines --ignore-platform\"\nnpm ERR! code ETARGET\nnpm ERR! notarget No matching version found for yarn@>= 2.2.0.\nnpm ERR! notarget In most cases you or one of your dependencies are requesting\nnpm ERR! notarget a package version that doesn't exist.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /tmp/renovate-cache/others/npm/_logs/2020-11-14T10_25_13_983Z-debug.log\n\n    at ChildProcess.exithandler (child_process.js:303:12)\n    at ChildProcess.emit (events.js:311:20)\n    at ChildProcess.EventEmitter.emit (domain.js:482:12)\n    at maybeClose (internal/child_process.js:1021:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)"
  },
  "type": "lerna",
  "lernaClient": "yarn"
}
```

**To Reproduce**

**Additional context**

### PR DESCRIPTION
**Pull request by christophehurpeau**
fixes #7726

## Changes:

When useWorkspaces is true in lerna.json, don't use lerna-specific code.
It's today specific to yarn but as npm 7 also brings workspaces, I guess it should also work for that use case too

## Context:

This will fix support for lerna and yarn berry: See #7726

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added unit tests, or
- [ ] Unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
Can you create a reproduction repo to test against as well? e.g. using lerna and yarn 2 like was failing for you?

**Review by viceice — APPROVED** [review]

**Comment by christophehurpeau** [comment]
@rarkins where can I create it ? How can I test this PR on it ?

**Comment by rarkins** [comment]
@christophehurpeau when you have the source code locally, once you have run `yarn` to install dependencies you can then run `yarn start ...` and use a GitHub personal access token. e.g. like

```
yarn start --token=$GITHUB_TOKEN christophehurpeau/renovate-7726
```

**Comment by JamieMagee** [comment]
These changes look correct, but as said above, it would be great to see a sample PR.

> It's today specific to yarn but as npm 7 also brings workspaces, I guess it should also work for that use case too

I can't find any issues or discussion related to npm v7 support in the Lerna repo. If anything, the most recent discussions is around yarn v2 support (and whether or not Lerna is abandoned)

**Comment by christophehurpeau** [comment]
> These changes look correct, but as said above, it would be great to see a sample PR.
> 
> > It's today specific to yarn but as npm 7 also brings workspaces, I guess it should also work for that use case too
> 
> I can't find any issues or discussion related to npm v7 support in the Lerna repo. If anything, the most recent discussions is around yarn v2 support (and whether or not Lerna is abandoned)

There is some recent work on the [next branch of lerna](https://github.com/lerna/lerna/tree/next)



> @christophehurpeau when you have the source code locally, once you have run `yarn` to install dependencies you can then run `yarn start ...` and use a GitHub personal access token. e.g. like
> 
> ```
> yarn start --token=$GITHUB_TOKEN christophehurpeau/renovate-7726
> ```

Thank you, I will try that soon

**Review by rarkins — COMMENTED** [review]
I've done a code review and this definitely needs a reproduction repo for validation

**Comment by christophehurpeau** [comment]
Small update: I have not been able to test it due to personal reasons but I plan on doing that during this week. Sorry for the delay..

**Comment by christophehurpeau** [comment]
Hello, I can confirm it works, both for root and workspace packages, I tested it in https://github.com/reviewflow/lerna-test

**Comment by christophehurpeau** [comment]
Thank you !

**Pull request merged**
