### PR TITLE
refactor(bundler): add tests

### PR DESCRIPTION
**Pull request by RahulGautamSingh**
## Changes
- add tests to files in `/bundler` 
- replace es-lint comments is some files with non-null assertion operator (!)

## Context
- TODO to fix coverage after strcit-null tests was implemented

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by rarkins — COMMENTED** [review]
How come non-null assertions don't need to be ignored now too?

**Comment by RahulGautamSingh** [comment]
> How come non-null assertions don't need to be ignored now too?

Not sure maybe we changed linter settings as they didn't throw any error. I will submit another PR today that makes `currentVersion` in non-optional for some interfaces, then the non-null assertions introduced in this PR will be gone.

Do you want to re-add the settings that show error when non-null assertions are used?

**Comment by rarkins** [comment]
I would first like to understand why our linting no longer requires an ignore for the non-null assertions

**Comment by RahulGautamSingh** [comment]
> I would first like to understand why our linting no longer requires an ignore for the non-null assertions

@viceice would know the reason, it was set off in this PR, https://github.com/renovatebot/renovate/pull/15140

**Comment by viceice** [comment]
we probably disabled it to not need thousands of comments

**Comment by rarkins** [comment]
Should we bulk remove the ignores in a standalone PR?

**Review by viceice — APPROVED** [review]

**Pull request merged**
