### PR TITLE
test(typescript): Gradual migration to strict "null" and "any" checks

### PR DESCRIPTION
**Pull request by zharinov**
## Changes:

- Introduce `tsconfig.strict.json` TypeScript config
- Add strict testing for migrated files
- Automatically migrate files that don't require any changes
- Migrate `clone.ts`

## Context:

- Ref #7154

## More candidates:

- [x] `"./lib/types/errors/external-host-error.ts"` — Depended on by >**112** files (40 direct imports)
- [x] `"./test/graphql-snapshot.ts"` — Depended on by >**81** files (1 direct imports)
- [x] `"./lib/util/mask.ts"` — Depended on by >**36** files (4 direct imports)
- [ ] `"./lib/util/cache/package/decorator.ts"` — Depended on by >**27** files (23 direct imports)
- [ ] `"./lib/workers/repository/model/commit-message.ts"` — Depended on by >**17** files (4 direct imports)
- [ ] `"./lib/manager/gradle/shallow/common.ts"` — Depended on by >**11** files (7 direct imports)
- [ ] `"./lib/datasource/npm/types.ts"` — Depended on by >**7** files (3 direct imports)
- [ ] `"./lib/logger/types.ts"` — Depended on by >**7** files (5 direct imports)
- [ ] `"./lib/manager/homebrew/util.ts"` — Depended on by >**6** files (3 direct imports)
- [ ] `"./lib/util/fs/proxies.ts"` — Depended on by >**5** files (5 direct imports)
- [ ] `"./lib/util/json-writer/code-format.ts"` — Depended on by >**5** files (2 direct imports)
- [ ] `"./lib/versioning/ruby/operator.ts"` — Depended on by >**5** files (3 direct imports)
- [ ] `"./lib/datasource/maven/types.ts"` — Depended on by >**4** files (2 direct imports)
- [ ] `"./lib/datasource/helm/types.ts"` — Depended on by >**3** files (3 direct imports)
- [ ] `"./lib/datasource/jenkins-plugins/types.ts"` — Depended on by >**3** files (1 direct imports)
- [ ] `"./lib/manager/gradle/deep/__testutil__/gradle.ts"` — Depended on by >**3** files (3 direct imports)
- [ ] `"./lib/manager/pre-commit/parsing.ts"` — Depended on by >**3** files (1 direct imports)
- [ ] `"./lib/manager/npm/extract/type.ts"` — Depended on by >**2** files (2 direct imports)
- [ ] `"./lib/workers/global/config/parse/__fixtures__/argv.ts"` — Depended on by >**2** files (2 direct imports)
- [ ] `"./lib/datasource/common.ts"` — Depended on by >**1** files (1 direct imports)
- [ ] `"./lib/datasource/packagist/types.ts"` — Depended on by >**1** files (1 direct imports)
- [ ] `"./lib/versioning/node/schedule.ts"` — Depended on by >**1** files (1 direct imports)
- [ ] `"./lib/versioning/ruby/strategies/pin.ts"` — Depended on by >**1** files (1 direct imports)
- [ ] `"./jest.config.ts"` — Depended on by >**0** files (0 direct imports)
- [ ] `"./lib/constants/index.ts"` — Depended on by >**0** files (0 direct imports)
- [ ] `"./lib/manager/gradle/shallow/update.spec.ts"` — Depended on by >**0** files (0 direct imports)
- [ ] `"./lib/manager/metadata.spec.ts"` — Depended on by >**0** files (0 direct imports)
- [ ] `"./lib/manager/npm/update/package-version/index.spec.ts"` — Depended on by >**0** files (0 direct imports)
- [ ] `"./lib/proxy.spec.ts"` — Depended on by >**0** files (0 direct imports)
- [ ] `"./lib/types/index.ts"` — Depended on by >**0** files (0 direct imports)
- [ ] `"./lib/types/platform/github/index.ts"` — Depended on by >**0** files (0 direct imports)
- [ ] `"./lib/types/platform/gitlab/index.ts"` — Depended on by >**0** files (0 direct imports)
- [ ] `"./lib/util/cache/memory/index.spec.ts"` — Depended on by >**0** files (0 direct imports)
- [ ] `"./lib/util/cache/package/index.spec.ts"` — Depended on by >**0** files (0 direct imports)
- [ ] `"./lib/util/git/config.spec.ts"` — Depended on by >**0** files (0 direct imports)
- [ ] `"./lib/util/html.spec.ts"` — Depended on by >**0** files (0 direct imports)
- [ ] `"./lib/util/index.spec.ts"` — Depended on by >**0** files (0 direct imports)
- [ ] `"./lib/util/object.spec.ts"` — Depended on by >**0** files (0 direct imports)
- [ ] `"./lib/util/sanitize.spec.ts"` — Depended on by >**0** files (0 direct imports)
- [ ] `"./lib/util/split.spec.ts"` — Depended on by >**0** files (0 direct imports)
- [ ] `"./lib/versioning/cargo/index.spec.ts"` — Depended on by >**0** files (0 direct imports)
- [ ] `"./lib/versioning/composer/index.spec.ts"` — Depended on by >**0** files (0 direct imports)
- [ ] `"./lib/versioning/git/index.spec.ts"` — Depended on by >**0** files (0 direct imports)
- [ ] `"./lib/versioning/hashicorp/index.spec.ts"` — Depended on by >**0** files (0 direct imports)
- [ ] `"./lib/versioning/helm/index.spec.ts"` — Depended on by >**0** files (0 direct imports)
- [ ] `"./lib/versioning/hex/index.spec.ts"` — Depended on by >**0** files (0 direct imports)
- [ ] `"./lib/versioning/loose/index.spec.ts"` — Depended on by >**0** files (0 direct imports)
- [ ] `"./lib/versioning/maven/index.spec.ts"` — Depended on by >**0** files (0 direct imports)
- [ ] `"./lib/versioning/node/index.spec.ts"` — Depended on by >**0** files (0 direct imports)
- [ ] `"./lib/versioning/npm/index.spec.ts"` — Depended on by >**0** files (0 direct imports)
- [ ] `"./lib/versioning/nuget/index.spec.ts"` — Depended on by >**0** files (0 direct imports)
- [ ] `"./lib/versioning/pep440/index.spec.ts"` — Depended on by >**0** files (0 direct imports)
- [ ] `"./lib/versioning/poetry/index.spec.ts"` — Depended on by >**0** files (0 direct imports)
- [ ] `"./lib/versioning/regex/index.spec.ts"` — Depended on by >**0** files (0 direct imports)
- [ ] `"./lib/versioning/ruby/index.spec.ts"` — Depended on by >**0** files (0 direct imports)
- [ ] `"./lib/versioning/semver-coerced/index.spec.ts"` — Depended on by >**0** files (0 direct imports)
- [ ] `"./lib/versioning/semver/index.spec.ts"` — Depended on by >**0** files (0 direct imports)
- [ ] `"./lib/versioning/swift/index.spec.ts"` — Depended on by >**0** files (0 direct imports)
- [ ] `"./lib/versioning/ubuntu/index.spec.ts"` — Depended on by >**0** files (0 direct imports)
- [ ] `"./lib/versioning/versioning-metadata.spec.ts"` — Depended on by >**0** files (0 direct imports)

### CODE REVIEW

**Comment by rarkins** [comment]
Is the plan to add files incrementally over time until every file is covered, and then add the rule to our main rules and remove this special test?

**Comment by zharinov** [comment]
Helper scripts usage: 
1. Clone [this repo](https://github.com/zharinov/strict-null-check-migration-tools) locally (my fork from Figma with Qerko enhancements)
2. Remove `node_modules` from Renovate repo
3. Run one of 3 commands listed in README

**Comment by rarkins** [comment]
Let's add that to our contributing documentation then so that it doesn't get buried in a closed PR

**Comment by zharinov** [comment]
> Is the plan to add files incrementally over time until every file is covered, and then add the rule to our main rules and remove this special test?

Yes, this one is ready to be merged, and then we have to gradually migrate files and add them to the list.
Once most of the files are covered, we'll switch listing strategy from `files` to `exclude`, and some good day finally turn on strict checks and remove this TS config.

More on this approach: https://www.figma.com/blog/inside-figma-a-case-study-on-strict-null-checks/

**Comment by rarkins** [comment]
@JamieMagee @viceice WDYT?

**Review by viceice — APPROVED** [review]
I think if we know a folder is ready, we can use a more simple `include` entry to not to be forced to list every single file in that folder.

**Comment by JamieMagee** [comment]
This seems like a manageable number of files. Thanks @zharinov!

**Comment by zharinov** [comment]
> This seems like a manageable number of files.

I think there is actually more than this candidate list, but at least seems bearable once we have established migration procedure.

**Pull request merged**
