### PR TITLE
fix(config): Support local presets in bot admin config

### LINKED ISSUE #6034: Support local presets in bot admin config
**What would you like Renovate to be able to do?**
Use a self hosted (internal/private) shared presets to extend the Renovate `config.js`. eg:
```js
module.exports = {
    platform: 'gitlab',
    autodiscover: false,
    repositories: [
        'renovate-bot/renovate',
        ...
    ],
    requireConfig: false,
    onboarding: false,
    extends: ["local>renovate-bot/shared-config"]
};
```

**Describe the solution you'd like**
The ability to use a [Local Preset](https://docs.renovatebot.com/config-presets/#local-presets) within the initial Renovate `config.js` (as above)

**Describe alternatives you've considered**
Currently hosting the shared presets on public GitHub/GitLab is a workaround. eg:
```js
module.exports = {
    platform: 'gitlab',
    autodiscover: false,
    repositories: [
        'renovate-bot/renovate',
        ...
    ],
    requireConfig: false,
    onboarding: false,
    extends: ['github>Init7/renovate-shared-config']
};
```

Another alternative is to reference the local preset from a config present in each scanned repository. eg: in a `renovate.json`

```json
{
	"extends": ["local>renovate-bot/shared-config"]
}
```

**Additional context**
This issue was originally raised here: https://github.com/renovatebot/config-help/issues/609 and https://github.com/renovatebot/renovate/issues/3019

### PR DESCRIPTION
**Pull request by cleverer**
## Changes:

Pass inputConfig to initial shared-config resolution to allow for self hosted preset resolution, as suggested by @viceice in https://github.com/renovatebot/config-help/issues/609#issuecomment-614117536

## Context:

Closes #6034

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added unit tests, or
- [x] Unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — COMMENTED** [review]
This needs unit and real tests

**Comment by cleverer** [comment]
alright, I'll see what I can do!

**Comment by cleverer** [comment]
Added unit tests and ran on real repo on https://try.gitea.io/

One note to add: as far as I can see, presets have to be public (on any platform)? Did spend quite some time figuring out why it failed, only to realise the change worked all along.

**Comment by rarkins** [comment]
They'd need to be public if there's no hostRules set for them

**Comment by cleverer** [comment]
> They'd need to be public if there's no hostRules set for them

Ah that makes sense, however feels quite unintuitive as I'd expect the `local>` presets to just work, since we already have an auth token… anyway, this would probably warrant it's own issue to discuss.

**Comment by rarkins** [comment]
> Ah that makes sense, however feels quite unintuitive as I'd expect the `local>` presets to just work, since we already have an auth token… anyway, this would probably warrant it's own issue to discuss.

It's not really "by design", it's perhaps "due to oversight". If the presets are resolved *before* the platform token is converted into a host rule, then it would fail. I haven't looked closely to confirm that sequence of events though.

**Comment by cleverer** [comment]
> > Ah that makes sense, however feels quite unintuitive as I'd expect the `local>` presets to just work, since we already have an auth token… anyway, this would probably warrant it's own issue to discuss.
> 
> It's not really "by design", it's perhaps "due to oversight". If the presets are resolved _before_ the platform token is converted into a host rule, then it would fail. I haven't looked closely to confirm that sequence of events though.

Just tried it out, it doesn't work even with configured host rule. (`fetchJSONFile()` doesn't take any options, so the request never can be authenticated, no?)

Should I open a new issue?

**Comment by viceice** [comment]
> > > Ah that makes sense, however feels quite unintuitive as I'd expect the `local>` presets to just work, since we already have an auth token… anyway, this would probably warrant it's own issue to discuss.
> > 
> > 
> > It's not really "by design", it's perhaps "due to oversight". If the presets are resolved _before_ the platform token is converted into a host rule, then it would fail. I haven't looked closely to confirm that sequence of events though.
> 
> Just tried it out, it doesn't work even with configured host rule. ([`fetchJSONFile()`](https://github.com/renovatebot/renovate/blob/2e2b33092cad6255ae6e585047a999e2d92a7235/lib/config/presets/gitea/index.ts#L40) doesn't take any options, so the request never can be authenticated, no?)
> 
> Should I open a new issue?

No, I think we should defer resolving presets after platform init, that way the local presets should work as is.

**Comment by cleverer** [comment]
> > > > Ah that makes sense, however feels quite unintuitive as I'd expect the `local>` presets to just work, since we already have an auth token… anyway, this would probably warrant it's own issue to discuss.
> > > 
> > > 
> > > It's not really "by design", it's perhaps "due to oversight". If the presets are resolved _before_ the platform token is converted into a host rule, then it would fail. I haven't looked closely to confirm that sequence of events though.
> > 
> > 
> > Just tried it out, it doesn't work even with configured host rule. ([`fetchJSONFile()`](https://github.com/renovatebot/renovate/blob/2e2b33092cad6255ae6e585047a999e2d92a7235/lib/config/presets/gitea/index.ts#L12) doesn't take any options, so the request never can be authenticated, no?)
> > Should I open a new issue?
> 
> No, I think we should defer resolving presets after platform init, that way the local presets should work as is.

That would probably be out of scope for me for now, does the PR look good otherwise? Or do you consider that a requirement to be implemented here?

**Pull request merged**
