### PR TITLE
feat(platform): update pr baseBranch

### LINKED ISSUE #19900: update pr upon changing baseBranch
### What would you like Renovate to be able to do?

as a renovate user
in order to change the baseBranch without having to update myself the existing PRs targetting an old base branch
I need renovate to update existing PRs baseBranch when renovate baseBranch is changed

Workaround: update the PRs using the script below using [github cli](https://cli.github.com/)

```bash
#!/bin/bash

set -x
set -f # disable file name expansion, especially in for loops

FROM="feature-bumps-for-v55"
TARGET="feature-bumps"
LIMIT="300"

echo "Editing renovate PRs to change base branch from ${FROM} to ${TARGET}"

PRS=$(gh pr list \
  --limit ${LIMIT} \
  --app "renovate" \
  --base "${FROM}" \
  --json number \
  | jq -r '.[].number' )

echo "first PRs (maxed at ${LIMIT}} to edit are: ${PRS}"

for p in $PRS; do
  gh pr edit $p --base ${TARGET}
done;


echo "rereun this command to check not more PR beyond $LIMIT is left to process"
```

### If you have any ideas on how this should be implemented, please tell us here.

similar as current PR submissions

### Is this a feature you are interested in implementing yourself?

No

### PR DESCRIPTION
**Pull request by RahulGautamSingh**
## Changes
- update the destination/target branch of existing prs when the basebranch is updated

## Context
- Closes: https://github.com/renovatebot/renovate/issues/19900

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by RahulGautamSingh** [comment]
Missing the code-changes for `AWS CodeCommit`.

**Comment by setchy** [comment]
Nice one @RahulGautamSingh 👏

**Comment by RahulGautamSingh** [comment]
There seems to be a problem. 
The existingPRs won't get updated as baseBranch change doesn't come under title/body update so current logic doesn't detect a change & skips update.
For this we will need to comapre the PR's target branch with the current base branch

There are 2 ways to do this:
1. Use cached baseBranch
2. Use existing pr's targetBranch

With (2) I ran into an issue that the targetBranch (base.ref in case of github) isn't being fecthed. So I wanted to discuss if some code-change is necessary to get the target-branch when we fetch PR information using API.

I got this as PR info from Github
```log
{
  bodyStruct: {
    debugData: {
      createdInVer: '0.0.0-semantic-release',
      updatedInVer: '0.0.0-semantic-release'
    },
    hash: '596ef3415e2fa328b1473fe2f0fb633e63c39de8ba4db8810df72526adfb735e',
    rebaseRequested: false
  },
  createdAt: '2023-03-08T20:28:33Z',
  labels: [],
  node_id: 'PR_kwDOJGaIwM5Lmnld',
  number: 13,
  reviewers: [],
  sha: '23f17c06d283f7eeccf96851f7ab9b015950b0f1',
  sourceBranch: 'renovate/react-18.x',
  sourceRepo: 'RahulGautamSingh-testing/normalRepo',
  state: 'open',
  title: 'Update dependency react to v18',
  updated_at: '2023-03-08T20:28:33Z'
}
```

**Comment by RahulGautamSingh** [comment]
Example PR info , github:

I got this as PR info from Github
```log
{
  bodyStruct: {
    debugData: {
      createdInVer: '0.0.0-semantic-release',
      updatedInVer: '0.0.0-semantic-release'
    },
    hash: '596ef3415e2fa328b1473fe2f0fb633e63c39de8ba4db8810df72526adfb735e',
    rebaseRequested: false
  },
  createdAt: '2023-03-08T20:28:33Z',
  labels: [],
  node_id: 'PR_kwDOJGaIwM5Lmnld',
  number: 13,
  reviewers: [],
  sha: '23f17c06d283f7eeccf96851f7ab9b015950b0f1',
  sourceBranch: 'renovate/react-18.x',
  sourceRepo: 'RahulGautamSingh-testing/normalRepo',
  state: 'open',
  title: 'Update dependency react to v18',
  updated_at: '2023-03-08T20:28:33Z'
}
```

**Comment by rarkins** [comment]
"targetBranch" is an optional field in the `Pr` interface: https://github.com/renovatebot/renovate/blob/01a1af5d7aefabf1b9a5fb22259247550bf6a3aa/lib/modules/platform/types.ts#L75

**Comment by RahulGautamSingh** [comment]
I think we will need to make changes to the return object here and targetBranch to it.

**Comment by RahulGautamSingh** [comment]
But this will come true as previously `branchPr.targetBranch `was `undefined` and create issue for us...
https://github.com/renovatebot/renovate/blob/a3cc159f7e30120da72b60196f3f8d706d5d5709/lib/workers/repository/update/branch/index.ts#L201-L205

**Comment by rarkins** [comment]
Yes, the question is can we tell the difference between:
- Unchanged baseBranch, but the user changes target branch and wants us to leave it that way, versus
- Changed baseBranch, user wants us to change the target branch?

**Comment by RahulGautamSingh** [comment]
Blocked by https://github.com/renovatebot/renovate/pull/21026

**Comment by RahulGautamSingh** [comment]
Blocked till we figure out a way to check if the targetBranch was edited by user or it was changed in config.

**Review by viceice — COMMENTED** [review]
just remove from review list 😁

**Comment by RahulGautamSingh** [comment]
Blocked by: https://github.com/renovatebot/renovate/pull/21724

**Pull request closed without merging**
