### PR TITLE
feat: v20

### LINKED ISSUE #4426: v20 planning
Proposed changes:
- [x] Default unicodeEmoji=true
- [x] Drop embedded yarn v1.9.4
- [x] Drop Node v10
- [x] Remove embedded package managers (yarn, pnpm, npm)

### PR DESCRIPTION
**Pull request by rarkins**
Closes #4426

### CODE REVIEW

**Comment by ViceIce** [comment]
Again:
image

**Comment by viceice** [comment]
- [ ] workflow `Docker Images CI / Build image` now need to be required instead of seperate docker jobs.

**Comment by viceice** [comment]
full docker image test run succeeded on https://github.com/viceice/renovate-test.

duplicate master issue because the old was opened by the app

**Comment by rarkins** [comment]
One more possible idea:
- Remove `npm`, `yarn` and `pnpm` as `dependencies` from `renovate`
- Add them back as globally installed modules to the slim and full Dockerfile builds
- Document that people who npm install `renovate` for use on JS dependencies need to `npm install -g` their manager(s) before running `renovate`

The idea is to bring Renovate's JS support in line with other languages, i.e. we don't bundle third party package managers and reduce our `node_modules` size.

I would like to do this either in v20 or v21 if necessary.

**Comment by viceice** [comment]
we can add the package managers as peer deps, so users will see  at least warnings

**Review by viceice — DISMISSED** [review]
LGTM

**Review by viceice — APPROVED** [review]

**Comment by rarkins** [comment]
@viceice what do you think about replacing the embedded npm package managers with `npx` calls?

**Comment by rarkins** [comment]
Moving the checkboxes so we can populate the description:

- [x] Use unicode emoji by default
- [x] Drop embedded `yarn` v1.9.4
- [x] Drop Node 10 support
- [x] Remove embedded package managers (yarn, pnpm, npm)
- [x] Add node v14 support to `package.json`
- [x] Remove pr config validation

**Comment by viceice** [comment]
> @viceice what do you think about replacing the embedded npm package managers with `npx` calls?

good idea, should be easy to do now

**Pull request closed without merging**
