### PR TITLE
fix(manager): fix git-submodule null refs

### PR DESCRIPTION
**Pull request by viceice**
Try to fix git-submodule tests

### CODE REVIEW

**Comment by JamieMagee** [comment]
This seems like a great place to use the optional chaining operator. I didn't use it originally as babel didn't have support, but now it seems it does. We could get rid of a lot of the `|| ''` and instead do something like:

```ts
const path = (
    await Git().raw([
      'config',
      '--file',
      gitModulesPath,
      '--get',
      `submodule.${submoduleName}.url`,
    ])
  )?.trim();
```

**Comment by viceice** [comment]
@JamieMagee  Feel free to update this branch 🙃

**Review by JamieMagee — APPROVED** [review]

**Comment by JamieMagee** [comment]
@viceice You got there before me. Ready for merge?

**Comment by viceice** [comment]
ready

**Pull request merged**
