### PR TITLE
feat(terraform): remove versioning validation from manager

### LINKED ISSUE #7642: Avoid `SkipReason.UnsupportedVersion` use in managers
**What Renovate type, platform and version are you using?**

WhiteSource Renovate App

**Describe the bug**

The `terraform` manager classifies non-semver-compatible tags as unsupported, which means that regex versioning can't be applied using a package rule because the `skipReason` is already set.

We should not set skipReason for this in the `terraform` manager. Such logic should be removed and then the remaining logic re-validated to make sure we don't cause any problems.

**Relevant debug logs**

Example extracted dep with `skipReason` already set:

```
 "depIndex": 0,
 "skipReason": "unsupported-version",
 "lookupName": "githubuser/myrepo",
 "datasource": "github-tags",
 "currentValue": "tfmodule_one-v0.0.9",
 "depNameShort": "githubuser/myrepo",
 "depName": "github.com/githubuser/myrepo",
 "depType": "github"
```

**To Reproduce**

A terraform dependency with a source definition like the following:

```
source = "github.com/githubuser/myrepo//terraform/modules/moduleone?ref=tfmodule_one-v0.0.9"
```

**Additional context**

https://github.com/renovatebot/config-help/issues/965

### PR DESCRIPTION
**Pull request by secustor**
## Changes:

Removing all version validations from the Terraform manger.

## Context:

Closes #7642

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added unit tests, or
- [ ] Unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
Thank you @secustor for stepping in. FYI I think that such values will be caught here: https://github.com/renovatebot/renovate/blob/aaeeafa5d13111de9eb033c0c1dcfdb6e8118591/lib/workers/repository/process/lookup/index.ts#L143

**Comment by secustor** [comment]
Np. 
I have guessed something like that. 
When I reworked the Terraform manager I simply rearranged/streamlined the logic and haven't looked into if it is still necessary :)

**Review by viceice — APPROVED** [review]
anything missing here?

**Comment by secustor** [comment]
No, but I wanted to wait for the result of the merge tests.

**Pull request merged**
