### PR TITLE
refactor: remove unreachable code

### PR DESCRIPTION
**Pull request by RahulGautamSingh**
## Changes
- remove if-block from `shouldReuseExistingBranch` which is unreachable

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by RahulGautamSingh** [comment]
Reason:(https://github.com/renovatebot/renovate/blob/496e12f795acc78f913f358bde1b3abe783e1083/lib/workers/repository/update/branch/index.ts#L359-L371)

**Review by viceice — COMMENTED** [review]
is it catched on other place?

**Comment by RahulGautamSingh** [comment]
> is it catched on other place?

Yes my top comment shows where

**Review by rarkins — APPROVED** [review]

**Comment by rarkins** [comment]
Was it any problem to leave this in just in case other code changes in future?

**Comment by RahulGautamSingh** [comment]
> Was it any problem to leave this in just in case other code changes in future?

No.

**Comment by rarkins** [comment]
In this case I would prefer to keep the code as-is, so that it's more robust in case changes to logic are made elsewhere.

**Pull request closed without merging**
