### PR TITLE
fix: copy embedded yarn to tmp folder for proper .npmrc handling

### LINKED ISSUE #763: Private registry lookup failing for repo-hosted .npmrc
Raised by @dherges in https://github.com/singapore/renovate/pull/309/files#r136535783

### PR DESCRIPTION
**Pull request by dherges**
Resolves #763

### CODE REVIEW

**Comment by dherges** [comment]
Wundertüte on the way! Edited on GitHub web....  :open_mouth: :crossed_fingers:

**Comment by dherges** [comment]
It still errors. Don't get it why. These are `yarnOptions` passed to `.spawnSync()`:

```
[ '/tmp/tmp-20560kTXZXC7NPTop/yarn-0.27.5.js',
  'install',
  '--ignore-scripts' ]
```

```bash
DEBUG: Spawning yarn install to create /tmp/tmp-20560kTXZXC7NPTop/yarn.lock (repository=184, dependencies=bootstrap, branch=renovate/bootstrap-4.x)
DEBUG: yarn stdout:
        (repository=184, dependencies=bootstrap, branch=renovate/bootstrap-4.x)
DEBUG: yarn stderr:
       error An unexpected error occurred: "https://registry.yarnpkg.com/@internal%2internal: Not found".
        (repository=184, dependencies=bootstrap, branch=renovate/bootstrap-4.x)
 WARN: yarn install error (repository=184, dependencies=bootstrap, branch=renovate/bootstrap-4.x)
       "err": {
         "errno": -2,
         "code": "ENOENT",
         "syscall": "open",
         "path": "/tmp/tmp-20560kTXZXC7NPTop/yarn.lock"
       },
       "stdout": "",
       "stderr": "error An unexpected error occurred: \"https://registry.yarnpkg.com/@internal%2internal: Not found\".\n"
 INFO: Error updating branch (repository=184, dependencies=bootstrap, branch=renovate/bootstrap-4.x)
```

**Comment by rarkins** [comment]
That's really strange. Can you temporarily change it to run your system yarn binary and confirm that it picks up the npmrc ?

**Comment by dherges** [comment]
Yes, tried this fist. Try it again. Stil works.

```
$ pwd
/tmp/tmp-20743uo505eR1fSCc
$ yarn install
yarn install v0.27.5
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 112.06s.
```


---

Looking at how yarn resolves npmrc, they go looking in cwd first:

https://github.com/yarnpkg/yarn/blob/0ef3bf1f03d128e4793eca3fe3b5f93542451f15/src/registries/npm-registry.js#L172-L178

And then debugged in the embedded yarn-0.27.5.js: it gets correct cwd
```
_this2.cwd = /tmp/tmp-20743uo505eR1fSCc
```

in

```
  getPossibleConfigLocations(filename, reporter) {
    var _this2 = this;

    return (0, (_asyncToGenerator2 || _load_asyncToGenerator()).default)(function* () {
      const possibles = [[false, path.join(_this2.cwd, filename)], [true, _this2.config.userconfig || path.join(userHome, filename)], [false, path.join(getGlobalPrefix(), filename)]];
```


But then nevertheless  fails w/ above error.

**Comment by rarkins** [comment]
Actually I meant altering renovate spawnSync to run `yarn` instead of `node`. In case there's something about spawn that's causing problems regardless of whether yarn is embedded or not

**Comment by rarkins** [comment]
https://github.com/yarnpkg/yarn/issues/3612

Maybe when you run it manually it's picking up the registry from somewhere else.. somehow

**Comment by dherges** [comment]
Let's go at this further on Monday. Will try to figure out

Cheers, David

**Comment by dherges** [comment]
Need to check this on monday at the corporate place w/ private registry whether it works. Just drafted out some patch.

**Comment by rarkins** [comment]
I've found a way to reproduce this myself - add an `.npmrc` to a repo with `yarn.lock` and enable lock file maintenance with open schedule. That way it attempts to recreate the yarn.lock every run. I've set the npmrc to something that should exists so that if yarn uses the npmrc then it should fail to generate yarn.lock. Anyway, it still succeeds, because it keeps trying the public npm registry. This includes with your fix in this PR.

I also tried:
- Adding registry to `.yarnrc`
- Using system `yarn`

Neither solved it.

I've started adding `console.warn` statements to the embedded `yarn` to try to debug further. It does appear to detect the `.npmrc` in the `tmp` dir:

```
[ false,
  '/private/var/folders/jz/0qcn37lx1td4b47p56sh6v000000gn/T/tmp-31864jPLPHca92Z7U/.npmrc',
  'registry=https://npm.nothingthere.co\n' ]
```

Next is to dig into their `getRegistry` logic

**Comment by dherges** [comment]
This is silly. With above changes it produces an error:

```
error An unexpected error occurred: "https://registry.yarnpkg.com/@internal%2internal: Not found"
 WARN: yarn install error (repository=184, dependencies=bootstrap, branch=renovate/bootstrap-4.x)
       "err": {
         "error": null,
         "file": "/bin/sh",
         "args": [
           "/bin/sh",
           "-c",
           "/bin/sh -c /tmp/tmp-282776hDXPWkuFTMF/yarn-0.27.5.js install --ignore-scripts"
         ],
         "options": {
           "cwd": "/tmp/tmp-282776hDXPWkuFTMF",
           "shell": true,
           "env": {
             "LESSOPEN": "| /usr/bin/lesspipe %s",
             "USER": "username",
             "npm_config_user_agent": "yarn/0.27.5 npm/? node/v8.4.0 linux x64",
....
```

```bash
$ cd /tmp/tmp-282776hDXPWkuFTMF
$ ./yarn-0.27.5.js install
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 77.89s.
$ cat node_modules/@internal/internal/package.json
{
  "name": "@internal/internal",
  "version": "2.2.20",
...
```

**Comment by rarkins** [comment]
I'm about 80% sure it's some weird yarn problem with yarn and it's npmrc handling when run "the wrong way". About 50% hopeful we can fix it (eg changing from spawn to exec or plain shell)

**Comment by dherges** [comment]
Yes, but look for the latest changes. I switched to execFileSync but it still errors. When run from shell it works.

Cheers, David

**Comment by rarkins** [comment]
Weird. BTW ideally we revert back to running "node" because otherwise renovate will no longer work on Windows

**Comment by dherges** [comment]
@rarkins I opened a question / issue at yarn. Maybe they can help a little why it happens.

**Comment by rarkins** [comment]
Closing this as the base code has changed. We can continue discussing in the issue instead.

**Pull request closed without merging**
