### PR TITLE
fix(fs): permit square brackets `[]` in file paths

### LINKED ISSUE #21624: File paths rejected as invalid when using `[]`
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

File paths including square brackets `[]` get rejected by Renovate as `file-access-violation-error`. See logs below.

Minimal repro with the setup:

https://github.com/RobHannay/renovate-path-repro

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Preventing access to path with illegal characters
```

(the following log is redacted but the meaning is there)

```
{
  "path": "pages/foo/[id]/bar/package.json"
}
```

```
ERROR: Repository has unknown error
```

```
{
  "err": {
    "message": "file-access-violation-error",
    "stack": "Error: file-access-violation-error\n    at ensurePath (/home/ubuntu/renovateapp/node_modules/renovate/dist/util/fs/util.js:21:15)\n    at ensureLocalPath (/home/ubuntu/renovateapp/node_modules/renovate/dist/util/fs/util.js:29:12)\n    at readLocalFile (/home/ubuntu/renovateapp/node_modules/renovate/dist/util/fs/index.js:25:54)\n    at Object.extractAllPackageFiles (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/manager/npm/extract/index.js:452:54)\n    at async extractAllPackageFiles (/home/ubuntu/renovateapp/node_modules/renovate/dist/modules/manager/index.js:39:21)\n    at async getManagerPackageFiles (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/extract/manager-files.js:25:33)\n    at async /home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/extract/index.js:51:30\n    at async Promise.all (index 3)\n    at async extractAllDependencies (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/extract/index.js:49:28)\n    at async extract (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/extract-update.js:106:32)\n    at async extractDependencies (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/process/index.js:107:30)\n    at async Object.renovateRepository (/home/ubuntu/renovateapp/node_modules/renovate/dist/workers/repository/index.js:52:15)\n    at async renovateRepository (/home/ubuntu/renovateapp/app/worker/index.js:260:26)\n    at async /home/ubuntu/renovateapp/app/worker/index.js:454:5"
  }
}
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction in the description above

### PR DESCRIPTION
**Pull request by RobHannay**
## Changes

Allows square brackets `[]` in file paths, as they are used heavily in Next.js projects. See minimal repro on the issue.

Those characters are also not forbidden in the referenced article:

https://www.mtu.edu/umc/services/websites/writing/characters-avoid/

## Context

- Introduced in #21433
- Closes #21624
- Similar to #21476

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [X] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [X] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — APPROVED** [review]

**Comment by chopeen** [comment]
@RobHannay Thanks for providing this change! This will fix multiple issues with out installation of Renovate.

Can you please sign [Renovate CLA](https://cla-assistant.io/renovateapp/renovate) so that PR can be merged soon? It's a mandatory requirement explained in [contributing.md#legal](https://github.com/renovatebot/renovate/blob/main/.github/contributing.md#legal).

**Comment by RobHannay** [comment]
> @RobHannay Thanks for providing this change! This will fix multiple issues in our installation of Renovate.
> 
> Can you please sign [Renovate CLA](https://cla-assistant.io/renovateapp/renovate) so that PR can be merged soon? It's a mandatory requirement explained in [contributing.md#legal](https://github.com/renovatebot/renovate/blob/main/.github/contributing.md?rgh-link-date=2023-04-21T11%3A37%3A52Z#legal).

Hey @chopeen  :) I have signed it, so I'm not sure how to get the check to pass? 🤔

**Comment by chopeen** [comment]
Thanks @RobHannay! I guess we need to wait for the CI or the maintainers to sort it out then.

**Comment by RobHannay** [comment]
> Thanks @RobHannay! I guess we need to wait for the CI or the maintainers to sort it out then.

Updating with `main` seemed to kick it into shape 😅

**Review by rarkins — APPROVED** [review]

**Review by rarkins — APPROVED** [review]

**Pull request merged**
