### PR TITLE
chore: add explanatory message to lock bot action

### PR DESCRIPTION
**Pull request by HonkingGoose**
## Changes:

- Adds a message to the lock bot when it lock issues/PR's.

## Context:

I think if a bot takes some action we should explain why the bot is taking this action.
Unless this is clear enough from the bot name?

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] Unit tests + ran on a real repository

## References:

https://github.com/dessant/lock-threads/blob/master/README.md#commenting-and-labeling

### CODE REVIEW

**Comment by HonkingGoose** [comment]
I'm marking this as a draft until we're happy with the message, I just copy/pasted the example from the README for the lock bot.

**Comment by viceice** [comment]
yes, we can add it, but we are locking all old issues before to reduce noise.

**Comment by rarkins** [comment]
I would prefer no message at all, actually - it adds extra noise for everyone who was subscribed to the issue/PR

**Comment by HonkingGoose** [comment]
> 
> 
> I would prefer no message at all, actually - it adds extra noise for everyone who was subscribed to the issue/PR

Do we have an example of the name of the lock bot? If the name of the bot says what it's doing we don't need a message.

**Comment by viceice** [comment]
it's done by `github-actions` 🙃

**Comment by rarkins** [comment]
I'm not convinced we need to *explain* locking a PR/issue that's 30 days old

**Comment by HonkingGoose** [comment]
> github-actions bot locked as resolved and limited conversation to collaborators 2 minutes ago

The message is quite clear as to what's going on.

---

> 
> 
> I'm not convinced we need to _explain_ locking a PR/issue that's 30 days old

Agreed, closing this PR. 😉

**Pull request closed without merging**
