### PR TITLE
docs: improve matchCurrentVersion docs

### PR DESCRIPTION
**Pull request by HonkingGoose**
## Changes:

- `semver` -> `SemVer`
- Improve grammar
- Slight rewrite of some sentences for clarity

## Context:

Just fixing this up, I'm not closing a specific issue with this PR.

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by HonkingGoose** [comment]
The linting failure seems to be something that broke on `main` and not something that I'm doing wrong. 😄

**Review by viceice — APPROVED** [review]
Looks good, error comes from https://github.com/renovatebot/renovate/commit/f710c81b64db4f52bf76c2ff0e96a623dbb27cb0 😕

**Comment by HonkingGoose** [comment]
Seems @rarkins pushed a new commit that fixes the issue, so I'll merge that into this branch, so that we can verify my branch is actually ok. 😄

**Comment by HonkingGoose** [comment]
The linting run passes now, so we're good to merge if you like the changes in the PR.

**Pull request merged**
