### PR TITLE
feat: Support toml up to v1.0.0-rc.1

### LINKED ISSUE #18668: Renovate does not support latest TOML v1.0.0 spec.
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### If you're self-hosting Renovate, select which platform you are using.

_No response_

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Renovate does support the latest TOML v1.0.0 spec (which was released [Jan 2021](https://github.com/toml-lang/toml/releases/tag/1.0.0)).

This (potentially) impacts any modules that require parsing of TOML files.

I ran into this issue when renovate failed to realize my project's `pyproject.toml` file due to a parsing exception thrown when it tried to read a heterogeneous array, such as:
```toml
[tool.poetry]
## ...
 include = [ 
   "README.md", 
   { path = "tests", format = "sdist" } 
 ] 
```

Support for this was added to toml in [1.0.0-rc.1 / 2020-04-01](https://github.com/toml-lang/toml/blob/main/CHANGELOG.md#100-rc1--2020-04-01).

Poking around a bit, it appears renovate has a pinned dependency on [@iarna/toml @ v2.2.5](https://www.npmjs.com/package/@iarna/toml/v/toml-0.5) which only supports TOML v0.5.0 (2018-07-26).

I'll also add that the latest published version of [@iarna/toml](https://github.com/iarna/iarna-toml) only supports TOML v1.0.0-rc.1. It does not look as if the package owner has intentions to update the package based on the repository activity. 

I have created a minimal reproduction that you can find at [BradenM/renovate-toml-v1-repro](https://github.com/BradenM/renovate-toml-v1-repro).

It contains additional details as well as an actions [workflow that runs renovate to reproduce the issue](https://github.com/BradenM/renovate-toml-v1-repro/actions/runs/3358868498/jobs/5566325881#step:2:397).

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Matched 1 file(s) for manager poetry: pyproject.toml (repository=bradenm/renovate-toml-v1-repro)
DEBUG: Error parsing pyproject.toml file (repository=bradenm/renovate-toml-v1-repro)
       "err": {
         "name": "TomlError",
         "fromTOML": true,
         "wrapped": null,
         "line": 9,
         "col": 38,
         "pos": 271,
         "message": "Inline lists must be a single type, not a mix of string and inline-table at row 10, col 39, pos 271:\n 9:   \"README.md\",\n10>   { path = \"tests\", format = \"sdist\" }\n                                          ^\n11: ]\n\n",
         "stack": "TomlError: Inline lists must be a single type, not a mix of string and inline-table at row 10, col 39, pos 271:\n 9:   \"README.md\",\n10>   { path = \"tests\", format = \"sdist\" }\n                                          ^\n11: ]\n\n\n    at TOMLParser.recordInlineListValue (/usr/src/app/node_modules/@iarna/toml/lib/toml-parser.js:1305:28)\n    at TOMLParser.runOne (/usr/src/app/node_modules/@iarna/toml/lib/parser.js:64:30)\n    at TOMLParser.returnNow (/usr/src/app/node_modules/@iarna/toml/lib/parser.js:107:17)\n    at TOMLParser.recordValue (/usr/src/app/node_modules/@iarna/toml/lib/toml-parser.js:523:19)\n    at TOMLParser.runOne (/usr/src/app/node_modules/@iarna/toml/lib/parser.js:64:30)\n    at TOMLParser.parse (/usr/src/app/node_modules/@iarna/toml/lib/parser.js:45:22)\n    at parseString (/usr/src/app/node_modules/@iarna/toml/parse-string.js:13:12)\n    at Object.extractPackageFile (/usr/src/app/node_modules/renovate/lib/modules/manager/poetry/extract.ts:130:26)\n    at extractPackageFile (/usr/src/app/node_modules/renovate/lib/modules/manager/index.ts:70:9)\n    at getManagerPackageFiles (/usr/src/app/node_modules/renovate/lib/workers/repository/extract/manager-files.ts:52:43)\n    at /usr/src/app/node_modules/renovate/lib/workers/repository/extract/index.ts:47:28\n    at async Promise.all (index 2)\n    at extractAllDependencies (/usr/src/app/node_modules/renovate/lib/workers/repository/extract/index.ts:45:26)\n    at extract (/usr/src/app/node_modules/renovate/lib/workers/repository/process/extract-update.ts:100:20)\n    at extractDependencies (/usr/src/app/node_modules/renovate/lib/workers/repository/process/index.ts:110:26)\n    at Object.renovateRepository (/usr/src/app/node_modules/renovate/lib/workers/repository/index.ts:48:52)\n    at attributes.repository (/usr/src/app/node_modules/renovate/lib/workers/global/index.ts:173:11)\n    at Object.start (/usr/src/app/node_modules/renovate/lib/workers/global/index.ts:158:7)\n    at /usr/src/app/node_modules/renovate/lib/renovate.ts:17:22"
       }

```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

### PR DESCRIPTION
**Pull request by BradenM**
## Changes

- Add a test demonstrating failure to parse valid toml v1 spec.
- Pin @iarna/iarna-toml to latest v3.0.0

## Context

Closes #18668

As discussed in the issue above, there does not seem to be a readily available / well-tested TOML v1.0.0 compliant nodejs-based parser in the wild currently.

However, the current @iarna-toml parser's README states:
> 1.0.0-rc.1 parsers can load almost any TOML 0.4 and TOML 0.5 document, but TOML 1.0.0-rc.1 docs are not always compatible with TOML 0.4 and TOML 0.5 parsers. If you're using this to generate TOML documents and you want an older parser to be able to read them you may want to use the latest TOML 0.5 version of this module.

Considering I do not believe renovate uses this library to write out TOML (and if so, certainly nothing structurally different),
I thought it may just be a good idea to go ahead and utilize v3.0.0.

Especially since it appears that TOMLv1 rc.1 covers all structural changes that were introduced.

At minimum, this would widen the scope of what renovate can support until a better alternative can be sourced.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — CHANGES_REQUESTED** [review]
renovate should suggest this update

@rarkins we need to check why we don't get that old major update from renovate.

**Comment by rarkins** [comment]
image

**Comment by viceice** [comment]
do we've enabled followTag?

**Comment by rarkins** [comment]
Once we update to `3.0.0` we would end up with any stable-looking version which is released `>=3.0.0`

**Comment by viceice** [comment]
but i still don't know why the V3 update isn't visible on dashboard. 🤔

**Comment by rarkins** [comment]
Because of `respectLatest=true`

**Review by rarkins — APPROVED** [review]

**Review by viceice — APPROVED** [review]
our slim yarn seems to have issues with npm embedded dependencies 😕

**Pull request merged**
