### PR TITLE
feat: DroneCI

### LINKED ISSUE #3460: Add drone CI support
**What would you like Renovate to be able to do?**
RenovateBot should be able to update Drone CI configuration with new docker image tags.

**Describe the solution you'd like**
RenovateBot updates the `.drone.yml` file just like a `.travis.yml` file or `Dockerfile`

**Additional context**
The default Drone CI configuration is a yaml file set in `.drone.ci`. The code will most likely look a lot like the `travis` manager.

A `drone.yml` file looks like this and may have multiple pipelines:
```yaml
---

kind: pipeline
name: Test

steps:
  - name: mix
    image: elixir:1.8.1-alpine
    environment:
      DB_HOST: mysql
      REDIS_HOST: redis
    commands:
      - apk add --no-cache gcc g++ git imagemagick libc-dev libmcrypt-dev make
      - mix local.hex --force
      - mix local.rebar --force
      - mix deps.get
      - mix test

services:
  - name: mysql
    image: mysql:5.7.24
    ports:
      - 3306

  - name: redis
    image: redis:alpine
    ports:
      - 6379
```

### PR DESCRIPTION
**Pull request by nihalwasheretoo**
Added DroneCI to the list of renovate's dependency managers.

Closes #3460

### CODE REVIEW

**Comment by jones2026** [comment]
@rarkins see any issues with this PR? I know I'd really love to see this feature!

**Comment by CubicNitrous** [comment]
This would be huge for me as well @rarkins

**Comment by rarkins** [comment]
Any chance you could test out this PR firstly, or provide some example config files to test against?

**Comment by nihal9ns** [comment]
I think this is a good one to test against : 
```
kind: pipeline
name: Test

steps:
  - name: mix
    image: elixir:1.8.1-alpine
    environment:
      DB_HOST: mysql
    commands:
      - apk add --no-cache gcc g++ git imagemagick libc-dev libmcrypt-dev make
      - mix local.hex --force
      - mix local.rebar --force
      - mix deps.get
      - mix test

  - name: node
    image: amd64/node:10.0.0@sha256:36adc17e9cceab32179d3314da9cb9c737ffb11f0de4e688f407ad6d9ca32201
    commands:
      - npm install
      - npm test

services:
  - name: mysql
    image: mysql:5.7.24
    ports:
      - 3306

  - name: redis
    image: redis:alpine
    ports:
      - 6379
```

**Pull request merged**
