### PR TITLE
ci: Upgrade "codecov-action" to v4.1.0

### PR DESCRIPTION
**Pull request by zharinov**
## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
Is this normal? Seems quite elaborate

**Comment by zharinov** [comment]
To be rebased, it includes code from another PR

**Comment by zharinov** [comment]
Really weird stacktrace reason:

```
FileNotFoundError: [Errno 2] No such file or directory: 'lib/modules/datasource/golang-version/__fixtures__/releases-invalid.go'
```

**Comment by zharinov** [comment]
Seems like I've fixed it, and we could upgrade

**Review by viceice — APPROVED** [review]

**Pull request merged**
