### PR TITLE
fix(manager:dockerfile): wrong replace with trimmed images

### LINKED ISSUE #11464: Prefix (amd64) being removed from docker image in Dockerfile; amd64 arch not ready for pull
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Please select which platform you are using if self-hosting.

_No response_

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### Describe the bug

I had the same issue as #10662. The version was being bumped before the amd64 image was available to pull. I added the amd64/ prefix to the Docker image per the advice in the issue. This did indeed work for several months, however Renovate has recently began to remove the prefix as a part of the update commit causing my build to fail again.

I have created a minimal reproduction repository here: https://github.com/kotatsuclub/renovate-docker-prefix-strip-mrr

There is a Renovate PR open in this repo where the amd64 prefix is stripped from the ghost image in the Dockerfile during the version upgrade. 

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: 1 flattened updates found: ghost
DEBUG: Returning 1 branch(es)
DEBUG: config.repoIsOnboarded=true
DEBUG: packageFiles with updates
{
  "config": {
    "dockerfile": [
      {
        "packageFile": "Dockerfile",
        "deps": [
          {
            "depName": "ghost",
            "currentValue": "4.11.0-alpine",
            "replaceString": "amd64/ghost:4.11.0-alpine",
            "autoReplaceStringTemplate": "{{depName}}{{#if newValue}}:{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
            "datasource": "docker",
            "lookupName": "amd64/ghost",
            "depType": "final",
            "depIndex": 0,
            "updates": [
              {
                "bucket": "non-major",
                "newVersion": "4.12.1",
                "newValue": "4.12.1-alpine",
                "newMajor": 4,
                "newMinor": 12,
                "updateType": "minor",
                "branchName": "renovate/ghost-4.x"
              }
            ],
            "warnings": [],
            "versioning": "docker",
            "currentVersion": "4.11.0",
            "isSingleVersion": true,
            "fixedVersion": "4.11.0-alpine"
          }
        ]
      }
    ]
  }
}
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

### PR DESCRIPTION
**Pull request by viceice**
## Changes:

Override `autoReplaceStringTemplate` when removing special prefixes from `depName`

## Context:

fixes #11464

https://github.com/viceice-tests/docker-manifest-list/pull/14/files

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by rarkins — DISMISSED** [review]

**Comment by rarkins** [comment]
@viceice thanks for this fix. I think we'd be better afterwards to remove the depName/lookupName from the autoreplace string altogether though

**Comment by HonkingGoose** [comment]
@viceice Seems we have a snapshot mismatch maybe?

**Comment by viceice** [comment]
> @viceice thanks for this fix. I think we'd be better afterwards to remove the depName/lookupName from the autoreplace string altogether though

This would make the replace more fuzzy. Hopefully this don't hurt us later.

**Comment by rarkins** [comment]
> This would make the replace more fuzzy. Hopefully this don't hurt us later.

Yeah, it would take more than one attempt to autoreplace at times, but should still work. I'll think about it more.

**Review by rarkins — APPROVED** [review]

**Pull request merged**
