### PR TITLE
feat(git): blobless git

### LINKED ISSUE #11398: Replace shallow clones with blobless
### What would you like Renovate to be able to do?

Use a blobless git clone instead of shallow

### If you have any ideas on how this should be implemented, please tell us here.

See #7840

### Is this a feature you are interested in implementing yourself?

Yes

### PR DESCRIPTION
**Pull request by rarkins**
## Changes:

Uses blobless git cloning instead of shallow cloning.

## Context:

Closes #11398

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
Using this repo as an example, comparing shallow to blobless:

```
❯ time git clone https://github.com/renovatebot/renovate --depth=2
Cloning into 'renovate'...
remote: Enumerating objects: 2302, done.
remote: Counting objects: 100% (2302/2302), done.
remote: Compressing objects: 100% (1964/1964), done.
remote: Total 2302 (delta 281), reused 1007 (delta 158), pack-reused 0
Receiving objects: 100% (2302/2302), 5.32 MiB | 20.32 MiB/s, done.
Resolving deltas: 100% (281/281), done.
git clone https://github.com/renovatebot/renovate --depth=2  0.32s user 0.41s system 39% cpu 1.854 total

/tmp/git
❯ du -sh renovate
 42M    renovate
```

```
❯ time git clone https://github.com/renovatebot/renovate --filter=blob:none
Cloning into 'renovate'...
remote: Enumerating objects: 65735, done.
remote: Counting objects: 100% (315/315), done.
remote: Compressing objects: 100% (228/228), done.
remote: Total 65735 (delta 108), reused 171 (delta 77), pack-reused 65420
Receiving objects: 100% (65735/65735), 8.47 MiB | 17.38 MiB/s, done.
Resolving deltas: 100% (41332/41332), done.
remote: Enumerating objects: 1781, done.
remote: Counting objects: 100% (1225/1225), done.
remote: Compressing objects: 100% (1144/1144), done.
remote: Total 1781 (delta 194), reused 119 (delta 81), pack-reused 556
Receiving objects: 100% (1781/1781), 5.24 MiB | 5.42 MiB/s, done.
Resolving deltas: 100% (266/266), done.
Updating files: 100% (1811/1811), done.
git clone https://github.com/renovatebot/renovate --filter=blob:none  1.23s user 1.05s system 46% cpu 4.929 total

/tmp/git
❯ du -sh renovate                                                          
 53M    renovate
```

When I re-ran this multiple times I had shallow clone vary between 1.9 and 4.5s too, but I'll go with 1.9 for now (best case).

Time taken increased from 1.9s to 4.9s and disk increased from 42MB to 53MB.

On the scale of things, a 3s increase is not important for such a large repo, and nor is ~10MB. Also need to consider that the shallow approach requires ref syncing/fetching later which adds to the time.

**Review by viceice — COMMENTED** [review]
We should do some real runs to verify everything works as expected. otherwise LGTM

**Review by viceice — DISMISSED** [review]

**Comment by rarkins** [comment]
@viceice I think I'll wait until I update the app to v26 before merging this. Just one less thing..

**Review by viceice — COMMENTED** [review]
Can you update the devel docs, as this requires git v2.26 ? Not sure aabout the version. Otherwise LGTM

**Comment by rarkins** [comment]
Maybe I'll include this in the major release and say `git` `2.33.0` is required? It's hard to tell which "improvements" to e.g. sparse checkout will be necessary or not but I'd like to add it soon so asking for 2.32.0 or 2.33.0 seems like a good idea. https://github.blog/2021-08-16-highlights-from-git-2-33/

**Comment by viceice** [comment]
Yes, lets do it in major bump, as it's potentially breaking some self-hosted users.

**Review by HonkingGoose — APPROVED** [review]

**Review by viceice — COMMENTED** [review]
Should we bump node js to v14.17? We should also consider removing node v12 from engines?

**Review by viceice — APPROVED** [review]

**Comment by HonkingGoose** [comment]
> Should we bump node js to v14.17? We should also consider removing node v12 from engines?

If you want to do this it should go in a new PR so that it's captured in a changelog from the commit. 😉

**Comment by rarkins** [comment]
Let's leave the engines-next setting for now

**Pull request merged**
