### PR TITLE
fix: revert mergeRenovateConfig removal

### PR DESCRIPTION
**Pull request by rarkins**

### CODE REVIEW

**Review by viceice — APPROVED** [review]

**Comment by stefee** [comment]
@rarkins 
What issue does this PR aim to fix? We've just had some PRs open unexpectedly across a few of our projects, but maybe it's not worth us reporting the issue if this fix is in the works?

**Comment by rarkins** [comment]
@stefee yes, this fixes the unexpected PRs problem. The problem is over and repos should be cleaned up over the next 1-2 hours once the next run happens. I've spun up some extra workers to try to process the queue quickly. Sorry for the trouble

**Comment by stefee** [comment]
Thanks for the speedy response. FWIW, this hasn't caused any major issues for us.

**Comment by cesine** [comment]
The config missing caused hundreds of PRs and jobs on our CI/CD this morning. Thanks for finding and fixing 👍

**Pull request merged**
