### PR TITLE
feat(presets): add vitest monorepo

### PR DESCRIPTION
**Pull request by cjpearson**
## Changes

Add vitest monorepo to the preset

## Context

Vitest and supporting packages are developed in a monorepo and released together under the same version number

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — APPROVED** [review]

**Comment by simon-abbott** [comment]
Any word on when this will be merged and released?

**Comment by viceice** [comment]
you need to use the GitHub button to update the branch then it'll automerged

**Comment by viceice** [comment]
we don't have the permission to update your branch

**Comment by simon-abbott** [comment]
@cjpearson, could you do that please?

**Pull request merged**
