### PR TITLE
test: log jest heap usage

### PR DESCRIPTION
**Pull request by viceice**
## Changes:

Log jest heap usage, so we can see any changes in pr's / ci runs.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by rarkins — DISMISSED** [review]

**Comment by HonkingGoose** [comment]
The build https://github.com/renovatebot/renovate/pull/8838/checks?check_run_id=1969286562 has 2 fatal out of memory errors (line 253 and 295 in the Unit tests section), but the test suite still passes. The error message looks like this:
`FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`

Is this intended? It feels weird to me to have such a log entry, and still have a passing build/test.

**Comment by HonkingGoose** [comment]
@viceice Maybe turn off the auto-merge until you're done making changes?

**Comment by viceice** [comment]
I think we should accept  the oom crashed for now, as long as the coverage matches it's ok for me. trying to resolve the oom issues in another pr.

Maybe revert the `max-old-space-size`  or raise a litle bit?

**Comment by viceice** [comment]
closing in favor of #8905

**Pull request closed without merging**
