### PR TITLE
feat(presets): add mono repo shedlock

### LINKED ISSUE #18822: Add shedLock (https://github.com/lukas-krecan/ShedLock) to the grouped package
### What would you like Renovate to be able to do?

The ShedLock packages should have the same version. 

A preset in group for this case should be interesting. 

### If you have any ideas on how this should be implemented, please tell us here.

I will also propose a PR to add this preset (also in recommended)

### Is this a feature you are interested in implementing yourself?

Yes

### PR DESCRIPTION
**Pull request by boretti**
## Changes

Add shedLock (https://github.com/lukas-krecan/ShedLock) to the grouped package in default preset.

## Context

The shedLock java package should be grouped.
- closes https://github.com/renovatebot/renovate/issues/18822

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by boretti** [comment]
Related issues #18822

**Review by viceice — COMMENTED** [review]
can't we group with source url instead? like we do for other monorepos? checkout the monorepo.ts

that packages need to publish the source url inside the pom files.

**Comment by boretti** [comment]
Hello. I agree, it would be better to use the mono repo feature. I will update the MR.

**Comment by boretti** [comment]
The following configuration was tested on a self hosted renovate :

```json
"packageRules": [
      {
        "groupName": "shedlock monorepo",
        "matchSourceUrlPrefixes":["https://github.com/lukas-krecan/ShedLock"]
      }
]
```
 which should be similar to the one produced by the monorepo.js file

**Review by rarkins — APPROVED** [review]

**Pull request merged**
