### PR TITLE
fix(onboarding): use semantic commit for onboarding PR

### PR DESCRIPTION
**Pull request by bodinsamuel**
## Changes:

- Use semantic commit for onboarding PR

## Context:

PR created when onboarding renovate is not following the semantic standard, this can break some automatic CI and force to modify the PR. Not a huge blocker but increase a bit the frustration; much better if everything is green when you see the PR imo.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — CHANGES_REQUESTED** [review]
This is not the right fix for the issue. it shouldn't be `auto` at that phase. see:

https://github.com/renovatebot/renovate/blob/5cdedd5e2c18362dd703d6172a50fda9e20aa984/lib/workers/repository/init/config.ts#L14-L16

https://github.com/renovatebot/renovate/blob/854d0a86e8fbd83b047f77a0b6e8a79b213e63d4/lib/workers/repository/init/semantic.ts#L8-L26

So you need to debug why the `config.semanticCommits = 'auto'` is passed to the factory

**Comment by viceice** [comment]
I think the issue is here:
https://github.com/renovatebot/renovate/blob/31e1e4d89e3f6d88b4a912fe0584cbef603f87e1/lib/workers/repository/onboarding/branch/index.ts#L50-L54

I think the onboarding config will reset `semanticCommits` back to `auto`. 

so there needs to be a check:

```ts
if ( onboardingConfig.onboardingConfig== 'auto') {
  onboardingConfig.onboardingConfig = config.onboardingConfig;
}
```

@rarkins WDYT?

**Comment by bodinsamuel** [comment]
If there is a better fix, good to me ☺️

**Comment by viceice** [comment]
Looks like this should fix #11716

**Comment by viceice** [comment]
> If there is a better fix, good to me ☺️

I'm not sure if that will fix the issue, see #11716. It seems the detection is happening to late. So can you past your findings there?

**Comment by sfirmery** [comment]
Concerning #11716, I make it works on my dev env with:

```diff
lib/workers/repository/init/config.ts
@@ -9,10 +9,10 @@ export async function getRepoConfig(
 ): Promise<RenovateConfig> {
   let config = { ...config_ };
   config.baseBranch = config.defaultBranch;
-  config = await checkOnboardingBranch(config);
-  config = await mergeRenovateConfig(config);
   if (config.semanticCommits === 'auto') {
     config.semanticCommits = await detectSemanticCommits();
   }
+  config = await checkOnboardingBranch(config);
+  config = await mergeRenovateConfig(config);
   return config;
 }
```

**Comment by EndzeitBegins** [comment]
Would love to see this implemented. As of now we adjust the commit message of all onboarding commits, as we force every PR to follow our commit convention. I

**Pull request closed without merging**
