### PR TITLE
fix(util/markdown): Sanitize URLs of Markdown links containing spaces

### PR DESCRIPTION
**Pull request by timmkrause**
## Changes:

Sanitize URLs of Markdown links containing spaces by replacing them with `%20`.

## Context:

image

One remark: I've tried `regEx(/\(https?:\/\/[^)]*\)/g).exec(res)` but it didn't return me the expected 2 results (only 1).

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
Please force push with the committer email matching your GitHub account email

**Comment by timmkrause** [comment]
I messed it up...

**Comment by viceice** [comment]
You can simply force-push a new commit to fix it, no need for creasting a new pr

**Comment by timmkrause** [comment]
@viceice I didn't know how exactly this should be done. Then I started fiddling around with `--amend --reset-author`, that made it a little better, but this obviously didn't fix my initial commit and started tinkering with interactive rebase and stuff and nope... I messed that up. It was easier now to simply start all over. What would have been the right command/easy way?

**Pull request closed without merging**
