### PR TITLE
fix(dockerfile): improve FROM/COPY regex matching

### PR DESCRIPTION
**Pull request by casdevs**
## Changes:
* use global multiline regexes to also correctly handle multiline 
statements
* correcly handle comments between statement lines
* correctly handle additional statement options
* be more tolerant with whitespace

## Context:

The current Dockerfile extraction logic only supports the most common forms of FROM and COPY --from statements.
I've replaced the line-per-line regex extraction logic with more generic global regexes that
* support valid multiline statements
* are more tolerant with different whitespacing
* do not fail if other valid statement options are used
* do not fail if comment lines are used between statement lines

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added unit tests, or
- [ ] Unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — CHANGES_REQUESTED** [review]
While supporting multiline we should also support reading the `escape` char, which can be used to change ` \ ` to eg:  `` ` ``

```Dockerfile
# escape=`
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019 `
  as build
```

https://github.com/visualon/docker-images/blob/4b4ac482cdc150edc20f1c3cf6c25beb08a1d315/windows/2019/builder/Dockerfile#L1

**Comment by casdevs** [comment]
ok, I did not even know that one can change the escape char in Dockerfiles...
maybe this should go into a separate PR because it requires more complex code and building up regexes at runtime

**Comment by casdevs** [comment]
another long-term alternative would be to use an existing Dockerfile parser for JS like e.g. https://www.npmjs.com/package/docker-file-parser

**Comment by viceice** [comment]
I think instead of this pr it makes more sense to use [docker-file-parser](https://www.npmjs.com/package/docker-file-parser) now.

**Comment by casdevs** [comment]
IMHO it would be a pity to lose all the additional forms of FROM and COPY --from statements now correctly being detected with this PR. All existing and additional new test cases succeed.

Why not going with a 90% solution now (compared to having 50% before) and implement the perfect 100% solution later?

**Comment by casdevs** [comment]
I should have regarded using https://www.npmjs.com/package/docker-file-parser in the first place instead of wasting 1-2 hours of regex development ;-)
Seems that especially properly handling character escaping and quoting gets very nasty with regexes.
Maybe I find the time to have a look into https://www.npmjs.com/package/docker-file-parser later this week.

**Comment by casdevs** [comment]
@viceice by the way: is it possible to test a single test case in your project via `yarn test ...` or do we have to run all test suites everytime? I'm not that familiar with your testing framework...

**Comment by rarkins** [comment]
That lib has only 37 stars so is definitely not a slam-dunk decision.

**Comment by rarkins** [comment]
> @viceice by the way: is it possible to test a single test case in your project via `yarn test ...` or do we have to run all test suites everytime? I'm not that familiar with your testing framework...

You can run like `yarn jest lib/dockerfile/extract -t "somestring"` so that only tests matching `somestring` in their name inside a `lib/dockerfile/extract` file get run

**Comment by viceice** [comment]
> @viceice by the way: is it possible to test a single test case in your project via `yarn test ...` or do we have to run all test suites everytime? I'm not that familiar with your testing framework...

You can run `yarn test lib/manager/dockerfile` to limit by path. check https://jestjs.io/docs/en/cli for more cli args

**Comment by casdevs** [comment]
> That lib has only 37 stars so is definitely not a slam-dunk decision.

@rarkins: ok should I have a try with https://www.npmjs.com/package/docker-file-parser (at least it originates from joyent and seems to handle all special cases regarding quoting, comments, multiline etc.) or would you rather prefer to merge my PR and we do an extended research regarding potential Dockerfile parsing libs first?

**Comment by viceice** [comment]
> That lib has only 37 stars so is definitely not a slam-dunk decision.

It has 12-20T downloads a week. 🤔 Looks like it's heavily used.

**Comment by casdevs** [comment]
another alternative could be [rcjsuen/dockerfile-ast](https://github.com/rcjsuen/dockerfile-ast):
way more downloads (> 325,000 / week), MIT license and a decent feature set, but still in its v0.x version...

would [joyent/node-docker-file-parser's license](https://github.com/joyent/node-docker-file-parser/blob/master/LICENSE) even be compatible with your project?

**Comment by casdevs** [comment]
this decision is not easy to make, so I would still be grateful if you could merge in my PR in the meantime so a lot of additional Dockerfile syntax gets covered by renovate...

**Review by viceice — APPROVED** [review]
LGTM.

@casdevs I think processing other escape chars shoulndt't be very hard with regex. We simply need to dynamically construct the regex and add the escape char instead of hardcoding the `\`.  Creating regex from string can be done with regex costructor. 🙃

**Pull request merged**
