### PR TITLE
fix(gomod): Do not tidy go.mod on major update without gomodUpdateImportPaths

### LINKED ISSUE #11901: Go module major version update PR doesn't actually update version
### How are you running Renovate?

WhiteSource Renovate hosted app on github.com

### Please select which platform you are using if self-hosting.

_No response_

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### Describe the bug

PR `Update module github.com/google/go-github/v38 to v39` doesn't actually update module version to v39. I'm not very sure other modules cause same problem, but I observed the problem on `go-github` at several public and private repositories.

Major version update PR of `go-github` worked at least until August 11 with same config. (v37 to v38)
https://github.com/at-wat/gh-pr-comment/pull/148

Minimal reproductions below use single-line `require` but same problem happens on the repo using multi-line `require` as well.  (https://github.com/at-wat/gh-pr-comment/pull/153/files#r712618249)
And, it looks independent from Go version (tried 1.14, 1.16 and 1.17) specified in `go.mod`.

According to the attached logs:
- New version is correctly fetched
    ```
    DEBUG: packageFiles with updates
    {
      ...
                "updates": [
                  {
                    "bucket": "major",
                    "newVersion": "v39.1.0",
                    "newValue": "v39.1.0",
                    "releaseTimestamp": "2021-09-23T16:43:50.000Z",
                    "newMajor": 39,
                    "newMinor": 1,
                    "updateType": "major",
                    "branchName": "renovate/github.com-google-go-github-v38-39.x"
                  }
                ],
      ...
    }
    ```
- `go mod tidy` step downloads old version
    ```
    DEBUG: exec completed(branch="renovate/github.com-google-go-github-v38-39.x")
    {
      ...
      "stderr": "go: downloading github.com/google/go-github/v38 v38.1.0\n ... \n"
    }
    ```
- `go.mod` is updated by `go mod tidy` step
    ```
    DEBUG: Found updated go.mod after go.sum update(branch="renovate/github.com-google-go-github-v38-39.x")
    ```

I'm suspecting that `go mod tidy` step is reverting the version since the major version in the import paths on the source code is pointing the old version like:
```go
import "github.com/google/go-github/v38/github"
```

#### Minimal reproductions:
- Go mod version 1.16
    https://github.com/at-wat/renovate-repro-go-github-major-1.16/pull/2
- Go mod version 1.17
    https://github.com/at-wat/renovate-repro-go-github-major-1.17/pull/2

### Relevant debug logs

<details><summary>Logs</summary>

#### Go mod version 1.16 ([renovate log](https://app.renovatebot.com/dashboard#github/at-wat/renovate-repro-go-github-major-1.16/466768385))
```
DEBUG: packageFiles with updates
{
  "config": {
    "gomod": [
      {
        "packageFile": "go.mod",
        "constraints": {
          "go": "^1.16"
        },
        "deps": [
          {
            "managerData": {
              "lineNumber": 4
            },
            "depName": "github.com/google/go-github/v38",
            "depType": "require",
            "currentValue": "v38.1.0",
            "datasource": "go",
            "depIndex": 0,
            "updates": [
              {
                "bucket": "major",
                "newVersion": "v39.1.0",
                "newValue": "v39.1.0",
                "releaseTimestamp": "2021-09-23T16:43:50.000Z",
                "newMajor": 39,
                "newMinor": 1,
                "updateType": "major",
                "branchName": "renovate/github.com-google-go-github-v38-39.x"
              }
            ],
            "warnings": [],
            "versioning": "semver",
            "sourceUrl": "https://github.com/google/go-github",
            "currentVersion": "v38.1.0",
            "isSingleVersion": true,
            "fixedVersion": "v38.1.0"
          }
        ]
      }
    ]
  }
}
DEBUG: processRepo()
DEBUG: Processing 1 branch: renovate/github.com-google-go-github-v38-39.x
DEBUG: Calculating hourly PRs remaining
DEBUG: Retrieving PR list
DEBUG: Retrieved 1 Pull Requests
DEBUG: currentHourStart=2021-09-27T01:00:00.000+00:00
DEBUG: PR hourly limit remaining: 2
DEBUG: Calculating prConcurrentLimit (20)
DEBUG: getBranchPr(renovate/github.com-google-go-github-v38-39.x)
DEBUG: findPr(renovate/github.com-google-go-github-v38-39.x, undefined, open)
DEBUG: findPr(renovate/github.com-google-go-github-v38-39.x, undefined, closed)
DEBUG: 0 PRs are currently open
DEBUG: PR concurrent limit remaining: 20
DEBUG: Calculated maximum PRs remaining this run
{
  "prsRemaining": 2
}
DEBUG: PullRequests limit = 2
DEBUG: Calculating hourly PRs remaining
DEBUG: currentHourStart=2021-09-27T01:00:00.000+00:00
DEBUG: PR hourly limit remaining: 2
DEBUG: Calculating branchConcurrentLimit (20)
DEBUG: 0 already existing branches found:
DEBUG: Branch concurrent limit remaining: 20
DEBUG: Calculated maximum branches remaining this run
{
  "branchesRemaining": 2
}
DEBUG: Branches limit = 2
DEBUG: Setting current branch to master(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: latest commit(branch="renovate/github.com-google-go-github-v38-39.x")
{
  "branchName": "master",
  "latestCommitDate": "2021-09-27T10:21:47+09:00"
}
DEBUG: getBranchPr(renovate/github.com-google-go-github-v38-39.x)(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: findPr(renovate/github.com-google-go-github-v38-39.x, undefined, open)(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: findPr(renovate/github.com-google-go-github-v38-39.x, undefined, closed)(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: branchExists=false(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: dependencyDashboardCheck=undefined(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: recreateClosed is false(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: findPr(renovate/github.com-google-go-github-v38-39.x, Update module github.com/google/go-github/v38 to v39, !open)(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: prAlreadyExisted=false(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: Checking schedule(at any time, null)(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: No schedule defined(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: Branch needs creating(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: Using reuseExistingBranch: false(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: manager.getUpdatedPackageFiles() reuseExistinbranch=false(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: gomod.updateDependency: v39.1.0(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: gomod: major update(branch="renovate/github.com-google-go-github-v38-39.x")
{
  "depName": "github.com/google/go-github/v38"
}
DEBUG: Updating github.com/google/go-github/v38 in go.mod(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: gomod.updateArtifacts(go.mod)(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: go get command included(branch="renovate/github.com-google-go-github-v38-39.x")
{
  "cmd": "go",
  "args": "get -d ./..."
}
DEBUG: go mod tidy command included(branch="renovate/github.com-google-go-github-v38-39.x")
{
  "cmd": "go",
  "args": "mod tidy"
}
DEBUG: additional go mod tidy command included(branch="renovate/github.com-google-go-github-v38-39.x")
{
  "cmd": "go",
  "args": "mod tidy"
}
DEBUG: Using docker to execute(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: Found version constraint - checking for a compatible image to use(branch="renovate/github.com-google-go-github-v38-39.x")
{
  "depName": "docker.io/renovate/go",
  "scheme": "npm",
  "constraint": "^1.16"
}
DEBUG: getLabels(https://index.docker.io, renovate/go, latest)(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: Found compatible image version(branch="renovate/github.com-google-go-github-v38-39.x")
{
  "depName": "docker.io/renovate/go",
  "scheme": "npm",
  "constraint": "^1.16",
  "version": "1.17.1"
}
DEBUG: Resolved tag constraint(branch="renovate/github.com-google-go-github-v38-39.x")
{
  "image": "docker.io/renovate/go",
  "tagConstraint": "^1.16",
  "tagVersioning": "npm",
  "tag": "1.17.1"
}
DEBUG: Docker image is already prefetched: docker.io/renovate/go:1.17.1(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: Executing command(branch="renovate/github.com-google-go-github-v38-39.x")
{
  "command": [
    "docker run --rm --name=renovate_go --label=renovate_child -v \"/mnt/renovate/gh/at-wat/renovate-repro-go-github-major-1.16\":\"/mnt/renovate/gh/at-wat/renovate-repro-go-github-major-1.16\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e GOPATH -e GOFLAGS -e CGO_ENABLED -w \"/mnt/renovate/gh/at-wat/renovate-repro-go-github-major-1.16\" docker.io/renovate/go:1.17.1 bash -l -c \"git config --global url.\\\"https://**redacted**@github.com/\\\".insteadOf \\\"https://github.com/\\\" && go get -d ./... && go mod tidy && go mod tidy\""
  ]
}
DEBUG: exec completed(branch="renovate/github.com-google-go-github-v38-39.x")
{
  "cmd": "docker run --rm --name=renovate_go --label=renovate_child -v \"/mnt/renovate/gh/at-wat/renovate-repro-go-github-major-1.16\":\"/mnt/renovate/gh/at-wat/renovate-repro-go-github-major-1.16\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e GOPATH -e GOFLAGS -e CGO_ENABLED -w \"/mnt/renovate/gh/at-wat/renovate-repro-go-github-major-1.16\" docker.io/renovate/go:1.17.1 bash -l -c \"git config --global url.\\\"https://**redacted**@github.com/\\\".insteadOf \\\"https://github.com/\\\" && go get -d ./... && go mod tidy && go mod tidy\"",
  "durationMs": 4295,
  "stdout": "",
  "stderr": "go: downloading github.com/google/go-github/v38 v38.1.0\ngo: downloading github.com/google/go-github v17.0.0+incompatible\ngo: downloading github.com/google/go-querystring v1.1.0\ngo: downloading golang.org/x/crypto v0.0.0-20210817164053-32db794688a5\ngo get: added github.com/google/go-github/v38 v38.1.0\ngo: downloading github.com/google/go-cmp v0.5.6\n"
}
DEBUG: Returning updated go.sum(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: Found updated go.mod after go.sum update(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: Updated 1 package files(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: Updated 2 lock files(branch="renovate/github.com-google-go-github-v38-39.x")
{
  "updatedArtifacts": [
    "go.sum",
    "go.mod"
  ]
}
DEBUG: 2 file(s) to commit(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: Committing files to branch renovate/github.com-google-go-github-v38-39.x(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: Setting git author name(branch="renovate/github.com-google-go-github-v38-39.x")
{
  "gitAuthorName": "Renovate Bot"
}
DEBUG: Setting git author email(branch="renovate/github.com-google-go-github-v38-39.x")
{
  "gitAuthorEmail": "bot@renovateapp.com"
}
DEBUG: git commit(branch="renovate/github.com-google-go-github-v38-39.x")
{
  "deletedFiles": [],
  "ignoredFiles": [],
  "result": {
    "author": null,
    "branch": "renovate/github.com-google-go-github-v38-39.x",
    "commit": "4b71cff",
    "root": false,
    "summary": {
      "changes": 2,
      "insertions": 16,
      "deletions": 0
    }
  }
}
DEBUG: git push(branch="renovate/github.com-google-go-github-v38-39.x")
{
  "result": {
    "pushed": [
      {
        "deleted": false,
        "tag": false,
        "branch": true,
        "new": true,
        "alreadyUpdated": false,
        "local": "refs/heads/renovate/github.com-google-go-github-v38-39.x",
        "remote": "refs/heads/renovate/github.com-google-go-github-v38-39.x"
      }
    ],
    "branch": {
      "local": "renovate/github.com-google-go-github-v38-39.x",
      "remote": "renovate/github.com-google-go-github-v38-39.x",
      "remoteName": "origin"
    },
    "ref": {
      "local": "refs/remotes/origin/renovate/github.com-google-go-github-v38-39.x"
    },
    "remoteMessages": {
      "all": [
        "Create a pull request for 'renovate/github.com-google-go-github-v38-39.x' on GitHub by visiting:",
        "https://github.com/at-wat/renovate-repro-go-github-major-1.16/pull/new/renovate/github.com-google-go-github-v38-39.x"
      ],
      "pullRequestUrl": "https://github.com/at-wat/renovate-repro-go-github-major-1.16/pull/new/renovate/github.com-google-go-github-v38-39.x"
    }
  }
}
INFO: Branch created(branch="renovate/github.com-google-go-github-v38-39.x")
{
  "commitSha": "4b71cff"
}
DEBUG: Ensuring PR(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: There are 0 errors and 0 warnings(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: getBranchPr(renovate/github.com-google-go-github-v38-39.x)(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: findPr(renovate/github.com-google-go-github-v38-39.x, undefined, open)(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: findPr(renovate/github.com-google-go-github-v38-39.x, undefined, closed)(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: Creating PR(branch="renovate/github.com-google-go-github-v38-39.x")
{
  "prTitle": "Update module github.com/google/go-github/v38 to v39"
}
DEBUG: Creating PR(branch="renovate/github.com-google-go-github-v38-39.x")
{
  "title": "Update module github.com/google/go-github/v38 to v39",
  "head": "at-wat:renovate/github.com-google-go-github-v38-39.x",
  "base": "master",
  "draft": false
}
DEBUG: PR created(branch="renovate/github.com-google-go-github-v38-39.x")
{
  "pr": 2,
  "draft": false
}
DEBUG: Adding labels '' to #2(branch="renovate/github.com-google-go-github-v38-39.x")
INFO: PR created(branch="renovate/github.com-google-go-github-v38-39.x")
{
  "pr": 2,
  "prTitle": "Update module github.com/google/go-github/v38 to v39"
}
DEBUG: Created Pull Request #2(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: PR is not configured for automerge(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: getBranchPr(renovate/github.com-google-go-github-v38-39.x)
DEBUG: findPr(renovate/github.com-google-go-github-v38-39.x, undefined, open)
DEBUG: Found PR #2
DEBUG: Returning from graphql open PR list
DEBUG: Ensuring Dependency Dashboard
DEBUG: ensureIssue(Dependency Dashboard)
INFO: Issue created
DEBUG: Removing any stale branches
DEBUG: config.repoIsOnboarded=true
DEBUG: Branch lists
{
  "branchList": [
    "renovate/github.com-google-go-github-v38-39.x"
  ],
  "renovateBranches": [
    "renovate/github.com-google-go-github-v38-39.x"
  ]
}
```

#### Go mod version 1.17 ([renovate log](https://app.renovatebot.com/dashboard#github/at-wat/renovate-repro-go-github-major-1.17/466768345))
```
DEBUG: packageFiles with updates
{
  "config": {
    "gomod": [
      {
        "packageFile": "go.mod",
        "constraints": {
          "go": "^1.17"
        },
        "deps": [
          {
            "managerData": {
              "lineNumber": 4
            },
            "depName": "github.com/google/go-github/v38",
            "depType": "require",
            "currentValue": "v38.1.0",
            "datasource": "go",
            "depIndex": 0,
            "updates": [
              {
                "bucket": "major",
                "newVersion": "v39.1.0",
                "newValue": "v39.1.0",
                "releaseTimestamp": "2021-09-23T16:43:50.000Z",
                "newMajor": 39,
                "newMinor": 1,
                "updateType": "major",
                "branchName": "renovate/github.com-google-go-github-v38-39.x"
              }
            ],
            "warnings": [],
            "versioning": "semver",
            "sourceUrl": "https://github.com/google/go-github",
            "currentVersion": "v38.1.0",
            "isSingleVersion": true,
            "fixedVersion": "v38.1.0"
          }
        ]
      }
    ]
  }
}
DEBUG: processRepo()
DEBUG: Processing 1 branch: renovate/github.com-google-go-github-v38-39.x
DEBUG: Calculating hourly PRs remaining
DEBUG: Retrieving PR list
DEBUG: Retrieved 1 Pull Requests
DEBUG: currentHourStart=2021-09-27T02:00:00.000+00:00
DEBUG: PR hourly limit remaining: 2
DEBUG: Calculating prConcurrentLimit (20)
DEBUG: getBranchPr(renovate/github.com-google-go-github-v38-39.x)
DEBUG: findPr(renovate/github.com-google-go-github-v38-39.x, undefined, open)
DEBUG: findPr(renovate/github.com-google-go-github-v38-39.x, undefined, closed)
DEBUG: 0 PRs are currently open
DEBUG: PR concurrent limit remaining: 20
DEBUG: Calculated maximum PRs remaining this run
{
  "prsRemaining": 2
}
DEBUG: PullRequests limit = 2
DEBUG: Calculating hourly PRs remaining
DEBUG: currentHourStart=2021-09-27T02:00:00.000+00:00
DEBUG: PR hourly limit remaining: 2
DEBUG: Calculating branchConcurrentLimit (20)
DEBUG: 0 already existing branches found:
DEBUG: Branch concurrent limit remaining: 20
DEBUG: Calculated maximum branches remaining this run
{
  "branchesRemaining": 2
}
DEBUG: Branches limit = 2
DEBUG: Setting current branch to master(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: latest commit(branch="renovate/github.com-google-go-github-v38-39.x")
{
  "branchName": "master",
  "latestCommitDate": "2021-09-27T10:19:01+09:00"
}
DEBUG: getBranchPr(renovate/github.com-google-go-github-v38-39.x)(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: findPr(renovate/github.com-google-go-github-v38-39.x, undefined, open)(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: findPr(renovate/github.com-google-go-github-v38-39.x, undefined, closed)(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: branchExists=false(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: dependencyDashboardCheck=undefined(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: recreateClosed is false(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: findPr(renovate/github.com-google-go-github-v38-39.x, Update module github.com/google/go-github/v38 to v39, !open)(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: prAlreadyExisted=false(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: Checking schedule(at any time, null)(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: No schedule defined(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: Branch needs creating(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: Using reuseExistingBranch: false(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: manager.getUpdatedPackageFiles() reuseExistinbranch=false(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: gomod.updateDependency: v39.1.0(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: gomod: major update(branch="renovate/github.com-google-go-github-v38-39.x")
{
  "depName": "github.com/google/go-github/v38"
}
DEBUG: Updating github.com/google/go-github/v38 in go.mod(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: gomod.updateArtifacts(go.mod)(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: go get command included(branch="renovate/github.com-google-go-github-v38-39.x")
{
  "cmd": "go",
  "args": "get -d ./..."
}
DEBUG: go mod tidy command included(branch="renovate/github.com-google-go-github-v38-39.x")
{
  "cmd": "go",
  "args": "mod tidy"
}
DEBUG: additional go mod tidy command included(branch="renovate/github.com-google-go-github-v38-39.x")
{
  "cmd": "go",
  "args": "mod tidy"
}
DEBUG: Using docker to execute(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: Found version constraint - checking for a compatible image to use(branch="renovate/github.com-google-go-github-v38-39.x")
{
  "depName": "docker.io/renovate/go",
  "scheme": "npm",
  "constraint": "^1.17"
}
DEBUG: getLabels(https://index.docker.io, renovate/go, latest)(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: Found compatible image version(branch="renovate/github.com-google-go-github-v38-39.x")
{
  "depName": "docker.io/renovate/go",
  "scheme": "npm",
  "constraint": "^1.17",
  "version": "1.17.1"
}
DEBUG: Resolved tag constraint(branch="renovate/github.com-google-go-github-v38-39.x")
{
  "image": "docker.io/renovate/go",
  "tagConstraint": "^1.17",
  "tagVersioning": "npm",
  "tag": "1.17.1"
}
DEBUG: Fetching Docker image: docker.io/renovate/go:1.17.1(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: Finished fetching Docker image(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: Executing command(branch="renovate/github.com-google-go-github-v38-39.x")
{
  "command": [
    "docker run --rm --name=renovate_go --label=renovate_child -v \"/mnt/renovate/gh/at-wat/renovate-repro-go-github-major-1.17\":\"/mnt/renovate/gh/at-wat/renovate-repro-go-github-major-1.17\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e GOPATH -e GOFLAGS -e CGO_ENABLED -w \"/mnt/renovate/gh/at-wat/renovate-repro-go-github-major-1.17\" docker.io/renovate/go:1.17.1 bash -l -c \"git config --global url.\\\"https://**redacted**@github.com/\\\".insteadOf \\\"https://github.com/\\\" && go get -d ./... && go mod tidy && go mod tidy\""
  ]
}
DEBUG: exec completed(branch="renovate/github.com-google-go-github-v38-39.x")
{
  "cmd": "docker run --rm --name=renovate_go --label=renovate_child -v \"/mnt/renovate/gh/at-wat/renovate-repro-go-github-major-1.17\":\"/mnt/renovate/gh/at-wat/renovate-repro-go-github-major-1.17\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -e GOPATH -e GOFLAGS -e CGO_ENABLED -w \"/mnt/renovate/gh/at-wat/renovate-repro-go-github-major-1.17\" docker.io/renovate/go:1.17.1 bash -l -c \"git config --global url.\\\"https://**redacted**@github.com/\\\".insteadOf \\\"https://github.com/\\\" && go get -d ./... && go mod tidy && go mod tidy\"",
  "durationMs": 8438,
  "stdout": "",
  "stderr": "go: downloading github.com/google/go-github/v38 v38.1.0\ngo: downloading github.com/google/go-github v17.0.0+incompatible\ngo: downloading github.com/google/go-querystring v1.1.0\ngo: downloading golang.org/x/crypto v0.0.0-20210817164053-32db794688a5\ngo get: added github.com/google/go-github/v38 v38.1.0\ngo get: upgraded github.com/google/go-querystring v1.0.0 => v1.1.0\ngo get: upgraded golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2 => v0.0.0-20210817164053-32db794688a5\ngo: downloading github.com/google/go-cmp v0.5.6\n"
}
DEBUG: Returning updated go.sum(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: Found updated go.mod after go.sum update(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: Updated 1 package files(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: Updated 2 lock files(branch="renovate/github.com-google-go-github-v38-39.x")
{
  "updatedArtifacts": [
    "go.sum",
    "go.mod"
  ]
}
DEBUG: 2 file(s) to commit(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: Committing files to branch renovate/github.com-google-go-github-v38-39.x(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: Setting git author name(branch="renovate/github.com-google-go-github-v38-39.x")
{
  "gitAuthorName": "Renovate Bot"
}
DEBUG: Setting git author email(branch="renovate/github.com-google-go-github-v38-39.x")
{
  "gitAuthorEmail": "bot@renovateapp.com"
}
DEBUG: git commit(branch="renovate/github.com-google-go-github-v38-39.x")
{
  "deletedFiles": [],
  "ignoredFiles": [],
  "result": {
    "author": null,
    "branch": "renovate/github.com-google-go-github-v38-39.x",
    "commit": "4435deb",
    "root": false,
    "summary": {
      "changes": 2,
      "insertions": 13,
      "deletions": 0
    }
  }
}
DEBUG: git push(branch="renovate/github.com-google-go-github-v38-39.x")
{
  "result": {
    "pushed": [
      {
        "deleted": false,
        "tag": false,
        "branch": true,
        "new": true,
        "alreadyUpdated": false,
        "local": "refs/heads/renovate/github.com-google-go-github-v38-39.x",
        "remote": "refs/heads/renovate/github.com-google-go-github-v38-39.x"
      }
    ],
    "branch": {
      "local": "renovate/github.com-google-go-github-v38-39.x",
      "remote": "renovate/github.com-google-go-github-v38-39.x",
      "remoteName": "origin"
    },
    "ref": {
      "local": "refs/remotes/origin/renovate/github.com-google-go-github-v38-39.x"
    },
    "remoteMessages": {
      "all": [
        "Create a pull request for 'renovate/github.com-google-go-github-v38-39.x' on GitHub by visiting:",
        "https://github.com/at-wat/renovate-repro-go-github-major-1.17/pull/new/renovate/github.com-google-go-github-v38-39.x"
      ],
      "pullRequestUrl": "https://github.com/at-wat/renovate-repro-go-github-major-1.17/pull/new/renovate/github.com-google-go-github-v38-39.x"
    }
  }
}
INFO: Branch created(branch="renovate/github.com-google-go-github-v38-39.x")
{
  "commitSha": "4435deb"
}
DEBUG: Ensuring PR(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: There are 0 errors and 0 warnings(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: getBranchPr(renovate/github.com-google-go-github-v38-39.x)(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: findPr(renovate/github.com-google-go-github-v38-39.x, undefined, open)(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: findPr(renovate/github.com-google-go-github-v38-39.x, undefined, closed)(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: Creating PR(branch="renovate/github.com-google-go-github-v38-39.x")
{
  "prTitle": "Update module github.com/google/go-github/v38 to v39"
}
DEBUG: Creating PR(branch="renovate/github.com-google-go-github-v38-39.x")
{
  "title": "Update module github.com/google/go-github/v38 to v39",
  "head": "at-wat:renovate/github.com-google-go-github-v38-39.x",
  "base": "master",
  "draft": false
}
DEBUG: PR created(branch="renovate/github.com-google-go-github-v38-39.x")
{
  "pr": 2,
  "draft": false
}
DEBUG: Adding labels '' to #2(branch="renovate/github.com-google-go-github-v38-39.x")
INFO: PR created(branch="renovate/github.com-google-go-github-v38-39.x")
{
  "pr": 2,
  "prTitle": "Update module github.com/google/go-github/v38 to v39"
}
DEBUG: Created Pull Request #2(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: PR is not configured for automerge(branch="renovate/github.com-google-go-github-v38-39.x")
DEBUG: getBranchPr(renovate/github.com-google-go-github-v38-39.x)
DEBUG: findPr(renovate/github.com-google-go-github-v38-39.x, undefined, open)
DEBUG: Found PR #2
DEBUG: Returning from graphql open PR list
DEBUG: Ensuring Dependency Dashboard
DEBUG: ensureIssue(Dependency Dashboard)
INFO: Issue created
DEBUG: Removing any stale branches
DEBUG: config.repoIsOnboarded=true
DEBUG: Branch lists
{
  "branchList": [
    "renovate/github.com-google-go-github-v38-39.x"
  ],
  "renovateBranches": [
    "renovate/github.com-google-go-github-v38-39.x"
  ]
}
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

### PR DESCRIPTION
**Pull request by at-wat**
## Changes:

- Skip `go mod tidy` execution if it is a major update and `gomodUpdateImportPaths` is not specified.
- Don't force running `go mod tidy` for major updates without `gomodUpdateImportPaths`.

Otherwise, updated version in `go.mod` will be removed by `go mod tidy`.

## Context:

Closes #11901
Related: `gomodUpdateImportPaths` was introduced by https://github.com/renovatebot/renovate/pull/9144

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by at-wat** [comment]
oops, I accidentally post the PR during entering the title. I'll update the description soon.

**Comment by rarkins** [comment]
@56KBs can you take a look if you have time?

**Comment by 56KBs** [comment]
@at-wat could you clarify the intention of the MR? As far as I can tell the description & logic in this MR is different to the documentation.

In terms of the description from this MR the logic sounds reasonable - I just wanted to check that is the intention before looking at the code/docs further.

**Comment by at-wat** [comment]
@56KBs Intended logic is written in [the PR description](https://github.com/renovatebot/renovate/pull/11976#issue-1012852476).
I'm not a native English speaker and the text may sounds wrong. I would appreciate if anyone good at English could suggest changes to the document.

**Comment by 56KBs** [comment]
I have some reservations about the changes, specifically with this:
> Skip `go mod tidy` execution if it is a major update and `gomodUpdateImportPaths` is not specified.

I think that this makes the `gomodTidy` functionality more difficult to understand, especially when interacting with `gomodUpdateImportPaths`.

If users wanted to run `gomodTidy` for all but major updates and do not want to use `gomodUpdateImportPaths`, I believe this would be possible via configuration alone if we `gomodTidy` did not forcibly run on major updates:
```json
{
  "packageRules": [
    {
      "matchUpdateTypes": ["minor", "patch"],
      "matchManagers": ["gomod"],
      "gomod": {
        "postUpdateOptions": ["gomodTidy"]
      }
    }
  ]
}
```

> Don't force running go mod tidy for major updates without `gomodUpdateImportPaths`.

Going back through the reason for enabling this I can see it was enabled in #9144 as there was the consideration that in future `gomodTidy` would become a default option rather than just on major updates (In hindsight, flipping the logic so that it runs on non-major probably would have been better). I think it makes sense to remove this implicit enabling on major updates, if there is no plan to enable `gomodTidy` by default.

Hopefully that helps @rarkins

**Comment by at-wat** [comment]
> > Skip go mod tidy execution if it is a major update and gomodUpdateImportPaths is not specified.
>
> I think that this makes the gomodTidy functionality more difficult to understand, especially when interacting with gomodUpdateImportPaths.

Unless doing this, Renovate PR like `Update module package/v1 to v2` is created but doesn't update the package. (see [an example](https://github.com/at-wat/renovate-repro-go-github-major-1.17/pull/2/files))
In my opinion, this is just a broken behavior and should be avoided by the system.
I'll leave the decision to rarkins.

**Comment by rarkins** [comment]
One first question: should we always run `gomodUpdateImportPaths` or does it need to remain optional?

**Comment by at-wat** [comment]
In my use cases, `gomodUpdateImportPaths` can be always enabled, but I'm not 100% sure it can be globally always enabled.

**Review by rarkins — APPROVED** [review]

**Pull request merged**
