### PR TITLE
fix(yarn): enableImmutableInstalls=false

### PR DESCRIPTION
**Pull request by rarkins**
## Changes:

Disables immutable installs for Yarn

## Context:

https://github.com/renovatebot/renovate/discussions/9481

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — DISMISSED** [review]

**Comment by ylemkimon** [comment]
I was going to open the same pull request :smile: I think it can be put here only for `Yarn >= 2`:
https://github.com/renovatebot/renovate/blob/893df627e4fbec4f832885a25dcb7ed3a11449b3/lib/manager/npm/post-update/yarn.ts#L98-L103

**Comment by ylemkimon** [comment]
FYI I've tested https://github.com/ylemkimon/renovate/commit/95e95a0c96ed8377f863fa78656a99d051d9e45e on https://github.com/ylemkimon/yarn-3-renovate (Yarn 3.0.0-rc.2) and it seems to fix the issue, see https://github.com/ylemkimon/yarn-3-renovate/pull/6 compared to https://github.com/ylemkimon/yarn-3-renovate/pull/2.

**Comment by rarkins** [comment]
@ylemkimon thanks for the confirmation! What's strange is that the original poster is pretty sure he's using Yarn 2.4.0 while the functionality is documented as only starting in 3.0.0-rc. Anyway hopefully no harm setting it explicitly to false for >=2

**Review by viceice — APPROVED** [review]

**Comment by ylemkimon** [comment]
As mentioned in https://github.com/yarnpkg/berry/pull/2530#issuecomment-818086367, it was probably built from the source after it got landed but before the version was bumped.

**Pull request merged**
