### PR TITLE
fix(npm): use lower case %2f encoding

### LINKED ISSUE #15942: Proget npm packaged returns 404 because of url encoding
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

latest

### Please select which platform you are using if self-hosting.

Bitbucket Server

### If you're self-hosting Renovate, tell us what version of the platform you run.

7.21

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

When trying to resolve npm packages from Proget, some packages fails to resolve because the url encoding make using of a capital `F` when replacing the `/` instead of lowercase. 

### Relevant debug logs

<details><summary>Logs</summary>

```
"https://private.npm.host/npm/npm/@angular%2Fanimations (GET,404)": 1,
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

### PR DESCRIPTION
**Pull request by mieliespoor**
## Changes

fixes #15942. This changes the casing for url encoding for npm to lowercase. 

## Context

When resolving npm packages from Proget, Renovate url encodes the package name by replacing the `/` with `%2F`. This then results in a 404 being returned by proget. When changing this to `%2f` a 200 response is returned. 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — CHANGES_REQUESTED** [review]
needs to be tested against github and gitlab registries

also needs git author fix (use force push to update)

**Comment by mieliespoor** [comment]
> needs to be tested against github and gitlab registries

Unfortunately, I don't have access to such registries to help with the tests.

**Comment by viceice** [comment]
you can use the public gitlab.com and github.com

**Comment by rarkins** [comment]
What's a good way to discover public packages on those?

**Comment by viceice** [comment]
no longer needed, fixed in proget v6.0.16

- https://inedo.myjetbrains.com/youtrack/issue/PG-2147
- https://my.inedo.com/downloads/issues?product=ProGet&fromVersion=6.0.16&toVersion=6.0.16

**Pull request closed without merging**
