### PR TITLE
feat: Allow specifying Docker user

### PR DESCRIPTION
**Pull request by Dahlgren**
Adds support for using UID and GID other than the default 1000:1000 when binarySource=docker

### CODE REVIEW

**Comment by rarkins** [comment]
Can you add an example of using it in the docs?

**Comment by Dahlgren** [comment]
@rarkins added example value with description to dockerUser section in `self-hosted-configuration.md`

**Comment by rarkins** [comment]
Thanks @Dahlgren 

To fix the coverage, you can add `// istanbul ignore if` before each of your new clauses. I don't think we gain much by adding a test for every single one anyway.

**Comment by Dahlgren** [comment]
Added ignore to if statements. Had to split up the docker arguments for gradle to pass user argument before image otherwise it's interpreted as executable to run

**Pull request merged**
