### PR TITLE
chore: fix github PR reopen test

### LINKED ISSUE #21279: Find out why `modules/platform/github/index › getBranchPr(branchName) › aborts reopen if PR is too old` errors locally
### Describe the proposed change(s).

The Renovate maintainers get this error when running `yarn jest platform/github/index -t "aborts reopen"` against the `main` branch locally:

```
  ● modules/platform/github/index › getBranchPr(branchName) › aborts reopen if PR is too old

    Missing mocks!
     *   POST https://api.github.com/repos/some/repo/git/refs

      51 |   missingLog = [];
      52 |   if (missing.length && throwOnPending) {
    > 53 |     throw new Error(`Missing mocks!\n * ${missing.join('\n * ')}`);
         |           ^
      54 |   }
      55 |   if (!isDone && throwOnPending) {
      56 |     throw new Error(`Pending mocks!\n * ${pending.join('\n * ')}`);

      at clear (test/http-mock.ts:53:11)
      at Object.<anonymous> (test/http-mock.ts:120:3)
```

The tests also fail when you run Jest on the _whole file_. 

We should find out why this test/whole file test fails locally, but passes on our GitHub Actions runs.

### PR DESCRIPTION
**Pull request by rarkins**
## Context

Closes #21279

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
This fixes it for me locally, but let's see if GitHub Actions results complains about _unused_ mocks

**Comment by rarkins** [comment]
@viceice @secustor @zharinov any ideas?

**Comment by viceice** [comment]
i think one test before the changed one doe to much mocks, which flow through the changed one

**Comment by rarkins** [comment]
But somehow it's different for local vs Actions

**Comment by viceice** [comment]
maybe jest cache error?

**Comment by rarkins** [comment]
I deleted mine locally and still got test failures. Maybe Actions has a cache problem causing it to *pass*?

**Comment by secustor** [comment]
Strangely it started working for me again after rebasing my branch on main :/

**Pull request closed without merging**
