### PR TITLE
fix(cargo): Fix nested directories in artifacts.ts

### PR DESCRIPTION
**Pull request by zharinov**
Ref #5059

### CODE REVIEW

**Comment by zharinov** [comment]
Generated by this branch: https://github.com/zharinov/indy-sdk/pulls

**Comment by zharinov** [comment]
I'm afraid it updates too much deps inside lockfiles: https://github.com/zharinov/indy-sdk/pull/19/files.
Need to validate if that's fine.

**Comment by rarkins** [comment]
> I'm afraid it updates too much deps inside lockfiles: [zharinov/indy-sdk/pull/19/files](https://github.com/zharinov/indy-sdk/pull/19/files).
> Need to validate if that's fine.

If it fails to update the first time, then it essentially unlocks and updates all deps. This may be the reason

**Comment by zharinov** [comment]
We'll see with debugger soon

**Comment by zharinov** [comment]
Ready for review. PRs [from master](compressed_log_sink) and [from this branch](compressed_log_sink) look similar, while latter also opens [PRs for monorepos](https://github.com/zharinov/indy-sdk/pulls).

**Pull request merged**
