### PR TITLE
fix(auth): fix HTTP Basic auth for NOPASS indexes

### PR DESCRIPTION
**Pull request by TheKevJames**
## Changes:

Some package indexes (Gemfury, at least!) requires HTTP auth is performed with no password, eg. in the form of `https://${FURY_AUTH}:@pypi.fury.io/USERNAME/`. In this case, users should provide an empty password and we need to forward on only the username.

See comments below for more info!

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added unit tests, or
- [x] Unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
@TheKevJames I'd like to understand this one better.

It looks like:
- For every source URL *already* extracted in `pyproject.yaml`:
- Find a host rule for it
- Add the username:password into the URL itself

Is it that simple?

If so then I'm confused about why it's not *already* working. Those same credentials in hostRules should be getting added to requests using the `Authorization` header: https://github.com/renovatebot/renovate/blob/34350e9252c935f4588cbd9c40be898159d0afd7/lib/util/http/auth.ts#L42-L52

**Comment by rarkins** [comment]
We could also check if the password is not undefined and that way it can be an empty string ?

**Comment by TheKevJames** [comment]
@rarkins I imagine that could work! Will test it.

Note the issue I was running into is [here](https://github.com/renovatebot/renovate/blob/4eaa81ac5699a21061d31b67c72eb5df683d8a52/lib/util/http/host-rules.ts#L18-L21) -- `host-rules.ts`'s `applyHostRules()` doesn't actually pass the `username` forwards to our auth function unless the password is set. Will look into changing both of those to undefined checks.

**Comment by TheKevJames** [comment]
Yup, that did the trick, replacing both those `if (options.password)` checks with `if (options.password !== undefined)` and passing in the host rules with the explicit null password (eg. `--host-rules='[{"hostName":"my.gemfury.domain.com","username":"'"${GEMFURY_TOKEN}"'", "password":""}]'`). @rarkins would you be comfortable with that approach? Happy to update this PR accordingly.

**Review by rarkins — APPROVED** [review]

**Review by viceice — APPROVED** [review]

**Pull request merged**
