### PR TITLE
fix(datasource/nuget): ensure projectUrl is exposed

### LINKED ISSUE #4794: NuGet data source does not handle project URL correctly
**What Renovate type are you using?**

Self-hosted

**Describe the bug**

Renovate does not handle `ProjectUrl` property of NuGet packages correctly, and therefore fails to display links in MRs.

**To Reproduce**

* Reference an old version of a NuGet package that has its projectUrl set to some non-GitHub URL, e.g. https://www.nuget.org/packages/Newtonsoft.Json or https://git.example.org/foo
* Let Renovate create an upgrade MR
* Observe that the package is not linked

**Analysis**

https://github.com/renovatebot/renovate/blob/eefedfe81c03a7a35afb104cd9e5056a4d9e62dd/lib/datasource/nuget/v2.ts#L39

where `parse` comes from 

https://github.com/renovatebot/renovate/blob/eefedfe81c03a7a35afb104cd9e5056a4d9e62dd/lib/datasource/nuget/v2.ts#L1

which expects a git repository URL and tries to transform it to the GitHub project page.

This is a wrong assumption because `projectUrl` might point to anything(see https://docs.microsoft.com/en-us/nuget/reference/nuspec#projecturl).

### PR DESCRIPTION
**Pull request by fgreinacher**
Closes #4794

### CODE REVIEW

**Comment by fgreinacher** [comment]
Test failures seem to be unrelated to my changes?!

**Comment by fgreinacher** [comment]
@rarkins This is a minimal fix for the linked issue. Feel free to close if it interferes with the refactoring you mentioned in the issue.

**Comment by rarkins** [comment]
@fgreinacher what do you think of this?

1. If the projectUrl satisfies our `parse`, then set the result as `sourceUrl` in the response.
2. If it doesn't, then set it as `homepage`

This way you should end up with a link in the PR no matter what.

**Comment by fgreinacher** [comment]
That sounds reasonable, although it’s still a bit weird to interpret only GitHub URLs as “sources”. What if we have an URL pointing to GitLab.com or self-hosted systems?

**Comment by rarkins** [comment]
But does projectUrl in the NuGet sense specifically mean the location of the source? If so then we can probably pass it through regardless. But if it could also be the projects home page then we are better to default to homepage than to sourceUrl.

**Comment by fgreinacher** [comment]
Unfortunately it can mean both 😐 NuGet does not differentiate between homepage and repository like e.g. NPM. Most packages have their GitHub/GitLab project URL in there

**Comment by rarkins** [comment]
So in that case, I think my suggestion makes sense. Unless we know it's a source URL, we mark it as homepage. Both get linked anyway. What we're working on with the refactor is to recognise GitLab and Bitbucket sources too, including self-hosted.

**Comment by fgreinacher** [comment]
Alright, sounds like a plan!

**Comment by fgreinacher** [comment]
All done

**Comment by fgreinacher** [comment]
Friendly ping 👀🙃

**Comment by fgreinacher** [comment]
@rarkins the image on Docker Hub is still at 19.66.9. could you check what’s wrong here?

**Comment by rarkins** [comment]
It seems Docker Hub didn't get the webhook for the latest release. There should be another release today and hopefully that will trigger the new build

**Comment by fgreinacher** [comment]
Great, this one worked! Thanks!

**Pull request merged**
