### PR TITLE
docs: list allowed values for matchStringsStrategy

### LINKED ISSUE #8880: scheme: matchStringsStrategy should contain enum
**What Renovate type, platform and version are you using?**

GitLab

**Describe the bug**

Current scheme (some properties dropped):
```json
"regexManagers": {
  "description": "Custom managers using regex matching.",
  "type": "array",
  "items": {
    "allOf": [
      {
        "type": "object",
        "properties": {
          "matchStringsStrategy": {
            "description": "Strategy how to interpret matchStrings.",
            "type": "string",
            "default": "any"
          }
        }
      }
    ]
  },
  "default": []
},
```

According to docs `matchStringsStrategy` can be `any`, `recursive`, `combination`.
So the property should contain `"enum": ["any", "recursive", "combination"]`.
The same with docs. There must be `allowedValues` like in https://docs.renovatebot.com/configuration-options/#rebasewhen.

**Relevant debug logs**

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [x] This is a really small bug, it does not need a reproduction (think small typo)
- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

Hand crafted scheme
```json
"regexManagers": {
  "description": "Custom managers using regex matching.",
  "type": "array",
  "items": {
    "allOf": [
      {
        "type": "object",
        "properties": {
          "matchStringsStrategy": {
            "description": "Strategy how to interpret matchStrings.",
            "type": "string",
            "enum": ["any", "recursive", "combination"],
            "default": "any"
          }
        }
      }
    ]
  },
  "default": []
},
```

### PR DESCRIPTION
**Pull request by HonkingGoose**
## Changes:

- List `allowedValues` in array for `matchStringsStrategy` object

## Context:

Closes #8880.

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — APPROVED** [review]
https://github.com/renovatebot/renovate/blob/6b494027b695f7931bd9289e803c2858c0d86307/lib/config/common.ts#L216

**Comment by HonkingGoose** [comment]
@viceice Are we good to merge this PR? If so, please mark it "ready for review".

**Comment by viceice** [comment]
Can't do it from mobile app. 😁

**Comment by HonkingGoose** [comment]
I've marked it ready for review. 😄

**Pull request merged**
