### PR TITLE
feat(gomod): support .git repository indicators on gitlab

### PR DESCRIPTION
**Pull request by bastianccm**
## Changes:

Allow go modules to indicate the repository using a `.git` suffix on private gitlab installations.

## Context:

Following up on #10218 this improves the situation with self-hosted go modules on private gitlab server. (I am not yet sure if this PR resolves this issue, but certainly it should help for people facing similar situations).

Gitlab does not provide proper go mod information to not reveal the existence of private repositories: https://gitlab.com/gitlab-org/gitlab/-/issues/3635

For Go, a possible workaround is to specify `.git` as a suffix to the existing repository path, to indicate the actual git repository: https://pkg.go.dev/cmd/go#hdr-Remote_import_paths

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by bastianccm** [comment]
As I now added support for getDigest on gitlab, should we split this into two PR's?

**Review by viceice — COMMENTED** [review]
Yes, please split in two PR's

**Comment by bastianccm** [comment]
I forced pushed this one back to your merge. Gitlab getDigest is split into #13361

**Comment by bastianccm** [comment]
Verified against an actual project with the newest Gitlab getDigest changes.

**Review by viceice — APPROVED** [review]

**Pull request merged**
