### PR TITLE
fix(regex): limit regex manager iterations to 10k to avoid OoM

### LINKED ISSUE #22083: Lazy matchStrings regex can cause out of memory crash
### How are you running Renovate?

Self-hosted Renovate

### If you're self-hosting Renovate, tell us what version of Renovate you run.

source

### If you're self-hosting Renovate, select which platform you are using.

github.com

### Was this something which used to work for you, and then stopped?

I am trying to get this working for the first time

### Describe the bug

This causes the problem: https://github.com/rarkins/sha_renovate/blob/505a1639c36daa398e09937f72432939d2740e0d/renovate.json#L9

Replacing it with `"^(?<currentDigest>.*?)(\n|$)"` works

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Matched 1 file(s) for manager regex: .sha.txt (repository=rarkins/sha_renovate)

<--- Last few GCs --->

[9672:0x128078000]    46270 ms: Mark-sweep 4037.6 (4130.8) -> 4034.0 (4129.8) MB, 2649.0 / 0.0 ms  (average mu = 0.318, current mu = 0.117) allocation failure; scavenge might not succeed
[9672:0x128078000]    51007 ms: Mark-sweep 4049.8 (4129.8) -> 4045.5 (4154.8) MB, 4674.1 / 0.0 ms  (average mu = 0.145, current mu = 0.013) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction in the description above

### PR DESCRIPTION
**Pull request by rarkins**
## Changes

Limits matchStrings matching to 10k to reduce change of hanging/crashing. The test completes in 16ms for me locally.

## Context

Fixes #22083

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by secustor — CHANGES_REQUESTED** [review]
We should document and log this behaviour.

**Comment by rarkins** [comment]
Do we document to anything like that detail today? I'm not sure where to add it where it makes sense

**Comment by secustor** [comment]
I would put a warning in the regex manager docs.

**Review by viceice — DISMISSED** [review]

**Comment by viceice** [comment]
> I would put a warning in the regex manager docs.
> 
> We document limitations as I'm aware.
> 
> @HonkingGoose Thoughts?

It's not only a regex manager limitation, it's an re2 bug. see my comment on the issue. I would open a bug on re2.

**Comment by secustor** [comment]
I agree we should open an issue on RE2, but with PR we are introducing a limitation and this should be documented or at least logged that that is happening.

**Comment by rarkins** [comment]
I'll go with a warn

**Review by secustor — APPROVED** [review]

**Review by HonkingGoose — CHANGES_REQUESTED** [review]
> I would put a warning in the regex manager docs.

We should add a warning to the `regexManager` config option docs. 

And _maybe_ explain it in our "Known Limitations" page as well?

**Review by viceice — APPROVED** [review]

**Pull request merged**
