### PR TITLE
docs(homepage): convert Markdown list to plain HTML list

### PR DESCRIPTION
**Pull request by HonkingGoose**
## Changes

- Convert Markdown list to plain HTML list

## Context

Helps with #29148, but does not close it.

I recently added a Markdown list to the homepage wrapped in a `<details>` tag, that lists the companies and projects that use Renovate. The goal is for screenreader users to expand the `<details>` element and then "have the screenreader read the list". With a proper list you can step through the list items, and go backwards and forwards in the list. Here's the PR that added this change:

- #29345

The changes from the PR above are now live on the published docs, and the `<details>` admonition expands into a long string: `- Prisma - Netlify - Envoy - Condé Nast - Microsoft - Atlassian - Sourcegraph - Mozilla - Deloitte - Telus - Yarn - HashiCorp - Automattic - Algolia - eBay - Cypress - Red Hat - Financial Times - Uber - Buildkite`. It should be a proper list! :melting_face: 

Renovate homepage, shows expanded admonition with badly formatted list

Maybe this problem is caused by my Markdown formatting? Or maybe I should force the correct rendering with `<ul`> and `<li`> HTML elements.

I'll try plain HTML elements first, to see if MkDocs and Material for MkDocs can render this properly.

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by rarkins — APPROVED** [review]

**Comment by viceice** [comment]
I'll try to check the root cause the next days. not enough time now. sorry.

**Comment by rarkins** [comment]
Shall we merge though?

**Comment by HonkingGoose** [comment]
I think we're safe to merge, as plain HTML elements _should_ work, fingers crossed.

If plain HTML elements _still_ render badly, we'll have to dive deeper for sure.

I look forward to your analysis later @viceice! :heart:

**Comment by HonkingGoose** [comment]
The plain HTML list works well on the published docs. 🥳

I guess we need to use a specific number of spaces, or tabs, or other formatting for a _Markdown_-based list to work. We likely will need to tell Prettier to stay away from the custom formatting in the collapsible admonition.

I'll let `@viceice` figure out the correct Markdown, or root cause for why it does _not_ work in Markdown. 🙂

**Pull request merged**
