### PR TITLE
feat(github): update pr baseBranch

### LINKED ISSUE #44: Prevent renovate from ever merging PRs
### Bug Report

In service manager repo renovate opened lockfile maintenance PR against default branch that was 3.21.x at the time. Since then default branch changed to 4.0.x and CI issues were fixed in that branch. On the next lockfile maintenance attempt renovate force pushed updates from the new default branch 4.0.x and since CI passed it auto-merged the PR that was still opened against old default branch 3.21.x.
See https://github.com/laminas/laminas-servicemanager/issues/197 and the renovate PR in question https://github.com/laminas/laminas-servicemanager/pull/185

This exposed flawed behavior that can have serious consequences while we are unaware.

As such auto-merging of pull requests must be entirely disabled in renovate config. That will not affect the lockfile maintenance flow of automerging branch without creating the PR.

### PR DESCRIPTION
**Pull request by RahulGautamSingh**
## Changes
- update base of an existing update PR when `baseBranch` is changed in config

## Context
- Part of: https://github.com/renovatebot/renovate/issues/19900
- Resolves: https://github.com/laminas/.github/issues/44

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by RahulGautamSingh** [comment]
Reproduction: 
https://github.com/RahulGautamSingh-testing/update-base-branch/pull/3

**Review by viceice — COMMENTED** [review]
we need to save the original base branch inside cache or body struct, so we can detect a manual changed PR target by users and don't overwite it.

we also need to open follow up PR's for other platforms.

**Comment by RahulGautamSingh** [comment]
> we need to save the original base branch inside cache or body struct, so we can detect a manual changed PR target by users and don't overwite it.
 Already done here: https://github.com/renovatebot/renovate/pull/21724
> we also need to open follow up PR's for other platforms.
Working on it.

**Review by rarkins — CHANGES_REQUESTED** [review]
The basic use case works as expected, however the logs are misleading:

```
DEBUG: Processing existing PR (repository=renovate-reproductions/22663, branch=renovate/node-18.x)
DEBUG: PR body changed (repository=renovate-reproductions/22663, branch=renovate/node-18.x)
       "prTitle": "Update Node.js to v18.16.0"
DEBUG: updatePr(1, Update Node.js to v18.16.0, body) (repository=renovate-reproductions/22663, branch=renovate/node-18.x)
DEBUG: PR updated...prNo: 1 (repository=renovate-reproductions/22663, branch=renovate/node-18.x)
 INFO: PR updated (repository=renovate-reproductions/22663, branch=renovate/node-18.x)
       "pr": 1,
       "prTitle": "Update Node.js to v18.16.0"
```

There's not a single mention of the old base branch or what's going on. Can you print an explicit message which says "PR base branch has changed" or something similar?

**Review by rarkins — APPROVED** [review]

**Pull request merged**
