### PR TITLE
fix(gitlab): Use gitlab platform token to authenticate against gitlab composer package registry

### LINKED ISSUE #10649: Self-hosted composer registry on self-hosted GitLab gives wrong package url
**How are you running Renovate?**

- [x] Self hosted

Please select which platform you are using:
- [x] GitLab self-hosted

Renovate version: 25.31.0

**Describe the bug**

I have created a Composer registry on a self-hosted GitLab instance and trying to use two composer repositories on a project.

When renovate parses the composer file and tries to check the version, it gives a 404 error while trying to check on packagist instead of the right repository url.

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```
DEBUG: Datasource 404 (repository=***REDACTED***)
       "datasource": "packagist",
       "lookupName": "***REDACTED***",
       "url": "https://packagist.org/p/***REDACTED***.json"
DEBUG: Failed to look up dependency ***REDACTED*** (repository=***REDACTED***, packageFile=composer.json, dependency=***REDACTED***)
....
DEBUG: packageFiles with updates (repository=***REDACTED***)
"config": {
    "composer": [
    {
        "packageFile": "composer.json",
        "deps": [
        ......
        {
            "depType": "require",
            "depName": "***REDACTED***",
            "currentValue": "^3.0",
            "datasource": "packagist",
            "lockedVersion": "3.0.0",
            "depIndex": 18,
            "updates": [],
            "warnings": [
            {
                "topic": "***REDACTED***",
                "message": "Failed to look up dependency ***REDACTED***"
            }
            ]
        }
        ],
        "lockFiles": ["composer.lock"],
        "registryUrls": [
           "https://wpackagist.org",
           "https://<GITLAB_URL>/api/v4/group/<GOURP_ID>/-/packages/composer",
           "https://packagist.org"
        ],
    }
...
DEBUG: exec completed (repository=***REDACTED***, branch=renovate/lock-file-maintenance)
       "cmd": "composer update --with-dependencies --ignore-platform-reqs --no-ansi --no-interaction --no-scripts --no-autoloader",
       "durationMs": 6604,
       "stdout": "",
       "stderr": "Loading composer repositories with package information\nUpdating dependencies\nLock file operations: 0 installs, 1 update, 0 removals\n- Installing ***REDACTED***/***REDACTED*** (3.0.0):
```
</details>

**Have you created a minimal reproduction repository?**

https://github.com/mrgesco/renovate-20210629

- [x] I have provided a minimal reproduction repository

### PR DESCRIPTION
**Pull request by LeoniePhiline**
## Changes:

This patch applies the configured gitlab platform token to 'packagist' contexts.
This way, self-hosted gitlab package registries are used as intended.

## Context:

Previous to this patch, packagist requests to self hosted gitlab composer package registries were performed unauthenticated. Configuration would have been possible with username and password, but not with the platform token.
Therefore, self hosted gitlab composer package registries were silently(!) skipped after gitlab would have responded with a "404 Group Not Found".

## Fixes:

Closes #10649

## Documentation

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — CHANGES_REQUESTED** [review]
I don't like this. Can't you simply add a host rule for packagist?

**Comment by viceice** [comment]
Needs futher discussions. @rarkins WDYT?

**Review by rarkins — COMMENTED** [review]
I feel like this is now perhaps crossing the line into "too messy". For example including packagist awareness into the platform index code

**Comment by viceice** [comment]
> I feel like this is now perhaps crossing the line into "too messy". For example including packagist awareness into the platform index code

Yeah, platform code shoudn't need any knowledge about any manager stuff

**Comment by rarkins** [comment]
Remind me again why we can't just have a default host rule for the platform which has host and token and no `hostType`?

**Comment by viceice** [comment]
> Remind me again why we can't just have a default host rule for the platform which has host and token and no `hostType`?

Because this will override any other rule, as it will be applied last.

**Comment by rarkins** [comment]
Can we refactor so that the blanket rule is added first to hostRules?

**Comment by rarkins** [comment]
hostRules don't match purely on order though. The implementation is here: https://github.com/renovatebot/renovate/blob/0a4b1036b52d280eb27a882b37a3f368b71b7359/lib/util/host-rules.ts#L113-L151

Matches:
- rules with no criteria
- rules with hostType only
- rules with host only
- rules with both hostType and host

**Comment by viceice** [comment]
> hostRules don't match purely on order though. The implementation is here:
> 
> https://github.com/renovatebot/renovate/blob/0a4b1036b52d280eb27a882b37a3f368b71b7359/lib/util/host-rules.ts#L113-L151
> 
> Matches:
> 
> * rules with no criteria
> * rules with hostType only
> * rules with host only
> * rules with both hostType and host

Yes, but the problem is if there are a token for general usage and username/password for specific access. Than always the token is used instead the username/password.

Lets discuss this in a new issue.

**Comment by LeoniePhiline** [comment]
I wasn't able to find a follow up discussion or issue. 

Could you help me find it?

**Comment by LeoniePhiline** [comment]
I linked this PR by accident. Please ignore everything between https://github.com/renovatebot/renovate/pull/14160#issuecomment-1036224699 and here. :)

Sorry for the noise.

**Pull request closed without merging**
