### PR TITLE
feat: .nvmrc files

### LINKED ISSUE #1270: Renovate .nvmrc files
https://github.com/creationix/nvm#nvmrc

Related to #1243 and #320

### PR DESCRIPTION
**Pull request by rarkins**
Adds initial support for `.nvmrc` renovation. If the existing value is a fully-specified semver version then it will be upgraded, otherwise left alone.

Closes #1270

### CODE REVIEW

**Comment by rarkins** [comment]
Future features:

- [ ] `pinVersions`
  * Pin from 'latest' or 'stable' or ranges (8, 8.9, etc) to exact versions
- [ ] `supportPolicy`
  * Use `supportPolicy` to decide when to upgrade

**Comment by vvo** [comment]
Thanks a lot for this :)

**Comment by rarkins** [comment]
Yes, if you already pin your version and it needs an update then Renovate will raise a PR. I think @Haroenv already saw one :)

**Comment by Haroenv** [comment]
Yep, it’s working in npm-search

**Pull request merged**
