### PR TITLE
feat: empty default onboarding config

### PR DESCRIPTION
**Pull request by rarkins**
Changes the default onboarding config from `{ extends: [‘config:base’] }` to `{}` (empty). Self-hosted bot users can add it back by configuring `onboardingConfig` in `config.js` or env. Doing this makes the bot less “opinionated” by default and more convenient for self-hosted users, who can configured everything in config.js or env now.

BREAKING CHANGE: onboarding config now defaults to empty config instead of config:base. Self-hosted bot users need to add it back if they with to retain it.

### CODE REVIEW

**Comment by Autre31415** [comment]
Is there documentation that explains all the differences between an empty config and `config:base`?

**Comment by rarkins** [comment]
My goal is that the default/empty config is as unopinionated as possible, to make it easiest for self-hosted users to define their own opinionated config without worrying that they have overridden all the necessary defaults. I guess it would be good to have a document that remains updated describing the default behaviour, although in a way the list of config options and their defaults already describes most of it.

`config:base` is an opinionated config that will keep changing over time, kind of like an eslint preset might or an adblocking list would. It uses Renovate's "description" extraction to "self-describe" itself as much as possible when added via onboarding.

If you are already using "config:base" then you just need to add it as the default `extends` value in your bot. If not then nothing changes, you can explore its source definitions and decide if there are any you wish to add.

**Comment by Autre31415** [comment]
I have a config file on one of my projects that looks like this:

```
{
  "extends": ["config:base"],
  "labels": ["renovate"],
  "prCreation": "immediate",
  "prHourlyLimit": 0,
  "lockFileMaintenance": {
    "enabled": false
  },
  "docker": {
    "enabled": false
  }
}
```

I'm curious what I would gain or lose by dropping the base config extension from a config like this.

**Comment by rarkins** [comment]
> I'm curious what I would gain or lose by dropping the base config extension from a config like this.

The source for `config:base` is [here](https://github.com/renovateapp/renovate-config/blob/dab9fde5c1408308ecca0ff0d6ac4ddf69f1f61e/packages/renovate-config-config/package.json#L16-L36).

These are all the same as app defaults:
```
        ":separateMajorReleases",
        ":combinePatchMinorReleases",
        ":ignoreUnstable",
        ":prImmediately",
        ":renovatePrefix",
        ":updateNotScheduled",
        ":automergeDisabled",
        ":maintainLockFilesDisabled",
        ":autodetectPinVersions",
```

This is currently the same as the app, but will not be in the next major release:
```
        ":semanticPrefixFixDepsChoreOthers",
```
(it will default to `chore` for everything)

These have a lower limit than the app default:
```
        ":prHourlyLimit2",
        ":prConcurrentLimit20",
```
I may make these unlimited in the app by default too.

These are not part of the app defaults:
```
        "group:monorepos",
        "helpers:disableTypesNodeMajor",
        "helpers:oddIsUnstablePackages"
```

**Pull request closed without merging**
