### PR TITLE
fix(github): revert hasIssuesDisabled graphql

### PR DESCRIPTION
**Pull request by rarkins**
## Changes:

Reverts github hasIssuesDisabled detection due to incompatibility with some versions of GHE

## Context:

#12439 (also needs autoMergeEnabled fixed)

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — APPROVED** [review]

**Comment by viceice** [comment]
maybe wait with this and give @zharinov some time to fix it like #12458

**Comment by zharinov** [comment]
Starting from what GHE version `hasIssuesDisabled` is supported? I didn't find it mentioned at changelog at all

**Comment by zharinov** [comment]
To the another hand, for GHE it may be not such a big deal to try query issues

**Comment by rarkins** [comment]
Will wait on @zharinov 's PR

**Pull request closed without merging**
