### PR TITLE
feat(poetry): Use single poetry update command

### LINKED ISSUE #12503: Do poetry lock maintenance for multiple packages in one command
### What would you like Renovate to be able to do?

When creating the lock file, poetry is updating it one package at a time. This is inefficient since poetry runs the whole dependency resolving multiple times.

poetry supports multiple arguments to update multiple packages at once, and renovate could take advantage of that.

### If you have any ideas on how this should be implemented, please tell us here.

Basically change 

```
      for (let i = 0; i < updatedDeps.length; i += 1) {
        const dep = updatedDeps[i];
        cmd.push(`poetry update --lock --no-interaction ${quote(dep.depName)}`);
      }
```
in https://github.com/renovatebot/renovate/blob/main/lib/manager/poetry/artifacts.ts#L120-L123

to something like 

```
      cmd.push(`poetry update --lock --no-interaction ${updatedDeps.map(dep => quote(dep.depName)).join(' ')}`)
```

### Is this a feature you are interested in implementing yourself?

Yes

### PR DESCRIPTION
**Pull request by FSuman**
## Changes:

Currently, when updating poetry.lock, one command per package is issued.

Poetry supports updating multiple packages at once, this is faster since we only do the dependency resolution once

## Context:

Closes #12503 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by FSuman** [comment]
Before change:

```
{"name":"renovate","hostname":"a3f2e19c9436","pid":8,"level":20,"logContext":"qmIGGDPLi","repository":"dev/organizations","branch":"renovate/all","command":["poetry update --lock --no-interaction flask","poetry update --lock --no-interaction gevent","poetry update --lock --no-interaction pytest"],"msg":"Executing command","time":"2021-11-05T04:28:29.016Z","v":0}
{"name":"renovate","hostname":"a3f2e19c9436","pid":8,"level":20,"logContext":"qmIGGDPLi","repository":"dev/organizations","branch":"renovate/all","cmd":"poetry update --lock --no-interaction flask","durationMs":70327,"stdout":"Creating virtualenv organizations-W2C7ri86-py3.10 in /home/ubuntu/.cache/pypoetry/virtualenvs\nUpdating dependencies\nResolving dependencies...\n\nWriting lock file\n  • Installing pycparser (2.20)\n  • Installing pycparser (2.20)\n  • Installing cffi (1.15.0)\n  • Installing cffi (1.15.0)\n  • Installing certifi (2021.10.8)\n  • Installing charset-normalizer (2.0.7)\n  • Installing certifi (2021.10.8)\n  • Installing charset-normalizer (2.0.7)\n  • Installing cryptography (35.0.0)\n  • Installing markupsafe (2.0.1)\n  • Installing idna (2.6)\n  • Installing pyparsing (2.4.7)\n  • Installing cryptography (35.0.0)\n  • Installing idna (2.6)\n  • Installing markupsafe (2.0.1)\n  • Installing urllib3 (1.26.7)\n  • Installing pyparsing (2.4.7)\n  • Installing urllib3 (1.26.7)\n  • Installing six (1.16.0)\n  • Installing six (1.16.0)\n  • Installing attrs (21.2.0)\n  • Installing click (7.1.2)\n  • Installing attrs (21.2.0)\n  • Installing future (0.18.2)\n  • Installing click (7.1.2)\n  • Installing packaging (21.2)\n  • Installing pyasn1 (0.4.8)\n  • Installing itsdangerous (2.0.1)\n  • Installing pyrsistent (0.18.0)\n  • Installing jinja2 (3.0.2)\n  • Installing packaging (21.2)\n  • Installing pyasn1 (0.4.8)\n  • Installing itsdangerous (2.0.1)\n  • Installing pyrsistent (0.18.0)\n  • Installing werkzeug (2.0.2)\n  • Installing jinja2 (3.0.2)\n  • Installing future (0.18.2)\n  • Installing requests (2.26.0)\n  • Installing werkzeug (2.0.2)\n  • Installing ipaddress (1.0.23)\n  • Installing requests (2.26.0)\n  • Installing simplejson (3.17.5)\n  • Installing pyopenssl (21.0.0)\n  • Installing simplejson (3.17.5)\n  • Installing pyopenssl (21.0.0)\n  • Installing ipaddress (1.0.23)\n  • Installing cachetools (4.2.4)\n  • Installing deprecation (2.1.0)\n  • Installing expiringdict (1.2.1)\n  • Installing deprecation (2.1.0)\n  • Installing flask (2.0.2)\n  • Installing jsonschema (4.2.0)\n  • Installing pylcp (3.8.0)\n  • Installing expiringdict (1.2.1)\n  • Installing flask (2.0.2)\n  • Installing jsonschema (4.2.0)\n  • Installing pylcp (3.8.0)\n  • Installing cachetools (4.2.4)\n  • Installing retrying (1.3.3)\n  • Installing regex (2021.11.2)\n  • Installing retrying (1.3.3)\n  • Installing regex (2021.11.2)\n  • Installing blinker (1.4)\n  • Installing couchdb (1.2)\n  • Installing blinker (1.4)\n  • Installing docker-pycreds (0.4.0)\n  • Installing couchdb (1.2)\n  • Installing greenlet (1.1.2)\n  • Installing inflection (0.5.1)\n  • Installing docker-pycreds (0.4.0)\n  • Installing iniconfig (1.1.1)\n  • Installing pycodestyle (2.8.0)\n  • Installing liblcp (15.4.8)\n  • Installing greenlet (1.1.2)\n  • Installing websocket-client (1.2.1)\n  • Installing pluggy (0.13.1)\n  • Installing py (1.10.0)\n  • Installing pyflakes (2.4.0)\n  • Installing toml (0.10.2)\n  • Installing mccabe (0.6.1)\n  • Installing inflection (0.5.1)\n  • Installing zope.event (4.5.0)\n  • Installing iniconfig (1.1.1)\n  • Installing pycodestyle (2.8.0)\n  • Installing liblcp (15.4.8)\n  • Installing zope.interface (5.4.0)\n  • Installing websocket-client (1.2.1)\n  • Installing zope.event (4.5.0)\n  • Installing pyflakes (2.4.0)\n  • Installing mccabe (0.6.1)\n  • Installing pluggy (0.13.1)\n  • Installing toml (0.10.2)\n  • Installing py (1.10.0)\n  • Installing zope.interface (5.4.0)\n  • Installing docker-py (1.10.6)\n  • Installing flake8 (4.0.1)\n  • Installing gevent (21.8.0)\n  • Installing gunicorn (20.1.0)\n  • Installing lcp-base-service (1.5.2)\n  • Installing newrelic (6.10.0.165)\n  • Installing points-couchdb (3.2.0)\n  • Installing pytest (6.2.5)\n  • Installing requests-mock (1.9.3)\n  • Installing lcp-base-service (1.5.2)\n  • Installing newrelic (6.10.0.165)\n  • Installing points-couchdb (3.2.0)\n  • Installing pytest (6.2.5)\n  • Installing requests-mock (1.9.3)\n  • Installing flake8 (4.0.1)\n  • Installing docker-py (1.10.6)\n  • Installing gunicorn (20.1.0)\n  • Installing gevent (21.8.0)\n","stderr":"","msg":"exec completed","time":"2021-11-05T04:29:39.343Z","v":0}
{"name":"renovate","hostname":"a3f2e19c9436","pid":8,"level":20,"logContext":"qmIGGDPLi","repository":"dev/organizations","branch":"renovate/all","command":["poetry update --lock --no-interaction flask","poetry update --lock --no-interaction gevent","poetry update --lock --no-interaction pytest"],"msg":"Executing command","time":"2021-11-05T04:29:39.343Z","v":0}
{"name":"renovate","hostname":"a3f2e19c9436","pid":8,"level":20,"logContext":"qmIGGDPLi","repository":"dev/organizations","branch":"renovate/all","cmd":"poetry update --lock --no-interaction gevent","durationMs":2997,"stdout":"Updating dependencies\nResolving dependencies...\n  • Installing pycparser (2.20)\n  • Installing pycparser (2.20)\n  • Installing cffi (1.15.0)\n  • Installing cffi (1.15.0)\n  • Installing certifi (2021.10.8)\n  • Installing charset-normalizer (2.0.7)\n  • Installing certifi (2021.10.8)\n  • Installing charset-normalizer (2.0.7)\n  • Installing cryptography (35.0.0)\n  • Installing markupsafe (2.0.1)\n  • Installing cryptography (35.0.0)\n  • Installing six (1.16.0)\n  • Installing markupsafe (2.0.1)\n  • Installing pyparsing (2.4.7)\n  • Installing idna (2.6)\n  • Installing six (1.16.0)\n  • Installing urllib3 (1.26.7)\n  • Installing idna (2.6)\n  • Installing urllib3 (1.26.7)\n  • Installing pyparsing (2.4.7)\n  • Installing attrs (21.2.0)\n  • Installing click (7.1.2)\n  • Installing attrs (21.2.0)\n  • Installing future (0.18.2)\n  • Installing jinja2 (3.0.2)\n  • Installing packaging (21.2)\n  • Installing pyasn1 (0.4.8)\n  • Installing pyrsistent (0.18.0)\n  • Installing future (0.18.2)\n  • Installing jinja2 (3.0.2)\n  • Installing ipaddress (1.0.23)\n  • Installing pyopenssl (21.0.0)\n  • Installing itsdangerous (2.0.1)\n  • Installing click (7.1.2)\n  • Installing requests (2.26.0)\n  • Installing packaging (21.2)\n  • Installing pyasn1 (0.4.8)\n  • Installing pyrsistent (0.18.0)\n  • Installing simplejson (3.17.5)\n  • Installing requests (2.26.0)\n  • Installing pyopenssl (21.0.0)\n  • Installing werkzeug (2.0.2)\n  • Installing ipaddress (1.0.23)\n  • Installing simplejson (3.17.5)\n  • Installing itsdangerous (2.0.1)\n  • Installing werkzeug (2.0.2)\n  • Installing cachetools (4.2.4)\n  • Installing deprecation (2.1.0)\n  • Installing expiringdict (1.2.1)\n  • Installing flask (2.0.2)\n  • Installing jsonschema (4.2.0)\n  • Installing pylcp (3.8.0)\n  • Installing regex (2021.11.2)\n  • Installing retrying (1.3.3)\n  • Installing cachetools (4.2.4)\n  • Installing expiringdict (1.2.1)\n  • Installing deprecation (2.1.0)\n  • Installing flask (2.0.2)\n  • Installing jsonschema (4.2.0)\n  • Installing regex (2021.11.2)\n  • Installing pylcp (3.8.0)\n  • Installing retrying (1.3.3)\n  • Installing blinker (1.4)\n  • Installing couchdb (1.2)\n  • Installing docker-pycreds (0.4.0)\n  • Installing blinker (1.4)\n  • Installing inflection (0.5.1)\n  • Installing iniconfig (1.1.1)\n  • Installing liblcp (15.4.8)\n  • Installing mccabe (0.6.1)\n  • Installing py (1.10.0)\n  • Installing pycodestyle (2.8.0)\n  • Installing pyflakes (2.4.0)\n  • Installing toml (0.10.2)\n  • Installing couchdb (1.2)\n  • Installing liblcp (15.4.8)\n  • Installing greenlet (1.1.2)\n  • Installing inflection (0.5.1)\n  • Installing docker-pycreds (0.4.0)\n  • Installing iniconfig (1.1.1)\n  • Installing pluggy (0.13.1)\n  • Installing mccabe (0.6.1)\n  • Installing py (1.10.0)\n  • Installing pycodestyle (2.8.0)\n  • Installing pyflakes (2.4.0)\n  • Installing websocket-client (1.2.1)\n  • Installing zope.event (4.5.0)\n  • Installing zope.interface (5.4.0)\n  • Installing pluggy (0.13.1)\n  • Installing greenlet (1.1.2)\n  • Installing toml (0.10.2)\n  • Installing websocket-client (1.2.1)\n  • Installing zope.interface (5.4.0)\n  • Installing zope.event (4.5.0)\n  • Installing docker-py (1.10.6)\n  • Installing flake8 (4.0.1)\n  • Installing gevent (21.8.0)\n  • Installing gunicorn (20.1.0)\n  • Installing lcp-base-service (1.5.2)\n  • Installing newrelic (6.10.0.165)\n  • Installing points-couchdb (3.2.0)\n  • Installing pytest (6.2.5)\n  • Installing requests-mock (1.9.3)\n  • Installing lcp-base-service (1.5.2)\n  • Installing newrelic (6.10.0.165)\n  • Installing points-couchdb (3.2.0)\n  • Installing pytest (6.2.5)\n  • Installing requests-mock (1.9.3)\n  • Installing flake8 (4.0.1)\n  • Installing docker-py (1.10.6)\n  • Installing gunicorn (20.1.0)\n  • Installing gevent (21.8.0)\n","stderr":"","msg":"exec completed","time":"2021-11-05T04:29:42.340Z","v":0}
{"name":"renovate","hostname":"a3f2e19c9436","pid":8,"level":20,"logContext":"qmIGGDPLi","repository":"dev/organizations","branch":"renovate/all","command":["poetry update --lock --no-interaction flask","poetry update --lock --no-interaction gevent","poetry update --lock --no-interaction pytest"],"msg":"Executing command","time":"2021-11-05T04:29:42.340Z","v":0}
{"name":"renovate","hostname":"a3f2e19c9436","pid":8,"level":20,"logContext":"qmIGGDPLi","repository":"dev/organizations","branch":"renovate/all","cmd":"poetry update --lock --no-interaction pytest","durationMs":2254,"stdout":"Updating dependencies\nResolving dependencies...\n  • Installing pycparser (2.20)\n  • Installing pycparser (2.20)\n  • Installing cffi (1.15.0)\n  • Installing cffi (1.15.0)\n  • Installing certifi (2021.10.8)\n  • Installing certifi (2021.10.8)\n  • Installing charset-normalizer (2.0.7)\n  • Installing charset-normalizer (2.0.7)\n  • Installing cryptography (35.0.0)\n  • Installing cryptography (35.0.0)\n  • Installing idna (2.6)\n  • Installing markupsafe (2.0.1)\n  • Installing idna (2.6)\n  • Installing markupsafe (2.0.1)\n  • Installing pyparsing (2.4.7)\n  • Installing urllib3 (1.26.7)\n  • Installing pyparsing (2.4.7)\n  • Installing urllib3 (1.26.7)\n  • Installing six (1.16.0)\n  • Installing six (1.16.0)\n  • Installing attrs (21.2.0)\n  • Installing click (7.1.2)\n  • Installing attrs (21.2.0)\n  • Installing itsdangerous (2.0.1)\n  • Installing packaging (21.2)\n  • Installing click (7.1.2)\n  • Installing pyasn1 (0.4.8)\n  • Installing jinja2 (3.0.2)\n  • Installing pyrsistent (0.18.0)\n  • Installing future (0.18.2)\n  • Installing werkzeug (2.0.2)\n  • Installing packaging (21.2)\n  • Installing pyopenssl (21.0.0)\n  • Installing itsdangerous (2.0.1)\n  • Installing pyrsistent (0.18.0)\n  • Installing future (0.18.2)\n  • Installing werkzeug (2.0.2)\n  • Installing jinja2 (3.0.2)\n  • Installing requests (2.26.0)\n  • Installing ipaddress (1.0.23)\n  • Installing pyopenssl (21.0.0)\n  • Installing requests (2.26.0)\n  • Installing ipaddress (1.0.23)\n  • Installing pyasn1 (0.4.8)\n  • Installing simplejson (3.17.5)\n  • Installing simplejson (3.17.5)\n  • Installing cachetools (4.2.4)\n  • Installing deprecation (2.1.0)\n  • Installing expiringdict (1.2.1)\n  • Installing flask (2.0.2)\n  • Installing jsonschema (4.2.0)\n  • Installing pylcp (3.8.0)\n  • Installing regex (2021.11.2)\n  • Installing retrying (1.3.3)\n  • Installing cachetools (4.2.4)\n  • Installing expiringdict (1.2.1)\n  • Installing deprecation (2.1.0)\n  • Installing flask (2.0.2)\n  • Installing jsonschema (4.2.0)\n  • Installing regex (2021.11.2)\n  • Installing pylcp (3.8.0)\n  • Installing retrying (1.3.3)\n  • Installing blinker (1.4)\n  • Installing couchdb (1.2)\n  • Installing docker-pycreds (0.4.0)\n  • Installing couchdb (1.2)\n  • Installing greenlet (1.1.2)\n  • Installing inflection (0.5.1)\n  • Installing iniconfig (1.1.1)\n  • Installing mccabe (0.6.1)\n  • Installing pluggy (0.13.1)\n  • Installing py (1.10.0)\n  • Installing pycodestyle (2.8.0)\n  • Installing pyflakes (2.4.0)\n  • Installing toml (0.10.2)\n  • Installing docker-pycreds (0.4.0)\n  • Installing greenlet (1.1.2)\n  • Installing blinker (1.4)\n  • Installing inflection (0.5.1)\n  • Installing liblcp (15.4.8)\n  • Installing iniconfig (1.1.1)\n  • Installing mccabe (0.6.1)\n  • Installing pluggy (0.13.1)\n  • Installing py (1.10.0)\n  • Installing pycodestyle (2.8.0)\n  • Installing liblcp (15.4.8)\n  • Installing websocket-client (1.2.1)\n  • Installing zope.interface (5.4.0)\n  • Installing toml (0.10.2)\n  • Installing websocket-client (1.2.1)\n  • Installing zope.interface (5.4.0)\n  • Installing pyflakes (2.4.0)\n  • Installing zope.event (4.5.0)\n  • Installing zope.event (4.5.0)\n  • Installing docker-py (1.10.6)\n  • Installing flake8 (4.0.1)\n  • Installing gevent (21.8.0)\n  • Installing gunicorn (20.1.0)\n  • Installing lcp-base-service (1.5.2)\n  • Installing gevent (21.8.0)\n  • Installing flake8 (4.0.1)\n  • Installing gunicorn (20.1.0)\n  • Installing docker-py (1.10.6)\n  • Installing lcp-base-service (1.5.2)\n  • Installing points-couchdb (3.2.0)\n  • Installing requests-mock (1.9.3)\n  • Installing pytest (6.2.5)\n  • Installing newrelic (6.10.0.165)\n  • Installing points-couchdb (3.2.0)\n  • Installing requests-mock (1.9.3)\n  • Installing pytest (6.2.5)\n  • Installing newrelic (6.10.0.165)\n","stderr":"","msg":"exec completed","time":"2021-11-05T04:29:44.594Z","v":0}
{"name":"renovate","hostname":"a3f2e19c9436","pid":8,"level":20,"logContext":"qmIGGDPLi","repository":"dev/organizations","branch":"renovate/all","msg":"Returning updated poetry.lock","time":"2021-11-05T04:29:44.595Z","v":0}
```

after change

```
{"name":"renovate","hostname":"pts-fsuman2","pid":325694,"level":20,"logContext":"T2AAvWxmC","repository":"dev/organizations","branch":"renovate/all","command":["poetry update --lock --no-interaction flask gevent pytest"],"msg":"Executing command","time":"2021-11-05T04:31:53.429Z","v":0}
{"name":"renovate","hostname":"pts-fsuman2","pid":325694,"level":20,"logContext":"T2AAvWxmC","repository":"dev/organizations","branch":"renovate/all","cmd":"poetry update --lock --no-interaction flask gevent pytest","durationMs":5099,"stdout":"Creating virtualenv organizations-W2C7ri86-py3.9 in /home/felipe.suman/.cache/pypoetry/virtualenvs\nUpdating dependencies\nResolving dependencies...\n\nWriting lock file\n  • Installing pycparser (2.20)\n  • Installing pycparser (2.20)\n  • Installing cffi (1.15.0)\n  • Installing cffi (1.15.0)\n  • Installing certifi (2021.10.8)\n  • Installing certifi (2021.10.8)\n  • Installing charset-normalizer (2.0.7)\n  • Installing charset-normalizer (2.0.7)\n  • Installing cryptography (35.0.0)\n  • Installing cryptography (35.0.0)\n  • Installing idna (2.6)\n  • Installing idna (2.6)\n  • Installing markupsafe (2.0.1)\n  • Installing six (1.16.0)\n  • Installing pyparsing (2.4.7)\n  • Installing urllib3 (1.26.7)\n  • Installing six (1.16.0)\n  • Installing markupsafe (2.0.1)\n  • Installing pyparsing (2.4.7)\n  • Installing urllib3 (1.26.7)\n  • Installing attrs (21.2.0)\n  • Installing click (7.1.2)\n  • Installing future (0.18.2)\n  • Installing attrs (21.2.0)\n  • Installing click (7.1.2)\n  • Installing packaging (21.2)\n  • Installing future (0.18.2)\n  • Installing pyasn1 (0.4.8)\n  • Installing pyopenssl (21.0.0)\n  • Installing ipaddress (1.0.23)\n  • Installing itsdangerous (2.0.1)\n  • Installing simplejson (3.17.5)\n  • Installing pyasn1 (0.4.8)\n  • Installing pyrsistent (0.18.0)\n  • Installing packaging (21.2)\n  • Installing requests (2.26.0)\n  • Installing jinja2 (3.0.2)\n  • Installing werkzeug (2.0.2)\n  • Installing pyrsistent (0.18.0)\n  • Installing itsdangerous (2.0.1)\n  • Installing simplejson (3.17.5)\n  • Installing pyopenssl (21.0.0)\n  • Installing ipaddress (1.0.23)\n  • Installing jinja2 (3.0.2)\n  • Installing requests (2.26.0)\n  • Installing werkzeug (2.0.2)\n  • Installing cachetools (4.2.4)\n  • Installing deprecation (2.1.0)\n  • Installing expiringdict (1.2.1)\n  • Installing flask (2.0.2)\n  • Installing jsonschema (4.2.0)\n  • Installing pylcp (3.8.0)\n  • Installing regex (2021.11.2)\n  • Installing retrying (1.3.3)\n  • Installing cachetools (4.2.4)\n  • Installing expiringdict (1.2.1)\n  • Installing deprecation (2.1.0)\n  • Installing flask (2.0.2)\n  • Installing jsonschema (4.2.0)\n  • Installing pylcp (3.8.0)\n  • Installing regex (2021.11.2)\n  • Installing retrying (1.3.3)\n  • Installing blinker (1.4)\n  • Installing couchdb (1.2)\n  • Installing blinker (1.4)\n  • Installing docker-pycreds (0.4.0)\n  • Installing iniconfig (1.1.1)\n  • Installing liblcp (15.4.8)\n  • Installing mccabe (0.6.1)\n  • Installing py (1.10.0)\n  • Installing pycodestyle (2.8.0)\n  • Installing pyflakes (2.4.0)\n  • Installing toml (0.10.2)\n  • Installing greenlet (1.1.2)\n  • Installing pluggy (0.13.1)\n  • Installing inflection (0.5.1)\n  • Installing docker-pycreds (0.4.0)\n  • Installing couchdb (1.2)\n  • Installing iniconfig (1.1.1)\n  • Installing liblcp (15.4.8)\n  • Installing mccabe (0.6.1)\n  • Installing pluggy (0.13.1)\n  • Installing pycodestyle (2.8.0)\n  • Installing pyflakes (2.4.0)\n  • Installing toml (0.10.2)\n  • Installing greenlet (1.1.2)\n  • Installing inflection (0.5.1)\n  • Installing zope.event (4.5.0)\n  • Installing py (1.10.0)\n  • Installing zope.interface (5.4.0)\n  • Installing websocket-client (1.2.1)\n  • Installing zope.interface (5.4.0)\n  • Installing websocket-client (1.2.1)\n  • Installing zope.event (4.5.0)\n  • Installing docker-py (1.10.6)\n  • Installing flake8 (4.0.1)\n  • Installing gevent (21.8.0)\n  • Installing gunicorn (20.1.0)\n  • Installing lcp-base-service (1.5.2)\n  • Installing newrelic (6.10.0.165)\n  • Installing points-couchdb (3.2.0)\n  • Installing pytest (6.2.5)\n  • Installing requests-mock (1.9.3)\n  • Installing lcp-base-service (1.5.2)\n  • Installing newrelic (6.10.0.165)\n  • Installing points-couchdb (3.2.0)\n  • Installing pytest (6.2.5)\n  • Installing requests-mock (1.9.3)\n  • Installing flake8 (4.0.1)\n  • Installing docker-py (1.10.6)\n  • Installing gunicorn (20.1.0)\n  • Installing gevent (21.8.0)\n","stderr":"","msg":"exec completed","time":"2021-11-05T04:31:58.528Z","v":0}
{"name":"renovate","hostname":"pts-fsuman2","pid":325694,"level":20,"logContext":"T2AAvWxmC","repository":"dev/organizations","branch":"renovate/all","msg":"Returning updated poetry.lock","time":"2021-11-05T04:31:58.528Z","v":0}
```

**Comment by rarkins** [comment]
Does this combining of commands work for all Poetry versions? i.e. it's not recently introduced functionality which might fail for older Poetry versions?

**Comment by FSuman** [comment]
@rarkins 

It's supported on most poetry versions, if not all. I'm not sure when exactly that was introduced or if it was always supported.

In any case, renovate already requires poetry 0.12.0 or greater since that's when they added the `--lock` option to `poetry update`. https://github.com/python-poetry/poetry/releases/tag/0.12.0

And 0.12.0 already supports multiple packages on the update command

```
(venv) felipe.suman:~$ poetry --version
Poetry 0.12.0
(venv) felipe.suman:~$ poetry update --help
Usage:
  update [options] [--] [<packages>]...

Arguments:
  packages                        The packages to update.

Options:
      --no-dev                    Do not install dev dependencies.
      --dry-run                   Outputs the operations but will not execute anything (implicitly enables --verbose).
      --lock                      Do not perform install (only update the lockfile).
  -h, --help                      Display this help message
  -q, --quiet                     Do not output any message
  -V, --version                   Display this application version
      --ansi                      Force ANSI output
      --no-ansi                   Disable ANSI output
  -n, --no-interaction            Do not ask any interactive question
  -v|vv|vvv, --verbose[=VERBOSE]  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Help:
 Update dependencies as according to the pyproject.toml file.
```

**Review by viceice — APPROVED** [review]

**Review by viceice — CHANGES_REQUESTED** [review]
@FSuman Please sign the CLA

https://github.com/renovatebot/renovate/pull/12504#issuecomment-961557930

**Comment by fsuman-points** [comment]
> @FSuman Please sign the CLA
> 
> [#12504 (comment)](https://github.com/renovatebot/renovate/pull/12504#issuecomment-961557930)

Turns out I made the commits with my work email configured, I hope that's not a problem. CLA is now signed though.

**Review by viceice — APPROVED** [review]

**Pull request merged**
