### PR TITLE
test: Use `@swc/jest`

### LINKED ISSUE #20477: Speed up Jest tests by using `@swc/jest`
### Describe the proposed change(s).

@viceice offered to try `@swc/jest` again. So here's their todo issue. 😉 

Related issues/PRs:

- #15053
- #14572

### PR DESCRIPTION
**Pull request by kdy1**
I'm opening this PR to check the CI results.

## Changes

This PR uses `@swc/jest` to speed up tests.

## Context

Closes #20477

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — CHANGES_REQUESTED** [review]
you need some more changes from my PR.
you should file the required code changes as separate PR's too, so we can merge them before this.

also: please correctly fill the PR template.

**Comment by rarkins** [comment]
@viceice from https://github.com/renovatebot/renovate/pull/15053 ?

**Comment by rarkins** [comment]
Maybe we can get it working first, then separate into PRs?

**Comment by viceice** [comment]
yes and yes.

- the compile error occured because the comments need to be before the function decorators.
- the istanbul comments are required to get 100 💯 code coverage

**Comment by HonkingGoose** [comment]
Hi @kdy1, I see you removed your assignment from the issue that you're closing with this PR (#20477). Do you still want to work on the improvements suggested by the maintainers?

**Comment by kdy1** [comment]
Sorry, but I concluded that I'm too busy to work on this.

**Comment by viceice** [comment]
no problem 🤗

**Pull request closed without merging**
