### PR TITLE
feat: buildkite plugin renovation

### LINKED ISSUE #1869: Support Buildkite plugin renovation
#### This is a:

* [ ] Bug report (non-security related)
* [x] Feature request
* [ ] I'm not sure which of those it is

#### I'm using:

* [x] The Renovate GitHub App
* [ ] Self-hosted GitHub
* [ ] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:

[Buildkite](http://buildkite.com/) is a provider of continuous integration services. Buildkite allows folks to use plugins within their build pipelines and you can find documentation on them here: https://buildkite.com/docs/agent/v3/plugins. Plugins are defined in the pipeline file (yaml) and they look like:
```yaml
steps:
  # Prebuild the app image, upload it to a registry for later steps
  - name: "Docker Build"
    plugins:
      docker-compose#v1.3.2:
        build: app
        image-repository: index.docker.io/org/repo
```

The plugin name is either a reference to a git repo, or a repo in the `buildkite-plugins` repository. The example above points to this repository: https://github.com/buildkite-plugins/docker-compose-buildkite-plugin

It would be great if we could:
* Renovate all yaml files that have plugin references in the .buildkite/ folder.
* Have a configuration to match pipeline files not inside of the .buildkite/ folder and renovate them.

Happy to help contribute or collaborate on a solution if one would be accepted.

### PR DESCRIPTION
**Pull request by rarkins**
This PR adds initial support for buildkite plugin renovation.

It supports `plugin-name` or `my/plugin-name` plugins, and fully specified semver versions only (e.g. `v1.3.2`). Currently it will always propose an upgrade to the latest version available, e.g. if current version is v1.3.1 and both v1.3.2 and v2.0.0 exist then v2.0.0 will be proposed.

Future work:
- Support git hash references in addition to semver versions
- Support fully specified git repositories
- Support more than one plugin inside a `plugins:` entry
- Split major/minor updates into separate PRs, like we do with npm dependencies
- Get release notes working

Closes #1869

### CODE REVIEW

**Comment by rarkins** [comment]
@KevinGrandon could you take a look here? I think this is nearly good to merge, however I don't think the current `filePattern` regex meets your requirements:

> - Renovate all yaml files that have plugin references in the .buildkite/ folder.
> - Have a configuration to match pipeline files not inside of the .buildkite/ folder and renovate them.

Do you want it to check every *.yml file inside `.buildkite` plus any file named `pipeline.yml` anywhere else in the repository? Right now we only do the latter.

cc @lox @toolmantim

**Comment by rarkins** [comment]
I have tested this against a couple of "real" repositories I found that use versioned buildkite plugins, including one of @toolmantim's: https://github.com/renovate-tests/docker-buildkite-plugin/pull/4

I will merge this PR with the buildkit option disabled by default and leave it as opt-in until one of you gives it the thumbs-up to be enabled by default.

**Comment by toolmantim** [comment]
This is great! The logic all looks AOK.

Sorry if this is a silly question… I'm new to Renovate, but I'm wondering how release notes / commits are picked up? I noticed in renovate-tests/docker-buildkite-plugin#4 that there's no notes or commits, but there's notes in the Github releases: https://github.com/buildkite-plugins/docker-buildkite-plugin/releases

**Comment by rarkins** [comment]
@toolmantim release notes/changelog are picked up from the source GitHub repository normally. I also noticed that they were missing from that PR and meant check it later but forgot to note it in the Future work above. There's perhaps a small mismatch between the tag used and the release note slug, for instance - but in theory it should work fine and the same way as for npm.

**Review by KevinGrandon — APPROVED** [review]
Left some comments above about pipeline file location, but this is a great start and would be totally reasonable to turn on and enable. Thanks so much for the quick turnaround here, this is amazing.

**Pull request merged**
