### PR TITLE
refactor(composer): Use COMPOSER_AUTH instead of writing to auth.json

### PR DESCRIPTION
**Pull request by zharinov**
Ref: #6932, #5653, #6907

### CODE REVIEW

**Review by viceice — APPROVED** [review]

**Comment by viceice** [comment]
so this superseeds #5653 and closes #6907 ?

**Comment by zharinov** [comment]
> so this superseeds #5653 and closes #6907 ?

Right, and later we also are planning to search host rules without `config.registryUrls`

**Comment by viceice** [comment]
did you do some real tests to be safe?

**Comment by zharinov** [comment]
Would it be enough to reproduce condition (2) from [this comment](https://github.com/renovatebot/renovate/pull/6932#pullrequestreview-465715432), right?

**Pull request merged**
