### PR TITLE
chore: sort presets and enforce with eslint rule

### LINKED ISSUE #18938: Sort Default Presets alphabetically
### Describe the proposed change(s).

Can we sort the presets in this file from A-Z and top-to-bottom? And even better, enforce the ordering with an ESLint rule?

https://github.com/renovatebot/renovate/blob/6c4864365cfdf49de0265b05a0e821d531ab47c6/lib/config/presets/internal/default.ts

The [Renovate, Default Presets docs](https://docs.renovatebot.com/presets-default/) shows the same semi-random order as the source file. This makes skimming the default presets tricky.

### PR DESCRIPTION
**Pull request by weikangchia**
## Changes

Sort presets and enforces with eslint rule

## Context

Closes #18938

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
Thanks, @weikangchia!

PRs with this much added/deleted are hard to review manually.

Let's say one preset was accidentally left out of this refactoring. Would any of our tests capture that? I'm wondering if we should add a snapshot first, for example.

**Comment by HonkingGoose** [comment]
> PRs with this much added/deleted are hard to review manually.

I agree! I was asked to review this PR. And the only way I would have is to make a list of all presets and tick them off one by one, to see if they're all accounted for. 🙂

> Let's say one preset was accidentally left out of this refactoring. Would any of our tests capture that? I'm wondering if we should add a snapshot first, for example.

I would like to know how we can test changes like this as well. 🙂

**Comment by weikangchia** [comment]
Hi @rarkins and @HonkingGoose  , I agreed that it is quite hard to review with too many changes 😅

I will try to see how can I write a test.

> I'm wondering if we should add a snapshot first, for example.

May I also clarify what does adding a snapshot first mean? Does it mean for each sort ordering change, I make a commit?

**Comment by rarkins** [comment]
Jest snapshots have objects sorted in key order, meaning that in theory the snapshot Jest saves should be the same before and after the ordering changes.

**Comment by weikangchia** [comment]
Thanks for the clarification. I have generated the Jest snapshot from the main branch and committed it to this PR branch and the test passes. This should be sufficient to ensure no presets are missing and also its child properties

**Comment by rarkins** [comment]
I've pushed that test to `main` branch and save the snapshot so that we can be sure it's unchanged in this PR

**Review by rarkins — APPROVED** [review]

**Pull request merged**
