### PR TITLE
feat(manager/dockerfile): add dedicated updater for Dockerfile

### PR DESCRIPTION
**Pull request by Churro**
## Changes

- Added an updater for Dockerfile that works based on line numbers that are collected during the extraction step
- Supports version, digest and depName replacement updates

**Note:** This branch is based on #15751. Since extraction and update are not directly dependent, I thought it would ease review if I'd make two PRs instead of one large for both. If you disagree here, please let me know.

## Context

- Needs #15751 to be merged first
- Solves #5626
- Solves #12623

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

Test repository: https://github.com/Churro/renovate-dockerfile-test2

### CODE REVIEW

**Review by viceice — CHANGES_REQUESTED** [review]
i don't like the custom updater. why do we need this? shouldn't this be possible with normal autoreplace?

**Comment by rarkins** [comment]
We always prefer autoreplace whenever possible

**Comment by Churro** [comment]
auto-replace works great with many other managers but not when the string to replace is spread across multiple lines. E.g., with image parts in multiple ARG values:
```
ARG IMAGE_NAME=node
ARG IMAGE_VER=16.13.1-alpine3.14
FROM $IMAGE_NAME:$IMAGE_VER as stage1
```

auto-replace works well when `upgrade.replaceString` and `autoReplaceStringTemplate` match one specific line/index:
```
ARG BUILD_BASE=ubuntu:18.04
FROM $BUILD_BASE as builder
```

I first tried to workaround this issue by customizing `replaceString` and the template but failed. This is because Dockerfiles are interpreted sequentially and the order in which statements occur matters. auto-replace works using `existingContent.indexOf(replaceString)` (= always first occurrence) and iterative replacements across the whole file.

In Dockerfiles, `ARG name=value` can be redefined multiple times with different values. If I'd simply search for `ARG VERSION=3.10` and replace `currentValue` with `newValue`, it may happen that subsequent dependency updates in the same file (that refer to the same `ARG VERSION=3.10` but in a different line) would fail. In one case, `3.10` could refer to a python image, in another case to alpine. Replacing would only work successfully if they would both, at the same time, upgrade to the same `newValue`, which is more than unlikely.

This is the reason, the updater in this PR relies on a set of lineNumbers it receives from extract to refer to specific, potentially multi-line ARG and/or FROM instructions. 

Summarizing, I understand your concerns but also think that a dedicated updater would make sense (at least until auto-replace is capable of covering this equivalently). Parameterization in Dockerfiles is **very common** (examples: [docker-cli](https://github.com/docker/cli/blob/master/Dockerfile), [cilium-proxy](https://github.com/cilium/proxy/blob/master/Dockerfile), [Apache airflow](https://github.com/apache/airflow/blob/main/Dockerfile), ...), so I think this would be a very useful feature addition for renovate.

**Comment by viceice** [comment]
i don't agree, i think that's a better use case for regex manager. this will make the dockerfile manager very complicated and complex to maintain in future.

**Comment by rarkins** [comment]
Manual update functions are a large burden on maintenance we'd like to avoid, so I would like that to be an option of last resort.

If there's an ARG which multiple dependencies reference in their version then those dependencies should be grouped together (because they're going to be upgraded together like it or not, even if we were to raise separate PRs). There's nothing about Renovate's sequential auto replace attempts which means it can't work with args or split definitions unless you literally split a version string or sha, which is a bad idea edge case IMO. The only thing it might cause a problem with is if a string is duplicated and you expect both duplicates to be updated at the same time.

Let's get back to some examples so we can talk in practice not theory? And of course focusing on real practical must-be-done-this-way examples and not "this is actually valid syntax even if there's much better ways" examples.

**Comment by Churro** [comment]
It would be great if you'd have some pointers how to tweak `extract.ts` to achieve the same thing with auto-replace: 
Enlist the individual image chunks as multiple dependencies in `deps` but with different `upgrade.replaceString` values?

There are many examples in-the-wild (plus in `update.spec.ts`) illustrating why I thought a custom updater would be the better choice for this use-case:
```Dockerfile
# ex1: multi-line 
# -> what to match/replace here? VERSION=3.10 (with spaces in front?) or only currentValue=3.10 ?
ARG \
  # multi-line arg
    VERSION=3.10

FROM \
alpine:${VERSION} as stage1

# ex2: unspecific version
# > what to match/replace here? VARIANT="12" as a whole or only currentValue=12 ?
ARG VARIANT="12"
FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:${VARIANT}

# ex3: image parts spread across variables
# > how to pass these parts from extract to auto-replace?
ARG NODE_IMAGE_HASH="@sha256:ba9c961513b853210ae0ca1524274eafa5fd94e20b856343887ca7274c8450e4"
ARG NODE_IMAGE_NAME="docker.io/library/node"
...
# something completely unrelated in between
...
ARG NODE_IMAGE_TAG=16.14.2-alpine3.14
ARG DUMMY_PREFIX=
FROM ${DUMMY_PREFIX}${NODE_IMAGE_NAME}:${NODE_IMAGE_TAG}${NODE_IMAGE_HASH}
```

Just FYI: #15751 is an improvement independent from this PR. It already solves the issue that images (as a whole string) can be in ARG values **using auto-replace**. Example from [pytorch](https://github.com/pytorch/pytorch/blob/0765a804911673fb2d9694a76ba0196ea0eddec4/Dockerfile):
```Dockerfile
ARG BASE_IMAGE=ubuntu:18.04
FROM ${BASE_IMAGE} as dev-base
```

**Comment by rarkins** [comment]
The global replace in autoReplace is undesirable and should be removed actually. IIRC it was Bazel holding that up

**Comment by Churro** [comment]
Thank you for your feedback and the inspiration on how to tackle the update with a different approach. 

I have now realized the same use-case using auto-replace only. The solution works for all code snippets posted above and this obsoletes the need for a custom updater. All functionality is now contained in PR #15751. 

I'd very much appreciate a review on that other PR and I'm going to close this one for obvious reasons.

**Pull request closed without merging**
