### PR TITLE
test(gitlab): improve test case

### PR DESCRIPTION
**Pull request by xingxing**
'master' is the default branch, it should not be used to asserted

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — CHANGES_REQUESTED** [review]
i don't see any improvement. please add a pr description why do you think this test change is required.

**Comment by xingxing** [comment]
https://github.com/renovatebot/renovate/blob/1f70da4aede2e7e0b31fa7479ff5ea82fab572c0/lib/config/presets/gitlab/index.ts#L21-L27

There are two situations will let the result to be 'master'.
1. The master branch's `default` attribute is `true`.
2. Can not found a branch, which its `default` attribute is `true`.

Following case will also passed, but obviously it is a typo. 

```typescript
httpMock
        .scope(codingApiHost)
        .get(`${basePath}/branches`)
        .reply(200, [
          {
            name: 'devel',
            defAult: true,
          },
          {
            name: 'master',
          },
        ])
        .get(`${basePath}/files/default.json/raw?ref=master`)
        .reply(200, { foo: 'bar' }, {});
```

Because we use the default value as the exception in this assertion. I think we  should  at least give chance to describe the non-default value case.

**Review by viceice — COMMENTED** [review]
this test just returns a preset from default branch, so it doesn't matter what's the name. here somebody decided to use master, which is the default value for a lot of old repos. so the test is valid as is.

**Comment by xingxing** [comment]
> this test just returns a preset from default branch, so it doesn't matter what's the name. here somebody decided to use master, which is the default value for a lot of old repos. so the test is valid as is.

Yes, indeed. But would you think we should at least have one assertion for a 'non-default' branch at here:

```typescript
 .get(`${basePath}/files/default.json/raw?ref=${nonDefault}`)
```

**Comment by viceice** [comment]
> > this test just returns a preset from default branch, so it doesn't matter what's the name. here somebody decided to use master, which is the default value for a lot of old repos. so the test is valid as is.
> 
> Yes, indeed. But would you think we should at least have one assertion for a 'non-master' branch at here:
> 
> ```typescript
>  .get(`${basePath}/files/default.json/raw?ref=${nonMaster}`)
> ```
> 
> In my opinion, current  'description' of that behavior, have missed a key factor: 'when the master branch isn't the "default" branch, it should use the actual one'.

sure, but main is still the new default on most repos. so you didn't really changed anything besides some renaming.

**Pull request merged**
