### PR TITLE
feat: unify file locations

### LINKED ISSUE #3272: docs: localDir, persistRepoData
The docs for selfhosting should mention the config options for `localDir` and `persistRepoData`.
They will improve the perfomance a lot.

### LINKED ISSUE #3466: Refactor/reconsider all file locations
Thinking through the various directories:

1. `OS_TMPDIR`: some of the third party tools we use are going to write to this no matter what. I think we should recommend for Docker that users volume map the tmp dir from the host disk to the Renovate image so that Renovate isn't continuously writing "layers" inside the container file system

2. Working dir: This is where we should clone repos to. It should be predictable.

3. Renovate cache: This is where we write persistent cached data between runs, e.g. when we cache datasources for 30 minutes. It should be considered non-private "shared" data between repos

4. Package manager caches: Most like npm, composer, etc all let you control where they write the cache to and read it back from later. A self-hosted bot owner would usually benefit from having a common, persistent cache, while in other cases it's beneficial to wipe the cache between runs, so we should make it configurable.

### PR DESCRIPTION
**Pull request by rarkins**
Refactors all file/directory operations to use predictable and configurable locations. Also updates docs to make it easier to know what to do.

Closes #3466, Closes #3272, Closes #3455

### CODE REVIEW

**Comment by rarkins** [comment]
@ViceIce could you take a look at this PR and confirm if you think it's right? It includes both some refactoring of locations (e.g. so that clones go to unique dirs) as well as updating docs. In this case you *should not* configure `config.localDir` directly.

**Comment by ViceIce** [comment]
I'll look at and test it tomorrow 😄

**Comment by rarkins** [comment]
In summary:

- By default, Renovate will put repo clones into somewhere like `/tmp/renovate/repos/gitlab/project1/repo2` and all cache under `/tmp/renovate/cache/`
- You can move all of them by specifying `baseDir` or move just the cache by specifying `cacheDir`
- Do not touch/configure `localDir`

**Review by viceice — APPROVED** [review]
Not testet yet but LGTM. 👌

**Comment by ViceIce** [comment]
Works as intended. 👍

**Pull request merged**
