### PR TITLE
test: Maven versioning tests

### PR DESCRIPTION
**Pull request by zharinov**
## Changes:

Use table syntax for versioning testing.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — DISMISSED** [review]

**Review by rarkins — DISMISSED** [review]

**Comment by viceice** [comment]
Missing coverage

**Comment by zharinov** [comment]
Yes, but unfortunately I can't see what lines aren't covered

**Comment by viceice** [comment]
> Yes, but unfortunately I can't see what lines aren't covered

It seems codecov isn't detecting it, so you need to manually run it locally 😏

**Comment by zharinov** [comment]
I've figured it out in last commit, it had something to do with modules import

**Pull request merged**
