### PR TITLE
fix(platform/bitbucket): update rebase instructions

### PR DESCRIPTION
**Pull request by setchy**
## Changes

Update rebase instructions to remove references to checkboxes and make consistent across both PR body and comments

## Context

- https://github.com/renovatebot/renovate/issues/5510

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — COMMENTED** [review]
looks good to me

**Review by secustor — APPROVED** [review]

**Comment by secustor** [comment]
@viceice Do you commented by accident or is something in your opinion missing?

**Comment by viceice** [comment]
> @viceice Do you commented by accident or is something in your opinion missing?  

just want to have more eye's because it's late here 😉

**Comment by secustor** [comment]
K, I haven't been sure as you written lgtm but haven't approved ;)

**Pull request merged**
