### PR TITLE
fix(presets): update the document links

### LINKED ISSUE #25236: Link preset docs to source
### Describe the proposed change(s).

Example preset docs page: https://docs.renovatebot.com/presets-group/

Currently links to https://github.com/renovatebot/renovate/edit/main/docs/usage/presets-group.md

Should link to https://github.com/renovatebot/renovate/edit/main/lib/config/presets/internal/group.ts

### PR DESCRIPTION
**Pull request by uozcan12**
## Changes

fix (presets): update the document #25236

## Context
- fixes #25236

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only

### CODE REVIEW

**Review by viceice — CHANGES_REQUESTED** [review]
totally wrong

**Comment by uozcan12** [comment]
What should I do? If you explain the steps clearly, I can fix the issue.

**Comment by viceice** [comment]
the docs generator needs to be updated, so it emits special yaml metadata to the generated markdown file, so the edit button links ho the mentioned source file.

**Comment by viceice** [comment]
> What should I do? If you explain the steps clearly, I can fix the issue.

- https://github.com/renovatebot/renovate/discussions/25548

There is the right solution 🙃

**Pull request closed without merging**
