### PR TITLE
refactor(ruby-version): convert to class-based

### PR DESCRIPTION
**Pull request by JamieMagee**
## Changes:

Convert the `ruby-version` datasource to be class-based.

Also adjusted the error handling to be more in line with other datasources. Previously `ruby-version` would throw for an empty result and a 404, but nearly all other datasources will return `null` for these cases (except `cdnjs`)

## Context:

#8647

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
I think the old behaviour was intended though. The Ruby version website should always return a result so failure to do so means an external host error.

**Comment by JamieMagee** [comment]
Okay, I've reverted that behaviour.

**Comment by rarkins** [comment]
BTW I think that Renovate's default behaviour to automatically "ignore" failed lookups in many datasources is technical debt. If I were starting over I'd make repositories explicitly ignore any intentionally unavailable private packages I order to onboard.

**Comment by JamieMagee** [comment]
Could you explain more? Would the onboarding PR contain config to disable dependencies that weren't available during the onboarding run?

**Comment by rarkins** [comment]
Right now we throw an external host error only for a few datasources where we *know* they should not error. e.g. if registry.npmjs.org returns 500 then we know that should not happen we abort the run. But whenever we're unsure, such as for custom registries, then we keep going - which can cause autoclosing if the error was just temporary.

In a scenario where every dependency lookup was mandatory, the bot would abort every run with external host error. Therefore we'd need:
- Some way to indicate that, e.g in Dependency Dashboard
- Ways to avoid that in the first place, e.g. asking users to configure credentials *or* ignore dependencies during onboarding

**Review by viceice — APPROVED** [review]

**Pull request merged**
