### PR TITLE
feat(presets): Update monorepo Jackson

### PR DESCRIPTION
**Pull request by danielcompton**
## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — COMMENTED** [review]
are they released together with same versions?

**Comment by MindTooth** [comment]
Screenshot 2024-01-30 at 13 27 04

---

They all share the same version.  So I guess all these can be added too.

**Comment by viceice** [comment]
> Screenshot 2024-01-30 at 13 27 04
> 
> ---
> 
> They all share the same version.  So I guess all these can be added too.

ok

> 
> Could this be a group for https://mvnrepository.com/artifact/com.fasterxml.jackson.dataformat or something too?

🤷‍♂️ if they share the same version

**Comment by MindTooth** [comment]
> > Could this be a group for https://mvnrepository.com/artifact/com.fasterxml.jackson.dataformat or something too?
> 
> 🤷‍♂️ if they share the same version

Yes. :smile:

**Comment by danielcompton** [comment]
Yep, they all track versions:

Screenshot of Safari at 31:01:2024 at 11_47_55 AM

Screenshot of Safari at 31:01:2024 at 11_47_34 AM

Screenshot of Safari at 31:01:2024 at 11_47_38 AM

**Review by viceice — COMMENTED** [review]
so probably add `https://github.com/FasterXML/jackson` to org groups below, so that all packages with sourceUrl starting with `https://github.com/FasterXML/jackson` will be grouped together?

See L515+

**Review by rarkins — DISMISSED** [review]

**Review by rarkins — APPROVED** [review]

**Pull request merged**
