### PR TITLE
docs: render default objects and arrays in config

### PR DESCRIPTION
**Pull request by Shegox**
## Changes

This PR adds that arrays and objects are printed as well. This is especially helpful to understand what to configure. 

## Context

Currently the defaults for the configuration are only shown on the website, if the config option is a primitive type.
Complex types, like arrays or objects are not displayed and it is hard to guess what subtypes/keys they contain. 

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

The difference in rendering of the configuration.md files can be seen in this commit: https://github.com/Shegox/renovate-docs-objects/commit/7b02ecf05f38a7a267c2605349f44825d6eb2bf6

### CODE REVIEW

**Comment by rarkins** [comment]
Do we have any which would be overly large?

**Comment by Shegox** [comment]
I uploaded the rendered diff at https://github.com/Shegox/renovate-docs-objects/commit/7b02ecf05f38a7a267c2605349f44825d6eb2bf6, if you select rich preview there, it shows the output. 

The longest default is: ``{"ignoreTopic":"Renovate Ignore Notification","ignoreMajor":"As this PR has been closed unmerged, Renovate will ignore this upgrade and you will not receive PRs for *any* future {{{newMajor}}}.x releases. However, if you upgrade to {{{newMajor}}}.x manually then Renovate will reenable minor and patch updates automatically.","ignoreDigest":"As this PR has been closed unmerged, Renovate will ignore this upgrade and you will not receive PRs for the `{{{depName}}}` `{{{newDigestShort}}}` update again.","ignoreOther":"As this PR has been closed unmerged, Renovate will now ignore this update ({{{newValue}}}). You will still receive a PR once a newer version is released, so if you wish to permanently ignore this dependency, please add it to the `ignoreDeps` array of your renovate config."}``

**Comment by rarkins** [comment]
Thanks. Let's try this then, worst case it should be an easy revert. We can experiment in future if prettified JSON output is possible too.

**Review by rarkins — APPROVED** [review]

**Review by viceice — APPROVED** [review]
We should cleanup that code later, as it looks very ugly

**Pull request merged**
