### PR TITLE
feat(github): Don't store `updatedAt` field in GraphQL cache record

### LINKED ISSUE #21023: Avoid package cache set every run for GitHub tags/releases
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

source

### If you're self-hosting Renovate, select which platform you are using.

github.com

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Even when using a completely "hot" cache and nothing changes, Renovate performs a lot of package cache set commands. I added logging to see which they were:

```
 WARN: Cache set (repository=renovatebot/renovate)
       "namespace": "github-tags-datasource-v2",
       "key": "https://api.github.com/:peter-evans:create-pull-request",
       "ttlMinutes": 43096.24955

 WARN: Cache set (repository=renovatebot/renovate)
       "namespace": "github-releases-datasource-v2",
       "key": "https://api.github.com/:actions:upload-artifact",
       "ttlMinutes": 43096.23288333333
```

Using this repo as an example, it results in 24 unnecessary set commands per run when doing dryRun=lookup:

```
       "set": {"count": 24, "avgMs": 1136, "medianMs": 577, "maxMs": 7438}
```

If I shortcut the set command (immediately return) then it reduces the lookup time:

Two runs without set:

```
DEBUG: Repository timing splits (milliseconds) (repository=renovatebot/renovate)
       "splits": {"init": 12387, "extract": 3572, "lookup": 14219},
       "total": 30336
```

```
DEBUG: Repository timing splits (milliseconds) (repository=renovatebot/renovate)
       "splits": {"init": 12174, "extract": 3395, "lookup": 14245},
       "total": 29949
```

Two runs with set:

```
DEBUG: Repository timing splits (milliseconds) (repository=renovatebot/renovate)
       "splits": {"init": 10507, "extract": 3426, "lookup": 21464},
       "total": 35540
```

```
DEBUG: Repository timing splits (milliseconds) (repository=renovatebot/renovate)
       "splits": {"init": 11238, "extract": 3393, "lookup": 21498},
       "total": 36281
```

i.e. it seems to add 5-6 seconds per run.

Ideas:
- Don't set if nothing has changed? or
- Don't set unless TTL remaining is less than half

### Relevant debug logs

_No response_

### Have you created a minimal reproduction repository?

I have read the minimal reproductions documentation and linked to such a repository in the bug description

### PR DESCRIPTION
**Pull request by zharinov**
## Changes

- ~~Separate `updatedAt` and cache data in order to optimize cache I/O~~
- Remove `updatedAt` field
- Rewrite cache only if any of items has changed

## Context

- Closes: #21023

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
What is the expected outcome?

When I do a dry run on this repo two times in a row I still see a lot of package cache sets:

```
DEBUG: Repository timing splits (milliseconds) (repository=renovatebot/renovate)
       "splits": {"init": 15133, "extract": 3496, "lookup": 14482},
       "total": 33262
DEBUG: Package cache statistics (repository=renovatebot/renovate)
       "get": {"count": 246, "avgMs": 269, "medianMs": 205, "maxMs": 1643},
       "set": {"count": 24, "avgMs": 431, "medianMs": 354, "maxMs": 1561}
DEBUG: http statistics (repository=renovatebot/renovate)
       "urls": {
         "https://api.github.com/graphql (POST,200)": 26,
         "https://api.github.com/repos/renovatebot/.github/contents/default.json (GET,200)": 1
       },
       "hostStats": {"api.github.com": {"requestCount": 27, "requestAvgMs": 1171, "queueAvgMs": 0}},
       "totalRequests": 27
```

I assume those 24 are for github tags/releases and that they're unnecessary.

**Comment by rarkins** [comment]
My expectation is that when I run on a repo two times in a row that there are no package cache sets on the second run.

**Comment by zharinov** [comment]
That's because we're still saving new `updatedAt` value to the package cache each run (it costs about 5ms).

**Comment by rarkins** [comment]
Why do we need to set the updatedAt?

Let's say I asked you not to set it every run. What would we lose?

**Comment by zharinov** [comment]
Hah, turns out it's the legacy field from the time when we tried to do zero GraphQL queries per run. So the answer is we only lose the potential possibility of doing zero queries, but seems like we don't want it anyway.

**Review by viceice — DISMISSED** [review]
🤷‍♂️ don't we have a equal comparison lib already?

**Comment by zharinov** [comment]
🤦 We do

**Review by viceice — CHANGES_REQUESTED** [review]
ok, so please use the existing 😁

**Review by viceice — APPROVED** [review]

**Review by rarkins — APPROVED** [review]
```
DEBUG: Package cache statistics (repository=renovatebot/renovate)
       "get": {"count": 222, "avgMs": 275, "medianMs": 186, "maxMs": 1669},
       "set": {"count": 0}
```

**Pull request merged**
