### PR TITLE
feat(internal): generate dynamic manager imports

### PR DESCRIPTION
**Pull request by viceice**
ref: #5759

Allows dynamically adding managers:
https://github.com/renovatebot/renovate/blob/8a6d9555a7ec44bafefe1aaabbe96b78ed35710c/lib/manager/index.spec.ts#L57-L63

### CODE REVIEW

**Comment by viceice** [comment]
needed force push, because i've reverted most changes

**Comment by rarkins** [comment]
@viceice do you want to fix the codecov fail?

**Comment by viceice** [comment]
yes, but on another pr

**Comment by viceice** [comment]
Ready for merge

**Pull request merged**
