### PR TITLE
feat(pnpm): Adding --recursive flag to pnpm install

### LINKED ISSUE #2015: pnpm recursive support
**What would you like Renovate to be able to do?**
Support `pnpm`s recursive feature

**Describe the solution you'd like**
It should "just work" in Renovate similar to Yarn's Workspaces or lerna

**Additional context**
https://pnpm.js.org/docs/en/pnpm-recursive.html

We need someone using `pnpm` to summarise how the internal/linking part works in particular, and how Renovate can know to do "pnpm recursive" rather than simply run `pnpm` separately in every directory. Nominating @zkochan for that!

### PR DESCRIPTION
**Pull request by ianwalter**
Adding the --recursive flag to pnpm install so that the top-level lock file gets updated for monorepos. In non-monorepos, the --recursive file doesn't seem to have an effect so it should be safe for those. Apologies if I missed something else in the issue, but it seems a lot has changed since then.

Closes #2015: pnpm recursive support

### CODE REVIEW

**Review by viceice — COMMENTED** [review]
LGTM so far, but what about older pnpm  versions we still support? Which version introduce the new parameter?

**Comment by ianwalter** [comment]
What version does renovate support? I thought I saw somewhere v3+? The flag was added in v3.0.0 it seems but the feature itself was added in v2. This change may also close #6782.

**Review by viceice — APPROVED** [review]

**Comment by ExE-Boss** [comment]
> In non-monorepos, the --recursive file doesn't seem to have an effect so it should be safe for those.

You should’ve asked @zkochan for clarification then.

**Comment by zkochan** [comment]
That should be fine.

**Pull request merged**
