### PR TITLE
ci(prettier): show diff if prettier made changes

### PR DESCRIPTION
**Pull request by Finkregh**
The normal output is not helpful, see also: https://github.com/prettier/prettier/issues/6885

## Changes

Linting with prettier now shows a diff if there are changes. This makes it easier to see what changes it actually want (not only the file names as before).

## Context

https://github.com/renovatebot/renovate/actions/runs/10395128990/job/28798791562?pr=30680
Output here does not really help.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by secustor** [comment]
Is there a reason you can not simply run [`lint-fix`](https://github.com/renovatebot/renovate/blob/main/package.json#L32) or `prettier-fix` ?

**Comment by Finkregh** [comment]
> Is there a reason you can not simply run [`lint-fix`](https://github.com/renovatebot/renovate/blob/main/package.json?rgh-link-date=2024-08-16T06%3A51%3A25Z#L32) or `prettier-fix` ?

Does that show a diff? Or does it push changes back into PR? I'd be fine with either one :)

**Comment by secustor** [comment]
This is run locally to fix such issues automatically and should be then commited by the dev. 
See this section of the local development guide: https://github.com/renovatebot/renovate/blob/main/docs/development/local-development.md#linting-and-formatting

**Comment by Finkregh** [comment]
It would still be nice if the CI would show me what should be changed, not everyone is willing/able to setup that quite huge development environment :)

What do you think about adding a link to the dev-docs if prettier fails? @secustor

**Comment by rarkins** [comment]
@Finkregh what's the problem you're trying to solve?

e.g you submit a PR which has prettier problems, and it fails on CI, and you want more details?

I don't object to this, but the "next step" will still be to run `pnpm prettier-fix`. Instead do you plan to fix prettier problems by hand using the diff?

**Comment by Finkregh** [comment]
@rarkins yes, exactly. Make it at least an option to see what the files should look like :)

**Comment by rarkins** [comment]
Seems ok for me for those who want to contribute via the GitHub UI and not Codespaces or locally. @secustor wdyt?

**Comment by secustor** [comment]
Fine by me, though not sure if this will really be that helpful as Github UI messes with whitespace in the Actions UI as far as I know.

**Review by rarkins — APPROVED** [review]

**Pull request merged**
