### PR TITLE
Update docs: update-lockfile does not support Yarn 2+

### PR DESCRIPTION
**Pull request by bmulholland**
When update-lockfile is set, that sets isLockfileUpdate to true (ref: https://github.com/renovatebot/renovate/blob/bca2cd2f5b7a57989f83ed23f94e9ec9cbecda18/lib/workers/repository/process/lookup/generate.ts#L84), which then calls `updateLockfileDependency`, which does not support Yarn 2+ (ref: https://github.com/renovatebot/renovate/blob/bca2cd2f5b7a57989f83ed23f94e9ec9cbecda18/lib/modules/manager/npm/update/locked-dependency/yarn-lock/index.ts#LL26C41-L26C41)

I'll fill in the lower parts and sign the CLA if it becomes clear that this is a change that will be accepted. I'm not willing to invest the time to do all that until then because my interactions on this repo have not been very helpful so far. Hoping that will change!

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by bmulholland** [comment]
Also: if I'm reading the code right, the docs are misleading about `in-range-only`. I thought that would not have the limited support that `update-lockfile` has, since there's no warning. Could someone confirm if that's true? If so, then I think there should also be a warning at the end of `in-range-only` in the same section, to say "required update-lockfile" support. I'm sure this seems obvious to the informed reader, but I adopted the setting based off what I read, when I was not informed, and it certainly wasn't obvious then.

**Comment by bmulholland** [comment]
Like I say, I'll go through the trouble of filling out a CLA when it's clear my contribution is correct and welcome.

**Comment by rarkins** [comment]
As a policy we do not review PRs until the CLA is signed, otherwise we could be accused of ripping off the code or whatever. You are welcome to close this and continue discussing it, please don't open PRs unless you can sign the CLA otherwise it's wasting your time and ours

**Comment by rarkins** [comment]
If this docs change is correct, it's something I wasn't aware of. I would prefer to have a minimal reproduction and feature request issue first to confirm.

**Review by rarkins — CHANGES_REQUESTED** [review]
Minimal reproduction to confirm first

**Comment by bmulholland** [comment]
Okay, I've signed it, but now I see your comment. Look, I've already invested over an hour debugging things in Renovate's code. Putting together a repro is another hour plus time investment that I'm just not going to do. I've tried to help out but I've frankly been blocked at every opportunity. OSS should be about collaboration and help, not shutting me down. I'm sorry but I tried to help others and am not feeling like doing anything else.

**Pull request closed without merging**
