### PR TITLE
fix: upgrade sorting by file replacement position

### LINKED ISSUE #7814: maven version patching replaces wrong characters when new version and current version have different sizes
**What Renovate type, platform and version are you using?**

self hosted Renovate, using docker : renovate/renovate:23.85.0 

**Describe the bug**

in a situation where there is more than one replacement to apply in a file, and the first replacement inserts a version that does not have the same number of characters as the existing one, the subsequent replacement does not replace the correct characters, because the position at which the replacement must be done is not correct anymore.

For some reason, there is self healing in the process, only a single replacement is impacted, because the additional characters are removed when applying the new version. This causes the bug to be difficult to diagnose at first.

**Relevant debug logs**

The default logs are not really helpful, but I have some samples that I got by adding these lines to lib/manager/maven/update.ts :

```js
  if (version === currentValue || upgrade.groupName) {
      var replacedPart = versionPart.replace(version, newValue);

      if(depName === SOME_DEPENDENCY_THAT_FAILS){

        logger_1.logger.info("version : " + version + " , replaced " + newValue);
        logger_1.logger.info("fileReplacePosition : " + fileReplacePosition);
        logger_1.logger.info("charAt(fileReplacePosition) : " + fileContent.charAt(fileReplacePosition));
        logger_1.logger.info("leftPart : " + leftPart);
        logger_1.logger.info("replacedPart : " + replacedPart);
        logger_1.logger.info("restPart : " + restPart);
        logger_1.logger.info("fileContent : " + fileContent);
      }

      return leftPart + replacedPart + restPart;
    }
```

relevant sample : 

```
INFO: version : >4.1.20 , replaced 4.1.23 (repository=***, branch=renovate/all-minor-patch)
 INFO: fileReplacePosition : 1546 (repository=***, branch=renovate/all-minor-patch)
 INFO: charAt(fileReplacePosition) : > (repository=***, branch=renovate/all-minor-patch)
```

You can see that field `version` starts with `>`. This is because a previous change updated a version with a different size, causing  `fileReplacePosition` to point to the wrong character

**To Reproduce**

I don't have a minimal repo to reproduce the issue just now. I may provide one at some point if it is too difficult to progress on this issue otherwise.

**Additional context**

A simplistic workaround that I could apply and that prevented issues for me was to add this to update.ts : 

```
    if(currentValue.length !== newValue.length) {
      logger_1.logger.warn("detected situation where version patching would cause issues, skipping " + depName);
      return fileContent;
    }
```

Of course, this is not good, because any version bump that actually changes the number of characters gets completeley skipped. But at least renovate does not attempt to push faulty XML files anymore.

I would really appreciate a fix, I intend to spend a little more time on this to find a better way to solve the problem, I'll post is here if I find any.

### PR DESCRIPTION
**Pull request by mofleury**
## Changes:

adjusted sorting comparator to make sure that ordering is consistent even if part of the upgrades have a replace positions, and others do not.

## Context:
closes  #7814

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added unit tests, or
- [x] Unit tests + ran on a real repository

### CODE REVIEW

**Comment by viceice** [comment]
@mofleury Please sign the CLA

**Comment by mofleury** [comment]
hm I did not spot this, there is now a test that fails because the result does not match the expected snapshot anymore.

I am really new to jest, and I don't know if this is a regression, or if the test should be updated... any hint would be greatly appreciated.

**Review by viceice — APPROVED** [review]

**Review by rarkins — APPROVED** [review]

**Comment by rarkins** [comment]
Thanks @mofleury !

**Comment by mofleury** [comment]
my pleasure :) Thank you for the quick merge and release!

**Pull request merged**
