### PR TITLE
chore: add pr:discussion-first and needs-details label actions

### PR DESCRIPTION
**Pull request by rarkins**
## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by zharinov — APPROVED** [review]

**Review by JamieMagee — APPROVED** [review]

**Review by HonkingGoose — APPROVED** [review]

**Review by viceice — APPROVED** [review]
I'm not sure that it works on PR's

**Comment by rarkins** [comment]
Isn't there already actions on PRs, e.g. for "no done comments"?

**Comment by viceice** [comment]
> Isn't there already actions on PRs, e.g. for "no done comments"?

I've disabled it because of permission issues

https://github.com/renovatebot/renovate/blob/77bd389582cbd725720721c847cb4aa451febc50/.github/workflows/label-actions.yml#L3-L7

**Comment by HonkingGoose** [comment]
@rarkins I think the new labels won't work, because our configuration of the action is:

```yaml
name: 'Label Actions'

on:
  issues:
    types: [labeled]
  discussion:
    types: [labeled]

permissions:
  contents: read
  issues: write
  discussions: write

jobs:
  reaction:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/label-actions@074b96a62f35c226ecb38e840f44941bde0343a6 # v3.0.0
        with:
          github-token: ${{ github.token }}
          process-only: 'issues, discussions'
```

We don't mention PR in the `on.X` section, or in the `with.process-only:` section. I think @viceice is worried about the permissions this action needs, and so they did not enable it for PRs.

I'll let you review things and make a decision.

**Pull request merged**
