### PR TITLE
feat(bazel-modules): support `single_version_override`

### PR DESCRIPTION
**Pull request by cgrindel**
## Changes

- Add support for `single_version_override` in `bazel-module` manager.

## Context

Related to #13658.
Related to cgrindel/renovate_bzlmod_support#19.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — COMMENTED** [review]
are we sure those should be fully ignored? a user can't override that via config. 🤔

**Comment by cgrindel** [comment]
> are we sure those should be fully ignored? a user can't override that via config. 🤔

Sorry. I don't understand your question. 

[The single_version_override declaration](https://bazel.build/rules/lib/globals/module#single_version_override) is slightly different from the other overrides. Here is the top line from the documentation:

> Specifies that a dependency should still come from a registry, but its version should be pinned, or its registry overridden, or a list of patches applied.

**Comment by cgrindel** [comment]
@viceice Gentle ping. Could you elaborate on your comment?

>are we sure those should be fully ignored? a user can't override that via config.

**Comment by viceice** [comment]
> @viceice Gentle ping. Could you elaborate on your comment?
> 
> >are we sure those should be fully ignored? a user can't override that via config. 

if you set a Skip reason, renovate will always ignore that dependency. there is no way for a user to override that. so renovate can never update that dependency. so a user always needs to manually do it.

if the override only changes the registry, we should simply add that to the original dep and ignore the override.

if the override defined a version, it should be updatable by renovate. we can return enabled=false, so they are disabled by default, but can be enabled by user via package rule.

**Comment by cgrindel** [comment]
> if you set a Skip reason, renovate will always ignore that dependency. there is no way for a user to override that. so renovate can never update that dependency. so a user always needs to manually do it.

That is exactly the workflow that we want, in this case. If the client specifies a `version` in `single_version_override`, they are [pinning the version](https://bazel.build/rules/lib/globals/module#single_version_override). We do not want to update that value. There is no other reason to specify the `version` in `single_version_override`.

> if the override only changes the registry, we should simply add that to the original dep and ignore the override.

Agreed. That is what this PR does. The test case for this scenario is [here](https://github.com/renovatebot/renovate/pull/22610/files#diff-a2c1f88a70360e06a3c50240c7d473603749d32b68a4a13fc085acf9642dd0b8R219-R240).

**Comment by viceice** [comment]
@rarkins @secustor @JamieMagee WDYT?

**Comment by secustor** [comment]
This seems like the same scenario as `required_version` of the Terraform manager. 

Usually developers use that feature to limit Terraform version avaiable to module users, tough we still update them under a different `depType` to allow an easy way to disable that feature.

**Comment by rarkins** [comment]
Seems ok to leave it as-is for now, maybe in future users will want a way to have it updated

**Review by viceice — APPROVED** [review]

**Pull request merged**
