### PR TITLE
fix(repository/update/pr/body): fix a test having wrong homepage and use regex

### PR DESCRIPTION
**Pull request by hasanwhitesource**
## Changes

Fixing a test and not changing behavior

## Context

Came across this while working on #14820 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by hasanwhitesource** [comment]
Separated pr from https://github.com/renovatebot/renovate/pull/16166

**Review by nabeelsaabna — DISMISSED** [review]
already approved before by rarkins  and viceice

**Review by rarkins — COMMENTED** [review]
Is this better fixed using our url join function?

**Comment by hasanwhitesource** [comment]
I don't think the ensure slashes is necessary for `joinUrl`

**Review by rarkins — APPROVED** [review]

**Pull request merged**
