### PR TITLE
fix(packagist): prevent packages.json being added twice

### LINKED ISSUE #779: Authenticate to private composer repository in Gitlab
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitLab self-hosted

### Have you checked the logs? Don't forget to include them if relevant

```
DEBUG: Packagist repository not found (repository=vendor/package)
       "regUrl": "https://gitlab.vendor.com/api/v4/group/2/-/packages/composer/packages.json"

DEBUG: Dependency lookup failure: not found (repository=vendor/package, dependency=vendor/core)
DEBUG: Response code 404 (Not Found) (repository=vendor/package)
       "err": {
         "name": "HTTPError",
         "host": "packagist.org",
         "hostname": "packagist.org",
```

### What would you like to do?

Authentication is required to access the private composer registry - https://docs.gitlab.com/ee/user/packages/composer_repository/#installing-a-package

I've already setup `.composer/auth.json` which is used by the `composer` CLI package but this does not seem to be used.

I had the same issue with NPM (https://docs.renovatebot.com/private-modules/) but I resolved that by setting the npm config.

I have tried using `hostRules` (https://docs.renovatebot.com/configuration-options/#hostrules) but not had any luck.

### PR DESCRIPTION
**Pull request by bytestream**
https://docs.gitlab.com/ee/user/packages/composer_repository/#installing-a-package say to use:
```
"repositories": [
    { "type": "composer", "url": "https://gitlab.com/api/v4/group/<group_id>/-/packages/composer/packages.json" }
  ],
```

If you do this then Renovate ruins the repository URL, example:
```js
var URL = require('url');

var regUrl = "https://gitlab.vendor.com/api/v4/group/2/-/packages/composer/packages.json";
console.log(
  URL.resolve(regUrl.replace(/\\/?$/, '/'), 'packages.json')
);
// https://gitlab.vendor.com/api/v4/group/2/-/packages/composer/packages.json/packages.json
```

Closes https://github.com/renovatebot/config-help/issues/779

### CODE REVIEW

**Review by rarkins — CHANGES_REQUESTED** [review]
Looks good, but needs a test added to ensure we don't regress

**Comment by bytestream** [comment]
@rarkins Would you mind suggesting one or submitting your own PR based off this? TypeScript is not really my thing.

**Comment by rarkins** [comment]
I think if you add it to the registryUrl on this line - https://github.com/bytestream/renovate/blob/dff3a05b0ff4e69bef2f2b9d973eca88f2ce0ef9/lib/datasource/packagist/index.spec.ts#L48 - then that should test it. Please also run `yarn lint-fix` to fix up the linting errors too.

**Comment by rarkins** [comment]
@viceice do you think this is the best approach or should we do the transforming at extract time?

**Review by viceice — COMMENTED** [review]
Sounds good to transform the registry url at extraction time, so we can handle it like any other registry url.

**Comment by bytestream** [comment]
What's necessary to make that happen?

**Comment by viceice** [comment]
@bytestream please move the registry url patching to extract function in composer manager instead of packagist datasource

**Comment by rarkins** [comment]
https://github.com/renovatebot/renovate/blob/938d896d31c553085baf4ad4a91a260db83fd8c3/lib/manager/pip_requirements/extract.ts#L24-L48

If the URL is trimmed there then it shouldn't require multiple changes to the datasource.

**Comment by viceice** [comment]
@rarkins isn't packagist the datasource for PHP / composer? 🤔

**Comment by rarkins** [comment]
My bad, try here: https://github.com/renovatebot/renovate/blob/938d896d31c553085baf4ad4a91a260db83fd8c3/lib/manager/composer/extract.ts#L38-L85

**Comment by bytestream** [comment]
@rarkins @viceice updated it

**Review by viceice — APPROVED** [review]

**Review by rarkins — APPROVED** [review]

**Pull request merged**
