### PR TITLE
test: use codeql compatible token / passwords

### PR DESCRIPTION
**Pull request by viceice**
## Changes:

Replace dummy passwords / token with codeql compatible values, so we don't get false positives

## Context:
https://github.com/github/codeql/blob/221a25993854d41ea455e91e146fe5ea0e8bd0ff/javascript/ql/src/semmle/javascript/security/SensitiveActions.qll#L183

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
Any easy way to confirm that it's worked? Not sure if CodeQL give us that detail after I have dismissed them previously

**Comment by viceice** [comment]
> Any easy way to confirm that it's worked? Not sure if CodeQL give us that detail after I have dismissed them previously

No, but i see new issues in pr checks, so i can at least fix those

**Comment by viceice** [comment]
Looks like special chars are not allowed for codeql 😕

**Comment by viceice** [comment]
Now ready to review

**Review by rarkins — APPROVED** [review]

**Pull request merged**
