### PR TITLE
fix(presets): add new opencost-ui to opencost monorepo

### PR DESCRIPTION
**Pull request by MindTooth**
## Changes

In anticipation for https://github.com/opencost/opencost-ui/pull/18 getting merged.

This adds the [opencost-ui](https://github.com/opencost/opencost-ui/pull/18) project as a separate repo for the opencost monorepo.  They've desided to split the projects, but still under the same umbrella.

They are released in the same pipeline, using the same version: https://github.com/opencost/opencost/blob/develop/.github/workflows/build-and-publish-release.yml

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

I ran `pnpm run lint`.

### CODE REVIEW

**Comment by MindTooth** [comment]
I've asked if they plan to do releases in opencost/opencost-ui repo as well, or else we won't be able to get a changelog. 🤔  Maybe it's not that important anyways.  As we will get the changelog for opencost/opencost in the same PR.

**Comment by HonkingGoose** [comment]
@MindTooth by the way: the [Renovate docs, key concepts page for changelogs](https://docs.renovatebot.com/key-concepts/changelogs/) has more info about getting Renovate to see and understand the changelogs. That may help getting changelogs functional for those packages.

**Comment by MindTooth** [comment]
I did a sin with force push, not sure how this works when files are renamed, sorry. 😔 

https://github.com/opencost/opencost-ui/pull/18 just got merged, so this is a go ahead.

I'm still at a loss on how changelog works after five years working with Renovate.  https://github.com/MindTooth/renovate-opencost-test/pull/5 does not pick up even when the log says it's fetching. 🤣

**Comment by MindTooth** [comment]
```
ERROR: Coverage for lines (96.89%) does not meet global threshold (100%)
ERROR: Coverage for functions (96.49%) does not meet global threshold (100%)
ERROR: Coverage for branches (95.16%) does not meet global threshold (100%)
ERROR: Coverage for statements (96.91%) does not meet global threshold (100%)
```

Hmm.  Not sure about this one?  Locally I have:

```
=============================== Coverage summary ===============================
Statements   : 100% ( 41977/41977 )
Branches     : 100% ( 13238/13238 )
Functions    : 100% ( 5218/5218 )
Lines        : 100% ( 41389/41389 )
================================================================================

Test Suites: 722 passed, 722 total
Tests:       15008 passed, 15008 total
Snapshots:   732 passed, 732 total
Time:        166.06 s
Ran all test suites.
```

**Review by rarkins — APPROVED** [review]

**Pull request merged**
