### PR TITLE
feat(cache): allow caching of null values

### PR DESCRIPTION
**Pull request by secustor**
## Changes:
This PR allows to cache `null` values. 

## Context:
https://github.com/renovatebot/renovate/pull/10619

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by JamieMagee** [comment]
The changes from your commit look fine, but there appear to be more commits included in this PR?

**Comment by secustor** [comment]
I have created this feature branch from main, which has received additional commits since the creation of the v26 branch.

**Comment by JamieMagee** [comment]
Ah, can you rebase your commit on top of the `v26` branch, so we don't include unnecessary changes (and it'll make it easier for Rhys when he merges `main` into the `v26` branch)

**Comment by rarkins** [comment]
Is it breaking though? Otherwise it can just merge into `main`

**Comment by secustor** [comment]
@viceice requested that this change is getting merged into v26 not into main directly https://github.com/renovatebot/renovate/pull/10619#discussion_r678963460

**Review by JamieMagee — DISMISSED** [review]

**Review by viceice — CHANGES_REQUESTED** [review]
@secustor Please rebase again and drop other commits

**Comment by viceice** [comment]
> Is it breaking though? Otherwise it can just merge into `main`

@rarkins I think we have a big cache change, if we no allow to cache null values. I remember we had some issues in the past. So i think it's safer to merge it to v26.

**Comment by rarkins** [comment]
> > Is it breaking though? Otherwise it can just merge into `main`
> 
> @rarkins I think we have a big cache change, if we no allow to cache null values. I remember we had some issues in the past. So i think it's safer to merge it to v26.

If we went from allowing `null` to not allowing `null` then we could easily break things (an existing cache could return values not expected by the new code) but hopefully here it has no such problem, don't you think? I'm ok with v26 though, just in case

**Review by viceice — COMMENTED** [review]
We do no longer cache `undefined`. I'm not sure if this will now cause higher load on renovate. we would need to check other code using cache for storing `undefined` or `null`

**Review by viceice — APPROVED** [review]

**Pull request merged**
