### PR TITLE
docs: fix wrong path for module description

### LINKED ISSUE #14608: Publish the `readme.md` files for `datasources`, `versioning` and `platforms`
## Problem

There's a [`readme.md`](https://github.com/renovatebot/renovate/blob/main/lib/modules/datasource/aws-machine-image/readme.md) file for the AWS Machine Image datasource. But the content of this readme is **not** published on the [AWS Machine Image Datasource docs page](https://docs.renovatebot.com/modules/datasource/#aws-machine-image-datasource).

This problem was found in https://github.com/renovatebot/renovate/pull/14582#discussion_r822702447.

## Proposed fix

We should edit our "build the documentation" scripts, so that we publish the `readme.md` files from:

- [ ] `datasources`
- [ ] `versioning`
- [ ] `platforms`

## Do you want to help?

I'll let a maintainer work on this. 😉

### PR DESCRIPTION
**Pull request by viceice**
## Changes
Fix search path for module readme's.

## Context
- regression of #14488
- ref #14608

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by viceice** [comment]
@rarkins @HonkingGoose Should we still refactor docs to use a sub page for each module? will make cross linking more easy.

**Comment by HonkingGoose** [comment]
I don't understand the difference between those options. 🙈

Can you explain the difference and give examples of what the pages will look like with both options?

**Comment by viceice** [comment]
> I don't understand the difference between those options. 🙈
> 
> Can you explain the difference and give examples of what the pages will look like with both options?

Checkout manager and platform, each module has it's own (sub) page. I like to extend it, so all modules (datasources, versionings ...)  use that doc schema.

**Comment by HonkingGoose** [comment]
Extending it so all 4 of those pages are similar sounds good to me!

**Review by rarkins — APPROVED** [review]

**Pull request merged**
