### PR TITLE
fix(lookup/get-digest): add new variable `lookupRegistryUrl`

### LINKED ISSUE #27576: warning cdnjs Custom registries are not allowed
### Discussed in https://github.com/renovatebot/renovate/discussions/27553

<div type='discussions-op-text'>

<sup>Originally posted by **nabeelsaabna** February 26, 2024</sup>
### How are you running Renovate?

Mend Renovate hosted app on github.com

### If you're self-hosting Renovate, tell us what version of Renovate you run.

_No response_

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

None

### Describe the problem

getting the error `Custom registries are not allowed for this datasource and will be ignored` without setting any custom registries

minimal reproduction repository:
https://github.com/nabeelsaabnaTests/pmdp-test-cdnjs

### Relevant debug logs

<details><summary>Logs</summary>

```

DEBUG: packageFiles with updates
{
  "baseBranch": "main"
  "config": {
    "html": [
      {
        "deps": [
          {
            "currentDigest": "sha512-zJYu9ICC+mWF3+dJ4QC34N9RA0OVS1XtPbnf6oXlvGrLGNB8egsEzu/5wgG90I61hOOKvcywoLzwNmPqGAdATA==",
            "currentValue": "1.2.1",
            "currentVersion": "1.2.1",
            "datasource": "cdnjs",
            "depName": "axios",
            "fixedVersion": "1.2.1",
            "isSingleVersion": true,
            "packageName": "axios/axios.min.js",
            "registryUrl": "https://api.cdnjs.com/",
            "replaceString": "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/axios/1.2.1/axios.min.js\" integrity=\"sha512-zJYu9ICC+mWF3+dJ4QC34N9RA0OVS1XtPbnf6oXlvGrLGNB8egsEzu/5wgG90I61hOOKvcywoLzwNmPqGAdATA==\" crossorigin=\"anonymous\">",
            "sourceUrl": "https://github.com/mzabriskie/axios",
            "versioning": "semver",
            "warnings": [],
            "updates": [
              {
                "bucket": "non-major",
                "newVersion": "1.6.7",
                "newValue": "1.6.7",
                "newMajor": 1,
                "newMinor": 6,
                "updateType": "minor",
                "newDigest": "sha512-NQfB/bDaB8kaSXF8E77JjhHG5PM6XVRxvHzkZiwl3ddWCEPBa23T76MuWSwAJdMGJnmQqM0VeY9kFszsrBEFrQ==",
                "branchName": "renovate/axios-1.x"
              }
            ]
          },
          {
            "currentDigest": "sha256-FtWfRI+thWlNz2sB3SJbwKx5PgMyKIVgwHCTwa3biXc=",
            "currentValue": "2.5.17",
            "currentVersion": "2.5.17",
            "datasource": "cdnjs",
            "depName": "vue",
            "fixedVersion": "2.5.17",
            "homepage": "http://vuejs.org",
            "isSingleVersion": true,
            "packageName": "vue/vue.min.js",
            "registryUrl": "https://api.cdnjs.com/",
            "replaceString": "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.17/vue.min.js\" integrity=\"sha256-FtWfRI+thWlNz2sB3SJbwKx5PgMyKIVgwHCTwa3biXc=\" crossorigin=\"anonymous\">",
            "sourceUrl": "https://github.com/vuejs/vue",
            "versioning": "semver",
            "warnings": [
              {
                "message": "Could not determine new digest for update (cdnjs package vue/vue.min.js)",
                "topic": "vue/vue.min.js"
              }
            ],
            "updates": [
              {
                "bucket": "non-major",
                "newVersion": "2.7.16",
                "newValue": "2.7.16",
                "newMajor": 2,
                "newMinor": 7,
                "updateType": "minor",
                "newDigest": "sha512-Wx8niGbPNCD87mSuF0sBRytwW2+2ZFr7HwVDF8krCb3egstCc4oQfig+/cfg2OHd82KcUlOYxlSDAqdHqK5TCw==",
                "branchName": "renovate/vue-monorepo"
              },
              {
                "updateType": "digest",
                "newValue": "2.5.17",
                "newDigest": "sha512-E0wcoW3BSv/ZvprR5qZnsQ//TAHOSaq5AvRWfuSvwqravuBXOeeSycmecbN4otneNObeipZ2UkKLhXn6p3jLvw==",
                "branchName": "renovate/vue-monorepo"
              }
            ]
          }
        ],
        "packageFile": "test.html"
      }
    ]
  }
}


DEBUG: Fetching changelog: https://github.com/mzabriskie/axios (1.2.1 -> 1.6.7) (branch="renovate/axios-1.x")
WARN: Package lookup failures (branch="renovate/axios-1.x")
{
  "warnings": [
    "Could not determine new digest for update (cdnjs package vue/vue.min.js)"
  ]
  "files": [
    "test.html"
  ]
}


DEBUG: Fetching changelog: https://github.com/vuejs/vue (2.5.17 -> 2.7.16) (branch="renovate/vue-monorepo")
WARN: Package lookup failures (branch="renovate/vue-monorepo")
{
  "warnings": [
    "Could not determine new digest for update (cdnjs package vue/vue.min.js)"
  ]
  "files": [
    "test.html"
  ]
}

DEBUG: repository problems
{
  "repoProblems": [
    "WARN: Custom registries are not allowed for this datasource and will be ignored",
    "WARN: Package lookup failures"
  ]
}
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction in the description above</div>

### PR DESCRIPTION
**Pull request by RahulGautamSingh**
## Changes
Add new variable `lookupRegistryUrl` which will be used to pass the url from the package lookup response to perform digest lookups.

## Context
Closes: https://github.com/renovatebot/renovate/issues/27576
I am not sure if this is best approach, but I would like to have a different variable because reusing url from the package looup response is a new and separate logic and it shouldn't be mixed up with the existing registryUrl logic. It also made it harder to debug issues as the logic were mixed. Now it should be more clear. 
Open to suggestions on this.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
@RahulGautamSingh please check out the changes I made recently including in #27724 which is merging now. For docker datasource at least, `getDigest()` should be returned the same `registryUrl` as was used/returned by `getReleases()`.

**Comment by RahulGautamSingh** [comment]
Both the changes serve the same purpose and this PR can be closed. My bad for not checking that PR earlier 😅, thought it was only dealing with `lookupName`. 

Also, I think we can remove this if-check now from the lookup function, as it serves no purpose.
https://github.com/renovatebot/renovate/blob/147d38a2a498d55c81a5a03b4bf8b2ac26c658b3/lib/workers/repository/process/lookup/index.ts#L494-L496

**Comment by RahulGautamSingh** [comment]
Both the changes serve the same purpose and this PR can be closed. My bad for not checking that PR earlier 😅, thought it was only dealing with `lookupName`. 

Also, I think we can remove this if-check now from the lookup function, as it serves no purpose. Doing it in your PR would've been better, I will refactor that in this PR instead if you agree.
https://github.com/renovatebot/renovate/blob/147d38a2a498d55c81a5a03b4bf8b2ac26c658b3/lib/workers/repository/process/lookup/index.ts#L494-L496

**Comment by rarkins** [comment]
@RahulGautamSingh have you confirmed that the cdnjs problem is now resolved by accident? :)

**Comment by RahulGautamSingh** [comment]
Doing a test run right now, but logically it should be fixed since we won't be calling the `resolveRegsitryUrls` from the `getDigest` function anymore when `config.regsitryUrl` is defined .. hence the code containing warning would never be executed.

**Review by viceice — COMMENTED** [review]
is this still relevant?

**Comment by RahulGautamSingh** [comment]
> is this still relevant?

No :(

**Pull request closed without merging**
