### PR TITLE
docs: Readme for hex manager

### PR DESCRIPTION
**Pull request by hallstain**

### CODE REVIEW

**Comment by rarkins** [comment]
@KonstantinKurganov 	I'm wondering if we should split this into two separate package managers - `mix` and `rebar3`? It looks like these are separate managers that both use the hex datasource.

**Comment by KonstantinKurganov** [comment]
@rarkins yeap, it is a good idea! I'll start with mix manager.

**Comment by KonstantinKurganov** [comment]
I think we can decline this pr. I'll make separate ones for mix and rebar3 containing own readme

**Comment by rarkins** [comment]
Ok I agree, thanks

**Pull request closed without merging**
