### PR TITLE
fix(bitbucket): add canMerge to pr

### PR DESCRIPTION
**Pull request by kallrobin**
Automerge logic checks for `pr.canMerge` https://github.com/renovatebot/renovate/blob/master/lib/workers/pr/index.js#L401.

Using bitbucket (cloud).
When trying to automerge with status checks it fails when checking for the `pr.canMerge` flag.
I looked into the code and found that on bitbucket-server that is set to whatever the response is from the API.
 
Sadly i’m not sure if this is the correct way to solve the problem, but it seems to work for me.

### CODE REVIEW

**Comment by iamstarkov** [comment]
arbitrary default value will break stuff

value for canMerge should be retrieved from some endpoint

also tests should be added

**Comment by JohnPhoto** [comment]
@iamstarkov I agree on all of the above, that said there are no endpoint in bitbucket-cloud which matches the bb-server GET merge (https://docs.atlassian.com/bitbucket-server/rest/6.4.0/bitbucket-rest.html#idp266).
Only to actually merge the PR with a POST (https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D/pullrequests/%7Bpull_request_id%7D/merge)

Do you have any insights into what endpoint/what logic to search for in the API?

We are looking into how to update the tests but we are not able to update the snapshots because other tests fails.

**Comment by iamstarkov** [comment]
[`/2.0/repositories/{username}/{repo_slug}/branch-restrictions/{id}`](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D/branch-restrictions/%7Bid%7D) maybe

**Comment by ViceIce** [comment]
@rarkins  I'm ok with this change, when the snapshots are updated. this is just a fix to allow automerge working on bitbucket cloud. I don't see a breaking change, because a failed merge would be recognized anyways (pr description will be changed).

@iamstarkov I see a benefit to check the branch restriction, but that will require `repository:admin` permissions for simply `GET`. Also that would be a new feature, so we should use a new issue /pr for that.

**Review by viceice — APPROVED** [review]
LGTM

**Pull request merged**
