### PR TITLE
fix: widen node engine range

### LINKED ISSUE #4823: Unsupported engine for renovate
when updating renovate you told me this

```
npm WARN notsup Unsupported engine for renovate@19.66.15: wanted: {"node":"^10.13.0 || ^12.0.0","yarn":">=1.10.1"} (current: {"node":"13.1.0","npm":"6.12.1"})
npm WARN notsup Not compatible with your version of node/npm: renovate@19.66.15
```

### PR DESCRIPTION
**Pull request by JamieMagee**
There are a few possibilities to fix this specific bug. This is the shortest fix, and still relatively low risk

Fixes #4823

### CODE REVIEW

**Comment by rarkins** [comment]
I've seen this in other projects - essentially it's a problem due to "supported" having dual meanings:

1. Technically, on which versions should this work on?
2. As a project, on which versions are we going to actually support if you raise a bug?

For example, I definitely do not want to guarantee that this should work with v13 and keep up with any breaking changes they make. Closer to v14, we might take a look.

**Comment by JamieMagee** [comment]
Yeah, so the alternative was `^10.13.0 || ^ 12.0.0 || ^13.0.0`. Would you prefer this? I have no strong opinion either way.

**Comment by rarkins** [comment]
I don't think that really changes much, so I'm fine with the current proposed change. Wondering if we might want to note somewhere else that we aren't going to do bugfixes on non-LTS releases though.

**Comment by JamieMagee** [comment]
Actually, thinking about it either `^10.13.0 || ^ 12.0.0 || ^13.0.0` or `^10.13.0 || >=12.0.0` would be better, as `11.x` is EOL as of 1st June 2019.

**Comment by rarkins** [comment]
Maybe `^10.13.0 || >=12.0.0` then

**Review by viceice — APPROVED** [review]

**Pull request merged**
