### PR TITLE
feat(gitlab): Auto-detect squash settings

### LINKED ISSUE #7859: Support GitLab merge requirements
**What Renovate type, platform and version are you using?**

GitLab.com, self-hosted

**Describe the bug**

Renovate's own automerging fails when merge squash requirements are set like below:

image

Renovate then deletes the branch which causes the MR to be closed. Renovate should not be fooled and know that the MR merge failed and do not delete the branch.

**Relevant debug logs**

```
DEBUG: Checking #13 for automerge (repository=renovate-bot/renovate-runner, branch=renovate/docker-renovate-renovate-23.x)
       "automerge": true,
       "automergeType": "pr",
       "automergeComment": "automergeComment"
DEBUG: PR is configured for automerge (repository=renovate-bot/renovate-runner, branch=renovate/docker-renovate-renovate-23.x)
DEBUG: getBranchStatus(renovate/docker-renovate-renovate-23.x) (repository=renovate-bot/renovate-runner, branch=renovate/docker-renovate-renovate-23.x)
DEBUG: Got res with 1 results (repository=renovate-bot/renovate-runner, branch=renovate/docker-renovate-renovate-23.x)
DEBUG: Automerging #13 (repository=renovate-bot/renovate-runner, branch=renovate/docker-renovate-renovate-23.x)
 INFO: PR automerged (repository=renovate-bot/renovate-runner, branch=renovate/docker-renovate-renovate-23.x)
       "pr": 13,
       "prTitle": "chore(deps): update renovate/renovate docker tag to v23.90.0"
DEBUG: Deleted remote branch (repository=renovate-bot/renovate-runner, branch=renovate/docker-renovate-renovate-23.x)
       "branchName": "renovate/docker-renovate-renovate-23.x"
DEBUG: No local branch to delete (repository=renovate-bot/renovate-runner, branch=renovate/docker-renovate-renovate-23.x)
       "branchName": "renovate/docker-renovate-renovate-23.x"
```

**To Reproduce**

Enable automerge in a GitLab repo where the merge squash requirement is set.

### PR DESCRIPTION
**Pull request by 56KBs**
## Changes:

When using a supported version of GitLab (14.0+), extract whether the repository requires, or encourages squashing, raising all new pull requests with squash enabled in those scenarios.

If an unsupported version of GitLab is encountered, squashing will not occur.

## Context:

Closes #7859 .

When a PR is raised within GitLab, with the `squash: true` value set, this means that the Renovate automated merging scenario should work without issue, as GitLab will respect the previously set `squash: true`  value.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by viceice** [comment]
This also d isn't a solution for  #7859, as it only implements auto squash and not explicit config options as required per issue.

**Comment by viceice** [comment]
This should also update docs to reflect the changes

**Comment by 56KBs** [comment]
> This also d isn't a solution for #7859, as it only implements auto squash and not explicit config options as required per issue.

From my understanding of the issue it's to be able to support Renovate raising PRs that can be auto-merged, this MR does fix this issue. Later discussions mentioned the possibility of manual configuration in order to achieve this.

Now that `automergeStrategy` I think this actually makes it slightly more difficult to implement explicit configuration, as `automergeStrategy: squash` can be used to force Renovate to raise with the squash flag. However I don't feel there is a suitable `automergeStrategy` value to stop Renovate raising with squash in the scenario your repository is configured with squashing allowed.

I'm happy to implement the desired behaviour but I chose not to do it in this PR due to the additional complexity of it.

> This should also update docs to reflect the changes

Where is the most suitable location for this documentation? I don't see any documentation for GitLab at a platform level to add to.

**Review by viceice — CHANGES_REQUESTED** [review]
- Needs deconflicting.
- The explicit config option can be done in separate pr, but then this pr sholdn't close #7859 because #10870 is now part it

**Comment by 56KBs** [comment]
De-conflicted - Thanks for updating the description to just reference, rather than close the ticket 👍 If this does get merged I will carry on the conversation within the original ticket to see what the expected behaviour would be for an explicit configuration option.

**Comment by rarkins** [comment]
I reopened #10870 so that this PR can close #7859

**Review by viceice — APPROVED** [review]

**Pull request merged**
