### PR TITLE
fix(manager): support newer kustomize urls

### PR DESCRIPTION
**Pull request by viceice**
Allow renovating modern base urls

```yml
bases:
- github.com/foo/bar?ref=v1.0.1
- github.com/fluxcd/flux/deploy?ref=1.19.0
```

ref: renovatebot/config-help#646

### CODE REVIEW

**Comment by ChipWolf** [comment]
LGTM, probably worth adding another test for `hostname.tld/org/repo?ref=<tag>`

**Comment by viceice** [comment]
> LGTM, probably worth adding another test for `hostname.tld/org/repo?ref=<tag>`

Are you expecting this to work, or just to fail silently?

**Comment by ChipWolf** [comment]
> > LGTM, probably worth adding another test for `hostname.tld/org/repo?ref=<tag>`
> 
> Are you expecting this to work, or just to fail silently?

It works. if the kustomize files are at the root of a repo, it's totally valid

**Comment by viceice** [comment]
`hostname.tld/org/repo?ref=1.2.3` should be translated to `https://hostname.tld/org/repo` git url?

**Comment by ChipWolf** [comment]
> `hostname.tld/org/repo?ref=1.2.3` should be translated to `https://hostname.tld/org/repo` git url?

yep

**Comment by viceice** [comment]
@rarkins  I think this is ready for merge. We should add support for arbitrary urls with another pr.

**Comment by viceice** [comment]
@ChipWolf Can you please open a new issue for other urls?

**Pull request merged**
