### PR TITLE
feat(node): nodenv(.node-version) support

### LINKED ISSUE #4959: Updating nodenv version when updating node version
**What would you like Renovate to be able to do?**
Actually renovate is able to update the node version from docker file and `.nvmrc`, that would be nice if you can handle the `.node-version` file as well 👍

https://github.com/nodenv/nodenv

**Describe the solution you'd like**
Updating the `.node-version` file when present

**Describe alternatives you've considered**
Doing by hands but not really productive :)

### PR DESCRIPTION
**Pull request by ViralRuparel**
Handle nodenv(.node-version) file to update node version.

Closes #4959

### CODE REVIEW

**Comment by ViralRuparel** [comment]
image

**Comment by rarkins** [comment]
@ViralRuparel does this fully work with ranges? e.g. if the file contains `12.15` then will they get an upgrade to `12.16`?

**Comment by ViralRuparel** [comment]
Yes, it does work. PFA.

**Comment by rarkins** [comment]
Please merge that and verify it working too. i.e. the actual commit

**Comment by ViralRuparel** [comment]
https://github.com/ViralRuparel/testrepo/pull/6 @rarkins Link to the PR that updates the node version and is merged!

**Comment by vschoener** [comment]
Awesome guys!

**Pull request merged**
