### PR TITLE
feat(docker): add cargo binary

### LINKED ISSUE #4072: Add cargo binary to Dockerfile

### PR DESCRIPTION
**Pull request by ZyanKLee**
Adds steps to Dockerfile to install cargo binary during build.

Closes #4072

### CODE REVIEW

**Comment by rarkins** [comment]
@ZyanKLee do you know if this approach lets us specify an exact version of Rust to use?

**Comment by ZyanKLee** [comment]
I'll have a look. Give me a moment

**Comment by ZyanKLee** [comment]
I updated the command to now only install rustup in the first step and in a second step use it to install the specific version.

**Comment by ZyanKLee** [comment]
... and updated the toolchain version number to the latest rust version (1.36.0).

**Pull request merged**
