### PR TITLE
fix: Use auto-discovered organisational preset configuration during on-boarding

### LINKED ISSUE #9851: Auto-discovered organisational presets not applied during on-boarding
**What Renovate type, platform and version are you using?**

Renovate Self-hosted

**Describe the bug**

When using organisational presets for configuration, the preset is not applied during the on-boarding MR - This can result in repositories not being on-boarded when they should be, based on the presets configuration.

e.g 

```
org/renovate-config
org/repository1
```

When `organisation/repository1` is on-boarded it should use the configuration from the `org/renovate-config` to identify any 

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```
DEBUG: Found 0 package file(s)
INFO: Repository has no package files - skipping
```

</details>

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

https://github.com/56KBs/renovate-reproduction-repo
https://github.com/56KBs/renovate-config

- [x] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

Discussion #9781

### PR DESCRIPTION
**Pull request by 56KBs**
## Changes:

When deciding whether to on-board, the global configuration was the only configuration loaded.
This can result in repositories not being on-boarded when the organisational presets being loaded would have resulted in dependencies being identified.

## Context:

Closes #9851 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — CHANGES_REQUESTED** [review]
Please create a refactoring pr first, so we can easier see whats changed

**Comment by 56KBs** [comment]
> Please create a refactoring pr first, so we can easier see whats changed

Thanks - For some context, the changes within `config.ts`, and the creation of `merge.ts` exist purely to break a circular dependency introduced from the functionality.

To clarify, would you like me to split those changes out into a refactoring PR, then the changes to fix the issue itself can be handled in a separate smaller PR?

**Comment by viceice** [comment]
> > Please create a refactoring pr first, so we can easier see whats changed
> 
> Thanks - For some context, the changes within `config.ts`, and the creation of `merge.ts` exist purely to break a circular dependency introduced from the functionality.
> 
> To clarify, would you like me to split those changes out into a refactoring PR, then the changes to fix the issue itself can be handled in a separate smaller PR?

Yes, please split. Thanks.

**Comment by viceice** [comment]
@56KBs Looks like your fix is gone?

**Comment by 56KBs** [comment]
> @56KBs Looks like your fix is gone?

Due to the splitting of the work into the refactoring PR, this PR ended up looking very confused & muddled (conflicts, etc) - I have recreated the branch from scratch and it can be found here #9888.

**Pull request closed without merging**
