### PR TITLE
fix(git): use semver and update simple-git import

### PR DESCRIPTION
**Pull request by viceice**
## Changes
- use semver for version check. we ensure a valid semver
- use named export for simple-git. fixes eslint warning. the previous bug is hopefully fixed.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by secustor** [comment]
Do we know why this has been semver-coerced so far?

**Review by rarkins — COMMENTED** [review]
Are you sure this works on all platforms? I thought we saw some where the git version string had build info appended, which is why coerced was used

**Comment by rarkins** [comment]
I recall us breaking people at least twice the first time we added this and I'm hesitant to make this change

**Comment by viceice** [comment]
> I recall us breaking people at least twice the first time we added this and I'm hesitant to make this change 

we now use simple-git to parse the version, so we get separate major, minor and patch values.
from that we build a valid semver.
check lines above my change.

**Comment by viceice** [comment]
https://github.com/renovatebot/renovate/blob/5b364e86e1113cb44adc98873dc13073f9a81bb5/lib/util/git/index.ts#L173-L179

**Review by rarkins — APPROVED** [review]

**Pull request merged**
