### PR TITLE
docs(manager/gitlabci): Add hint about environment variables

### PR DESCRIPTION
**Pull request by peschmae**
## Changes

Update the docs for the gitlabci manager, mentioning that CI components are supported, but shouldn't reference environment variables

## Context

Helps debugging issues if the CI compoent can't be resolved, as described in #27964 

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — COMMENTED** [review]
did you tried to use registry aliases to replace them with working urls?

**Comment by peschmae** [comment]
I didn't try to use the registry alias, to replace the reference to the environment variable, but that might work as well.

Maybe the GitLab manager could automatically add `$ci_server_fqdn` and `$ci_server_host` as registry aliases, if GitLab is used, since those environemnt variables are always referencing back to the currently used instance anyways.

**Comment by candrews** [comment]
> did you tried to use registry aliases to replace them with working urls?

Would that approach be to configuration like the following to Renovate's `config.js`, following the documentation at https://docs.renovatebot.com/configuration-options/#registryaliases?

```javascript
{
  "registryAliases": {
    "$ci_server_fqdn": process.env.CI_SERVER_FQDN,
    "$ci_server_host": process.env.CI_SERVER_HOST
  }
}
```

**Comment by ad-mcas** [comment]
> > did you tried to use registry aliases to replace them with working urls?
> 
> Would that approach be to configuration like the following to Renovate's `config.js`, following the documentation at https://docs.renovatebot.com/configuration-options/#registryaliases?
> 
> ```js
> {
>   "registryAliases": {
>     "$ci_server_fqdn": process.env.CI_SERVER_FQDN,
>     "$ci_server_host": process.env.CI_SERVER_HOST
>   }
> }
> ```
> 
> If so, this seems like a reasonable thing to include in the default configuration.


Seems that `registryAliases` is not used on gitlabci when it extract component and include (cf. https://github.com/renovatebot/renovate/blob/01d4d0db8af4037d619e04c7ae21848acf9e6682/lib/modules/manager/gitlabci/extract.ts#L148). 

So the hint indicated  by @peschmae is correct.

**Comment by candrews** [comment]
I think it would even better for the GitLab CI manager to support registry alias so I've created a PR adding that support: https://github.com/renovatebot/renovate/pull/28607

With that, my suggestion at https://github.com/renovatebot/renovate/pull/27965#issuecomment-2032710865 would work.

**Comment by candrews** [comment]
With the release of https://github.com/renovatebot/renovate/releases/tag/37.321.0 I suggest that this PR be closed.

**Comment by peschmae** [comment]
Fixed by #28607

**Pull request closed without merging**
