### PR TITLE
refactor(maven): Extract `getMavenUrl` function for caching purpose

### PR DESCRIPTION
**Pull request by zharinov**
ref #5538

### CODE REVIEW

**Comment by zharinov** [comment]
This is the intermediate PR in order to simplify main caching logic

**Comment by zharinov** [comment]
Tested on real repo: https://github.com/zharinov/renovate-test-maven/pulls

**Comment by zharinov** [comment]
Ready for review, main PR is coming soon, just need to adjust tests

**Review by viceice — APPROVED** [review]
LGTM

**Pull request merged**
