### PR TITLE
feat(bazel): Support GitLab-based http archives

### LINKED ISSUE #7945: Bazel: Update dependencies hosted on GitLab
**What would you like Renovate to be able to do?**

It'd be awesome if Renovate could update GitLab-hosted Bazel dependencies in the same way it does GitHub-hosted ones.
  

**Did you already have any implementation ideas?**

Currently Renovate seems to be GitHub-only, with a filter happening in the lines below. In the Renovate log, this manifests as  GitLab dependencies failing with  "Failed to find dependency in bazel WORKSPACE definition".
https://github.com/renovatebot/renovate/blob/c63ffa5d6232da8e68186389561531ac8f3c5943/lib/manager/bazel/extract.ts#L24-L26
I assume we'd also need GitLab release, tag, commit fetching logic, parallel to the GitHub case elsewhere, unless it's been implemented for something else. I haven't looked at that part of the codebase yet. Update: `gitlab-tags` datasource already built, says @viceice.

**Other notes**

#7851 and #7852 otherwise together made Renovate work great on all the rest of our (GitHub) dependencies. Only the GitLab minority remain. So, while this is lower priority than those were, adding GitLab support would take us to full dependency update automation with Renovate (!).

Here's an example of a GitLab-hosted Bazel dependency, in case it's helpful. It's for a popular C++ linear algebra library.
```
http_archive(
    name = "eigen",
    build_file = "@//Bazel:eigen.BUILD",
    url = "https://gitlab.com/libeigen/eigen/-/archive/3.3.8/eigen-3.3.8.tar.gz",
    sha256 = "146a480b8ed1fb6ac7cd33fec9eb5e8f8f62c3683b3f850094d9d5c35a92419a",
    strip_prefix = "eigen-3.3.8",
)
```

Related issue: #6847 starts with a general request for http_archives from other, non github sources but eventually gets scoped toward Go.

Thanks for considering!
Chris

### PR DESCRIPTION
**Pull request by zharinov**
## Context

- Closes: #7945

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by zharinov** [comment]
https://github.com/renovate-testing/test-7945-bazel-gitlab/pull/1/files
https://github.com/renovate-testing/test-7945-bazel-gitlab-1/pull/1/files

**Review by rarkins — COMMENTED** [review]
Do we need to worry if the pathName is empty or incomplete?

**Comment by zharinov** [comment]
I think it never will be like that:
```
> new URL('https://example.com').pathname
'/'
```

**Comment by rarkins** [comment]
But there's no validation for p0, p1, etc

**Comment by zharinov** [comment]
If `p3` and `p4` are strings with particular values, there is no way for `p0` and `p1` to be undefined, otherwise we return `null`

**Review by rarkins — APPROVED** [review]

**Pull request merged**
