### PR TITLE
[Feat] Requested Reviewers

### PR DESCRIPTION
**Pull request by SebastienElet**
This PR allow to specify requested reviewers for PR.

The github API is still in preview : https://developer.github.com/v3/pulls/review_requests/

### CODE REVIEW

**Comment by rarkins** [comment]
@SebastienElet thanks for the contribution. It has merge conflicts because I did a major refactor just today, so I will fix them and then push the changes.

**Comment by singapore** [comment]
I can't see if CircleCI is building/testing this PR. As per my reading of [their documentation](https://circleci.com/docs/fork-pr-builds/), it should have been built

**Comment by SebastienElet** [comment]
@rarkins i could refactor/rebase my PR if needed (and play with async/await 😀). Let me know if i should do it.

**Comment by rarkins** [comment]
Already done, hopefully merging soon

**Comment by rarkins** [comment]
Published as version 8.2.0 - thanks!

**Comment by SebastienElet** [comment]
Thanks a lot !

**Pull request merged**
