### PR TITLE
fix: log duration after rawExec error

### PR DESCRIPTION
**Pull request by rarkins**
## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by secustor — APPROVED** [review]

**Review by viceice — APPROVED** [review]
why round?

**Comment by rarkins** [comment]
> why round?

Copy pasted from the code below it on the "happy path". Maybe unnecessary but we can trim it later

**Comment by rarkins** [comment]
image

**Comment by viceice** [comment]
> image
> 

looks like it makes no sense. the substraction will never be a float, so round does nothing but uses time

**Pull request merged**
