### PR TITLE
fix(pipenv): Specify `Pipfile` location while executing `pipenv lock`

### LINKED ISSUE #8134: Renovate doesn't update `Pipfile.lock` file
**What Renovate type, platform and version are you using?**

Hosted App on GitHub.com

**Describe the bug**

I was able to reproduce https://github.com/renovatebot/renovate/issues/5117. In short, Renovate doesn't update `Pipfile.lock` file while upgrading a python dependency (manager is pipenv).

**Relevant debug logs**

```
DEBUG: Matched 1 file(s) for manager pipenv: pypi-test/Pipfile
DEBUG: pipenv.extractPackageFile()
DEBUG: Found pipenv package files
DEBUG: Found 1 package file(s)
INFO: Dependency extraction complete
{
  "baseBranch": "master",
  "stats": {
    "managers": {
      "pipenv": {
        "fileCount": 1,
        "depCount": 1
      }
    },
    "total": {
      "fileCount": 1,
      "depCount": 1
    }
  }
}
DEBUG: Package releases lookups complete
{
  "baseBranch": "master"
}
DEBUG: packageFiles with updates
{
  "config": {
    "pipenv": [
      {
        "packageFile": "pypi-test/Pipfile",
        "deps": [
          {
            "depType": "packages",
            "depName": "tenacity",
            "managerData": {},
            "currentValue": "==5.0.4",
            "datasource": "pypi",
            "depIndex": 0,
            "updates": [
              {
                "fromVersion": "5.0.4",
                "toVersion": "5.1.5",
                "newValue": "==5.1.5",
                "newMajor": 5,
                "newMinor": 1,
                "updateType": "minor",
                "isSingleVersion": true,
                "isRange": true
              },
              {
                "fromVersion": "5.0.4",
                "toVersion": "6.3.1",
                "newValue": "==6.3.1",
                "newMajor": 6,
                "newMinor": 3,
                "updateType": "major",
                "isSingleVersion": true,
                "isRange": true
              }
            ],
            "warnings": [],
            "fixedVersion": "5.0.4"
          }
        ],
        "registryUrls": [
          "https://pypi.org/simple"
        ],
        "constraints": {
          "python": "== 3.8.*"
        }
      }
    ]
  }
}
DEBUG: branchifyUpgrades
DEBUG: 2 flattened updates found: tenacity, tenacity
DEBUG: Returning 2 branch(es)
DEBUG: config.repoIsOnboarded=true
DEBUG: processRepo()
DEBUG: Processing 2 branches: renovate/tenacity-5.x, renovate/tenacity-6.x
DEBUG: Calculating hourly PRs remaining
DEBUG: Retrieving PR list
DEBUG: Retrieved 21 Pull Requests
DEBUG: currentHourStart=2020-12-24T13:00:00.000+00:00
DEBUG: PR hourly limit remaining: 2
DEBUG: Calculating prConcurrentLimit (20)
DEBUG: getBranchPr(renovate/tenacity-5.x)
DEBUG: findPr(renovate/tenacity-5.x, undefined, open)
DEBUG: getBranchPr(renovate/tenacity-6.x)
DEBUG: findPr(renovate/tenacity-6.x, undefined, open)
DEBUG: 0 PRs are currently open
DEBUG: PR concurrent limit remaining: 20
DEBUG: Calculated maximum PRs remaining this run
{
  "prsRemaining": 2
}
DEBUG: PullRequests limit = 2
DEBUG: getBranchPr(renovate/tenacity-5.x)(branch="renovate/tenacity-5.x")
DEBUG: findPr(renovate/tenacity-5.x, undefined, open)(branch="renovate/tenacity-5.x")
DEBUG: processBranch with 1 upgrades(branch="renovate/tenacity-5.x")
DEBUG: Setting current branch to master(branch="renovate/tenacity-5.x")
DEBUG: latest commit(branch="renovate/tenacity-5.x")
{
  "branchName": "master",
  "latestCommitDate": "2020-12-24T14:10:29+01:00"
}
DEBUG: getBranchPr(renovate/tenacity-5.x)(branch="renovate/tenacity-5.x")
DEBUG: findPr(renovate/tenacity-5.x, undefined, open)(branch="renovate/tenacity-5.x")
DEBUG: branchExists=false(branch="renovate/tenacity-5.x")
DEBUG: Branch has 1 upgrade(s)(branch="renovate/tenacity-5.x")
DEBUG: recreateClosed is false(branch="renovate/tenacity-5.x")
DEBUG: findPr(renovate/tenacity-5.x, Update dependency tenacity to v5.1.5, !open)(branch="renovate/tenacity-5.x")
DEBUG: prAlreadyExisted=false(branch="renovate/tenacity-5.x")
DEBUG: Checking schedule(at any time, null)(branch="renovate/tenacity-5.x")
DEBUG: No schedule defined(branch="renovate/tenacity-5.x")
DEBUG: Branch needs creating(branch="renovate/tenacity-5.x")
DEBUG: Using reuseExistingBranch: false(branch="renovate/tenacity-5.x")
DEBUG: manager.getUpdatedPackageFiles()(branch="renovate/tenacity-5.x")
{
  "reuseExistingBranch": false,
  "branchName": "renovate/tenacity-5.x"
}
DEBUG: Starting search at index 115(packageFile="pypi-test/Pipfile", branch="renovate/tenacity-5.x")
{
  "depName": "tenacity"
}
DEBUG: Found match at index 115(packageFile="pypi-test/Pipfile", branch="renovate/tenacity-5.x")
{
  "depName": "tenacity"
}
DEBUG: pipenv.extractPackageFile()(branch="renovate/tenacity-5.x")
DEBUG: Contents updated(packageFile="pypi-test/Pipfile", branch="renovate/tenacity-5.x")
{
  "depName": "tenacity"
}
DEBUG: pipenv.updateArtifacts(pypi-test/Pipfile)(branch="renovate/tenacity-5.x")
DEBUG: Using pipenv cache /tmp/renovate-cache/others/pipenv(branch="renovate/tenacity-5.x")
DEBUG: Using python constraint from config(branch="renovate/tenacity-5.x")
DEBUG: pipenv lock command(branch="renovate/tenacity-5.x")
{
  "cmd": "pipenv lock"
}
DEBUG: Using docker to execute(branch="renovate/tenacity-5.x")
DEBUG: Found pep440 version constraint - checking for a compatible docker.io/renovate/python image to use(branch="renovate/tenacity-5.x")
{
  "constraint": "== 3.8.*"
}
DEBUG: getLabels(https://index.docker.io, renovate/python, latest)(branch="renovate/tenacity-5.x")
DEBUG: Missing versioning(branch="renovate/tenacity-5.x")
DEBUG: Found compatible pep440 version(branch="renovate/tenacity-5.x")
{
  "constraint": "== 3.8.*",
  "version": "3.8.6"
}
DEBUG: Resolved tag constraint(branch="renovate/tenacity-5.x")
{
  "image": "docker.io/renovate/python",
  "tagConstraint": "== 3.8.*",
  "tagVersioning": "pep440",
  "tag": "3.8.6"
}
DEBUG: Fetching Docker image: docker.io/renovate/python:3.8.6(branch="renovate/tenacity-5.x")
DEBUG: Finished fetching Docker image(branch="renovate/tenacity-5.x")
DEBUG: Executing command(branch="renovate/tenacity-5.x")
{
  "command": "docker run --rm --name=renovate_python --label=renovate_child -v \"/mnt/renovate/gh/hisener/renovate-tests\":\"/mnt/renovate/gh/hisener/renovate-tests\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -v \"/tmp/renovate-cache/others/pipenv\":\"/tmp/renovate-cache/others/pipenv\" -e PIPENV_CACHE_DIR -w \"/mnt/renovate/gh/hisener/renovate-tests\" docker.io/renovate/python:3.8.6 bash -l -c \"pip install --user pipenv && pipenv lock\""
}
DEBUG: exec completed(branch="renovate/tenacity-5.x")
{
  "cmd": "docker run --rm --name=renovate_python --label=renovate_child -v \"/mnt/renovate/gh/hisener/renovate-tests\":\"/mnt/renovate/gh/hisener/renovate-tests\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -v \"/tmp/renovate-cache/others/pipenv\":\"/tmp/renovate-cache/others/pipenv\" -e PIPENV_CACHE_DIR -w \"/mnt/renovate/gh/hisener/renovate-tests\" docker.io/renovate/python:3.8.6 bash -l -c \"pip install --user pipenv && pipenv lock\"",
  "durationMs": 25403,
  "stdout": "Collecting pipenv\n  Downloading pipenv-2020.11.15-py2.py3-none-any.whl (3.9 MB)\nRequirement already satisfied: pip>=18.0 in /usr/local/python/3.8.6/lib/python3.8/site-packages (from pipenv) (20.3.3)\nRequirement already satisfied: setuptools>=36.2.1 in /usr/local/python/3.8.6/lib/python3.8/site-packages (from pipenv) (49.2.1)\nCollecting virtualenv-clone>=0.2.5\n  Downloading virtualenv_clone-0.5.4-py2.py3-none-any.whl (6.6 kB)\nCollecting certifi\n  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)\nCollecting virtualenv\n  Downloading virtualenv-20.2.2-py2.py3-none-any.whl (5.7 MB)\nCollecting appdirs<2,>=1.4.3\n  Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)\nCollecting distlib<1,>=0.3.1\n  Downloading distlib-0.3.1-py2.py3-none-any.whl (335 kB)\nCollecting filelock<4,>=3.0.0\n  Downloading filelock-3.0.12-py3-none-any.whl (7.6 kB)\nCollecting six<2,>=1.9.0\n  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)\nInstalling collected packages: six, filelock, distlib, appdirs, virtualenv-clone, virtualenv, certifi, pipenv\nSuccessfully installed appdirs-1.4.4 certifi-2020.12.5 distlib-0.3.1 filelock-3.0.12 pipenv-2020.11.15 six-1.15.0 virtualenv-20.2.2 virtualenv-clone-0.5.4\n",
  "stderr": "Creating a virtualenv for this project...\nPipfile: /mnt/renovate/gh/hisener/renovate-tests/Pipfile\nUsing /usr/local/python/3.8.6/bin/python3 (3.8.6) to create virtualenv...\n\r⠋ Creating virtual environment...\b\r⠙ Creating virtual environment...\b\r⠹ Creating virtual environment...\b\r⠸ Creating virtual environment...\b\r⠼ Creating virtual environment...\b\r⠴ Creating virtual environment...\b\r⠦ Creating virtual environment...\b\r⠧ Creating virtual environment...\b\r⠇ Creating virtual environment...\b\r⠏ Creating virtual environment...\b\r⠋ Creating virtual environment...\b\r⠙ Creating virtual environment...\b\r⠹ Creating virtual environment...\b\r⠸ Creating virtual environment...\b\r⠼ Creating virtual environment...\b\r⠴ Creating virtual environment...\b\r⠦ Creating virtual environment...\b\r⠧ Creating virtual environment...\b\r⠇ Creating virtual environment...\b\r⠏ Creating virtual environment...\b\r⠋ Creating virtual environment...\b\r⠙ Creating virtual environment...\b\r⠹ Creating virtual environment...\b\r⠸ Creating virtual environment...\b\r⠼ Creating virtual environment...\b\r⠴ Creating virtual environment...\b\r⠦ Creating virtual environment...\b\r⠧ Creating virtual environment...\b\r⠇ Creating virtual environment...\b\r⠏ Creating virtual environment...\b\r⠋ Creating virtual environment...\b\r⠙ Creating virtual environment...\b\r⠹ Creating virtual environment...\b\r⠸ Creating virtual environment...\b\r⠼ Creating virtual environment...\b\r⠴ Creating virtual environment...\b\r⠦ Creating virtual environment...\b\r⠧ Creating virtual environment...\b\r⠇ Creating virtual environment...created virtual environment CPython3.8.6.final.0-64 in 2793ms\n  creator CPython3Posix(dest=/home/ubuntu/.local/share/virtualenvs/renovate-tests-156F3VvU, clear=False, no_vcs_ignore=False, global=False)\n  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/ubuntu/.local/share/virtualenv)\n    added seed packages: pip==20.3.1, setuptools==51.0.0, wheel==0.36.1\n  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator\n\n\b✔ Successfully created virtual environment! \nVirtualenv location: /home/ubuntu/.local/share/virtualenvs/renovate-tests-156F3VvU\nCreating a Pipfile for this project...\nLocking [dev-packages] dependencies...\nLocking [packages] dependencies...\nUpdated Pipfile.lock (db4242)!\n"
}
DEBUG: Updated 1 package files(branch="renovate/tenacity-5.x")
DEBUG: No updated lock files in branch(branch="renovate/tenacity-5.x")
DEBUG: 1 file(s) to commit(branch="renovate/tenacity-5.x")
DEBUG: Committing files to branch renovate/tenacity-5.x(branch="renovate/tenacity-5.x")
INFO: Branch created(branch="renovate/tenacity-5.x")
{
  "commitSha": "4859a46"
}
DEBUG: Ensuring PR(branch="renovate/tenacity-5.x")
DEBUG: There are 0 errors and 0 warnings(branch="renovate/tenacity-5.x")
DEBUG: getBranchPr(renovate/tenacity-5.x)(branch="renovate/tenacity-5.x")
DEBUG: findPr(renovate/tenacity-5.x, undefined, open)(branch="renovate/tenacity-5.x")
DEBUG: Creating PR(branch="renovate/tenacity-5.x")
{
  "prTitle": "Update dependency tenacity to v5.1.5"
}
DEBUG: Creating PR(branch="renovate/tenacity-5.x")
{
  "title": "Update dependency tenacity to v5.1.5",
  "head": "hisener:renovate/tenacity-5.x",
  "base": "master",
  "draft": false
}
DEBUG: PR created(branch="renovate/tenacity-5.x")
{
  "pr": 23,
  "draft": false
}
DEBUG: Adding labels '' to #23(branch="renovate/tenacity-5.x")
INFO: PR created(branch="renovate/tenacity-5.x")
{
  "pr": 23,
  "prTitle": "Update dependency tenacity to v5.1.5"
}
DEBUG: Created Pull Request #23(branch="renovate/tenacity-5.x")
DEBUG: Checking #23 for automerge(branch="renovate/tenacity-5.x")
{
  "automerge": false,
  "automergeType": "pr",
  "automergeComment": "automergeComment"
}
DEBUG: No automerge(branch="renovate/tenacity-5.x")
DEBUG: getBranchPr(renovate/tenacity-6.x)(branch="renovate/tenacity-6.x")
DEBUG: findPr(renovate/tenacity-6.x, undefined, open)(branch="renovate/tenacity-6.x")
DEBUG: processBranch with 1 upgrades(branch="renovate/tenacity-6.x")
DEBUG: Setting current branch to master(branch="renovate/tenacity-6.x")
DEBUG: latest commit(branch="renovate/tenacity-6.x")
{
  "branchName": "master",
  "latestCommitDate": "2020-12-24T14:10:29+01:00"
}
DEBUG: getBranchPr(renovate/tenacity-6.x)(branch="renovate/tenacity-6.x")
DEBUG: findPr(renovate/tenacity-6.x, undefined, open)(branch="renovate/tenacity-6.x")
DEBUG: branchExists=false(branch="renovate/tenacity-6.x")
DEBUG: Branch has 1 upgrade(s)(branch="renovate/tenacity-6.x")
DEBUG: recreateClosed is false(branch="renovate/tenacity-6.x")
DEBUG: findPr(renovate/tenacity-6.x, Update dependency tenacity to v6, !open)(branch="renovate/tenacity-6.x")
DEBUG: prAlreadyExisted=false(branch="renovate/tenacity-6.x")
DEBUG: Checking schedule(at any time, null)(branch="renovate/tenacity-6.x")
DEBUG: No schedule defined(branch="renovate/tenacity-6.x")
DEBUG: Branch needs creating(branch="renovate/tenacity-6.x")
DEBUG: Using reuseExistingBranch: false(branch="renovate/tenacity-6.x")
DEBUG: manager.getUpdatedPackageFiles()(branch="renovate/tenacity-6.x")
{
  "reuseExistingBranch": false,
  "branchName": "renovate/tenacity-6.x"
}
DEBUG: Starting search at index 115(packageFile="pypi-test/Pipfile", branch="renovate/tenacity-6.x")
{
  "depName": "tenacity"
}
DEBUG: Found match at index 115(packageFile="pypi-test/Pipfile", branch="renovate/tenacity-6.x")
{
  "depName": "tenacity"
}
DEBUG: pipenv.extractPackageFile()(branch="renovate/tenacity-6.x")
DEBUG: Contents updated(packageFile="pypi-test/Pipfile", branch="renovate/tenacity-6.x")
{
  "depName": "tenacity"
}
DEBUG: pipenv.updateArtifacts(pypi-test/Pipfile)(branch="renovate/tenacity-6.x")
DEBUG: Using pipenv cache /tmp/renovate-cache/others/pipenv(branch="renovate/tenacity-6.x")
DEBUG: Using python constraint from config(branch="renovate/tenacity-6.x")
DEBUG: pipenv lock command(branch="renovate/tenacity-6.x")
{
  "cmd": "pipenv lock"
}
DEBUG: Using docker to execute(branch="renovate/tenacity-6.x")
DEBUG: Found pep440 version constraint - checking for a compatible docker.io/renovate/python image to use(branch="renovate/tenacity-6.x")
{
  "constraint": "== 3.8.*"
}
DEBUG: Missing versioning(branch="renovate/tenacity-6.x")
DEBUG: Found compatible pep440 version(branch="renovate/tenacity-6.x")
{
  "constraint": "== 3.8.*",
  "version": "3.8.6"
}
DEBUG: Resolved tag constraint(branch="renovate/tenacity-6.x")
{
  "image": "docker.io/renovate/python",
  "tagConstraint": "== 3.8.*",
  "tagVersioning": "pep440",
  "tag": "3.8.6"
}
DEBUG: Docker image is already prefetched: docker.io/renovate/python:3.8.6(branch="renovate/tenacity-6.x")
DEBUG: Executing command(branch="renovate/tenacity-6.x")
{
  "command": "docker run --rm --name=renovate_python --label=renovate_child -v \"/mnt/renovate/gh/hisener/renovate-tests\":\"/mnt/renovate/gh/hisener/renovate-tests\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -v \"/tmp/renovate-cache/others/pipenv\":\"/tmp/renovate-cache/others/pipenv\" -e PIPENV_CACHE_DIR -w \"/mnt/renovate/gh/hisener/renovate-tests\" docker.io/renovate/python:3.8.6 bash -l -c \"pip install --user pipenv && pipenv lock\""
}
DEBUG: exec completed(branch="renovate/tenacity-6.x")
{
  "cmd": "docker run --rm --name=renovate_python --label=renovate_child -v \"/mnt/renovate/gh/hisener/renovate-tests\":\"/mnt/renovate/gh/hisener/renovate-tests\" -v \"/tmp/renovate-cache\":\"/tmp/renovate-cache\" -v \"/tmp/renovate-cache/others/pipenv\":\"/tmp/renovate-cache/others/pipenv\" -e PIPENV_CACHE_DIR -w \"/mnt/renovate/gh/hisener/renovate-tests\" docker.io/renovate/python:3.8.6 bash -l -c \"pip install --user pipenv && pipenv lock\"",
  "durationMs": 21342,
  "stdout": "Collecting pipenv\n  Downloading pipenv-2020.11.15-py2.py3-none-any.whl (3.9 MB)\nRequirement already satisfied: pip>=18.0 in /usr/local/python/3.8.6/lib/python3.8/site-packages (from pipenv) (20.3.3)\nRequirement already satisfied: setuptools>=36.2.1 in /usr/local/python/3.8.6/lib/python3.8/site-packages (from pipenv) (49.2.1)\nCollecting virtualenv-clone>=0.2.5\n  Downloading virtualenv_clone-0.5.4-py2.py3-none-any.whl (6.6 kB)\nCollecting certifi\n  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)\nCollecting virtualenv\n  Downloading virtualenv-20.2.2-py2.py3-none-any.whl (5.7 MB)\nCollecting appdirs<2,>=1.4.3\n  Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)\nCollecting distlib<1,>=0.3.1\n  Downloading distlib-0.3.1-py2.py3-none-any.whl (335 kB)\nCollecting filelock<4,>=3.0.0\n  Downloading filelock-3.0.12-py3-none-any.whl (7.6 kB)\nCollecting six<2,>=1.9.0\n  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)\nInstalling collected packages: six, filelock, distlib, appdirs, virtualenv-clone, virtualenv, certifi, pipenv\nSuccessfully installed appdirs-1.4.4 certifi-2020.12.5 distlib-0.3.1 filelock-3.0.12 pipenv-2020.11.15 six-1.15.0 virtualenv-20.2.2 virtualenv-clone-0.5.4\n",
  "stderr": "Creating a virtualenv for this project...\nPipfile: /mnt/renovate/gh/hisener/renovate-tests/Pipfile\nUsing /usr/local/python/3.8.6/bin/python3 (3.8.6) to create virtualenv...\n\r⠋ Creating virtual environment...\b\r⠙ Creating virtual environment...\b\r⠹ Creating virtual environment...\b\r⠸ Creating virtual environment...\b\r⠼ Creating virtual environment...\b\r⠴ Creating virtual environment...\b\r⠦ Creating virtual environment...\b\r⠧ Creating virtual environment...\b\r⠇ Creating virtual environment...\b\r⠏ Creating virtual environment...\b\r⠋ Creating virtual environment...\b\r⠙ Creating virtual environment...\b\r⠹ Creating virtual environment...\b\r⠸ Creating virtual environment...\b\r⠼ Creating virtual environment...\b\r⠴ Creating virtual environment...\b\r⠦ Creating virtual environment...\b\r⠧ Creating virtual environment...\b\r⠇ Creating virtual environment...\b\r⠏ Creating virtual environment...\b\r⠋ Creating virtual environment...\b\r⠙ Creating virtual environment...\b\r⠹ Creating virtual environment...\b\r⠸ Creating virtual environment...\b\r⠼ Creating virtual environment...\b\r⠴ Creating virtual environment...\b\r⠦ Creating virtual environment...\b\r⠧ Creating virtual environment...\b\r⠇ Creating virtual environment...\b\r⠏ Creating virtual environment...\b\r⠋ Creating virtual environment...\b\r⠙ Creating virtual environment...\b\r⠹ Creating virtual environment...\b\r⠸ Creating virtual environment...\b\r⠼ Creating virtual environment...\b\r⠴ Creating virtual environment...\b\r⠦ Creating virtual environment...\b\r⠧ Creating virtual environment...\b\r⠇ Creating virtual environment...\b\r⠏ Creating virtual environment...\b\r⠋ Creating virtual environment...\b\r⠙ Creating virtual environment...\b\r⠹ Creating virtual environment...created virtual environment CPython3.8.6.final.0-64 in 3007ms\n  creator CPython3Posix(dest=/home/ubuntu/.local/share/virtualenvs/renovate-tests-156F3VvU, clear=False, no_vcs_ignore=False, global=False)\n  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/ubuntu/.local/share/virtualenv)\n    added seed packages: pip==20.3.1, setuptools==51.0.0, wheel==0.36.1\n  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator\n\n\b✔ Successfully created virtual environment! \nVirtualenv location: /home/ubuntu/.local/share/virtualenvs/renovate-tests-156F3VvU\nCreating a Pipfile for this project...\nLocking [dev-packages] dependencies...\nLocking [packages] dependencies...\nUpdated Pipfile.lock (db4242)!\n"
}
DEBUG: Updated 1 package files(branch="renovate/tenacity-6.x")
DEBUG: No updated lock files in branch(branch="renovate/tenacity-6.x")
DEBUG: 1 file(s) to commit(branch="renovate/tenacity-6.x")
DEBUG: Committing files to branch renovate/tenacity-6.x(branch="renovate/tenacity-6.x")
```

**Have you created a minimal reproduction repository?**

See:
- https://github.com/hisener/renovate-tests
- https://github.com/hisener/renovate-tests/pull/23
- https://github.com/hisener/renovate-tests/pull/24

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [x] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

See also https://github.com/renovatebot/renovate/discussions/8133.

### PR DESCRIPTION
**Pull request by hisener**
## Changes:

As the summary says, this change adds the `PIPENV_PIPFILE` environment variable to specify `Pipfile` location while executing `pipenv lock`. So that Renovate can update `Pipfile.lock` files under sub-directories.

## Context:

Fixes https://github.com/renovatebot/renovate/issues/8134.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] Unit tests + ran on a real repository

I haven't added a new unit test because I am not familiar with jest. Will have a look at it later if this change makes sense to reviewers.

### CODE REVIEW

**Review by viceice — COMMENTED** [review]
I think you simply need to run `yarn jest -u` to update snapshots.

**Review by viceice — COMMENTED** [review]
Have you done a real test? You can use `yarn start` to run renovate from current branch.

**Comment by rarkins** [comment]
I can't tell I'd this variable is meant to be relative or absolute. However if the problem is simply that we're not running the command within the subdirectory, maybe that's a better thing to fix instead?

**Comment by hisener** [comment]
> Have you done a real test? You can use `yarn start` to run renovate from current branch.

I've just tried but having some issue with `pipenv` https://github.com/hisener/renovate-tests/pull/27#issuecomment-751246018

> I can't tell I'd this variable is meant to be relative or absolute.

I think it supports both.

> However if the problem is simply that we're not running the command within the subdirectory, maybe that's a better thing to fix instead?

Works for me, looks like that's also what other managers do. Will try.

https://github.com/renovatebot/renovate/blob/19359d3114b7554f39a0c7d6ed2cac565e298ab6/lib/manager/poetry/artifacts.ts#L131

**Comment by hisener** [comment]
Verified using `docker run --rm -v $(pwd):/usr/src/app renovate/python:3.8.6 bash -l -c 'pip install --user pipenv && cd pypi-test && pipenv lock'` in test repo but I cannot run Renovate using yarn start. It fails during lock: `Command failed: pipenv lock Warning: Python 3.8 was not found on your system`. See https://github.com/hisener/renovate-tests/pull/27#issuecomment-751246018

I am using Renovate image to prevent installing everything on my machine

```
$ docker run -it --rm -v $(pwd):/usr/src/app renovate/renovate:24.10.1 bash
# yarn start --log-level=debug
```

Any idea why it fails?

**Comment by viceice** [comment]
Sure, try `yarn start --binarySource docker`, so renovate will start python in docker sidecar container.

**Comment by hisener** [comment]
That failed with `error: unknown option '--binarySource'` but solved it by adding `binarySource: 'docker'` to `config.js`. Then, while running Docker in Docker I got `/var/run/docker.sock: connect: permission denied` then I had to use `-u root`. But that also didn't work because of access to files under `/tmp`. Attaching my own `/tmp` also doesn't work: `Permission denied: '/tmp/renovate/cache/others/pipenv/pkgs'`. You can see in history of https://github.com/hisener/renovate-tests/pull/27#issuecomment-751246018.

Tbh, I don't think any of these related to this change. I gave up for now because I got to go. I am not sure I will be able to test without installing everything on my machine. :crying_cat_face:

**Comment by hisener** [comment]
I managed to test using the commands below after changing the owner of `/var/run/docker.sock`. Not a good solution but it worked (`sudo chown $USER /var/run/docker.sock`).

```
$ docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/:/tmp/ -v $(pwd):/opt/renovate renovate/renovate:24.10.1 bash
# cd /opt/renovate/
# yarn start --log-level=debug
```

Now, it updated `Pipfile.lock`, see https://github.com/hisener/renovate-tests/pull/27.

Open point: why didn't global binary mode work (without `binarySource: 'docker'`)? I.e:
```
$ docker run -it --rm -v $(pwd)/opt/renovate renovate/renovate:24.10.1 bash
# cd /opt/renovate/
# yarn start --log-level=debug
...
Command failed: pipenv lock Warning: Python 3.8 was not found on your system
```
See https://github.com/hisener/renovate-tests/pull/28#issuecomment-751271658.

**Comment by viceice** [comment]
It's because you test project request python 3.8 and you have 3.9 locally. So pipenv fails.

You should use a `config.js` in renovate git root, it will be ignored by git. You need to configure the renovate docker user too, as it runs as ubuntu (1000) by default.

You should also not change the docker socket access. Instead add your user to the docker group to access the socket.

**Review by viceice — APPROVED** [review]

**Comment by hisener** [comment]
> It's because you test project request python 3.8 and you have 3.9 locally. So pipenv fails.

Does it mean that the fix will not work for `renovate/renovate` image that contains everything? That's the one I am using.

> You should use a `config.js` in renovate git root, it will be ignored by git. You need to configure the renovate docker user too, as it runs as ubuntu (1000) by default.

Which user do I need to use?

> You should also not change the docker socket access. Instead add your user to the docker group to access the socket.

My user was already in docker group though. I am getting the same error in my MacBook. It might be because I am using Docker 20.10 and this image has 19.03. 🤷‍♂️ 

```
$ docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/:/tmp/ -v $(pwd):/opt/renovate renovate/renovate:24.10.1 bash
# docker container ps
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/json: dial unix /var/run/docker.sock: connect: permission denied
```

**Comment by viceice** [comment]
> > It's because you test project request python 3.8 and you have 3.9 locally. So pipenv fails.
> 
> Does it mean that the fix will not work for `renovate/renovate` image that contains everything? That's the one I am using.


Yes, i think so. Can you switch to the slim image? Then all external tool run in sidecar containers.


> > You should use a `config.js` in renovate git root, it will be ignored by git. You need to configure the renovate docker user too, as it runs as ubuntu (1000) by default.
> 
> Which user do I need to use?


It should be your current uid.


> > You should also not change the docker socket access. Instead add your user to the docker group to access the socket.
> 
> My user was already in docker group though. I am getting the same error in my MacBook. It might be because I am using Docker 20.10 and this image has 19.03. 🤷‍♂️ 
> 
> ```
> $ docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/:/tmp/ -v $(pwd):/opt/renovate renovate/renovate:24.10.1 bash
> # docker container ps
> Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/json: dial unix /var/run/docker.sock: connect: permission denied
> ```

🤔 Not sure what's going on. Can we move further discussion on this to a github discussion please.

**Comment by hisener** [comment]
> Yes, i think so. Can you switch to the slim image? Then all external tool run in sidecar containers.

Sidecar works as expected, check https://github.com/hisener/renovate-tests/pull/27. I just couldn't test "global" binary source path (https://github.com/hisener/renovate-tests/pull/28).

> 🤔 Not sure what's going on. Can we move further discussion on this to a github discussion please.

Sure.

**Comment by hisener** [comment]
@viceice @rarkins As I concerned it doesn't work for older Python versions when the `binarySource` is set to global. Filed https://github.com/renovatebot/renovate/issues/8163.

**Pull request merged**
