### PR TITLE
chore(eslint): update eslint rules

### PR DESCRIPTION
**Pull request by viceice**
This pr enables previously disabled rules.

Currently only as warning, until all warnings are fixed

- [ ] Should we fix all warnigs in this pr and change config to error?

### CODE REVIEW

**Comment by rarkins** [comment]
image

**Comment by ViceIce** [comment]
@rarkins  I now, a lot warnings. 😅

**Review by JamieMagee — APPROVED** [review]
I'm fine with "as warning" for now. We can tackle them as we go along.

Any reason for these specific ones, and not the rest?

**Comment by rarkins** [comment]
I think we're already at risk here of creating a lot of "noise" that gets ignored. e.g. when there's 845 warnings, people aren't going to notice the 846th one. So I think I prefer to get warnings down to zero first before adding more, what do you think? We should probably also have separate issues for each rule describing the plan for fixing them.

**Comment by ViceIce** [comment]
Sounds reasonable

**Pull request merged**
