### PR TITLE
fix: handle parsing of invalid YAML in .travis.yml

### LINKED ISSUE #2492: Handle/skip invalid YML in .travis.yml
Example: 

```
after_deploy:
  - "curl -H 'Content-Type: application/json' --data '{\'build\': true}' -X POST $DOCKER_HUB_URL;"
```

### PR DESCRIPTION
**Pull request by nihalwasheretoo**
Closes #2492

### CODE REVIEW

**Comment by nihal9ns** [comment]
@rarkins finally it's ready

**Comment by rarkins** [comment]
@nihal9ns you deleted `yarn.lock`

**Review by viceice — CHANGES_REQUESTED** [review]
Please do not remove `yarn.lock`

**Comment by nihal9ns** [comment]
@rarkins @ViceIce sorry about that, didn't realise. Added yarn.lock which is currently in the master branch.

**Review by viceice — APPROVED** [review]
LGTM

**Pull request merged**
