### PR TITLE
fix(manager/gitlabci-include): Local include updates

### LINKED ISSUE #6713: gitlab-ci include:local not working
**What Renovate type are you using?**

I'm using `renovate/renovate:21.25.0` with Gitlab CI.

**Describe the bug**

Gitlab CI `include:local` is still not working. I tried to add support with the following pr and now Renovate recognizes the dependencies but is unable to update: https://github.com/renovatebot/renovate/pull/6630

**Relevant debug logs**

```
[...]
DEBUG: latest commit (repository=jonmi/gitlab-include-demo)
        "branchName": "master",
        "latestCommitDate": "2020-07-08 20:00:35 +0000"
 DEBUG: getLabels(https://index.docker.io, library/node, latest) (repository=jonmi/gitlab-include-demo)
 DEBUG: getManifestResponse(https://index.docker.io, library/node, latest) (repository=jonmi/gitlab-include-demo)
 DEBUG: Package releases lookups complete (repository=jonmi/gitlab-include-demo)
        "baseBranch": "master"
 DEBUG: packageFiles with updates (repository=jonmi/gitlab-include-demo)
        "config": {
          "gitlabci": [
            {
              "packageFile": ".gitlab-ci.yml",
              "manager": "gitlabci",
              "deps": [
                {
                  "depName": "alpine",
                  "replaceString": "alpine",
                  "autoReplaceStringTemplate": "{{depName}}{{#if newValue}}:{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
                  "datasource": "docker",
                  "depType": "image",
                  "depIndex": 0,
                  "updates": [],
                  "warnings": [],
                  "skipReason": "unsupported-value"
                }
              ]
            }
          ],
          "gitlabci-include": [
            {
              "packageFile": ".gitlab-ci.yml",
              "manager": "gitlabci-include",
              "deps": [
                {
                  "depName": "node",
                  "currentValue": "12.18.2-alpine",
                  "replaceString": "node:12.18.2-alpine",
                  "autoReplaceStringTemplate": "{{depName}}{{#if newValue}}:{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
                  "datasource": "docker",
                  "commitMessageTopic": "Node.js",
                  "depType": "image",
                  "depIndex": 0,
                  "updates": [
                    {
                      "fromVersion": "12.18.2-alpine",
                      "toVersion": "12.18.2",
                      "newValue": "12.18.2",
                      "newMajor": 12,
                      "newMinor": 18,
                      "updateType": "minor",
                      "isSingleVersion": true
                    },
                    {
                      "fromVersion": "12.18.2-alpine",
                      "toVersion": "14.5.0",
                      "newValue": "14.5.0",
                      "newMajor": 14,
                      "newMinor": 5,
                      "updateType": "major",
                      "isSingleVersion": true
                    }
                  ],
                  "warnings": [],
                  "sourceUrl": "https://github.com/nodejs/node",
                  "dockerRegistry": "https://index.docker.io",
                  "dockerRepository": "library/node"
                }
              ]
            }
          ]
        }
 DEBUG: branchifyUpgrades (repository=jonmi/gitlab-include-demo)
 DEBUG: 1 flattened updates found: node (repository=jonmi/gitlab-include-demo)
 DEBUG: Returning 1 branch(es) (repository=jonmi/gitlab-include-demo)
  WARN: No github.com token has been configured. Skipping release notes retrieval (repository=jonmi/gitlab-include-demo)
        "manager": "gitlabci-include",
        "depName": "node",
        "sourceUrl": "https://github.com/nodejs/node"
 DEBUG: config.repoIsOnboarded=true (repository=jonmi/gitlab-include-demo)
 DEBUG: processRepo() (repository=jonmi/gitlab-include-demo)
 DEBUG: Processing 1 branch: renovate/docker-node-12.x (repository=jonmi/gitlab-include-demo)
 DEBUG: Calculating hourly PRs remaining (repository=jonmi/gitlab-include-demo)
 DEBUG: currentHourStart=1594238400000 (repository=jonmi/gitlab-include-demo)
 DEBUG: PR hourly limit remaining: 2 (repository=jonmi/gitlab-include-demo)
 DEBUG: Enforcing prConcurrentLimit (20) (repository=jonmi/gitlab-include-demo)
 DEBUG: 0 PRs are currently open (repository=jonmi/gitlab-include-demo)
 DEBUG: PR concurrent limit remaining: 20 (repository=jonmi/gitlab-include-demo)
 DEBUG: Calculated maximum PRs remaining this run (repository=jonmi/gitlab-include-demo)
        "prsRemaining": 2
 DEBUG: processBranch with 1 upgrades (repository=jonmi/gitlab-include-demo, dependencies=node, branch=renovate/docker-node-12.x)
 DEBUG: Setting baseBranch to master (repository=jonmi/gitlab-include-demo, branch=renovate/docker-node-12.x)
 DEBUG: Setting baseBranch to master (repository=jonmi/gitlab-include-demo, branch=renovate/docker-node-12.x)
 DEBUG: latest commit (repository=jonmi/gitlab-include-demo, branch=renovate/docker-node-12.x)
        "branchName": "master",
        "latestCommitDate": "2020-07-08 20:00:35 +0000"
 DEBUG: getBranchPr(renovate/docker-node-12.x) (repository=jonmi/gitlab-include-demo, branch=renovate/docker-node-12.x)
 DEBUG: branchExists=false (repository=jonmi/gitlab-include-demo, branch=renovate/docker-node-12.x)
 DEBUG: Branch has 1 upgrade(s) (repository=jonmi/gitlab-include-demo, branch=renovate/docker-node-12.x)
 DEBUG: recreateClosed is false (repository=jonmi/gitlab-include-demo, branch=renovate/docker-node-12.x)
 DEBUG: findPr(renovate/docker-node-12.x, chore(deps): update node docker tag to v12.18.2, !open) (repository=jonmi/gitlab-include-demo, branch=renovate/docker-node-12.x)
 DEBUG: prAlreadyExisted=false (repository=jonmi/gitlab-include-demo, branch=renovate/docker-node-12.x)
 DEBUG: Checking schedule(at any time, null) (repository=jonmi/gitlab-include-demo, branch=renovate/docker-node-12.x)
 DEBUG: No schedule defined (repository=jonmi/gitlab-include-demo, branch=renovate/docker-node-12.x)
 DEBUG: Branch needs creating (repository=jonmi/gitlab-include-demo, branch=renovate/docker-node-12.x)
 DEBUG: Using reuseExistingBranch: false (repository=jonmi/gitlab-include-demo, branch=renovate/docker-node-12.x)
 DEBUG: manager.getUpdatedPackageFiles() (repository=jonmi/gitlab-include-demo, branch=renovate/docker-node-12.x)
        "reuseExistingBranch": false,
        "branchName": "renovate/docker-node-12.x"
  WARN: Cannot find replaceString in current file content (repository=jonmi/gitlab-include-demo, packageFile=.gitlab-ci.yml, branch=renovate/docker-node-12.x)
        "depName": "node",
        "existingContent": "include:\n  - local: 'tag.yml'\n\nstages:\n- pass\n\npass:\n  stage: pass\n  image: alpine\n  script:\n    - echo pass\n",
        "replaceString": "node:12.18.2-alpine"
 DEBUG: No content changed (repository=jonmi/gitlab-include-demo, packageFile=.gitlab-ci.yml, branch=renovate/docker-node-12.x)
        "depName": "node"
[...]
```

**To Reproduce**

Demo Gitlab Repo: https://gitlab.com/jonmi/gitlab-include-demo

**Additional context**

It seems like the problem is that Renovate searches in the wrong file for the version string. I'm not 100% sure what's necessary but after looking into the existing code I think custom `extractAllPackageFiles` and `update` methods need to be implemented (as done for maven). Maybe somebody has the time to look into it.

### PR DESCRIPTION
**Pull request by l0nax**
## Changes:

This PR fixes the problems as described in #6713 where the `include:local` blocks from the GitLab CI YAML file where ignored by renovate.

## Context:

Fixes #6713 

Related to #6745

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — CHANGES_REQUESTED** [review]
Sorry, but this is the wrong way to solve this.

The manager needs to be refactored to use `extractAllPackageFiles`.
https://github.com/renovatebot/renovate/blob/586a83ec8fbe12205a7f3add1f2de98f5ee4ef6c/lib/manager/common.ts#L242-L245

there it's possible to return the file.

**Comment by rarkins** [comment]
?!

**Comment by rarkins** [comment]
image

@l0nax are you running `pull[bot]`? It looks like it force-pushed to your `master`, overriding your commits, then triggering GitHub to close the MR because there's 0 files changed. However it's showing up as mistakenly "Merged" and with me as the committer (because I committed to master last).

**Comment by l0nax** [comment]
@rarkins No, I didn't configure the `pull[bot]`.

**Comment by viceice** [comment]
@l0nax but it's enabled on your repo and has overwritten you master

image

So you should never use master /main branch to open pr's ;)

**Comment by l0nax** [comment]
Thanks, I will notice this for the future :)

@viceice but not all managers have `extractAllPackageFiles` implemented.

**Comment by l0nax** [comment]
@viceice since `doAutoReplace` does call `checkBranchDepsMatchBaseDeps` which does use the `extractPackageFile` function, how should it be implemented that the correct file will be updated and not the package file (i.e. `.gitlab-ci.yaml`)?

**Comment by viceice** [comment]
`extractAllPackageFiles` extracts all files at once and returns deps per package (with corresponding file name) so it should simply work, because renovate simply replaces the version in the target file when using auto replace.

**Comment by rarkins** [comment]
I think the Batect manager was a good example of doing this?

**Comment by l0nax** [comment]
So the `extractAllPackageFiles` should be added to the `gitlabci` manager?

**Comment by viceice** [comment]
It should replace the existing `extractPackageFile`

**Comment by l0nax** [comment]
@viceice I've reimplemented it and created a new PR: #8810

**Pull request merged**
