### PR TITLE
feat(platform/azure): handle disabled repos without exit

### LINKED ISSUE #13013: Renovate exit with code 0 when a Azure repository is disabled
### What would you like Renovate to be able to do?

I would like Renovate doesn't exit with 0 when Azure Repository is disabled.

Right now, I use renovate running on Kubernetes as a CronJob.
If I disable a repos in Azure, renovate will fail, and Job will restart continuously.

### If you have any ideas on how this should be implemented, please tell us here.

Maybe by setting WARNING instear ERROR level when renovate fails to access to the repository ?

Thanks for your support

### Is this a feature you are interested in implementing yourself?

No

<details><summary>Click me to see logs</summary>

```


DEBUG: Using RE2 as regex engine
DEBUG: Parsing configs
DEBUG: Converting GITHUB_COM_TOKEN into a global host rule
DEBUG: File config
       "config": {
         "platform": "azure",
         "endpoint": "https://dev.azure.com/my-company",
         "autodiscover": true,
         "autodiscoverFilter": "IFS/*",
         "schedule": [
           "after 6pm every weekday",
           "before 5am every weekday",
           "every weekend"
         ],
         "prConcurrentLimit": 2,
         "gitAuthor": "Renovate Bot <renovate-bot@my-company.fr>",
         "dryRun": false
       }
DEBUG: CLI config
       "config": {}
DEBUG: Env config
       "config": {
         "hostRules": [
           {"hostType": "github", "matchHost": "github.com", "token": "***********"}
         ],
         "token": "***********"
       }
DEBUG: Combined config
       "config": {
         "platform": "azure",
         "endpoint": "https://dev.azure.com/my-company",
         "autodiscover": true,
         "autodiscoverFilter": "IFS/*",
         "schedule": [
           "after 6pm every weekday",
           "before 5am every weekday",
           "every weekend"
         ],
         "prConcurrentLimit": 2,
         "gitAuthor": "Renovate Bot <renovate-bot@my-company.fr>",
         "dryRun": false,
         "hostRules": [
           {"hostType": "github", "matchHost": "github.com", "token": "***********"}
         ],
         "token": "***********"
       }
DEBUG: Adding trailing slash to endpoint
DEBUG: Found valid git version: 2.34.1
DEBUG: Using configured gitAuthor (Renovate Bot <renovate-bot@my-company.fr>)
DEBUG: Adding token authentication for dev.azure.com to hostRules
DEBUG: Using baseDir: /tmp/renovate
DEBUG: Using cacheDir: /tmp/renovate/cache
DEBUG: Initializing Renovate internal cache into /tmp/renovate/cache/renovate/renovate-cache-v1
DEBUG: Commits limit = null
DEBUG: Autodiscovering Azure DevOps repositories
 INFO: Autodiscovered repositories
       "length": 1,
       "repositories": ["IFS/MyCompany.MyProject"]
DEBUG: Clearing hostRules
DEBUG: Adding token authentication for github.com to hostRules
DEBUG: Adding token authentication for dev.azure.com to hostRules
 INFO: Repository started (repository=IFS/MyCompany.MyProject)
       "renovateVersion": "29.36.2"
DEBUG: Using localDir: /tmp/renovate/repos/azure/IFS/MyCompany.MyProject (repository=IFS/MyCompany.MyProject)
DEBUG: initRepo("IFS/MyCompany.MyProject") (repository=IFS/MyCompany.MyProject)
DEBUG: Repository details (repository=IFS/MyCompany.MyProject)
       "repositoryDetails": {
         "id": "ReposId",
         "name": "MyCompany.MyProject",
         "url": "https://dev.azure.com/my-company/ProjectId/_apis/git/repositories/ReposId",
         "project": {
           "id": "ProjectId",
           "name": "IFS",
           "url": "https://dev.azure.com/my-company/_apis/projects/ProjectId",
           "state": "wellFormed",
           "revision": 662,
           "visibility": 0,
           "lastUpdateTime": "2021-07-21T08:31:15.143Z"
         },
         "defaultBranch": "refs/heads/main",
         "size": 642328,
         "remoteUrl": "https://my-company@dev.azure.com/my-company/IFS/_git/MyCompany.MyProject",
         "sshUrl": "git@ssh.dev.azure.com:v3/my-company/IFS/MyCompany.MyProject",
         "webUrl": "https://dev.azure.com/my-company/IFS/_git/MyCompany.MyProject",
         "isDisabled": true
       }
DEBUG: IFS/MyCompany.MyProject owner = ?owner? (repository=IFS/MyCompany.MyProject)
DEBUG: IFS/MyCompany.MyProject default branch = main (repository=IFS/MyCompany.MyProject)
DEBUG: git error (repository=IFS/MyCompany.MyProject)
       "err": {
         "task": {
           "commands": [
             "-c",
             "http.extraheader=AUTHORIZATION: basic **redacted**",
             "ls-remote",
             "--heads",
             "https://my-company@dev.azure.com/my-company/IFS/_git/MyCompany.MyProject"
           ],
           "format": "utf-8",
           "parser": "[function]"
         },
         "message": "remote: TF401019: The Git repository with name or identifier MyCompany.MyProject does not exist or you do not have permissions for the operation you are attempting.\nfatal: repository 'https://dev.azure.com/my-company/IFS/_git/MyCompany.MyProject/' not found\n",
         "stack": "Error: remote: TF401019: The Git repository with name or identifier MyCompany.MyProject does not exist or you do not have permissions for the operation you are attempting.\nfatal: repository 'https://dev.azure.com/my-company/IFS/_git/MyCompany.MyProject/' not found\n\n    at Object.action (/usr/src/app/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:38:28)\n    at PluginStore.exec (/usr/src/app/node_modules/simple-git/src/lib/plugins/plugin-store.ts:24:29)\n    at /usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:114:40\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:111:14)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:88:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
       }
ERROR: Repository has unknown error (repository=IFS/MyCompany.MyProject)
       "err": {
         "task": {
           "commands": [
             "-c",
             "http.extraheader=AUTHORIZATION: basic **redacted**",
             "ls-remote",
             "--heads",
             "https://my-company@dev.azure.com/my-company/IFS/_git/MyCompany.MyProject"
           ],
           "format": "utf-8",
           "parser": "[function]"
         },
         "message": "remote: TF401019: The Git repository with name or identifier MyCompany.MyProject does not exist or you do not have permissions for the operation you are attempting.\nfatal: repository 'https://dev.azure.com/my-company/IFS/_git/MyCompany.MyProject/' not found\n",
         "stack": "Error: remote: TF401019: The Git repository with name or identifier MyCompany.MyProject does not exist or you do not have permissions for the operation you are attempting.\nfatal: repository 'https://dev.azure.com/my-company/IFS/_git/MyCompany.MyProject/' not found\n\n    at Object.action (/usr/src/app/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:38:28)\n    at PluginStore.exec (/usr/src/app/node_modules/simple-git/src/lib/plugins/plugin-store.ts:24:29)\n    at /usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:114:40\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:111:14)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:88:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
       }
DEBUG: Unknown res (repository=IFS/MyCompany.MyProject)
       "res": "unknown-error"
DEBUG: Repository timing splits (milliseconds) (repository=IFS/MyCompany.MyProject)
       "splits": {},
       "total": 1013
 INFO: Repository finished (repository=IFS/MyCompany.MyProject)
       "durationMs": 1013
DEBUG: Renovate exiting
 INFO: Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 50,
           "logContext": "",
           "repository": "IFS/MyCompany.MyProject",
           "err": {
             "task": {
               "commands": [
                 "-c",
                 "http.extraheader=AUTHORIZATION: basic **redacted**",
                 "ls-remote",
                 "--heads",
                 "https://my-company@dev.azure.com/my-company/IFS/_git/MyCompany.MyProject"
               ],
               "format": "utf-8",
               "parser": "[function]"
             },
             "message": "remote: TF401019: The Git repository with name or identifier MyCompany.MyProject does not exist or you do not have permissions for the operation you are attempting.\nfatal: repository 'https://dev.azure.com/my-company/IFS/_git/MyCompany.MyProject/' not found\n",
             "stack": "Error: remote: TF401019: The Git repository with name or identifier MyCompany.MyProject does not exist or you do not have permissions for the operation you are attempting.\nfatal: repository 'https://dev.azure.com/my-company/IFS/_git/MyCompany.MyProject/' not found\n\n    at Object.action (/usr/src/app/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:38:28)\n    at PluginStore.exec (/usr/src/app/node_modules/simple-git/src/lib/plugins/plugin-store.ts:24:29)\n    at /usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:114:40\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:111:14)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:88:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
           },
           "msg": "Repository has unknown error"
         }
       ]
Copy/paste any log here, between the starting and ending backticks
```

</details>

### PR DESCRIPTION
**Pull request by olegkrivtsov**
## Changes:

Renovate exit with code 0 when a Azure repository is disabled #13013

## Context:

Closes #13013

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — APPROVED** [review]

**Comment by HonkingGoose** [comment]
This change is not shown in the actual release notes for `31.11.5`.

The change got merged with a proper "Conventional Commits" PR title: `feat(platform/azure): handle disabled repos without exit`.
But the commit message on the `main` branch is: `Fix issue (#13225)`: https://github.com/renovatebot/renovate/commit/7d60807039e4c3876dcac32ff3f618ee2600e3dd

- Release notes for `31.11.5`: https://github.com/renovatebot/renovate/releases/tag/31.11.5
- Diff from GitHub between https://github.com/renovatebot/renovate/compare/31.11.4...31.11.5

**Comment by viceice** [comment]
fixed

**Comment by HonkingGoose** [comment]
@viceice I see that you added this change to the "Bug Fixes" section in the release notes, but I think this is a `feat:` type commit, so it should go under a "Features" section in the release notes? Or is this actually more of a "bugfix" change?

Maybe you should change it so that its under it own Feature section, like in this changelog: https://github.com/renovatebot/renovate/releases/tag/31.11.0

**Comment by viceice** [comment]
i think a bugfix is ok for that small change 🤗

**Pull request merged**
