### PR TITLE
feat: make some managers lazy

### PR DESCRIPTION
**Pull request by viceice**
## Changes
Make `npm`, `gradle` and `terraform` lazy loading. 
I see ~10sec test time improvement (~130sec -> 120sec)

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by viceice** [comment]
please feedback if i should continue, lot's of work.

**Comment by rarkins** [comment]
I don't really like the look of this at first glance. Can the lazy loading be pushed to the manager index to both remove duplication but also to keep manager implementations simple?

**Review by rarkins — CHANGES_REQUESTED** [review]
I think we need to find a different way if we are to do this. This proposed approach causes too much "undesirable" and duplicate changes to our manager modules

**Comment by JamieMagee** [comment]
I agree with @rarkins. A dependency injection container, like [inversify][1], which controls the lifetime of objects might be a better way to do something like this.

[1]: https://inversify.io/

**Comment by viceice** [comment]
> I agree with @rarkins. A dependency injection container, like [inversify](https://inversify.io/), which controls the lifetime of objects might be a better way to do something like this.

That would not solve the initial loading of all deps. Everything would be loaded advance again. 😕 


i'll try a diffenrent aproach. at least this idea brought better test perf, because we don't load all managers into each test.

**Comment by JamieMagee** [comment]
> That would not solve the initial loading of all deps. Everything would be loaded advance again. confused

True, I was more thinking of datasources, which are classes, and you don't have to incur the cost until you call the constructor.

**Comment by viceice** [comment]
> > That would not solve the initial loading of all deps. Everything would be loaded advance again. confused
> 
> True, I was more thinking of datasources, which are classes, and you don't have to incur the cost until you call the constructor.

this still load all files and all transitive deps if they're not imported dynamically inside the constructor.

**Pull request closed without merging**
