### PR TITLE
docs: fix preset layout

### LINKED ISSUE #13348: Fix Markdown generation script so output is correct
**What browser are you using?**

Firefox 94.0.2 (64 bit) on Windows 11

**Describe the bug**

The config JSON is displayed too big.

Affected page example: https://docs.renovatebot.com/presets-config/

bad-display-config-preset

**Steps to reproduce**

1. Edit the `mkdocs.yml` file, like this:
    ```yaml
    markdown_extensions:
      - meta
      - pymdownx.highlight <--- add this
      - pymdownx.superfences <-- add this
    ```
1. Run `make && mkdocs serve`.
1. Open development server preview and go to the `Full Config Presets` page via the sidebar.
1. See display of JSON config in too big font size

**Additional context**

The JSON displayed properly before PR renovatebot/renovatebot.github.io#97. I'm not sure _why_ it breaks though.

I suspect the breakage is due to the auto-generated content of the pages, as the Markdown files where the code blocks are hard-coded in the files themselves all display properly.

### PR DESCRIPTION
**Pull request by viceice**
## Changes:
- add newline after preset json
- declare preset json as json

## Context:
- fixes #13348
- renovatebot/renovatebot.github.io#125

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by rarkins — APPROVED** [review]

**Comment by HonkingGoose** [comment]
There's a condition that's not met:

- **license/cla** _Expected — Waiting for status to be reported_

Not sure why the CLA check is still pending, maybe there's a problem with the CLA check servers?

**Review by HonkingGoose — COMMENTED** [review]
Looks okay to me, just from looking at it.

I would like to know if this actually works before merging it, but I don't think there's a way that's easy enough for me to do myself...

**Comment by viceice** [comment]
> Looks okay to me, just from looking at it.
> 
> I would like to know if this actually works before merging it, but I don't think there's a way that's easy enough for me to do myself...

before:
````md
### config:base

Default base configuration for all languages

```
{
  "extends": [
    ":dependencyDashboard",
    ":semanticPrefixFixDepsChoreOthers",
    ":ignoreModulesAndTests",
    ":autodetectPinVersions",
    ":prHourlyLimit2",
    ":prConcurrentLimit10",
    "group:monorepos",
    "group:recommended",
    "workarounds:all"
  ]
}
```
----

### config:js-app
````

after:

````md

### config:base

Default base configuration for all languages

```json
{
  "extends": [
    ":dependencyDashboard",
    ":semanticPrefixFixDepsChoreOthers",
    ":ignoreModulesAndTests",
    ":autodetectPinVersions",
    ":prHourlyLimit2",
    ":prConcurrentLimit10",
    "group:monorepos",
    "group:recommended",
    "workarounds:all"
  ]
}
```

----

### config:js-app
````

**Comment by HonkingGoose** [comment]
That looks a lot better! 🥳

**Pull request merged**
