### PR TITLE
ci(workflow): add cache to workflows using actions/setup-node

### PR DESCRIPTION
**Pull request by oscard0m**
## Description

Add `cache` to workflows using `actions/setup-node`

## Context

`setup-node` GitHub Action just released a new option to add cache to steps using it.

You can find the details here: https://github.blog/changelog/2021-07-02-github-actions-setup-node-now-supports-dependency-caching/

---

🤖 This PR has been generated automatically by [this octoherd script](https://github.com/oscard0m/octoherd-script-add-cache-to-node-github-action), feel free to run it in your GitHub user/org repositories! 💪🏾

### CODE REVIEW

**Review by viceice — CHANGES_REQUESTED** [review]
This is wrong, we use yarn.

It has changed quotes which needs to be reverted.

Old cache options need to be removed

**Comment by rarkins** [comment]
@oscard0m I don't like the idea of uninvited automated PRs unless they're 100% correct and welcome. 

Cc @gr2m

**Comment by HonkingGoose** [comment]
I've opened issue #10706 to discuss the work needed, and to track this change properly.

**Comment by oscard0m** [comment]
I apologize for the noise this PR has caused to you (@viceice @rarkins @HonkingGoose ) and the Renovate team. 🙏🏽 🙏🏽 🙏🏽 

My intention was to help Renovate move forward with the usage of `cache` option but you are totally right that is not okay to open automated PR's without its proper issue creation and following the whole process. Again, I'm so sorry for this and I totally understand your concerns.

---

Still, if you would like to, I would be happy to participate in https://github.com/renovatebot/renovate/issues/10706 if I'm invited to it. :)

---

P.S.: This PR has been 100% done by myself, on my own initiative. @gr2m has nothing to do with this.

**Comment by rarkins** [comment]
@oscard0m great, we'd appreciate that. As a general rule, do not create bulk unsolicited issues or PRs, but if you do then make sure they're likely to be 100% correct and welcomed.

**Comment by oscard0m** [comment]
> @oscard0m great, we'd appreciate that. As a general rule, do not create bulk unsolicited issues or PRs, but if you do then make sure they're likely to be 100% correct and welcomed.

The process I will follow is to always create an issue first and potential automated PR creation will be discussed in that issue first.

Also, I plan to write a small blog post on this. This is something I never thought about and I would like to write my reflections for the community.

Once again sorry, and appreciate your patience on this. :)

**Pull request closed without merging**
