### PR TITLE
refactor: revert replace emoji shortcodes with their unicode equivalent 

### PR DESCRIPTION
**Pull request by nvdbleek**
…ent (#4000)"

This reverts commit 69566652e49dc97d24da516e7f3384dbcfa0f2e5.

This PR reverts the emoji shortcodes to Unicode character change. We will make it configurable to use either shortcodes or  Unicode characters because old versions bitbucket server/MySQL have problems with the 4-byte Unicode characters.

### CODE REVIEW

**Comment by nvdbleek** [comment]
This PR is related to #3799

**Comment by rarkins** [comment]
Sorry, I didn’t see this one when I merged my own revert earlier. Just seeing it now.

**Comment by rarkins** [comment]
Sorry, I didn’t see this one when I merged my own revert earlier. Just seeing it now.

**Comment by nvdbleek** [comment]
@rarkins no problem. Thank you for picking it up so fast. I will work on the real 'fix' and make it configurable tonight. But I don't think I'll be able to finish this tonight. Is it OK if I get this done before Monday morning?

**Comment by nvdbleek** [comment]
Already reverted in 3465ea7e4287994e40b0f63b6a2e50bda77e9ad9

**Comment by rarkins** [comment]
@nvdbleek no problem at all. Feel free to float your proposed solution for feedback first. I was thinking maybe a new function like lib/util/emoji.js that returns the right text based on the configured preference.

**Pull request closed without merging**
