### PR TITLE
fix(workers): guarantee symmetric result from sort branch predicate

### LINKED ISSUE #17276: Make predicate function(s) symmetrical
### Describe the proposed change(s).

I'm creating an issue to capture the todo, from discussion #17214.

> I noticed the following in the code:
> 
> ```ts
>     branches.sort((a, b) => {
>         if (a.isVulnerabilityAlert && !b.isVulnerabilityAlert) {
>             return -1;
>         }
>         ...
> ```
> 
> Most sort algorithms expect the predicate function to be symmetrical, else it might get in a endless loop, crash or generate a random result.
> 
> With other words it will be safer if the code looks like this:
> 
> ```ts
>     branches.sort((a, b) => {
>         if (a.isVulnerabilityAlert && !b.isVulnerabilityAlert) {
>             return -1;
>         }
>         if (!a.isVulnerabilityAlert && b.isVulnerabilityAlert) {
>             return 1;
>         }
>         ...
> ```

I think this means that we should check our code for the "bad pattern" and replace it with the "good pattern".

### PR DESCRIPTION
**Pull request by ns-ggeorgiev**
## Changes

Assures symmetrical response from the branch sort predicate when there is a difference in the isVulnerabilityAlert flag.

## Context

If left as is, in some rare cases it might leave the list of branches in-properly sorted.

- fixes #17276

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

Note: this is trivial change with very hard real time simulation.

### CODE REVIEW

**Review by viceice — CHANGES_REQUESTED** [review]
please apply same changes from mine to this PR from the other.

**Comment by HonkingGoose** [comment]
> Also what Semantic PR issue is? How I can fix it?

Your pull request title needs a `:` character after the `(scope)` part. This should work:

```
fix(workers): guarantee symmetric result from sort branch predicate
```

**Comment by viceice** [comment]
> > please apply same changes from mine to this PR from the other.
> 
> I am not sure what you mean. Please elaborate.
> 
> Also what Semantic PR issue is? How I can fix it?

- https://github.com/renovatebot/renovate/pull/18274

I've made the required changes there before you closed that.

**Comment by ns-ggeorgiev** [comment]
> > > please apply same changes from mine to this PR from the other.
> > 
> > 
> > I am not sure what you mean. Please elaborate.
> > Also what Semantic PR issue is? How I can fix it?
> 
> * [fix: guarantee symmetric result from sort branch predicate #18274](https://github.com/renovatebot/renovate/pull/18274)
> 
> I've made the required changes there before you closed that.
> 
> 1. semantic PR title
> 2. reference related issue for auto close in PR body

done

**Comment by HonkingGoose** [comment]
@viceice Should this pull request close issue #17276? The PR only mentions the issue right now. If you want this PR to close the issue automatically, you should edit the top post, so it has this text:

```markdown
Closes #17276.
```

**Review by viceice — COMMENTED** [review]
@HonkingGoose  yes, it should close that issue, checkout the linked closed PR, which was replaced by this PR.

@ns-ggeorgiev you didn't made the right change to the PR body. please check the closed PR, which I've changed accordingly.

**Comment by rarkins** [comment]
@viceice I don't see anything in https://github.com/renovatebot/renovate/pull/18274/files#diff-dbcb9fcb89d0305e9ac34473f8f20d2624c0a6cdec047ad46689aac1b6646ef1

**Comment by viceice** [comment]
i was sure to have added the fixes keyword

**Review by viceice — APPROVED** [review]

**Comment by ns-ggeorgiev** [comment]
it seems all set, now, right?

**Pull request merged**
