### PR TITLE
feat(maven): Support for pin strategy

### LINKED ISSUE #3716: rangeStrategy=pin not working for maven
### Which Renovate are you using? CLI, App, or Pro
OSS docker

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

### What is your question?
I have this config:

```
{
  "extends": [
    "config:base"
  ],
  "maven": {
    "ignoreDeps": ["org.apache.commons:commons-math3"]
  },
  "packageRules": [
    {
      "managers": ["maven"],
      "packageNames": ["com.google.guava:guava"],
      "versionScheme": "docker"
    },
    {
      "managers": ["maven"],
      "packageNames": ["org.projectlombok:lombok"],
      "rangeStrategy": "pin"
    }
  ]
}
```

With this lombok dependency in my maven pom:

```
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>[1.12.6,1.18.6]</version>
        </dependency>
```

And the latest version of lombok being 1.18.8.

Which, if I understand correctly, should pin the lombok dependency version to the version `1.18.8` when it get's updated. However, the onboarding PR states:

`Upgrade org.projectlombok:lombok to [1.12.6,1.18.8]`

Am i misunderstanding, or mis-configuring renovate?

Cheers

### PR DESCRIPTION
**Pull request by zharinov**
Closes #3716

### CODE REVIEW

**Comment by zharinov** [comment]
@rarkins example pin PR

**Comment by rarkins** [comment]
> @rarkins example pin PR

@zharinov ?

**Comment by zharinov** [comment]
Sorry, https://github.com/zharinov/java-test-6/pull/4

**Comment by rarkins** [comment]
The 2.4.3 pinning looks pretty strange:
image

I would have expected 2.9.8 was available if the user specified it as upper range. Or was this a made-up example you did?

**Comment by zharinov** [comment]
Yes, I expected upper version too, I need to research more on why we're getting bottom one

**Comment by zharinov** [comment]
@rarkins It seems I solved it ([check out example PR](https://github.com/zharinov/java-test-6/pull/4))

**Comment by zharinov** [comment]
Gosh, it shows right versions in PR, but left older versions in the code :(

**Comment by zharinov** [comment]
Though for the new repo it worked great: https://github.com/zharinov/java-test-7/pull/1

**Comment by rarkins** [comment]
@zharinov that sounds like a flaw in the update algorithm - if it can't find the current or the old version then it should return `null` to allow for a rebase. I think you added some logic to bypass that for placeholders?

**Comment by rarkins** [comment]
This will probably cause a problem even in normal scenarios with a placeholder, e.g. current is 1.0.0, PR has 1.0.1, and then new version 1.0.2 is released. I think it will fail to rebase with new 1.0.2

**Comment by zharinov** [comment]
Got it, manual rebase checkbox solved it.
But anyway, your point is vaild. What if we'll use version of the last grouped dependency instead of the first one?
I mean, write something like in `updateDependency`:
```javascript  
if (version === currentValue || upgrade.groupName) {
   const replacedPart = versionPart.replace(currentValue, newValue);
  return leftPart + replacedPart + restPart;
}
```

It would force rebasing for this cases, if needed. In this case, it won't be relying to assumption that update was from previous grouped dep when returning untouched file content, while at the higher level we still have content equality check.

**Comment by rarkins** [comment]
I think we need to add a test with and without a placeholder e.g. with values 1.0.0, 1.0.1, 1.0.2. I think if it's a non-placeholder then if the existing content includes value 1.0.1 then we should return `null`, which current triggers a rebase. But for placeholder currently I think we'll incorrectly return current content, meaning the PR is stuck on 1.0.1. After that we can test your new logic to make sure it works. But shall we do this in a separate fix PR?

**Comment by zharinov** [comment]
Sure, I'll do this

**Review by viceice — APPROVED** [review]
LGTM

**Pull request merged**
