### PR TITLE
feat: create json schema from definitions file

### LINKED ISSUE #545: Use automated validation of configuration option values (e.g. JSON Schema)
We should use a validation library to explicitly define and later verify configs (especially user-provided ones in `renovate.json`): Example: https://validatejs.org/ (but need to evaluate)

Example field: `automerge` (values are 'none', 'patch', 'minor', 'any')

Question: should validations be written in javascript, or do any of these libraries support a string/json approach of definitions? Some of our config objects are overloaded (e.g. can be string or array) so Javascript might be easier for that.

Such definitions should be incorporated into our existing definitions file: https://github.com/singapore/renovate/blob/master/lib/config/definitions.js

If the config fails to parse then it should produce an error that is presented to the user (e.g. like https://github.com/singapore/renovate/blob/beb37bc1283a9cadd38f863110be15a55ab7026a/lib/workers/package-file/index.js#L22-L28 does)

### PR DESCRIPTION
**Pull request by rishabh1403**
Closes #545

### CODE REVIEW

**Comment by rishabh1403** [comment]
@rarkins Please review, also added the generated output, Let me know if we need to remove or change the placement of files.

**Comment by rarkins** [comment]
@rishabh1403 	how does this compare to the existing JSON schema? The existing one is likely a little out of date, but overall there should still be a lot of overlap and minimal diffs

**Comment by rishabh1403** [comment]
> @rishabh1403 how does this compare to the existing JSON schema? The existing one is likely a little out of date, but overall there should still be a lot of overlap and minimal diffs

@rarkins 
- The existing one uses `$ref` at some places whose relevance I couldn't find.
- some of the array types have explicit declarations that all items in the array would be `strings` ( I didn't find anything in config definition which suggests these too ) 
- Some of the strings were of format `regex`, but there were no indication in definitions file about that too

apart from these differences both are similar

**Comment by rarkins** [comment]
@rishabh1403 	can you give me an example of each of those and suggest how we can close the gap? For example specifying that a field should be a regex seems like a good idea, but I'm guessing someone added that by hand previously. Maybe now we should find a way to specify that information into our definitions and maybe even use it automatically in our validation too.

**Comment by rishabh1403** [comment]
@rarkins 
- array of strings
```
"extends": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description":
        "Configuration presets to use/extend. Note: does not work if configured in config.js"
    },
```
- $ref in schema
```
"onboardingConfig": {
      "type": "object",
      "description": "Configuration to use in onboarding PRs",
      "default": {},
      "$ref": "#"
    },
```
- another format field
```
"unstablePattern": {
      "type": "string",
      "description": "Regex for identifying unstable versions (docker only)",
      "format": "regex"
    },
```

I think for the regex part, we can have another field in definitions called `format`.

**Comment by rarkins** [comment]
Specifying the type of array items seems like a good idea. Let's add a new field (where applicable) called `subtype`, which will then map to this. e.g. `extends` should have subtype `string`.

I think that saying `"$ref": "#"` is a clever way to say that this object itself can contain a full config. Is it used in many places? I assume it applies to most of our `object` types.

Let's also support adding `format` to our definitions, e.g. for `unstablePattern`.

**Comment by rishabh1403** [comment]
@rarkins please review

**Comment by rarkins** [comment]
@rishabh1403 do you think we should also rename/align our fields to match JSON scheme, e.g. array not list, and object not json?

**Comment by rishabh1403** [comment]
> @rishabh1403 do you think we should also rename/align our fields to match JSON scheme, e.g. array not list, and object not json?

That would make it more consistent for sure

**Comment by rarkins** [comment]
OK, please go ahead and make that change too then as part of this PR

**Comment by rarkins** [comment]
Do we have any more alignments to make with JSON Schema in general or the previous spec for Renovate specifically?

**Comment by rishabh1403** [comment]
> Do we have any more alignments to make with JSON Schema in general or the previous spec for Renovate specifically?

Nope, rest everything is similar between both the files

**Comment by rishabh1403** [comment]
@rarkins we can also change `allowedValues` field to `enum`, but then some code will also need changing, and also it makes it less clear about it's intent, let me know your thoughts on this

**Comment by rishabh1403** [comment]
@rarkins Please review, all the discussed changes have been made

**Pull request merged**
