### PR TITLE
feat(gradle):infer gradle-wrapper url from distributionUrl

### PR DESCRIPTION
**Pull request by driver733**
Closes # https://github.com/renovatebot/renovate/issues/4807

Now `gradle-wrapper` url is now inferred from the `distributionUrl` from the `gradle-wrapper.properties`.

### CODE REVIEW

**Review by viceice — APPROVED** [review]

**Review by viceice — CHANGES_REQUESTED** [review]
Needs test fixes

**Comment by driver733** [comment]
@viceice The tests are fixed.

**Review by viceice — APPROVED** [review]
LGTM

**Comment by driver733** [comment]
@viceice It seems that there are some [issues](https://github.com/renovatebot/renovate/pull/5786/checks?check_run_id=536762197#step:10:11) with the Docker Registry login in the `release` pipeline. Can you check?

**Comment by viceice** [comment]
I know, sorry. will be fixed by #5788

**Comment by driver733** [comment]
@viceice Thanks for the fix!
The PR has passed all checks. Can you merge it?

**Pull request merged**
