### PR TITLE
feat: dynamic manager config

### LINKED ISSUE #5279: feat: move manager config inside manager/x instead of config/definitions
We all manager x logic be contained within `lib/manager/x`. As such we should deprecate manager config definitions like [this helmfile one](https://github.com/renovatebot/renovate/blob/a253e9d638b126f3050f05e50d3aa02e694183f3/lib/config/definitions.ts#L1717-L1731) and instead have them as an export from `lib/manager/helmfile/index.ts`.

There's some associated logic like "get manager config" that might need to be refactored too. e.g. a manager's config will be a combination of its default exported config plus also any custom config that the user defines for that manager.

Waiting on #5278 first.

### PR DESCRIPTION
**Pull request by rarkins**
Move manager definitions and default configs from lib/config/definitions to lib/manager/x

Closes #5279

### CODE REVIEW

**Comment by rarkins** [comment]
I think we may still have a circular import problem however it's hidden by the dynamic manager `require`s. Linting and building both work, but `yarn start` errors out:

```
FATAL: Can not load manager "bundler".
       "err": {
         "message": "options is not defined",
         "stack": "ReferenceError: options is not defined\n    at getOptions (/Users/rhys/src/renovate/lib/config/definitions.ts:2234:3)\n    at Object.<anonymous> (/Users/rhys/src/renovate/lib/platform/index.ts:12:28)\n    at Module._compile (internal/modules/cjs/loader.js:778:30)\n    at Module._compile (/Users/rhys/src/renovate/node_modules/pirates/lib/index.js:99:24)\n    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)\n    at Object.newLoader [as .ts] (/Users/rhys/src/renovate/node_modules/pirates/lib/index.js:104:7)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Module.require (internal/modules/cjs/loader.js:692:17)"
       }
```

**Comment by ViceIce** [comment]
can we move it to new dynamic import syntax? then we need to call a promise await on startup to init managers instead of auto init.

**Comment by ViceIce** [comment]
ok, platform should be loaded dynamically too

**Comment by ViceIce** [comment]
https://github.com/renovatebot/renovate/blob/987e0a2bfd06c81b534aae132f9835a17edac61d/lib/platform/index.ts#L12-L14

**Review by viceice — DISMISSED** [review]
LGTM, hopefully no mistake while copy'n'paste config. 😅

**Comment by rarkins** [comment]
> LGTM, hopefully no mistake while copy'n'paste config. 😅

I think the JSON schema works as a good check in this case. From what I can see, the only field that changed was the "description" one.

**Comment by ViceIce** [comment]
image

Looks like we have some missing test await again

**Pull request merged**
