### PR TITLE
fix: replacement for pep440 versioning

### PR DESCRIPTION
**Pull request by t-kulmburg**
As requested I am splitting my replacement pr #17476.
This pr makes sure the correct `replacementName` and `replacementVersion` are used, as some dependencies didn't get replacements.
It also fixes a problem I encountered with pep440, where now the rangeStrategy handling is skipped when the update is a replacement (used to throw an exception and therefore didn't replace the value).

### CODE REVIEW

**Comment by JamieMagee** [comment]
Can you add any new tests?

**Review by JamieMagee — CHANGES_REQUESTED** [review]
Can you add any new tests?

**Comment by t-kulmburg** [comment]
Any updates here? @JamieMagee

**Review by viceice — APPROVED** [review]

**Review by viceice — CHANGES_REQUESTED** [review]
This should prbably also be split into 2 PR's:
1. feat: support replacement for pep440
2. fix: use correct values for replacements

**Comment by JamieMagee** [comment]
If you hit this issue with pep440 versioning, do you think might need this for other versioning schemes that support replacement range strategies?

**Review by JamieMagee — DISMISSED** [review]
Needs deconflicting, and potentially a follow-up issue for other versioning schemes, but otherwise looks good to go!

**Comment by t-kulmburg** [comment]
I did not encounter any problems like this with the other managers/datasources I tested, [they are listed here in my README](https://gitlab.com/t.kulmburg/replacement-demo/-/blob/main/README.md). For the pep440 datasource however there is an Error in `versioning/pep440/handleReplaceStrategy`, which is fixed/avoided by this PR.
Of course I cannot guarantee that no other problems could pop up, as I only tested one replacement per Manager.

**Review by JamieMagee — APPROVED** [review]

**Review by viceice — APPROVED** [review]

**Pull request merged**
