### PR TITLE
feat(sbt): Support private variable version resolving

### PR DESCRIPTION
**Pull request by yamachu**
ref: https://github.com/renovatebot/renovate/issues/3827

Thanks to https://github.com/renovatebot/renovate/pull/3828 , I could update scala packages automatically.

In my use case, I make private variable which shows package version.

For example

Dependencies.scala
```scala
object Dependencies
{
  private val somePackageVersion = "1.2.3"
  private val anotherPackageVersion = "2.3.4"
  
  private val somePackage = "foo" % "bar" % somePackageVersion
  private val anotherPackage = "buz" % "piyo" % anotherPackageVersion

  lazy val myAwesomeLibraryDependencies = Seq(somePackage, anotherPackage)
}
```

build.sbt
```sbt
~...

libraryDependencies ++= myAwesomeLibraryDependencies
```

If renovate supports private variable, it would be able to parse this structure.

### CODE REVIEW

**Review by zharinov — APPROVED** [review]
Thanks @yamachu, looks good to me

**Review by viceice — COMMENTED** [review]
The regex should be constant in module scope.

**Comment by rarkins** [comment]
@viceice is that related to this PR specifically, or something should be refactored before or after?

**Comment by yamachu** [comment]
Thanks!

**Comment by rarkins** [comment]
@yamachu thank you!

**Pull request merged**
