### PR TITLE
fix(renovate-config-validator): support .renovaterc

### PR DESCRIPTION
**Pull request by suzuki-shunsuke**
## Changes

~~Fix two bugs.~~

Fix a bug.

- ~~A configuration file *.json parses as JSON5. So renovate-config-validator allows invalid JSON wrongly~~
- renovate-config-validator can't parse `.renovaterc`

## Context

- https://github.com/renovatebot/renovate/discussions/22990

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by suzuki-shunsuke** [comment]
Oh, some workflows run when a pull request becomes `Ready for review`.
I usually make a pull request draft until CI succeeds.
CI succeeded so I make this pull request `Ready for review`, then some workflows started. So I was confused.

**Review by rarkins — COMMENTED** [review]
Parsing the `renovate.json` file as `json5` was intentional by @viceice

**Comment by suzuki-shunsuke** [comment]
> Parsing the `renovate.json` file as `json5` was intentional by viceice

I see. I found the related pull request and the review comment.

- https://github.com/renovatebot/renovate/pull/12644
- https://github.com/renovatebot/renovate/pull/12644#discussion_r751234297

But I think `renovate-config-validator` should fail if `renovate.json` is invalid as JSON.

**Comment by rarkins** [comment]
I'm ok with the validator being strict, but Renovate itself being more lenient (json5)

**Comment by suzuki-shunsuke** [comment]
I renamed JSON5 `renovate.json5` to `renovate.json`, then Renovate can't parse `renovate.json` because it is invalid as JSON.

https://github.com/suzuki-shunsuke/test-renovate/blob/36ff3369829f9ffe4c3a81b75fd297e04130df0f/renovate.json
https://github.com/suzuki-shunsuke/test-renovate/issues/20#issue-680143856

> Action Required: Fix Renovate Configuration
> 
> There is an error with this repository's Renovate configuration that needs to be fixed. As a precaution, Renovate will stop PRs until it is resolved.
> 
> Location: `renovate.json`
> Error type: Invalid JSON (parsing failed)
> Message: `Syntax error: expecting String near {
>    exten`

**Comment by suzuki-shunsuke** [comment]
I think the file format should be not `JSON5` but `JSON` if the file extension is `.json`.
Both validator and renovate should not allow invalid JSON.

**Comment by rarkins** [comment]
@viceice do you recall?

**Review by viceice — CHANGES_REQUESTED** [review]
we always parse as JSON5, so current behavior is expected.

**Comment by viceice** [comment]
> You don't think https://github.com/renovatebot/renovate/pull/22991#issuecomment-1608891227 is an issue, right?

please create a minimal reproduction and a discussion with debug log, so we can see what's going on. renovate should parse all configs as JSON5, every other behavior is a bug.

**Comment by suzuki-shunsuke** [comment]
> please create a minimal reproduction and a discussion with debug log, so we can see what's going on. renovate should parse all configs as JSON5, every other behavior is a bug.

Sure. I'll do it. Thank you.

And I'll fix this pull request to fix a bug that renovate-config-validator can't parse .renovaterc.

- https://github.com/renovatebot/renovate/discussions/22990

**Comment by suzuki-shunsuke** [comment]
I created a minimal reproduction repository and a discussion.

- https://github.com/renovatebot/renovate/discussions/23002
- https://github.com/suzuki-shunsuke/renovate-reproduction-repo-2

And I fixed this pull request.

**Review by viceice — APPROVED** [review]

**Pull request merged**
