### PR TITLE
refactor(rubygems): Remove unnecessary datasource class

### PR DESCRIPTION
**Pull request by zharinov**
## Changes

- Move all functionality of `InternalRubyGemsDatasource` class to the `RubyGemsDatasource`

## Context

- Ref: #3670

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by zharinov** [comment]
Actually, I think this `packageName.toLowerCase()` thing is incorrect actually.
For example, package `ADB` is available via https://rubygems.org/api/v1/versions/ADB.json, not https://rubygems.org/api/v1/versions/adb.json

**Comment by rarkins** [comment]
Looks a bit big/complex for a refactor

**Comment by zharinov** [comment]
Yes, it's fix now

**Comment by zharinov** [comment]
Okay, just reverted all potentially destructive changes

**Review by rarkins — APPROVED** [review]

**Pull request merged**
