### PR TITLE
refactor(migrations): gitLabAutomerge and azureAutoComplete

### PR DESCRIPTION
**Pull request by pret-a-porter**
## Changes:

One more migration from previously huge PR https://github.com/renovatebot/renovate/pull/12957

## Context:

1. https://github.com/renovatebot/renovate/issues/11459
2. Part of https://github.com/renovatebot/renovate/pull/12957 

## Documentation

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — COMMENTED** [review]
i don't like to have two migrations for this simple thing. 🤔

**Comment by pret-a-porter** [comment]
Sometimes it looks exhaustive, but provide ability to maintain these many migrations easily. Instead of changing huge script, developer can change only one specific migration and related unit test.

**Comment by viceice** [comment]
> Sometimes it looks exhaustive, but provide ability to maintain these many migrations easily. Instead of changing huge script, developer can change only one specific migration and related unit test.

🤔 @rarkins WDYT?

**Comment by rarkins** [comment]
I don't really understand, actually. The original migration seemed pretty simple

**Comment by pret-a-porter** [comment]
I mean not possible to refactor this migration to only one, because:
```
const config = {
  a: 'one',
  b: 'two',
};
for (const [key, value] of Object.entries(config)) {
  console.log(key, value);
  delete config.b;
}
// a one
// b two
```

**Review by viceice — COMMENTED** [review]
i think this is a candidate for the regex migration to combine to a single migration 🙃

**Comment by pret-a-porter** [comment]
> i think this is a candidate for the regex migration to combine to a single migration 🙃

Haha, cool! Done :)

**Review by rarkins — APPROVED** [review]

**Pull request merged**
