### PR TITLE
tests: Improve error handling test cases

### LINKED ISSUE #2028: Optimise jest rules to best practices
Simplify our existing tests to be more readable using jest best practices.

e.g. using https://github.com/sapegin/jest-cheat-sheet

Examples of shortcuts we're not using:

```
.toThrow()
.toBeNull()
```

### PR DESCRIPTION
**Pull request by hassan23**
Improving the jest error handling rules in the following ways:

- Replacing `try` `catch` block by `toThrow` method for simple errors. e.g.:
```
try {	
  cli.getConfig(argv);	
} catch (err) {	
  e = err;	
}	
expect(e.message).toEqual(	
   "Invalid boolean value: expected 'true' or 'false', but got 'badvalue'"
)
```
will be replaced by
```
expect(() => cli.getConfig(argv)).toThrow(
   "Invalid boolean value: expected 'true' or 'false', but got 'badvalue'"
)
```
- Using `.rejects.toEqual` when dealing with `Promise`s and with a specific error message, as `toThrow` passes the test for any error message. e.g.:
```
let err;
try {	        
   Error('Unsupported platform: foo.')
   await configParser.parseConfigs(env, defaultArgv);
} catch (e) {	
     err = e;	
}	
expect(err.message).toBe('Unsupported platform: foo.');
```
Will be replaced by
```
await expect(configParser.parseConfigs(env, defaultArgv)).rejects.toEqual(
   Error('Unsupported platform: foo.')
)
```
Closes #2028

### CODE REVIEW

**Comment by rarkins** [comment]
@hassan23 can you explain the difference and choice between these two approaches?

toThrow:
```
expect(() => cli.getConfig(argv)).toThrow(
```

rejects.toEqual:
```
await expect(configParser.parseConfigs(env, defaultArgv)).rejects.toEqual(
```

Is there a reason to use one and not the other?

**Comment by hassan23** [comment]
> @hassan23 can you explain the difference and choice between these two approaches?
> 
> toThrow:
> 
> ```
> expect(() => cli.getConfig(argv)).toThrow(
> ```
> rejects.toEqual:
> 
> ```
> await expect(configParser.parseConfigs(env, defaultArgv)).rejects.toEqual(
> ```
> Is there a reason to use one and not the other?

@rarkins 
- The former is used only when we are dealing with normal synchronous functions. It requires a function which returns a function that throws an error, `toThrow` will check the error as well the error message.
- When dealing with an async function(`Promise`), `toThrow` does not work directly on a rejected promise. `.rejects` is to be used to unwrap the `error` for the rejected promise. After that `toThrow` can be used but I didn't use it because:
       - Message inside 'toThrow' is not getting checked properly, `toThrow` will pass the test even if part of the error message is there or even no message at all
      - `toThrow` will fail when the rejected promise is not throwing an error

**NOTE**: I just checked that if I wrap the error message in `Error` inside `toThrow` it works fine, no need to put `.toEqual`(only except for the second reason)

Thoughts?

**Comment by rarkins** [comment]
@hassan23 it could be good to keep the syntax similar for both approaches

**Comment by hassan23** [comment]
> @hassan23 it could be good to keep the syntax similar for both approaches

Ok I will change `toEqual` to `toThrow`.

I think we should still wrap the error in `Error` function to match the exact error message, what's your thought about it?

**Comment by rarkins** [comment]
I’m happy to go with your recommendation. Our goal is it’s easy to understand and easy to copy for people writing future tests.

**Pull request merged**
