### PR TITLE
feat(config/validation): add validation for negative numbers

### PR DESCRIPTION
**Pull request by RahulGautamSingh**
## Changes
- Validate negative numbers when they are set for integer types.

## Context
Ref this discussion: https://github.com/renovatebot/renovate/pull/29137#discussion_r1606402087

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
Are you sure we never use a negative number like -1 intentionally?

**Comment by RahulGautamSingh** [comment]
> Are you sure we never use a negative number like -1 intentionally?

We do but only for `prPriority`. I am still to add that change here.

**Comment by rarkins** [comment]
I think that this PR is maybe oversimplifying things. Not all numbers need to be positive, even if most are. A broad rule doesn't work.

Also yes, prPriority should always be part of packageRules

**Comment by RahulGautamSingh** [comment]
We can add `allowNegative` field for config options of type: `integer`. That will help differentiate them better.

**Review by viceice — APPROVED** [review]

**Review by rarkins — CHANGES_REQUESTED** [review]
Please test against a real repo and show us the results.

**Comment by RahulGautamSingh** [comment]
Repro: https://github.com/Rahul-renovate-testing/feat-29178/issues/1

**Review by rarkins — APPROVED** [review]

**Pull request merged**
