### PR TITLE
fix: replace duplicate configured repos with autodiscovered

### PR DESCRIPTION
**Pull request by hulkish**

### CODE REVIEW

**Comment by rarkins** [comment]
What’s the use case exactly?

**Comment by hulkish** [comment]
@rarkins Not necessarily a use case that is recommended. More of preventing renovate running on same repositories on the same pass, for ex:

- You're using self hosted renovate as a cli.
- You've defined `repositories` in `config.js`
- You're using `--autodiscover`

**Comment by rarkins** [comment]
Would there be a use case where (a) you want to autodiscover but (b) you want custom settings for just a few repositories. Then you want to configure those few repositories manually and have that manual configuration apply, while the rest have no custom config?

**Comment by rarkins** [comment]
@hulkish in that case I don't get it though. Didn't the old implementation successfully replace manually configured repos with discovered ones?
```
config.repositories = await getPlatformApi(config.platform).getRepos()
```

**Comment by hulkish** [comment]
Yes, except it "completely replaced all" configured ones.

**Comment by rarkins** [comment]
But shouldn’t autodiscover find *all* repos it has access to? So any others are essentially a config mistake?

**Comment by hulkish** [comment]
If they have a renovate.json in each repo - yes maybe. But, for ones they don't - and they override your config.js repos - i think thats not good. But, this pr doesn't fix the latter.

**Comment by rarkins** [comment]
I don’t see a use case where a repo is not autodiscovered yet would still work if you configured it manually. Config is another matter

**Comment by hulkish** [comment]
Well Im saying the use case is really more of config validation for this.

**Comment by rarkins** [comment]
I mean give me an example where this is useful or the existing functionality is detrimental. 

Eg You configure repositories a,b,c and then run autodiscover and it finds a,b,d,e?

**Comment by hulkish** [comment]
So, let's say this is my config.js:
```
module.exports = {
  repositories: [ 
    {
      repository: 'hulkish/foobar',
      rebaseStalePrs: true
    }
  ]
};
```

When i run renovate with autodiscover - My `rebaseStalePrs` option is thrown out without me knowing. This can be a little confusing, i think.

Given, to your point - this isn't necessarily a supportef use case. However, I think renovate has a responsibility to tell the user when their config is being discarded.

**Comment by rarkins** [comment]
I don't like the exact approach you've taken in this PR, but that's probably because you were trying to make it non-breaking. Instead, let's do it properly as I need to increment a major version ASAP anyway. I support this logic:

- Autodiscover all repositories
- Iterate through manually configured `config.repositories` and if any match with the autodiscovered, add in their manual configuration
- If any have no match, warn that they are not in the autodiscovered list

e.g. in the example above, your `rebaseStalePrs: true` would not be lost. The result would still be that `config.repositories.length === autodiscovered.length` -- i.e. any manually configured repositories that are not accessible by this token would be skipped with a warning.

Sound OK?

**Comment by hulkish** [comment]
Yep, i think thats best foot forward.

**Comment by rarkins** [comment]
@hulkish great, please let me know when ready for review again

**Comment by rarkins** [comment]
Implemented in https://github.com/renovateapp/renovate/commit/02e52a8c79143492f6ffb85ef6e44055dd9ab468

**Pull request closed without merging**
