### PR TITLE
fix(rust): Fix failure to update short version numbers (#4276)

### LINKED ISSUE #4276: skip-reason: "unsupported-value" with Rust (cargo)
**What Renovate type are you using?**
Renovate Gitlab App

**Describe the bug**
Renovate Gitlab App does not create merge requests

**Did you see anything helpful in debug logs?**
https://renovatebot.com/dashboard#gitlab/schmilblick/violetear/web-client/86538280

**Expected behavior**
Merge requests created with dependency updates

### PR DESCRIPTION
**Pull request by djcsdy**
I *think* this PR fixes #4276.

I am still working on figuring out how to test my changes, but I wanted to share this change early as I think it will be obvious to project members whether the change is correct or not :-).

Closes #4276

### CODE REVIEW

**Comment by rarkins** [comment]
Haha yes, I think that's it. Although should only be necessary to update the definitions file and not also the extract one.

**Comment by djcsdy** [comment]
Yeah, I noticed that those looked redundant. However I also noticed that many other adapters set `versionScheme` in both places so I went with the flow :-).

**Comment by djcsdy** [comment]
@rarkins Just to be clear, are you asking me to remove `versionStrategy: 'cargo'` from `cargo/extract.ts`? I’m happy to do it if you’d like.

**Comment by rarkins** [comment]
@djcsdy yes, please remove it. The extract function doesn't need to add it unless it's missing from the manager's definitions.

**Comment by djcsdy** [comment]
OK, this should be ready for merge now.

I still haven’t verified that this fixes the problem but I imagine that for such a small change you can probably handle that :-).

**Comment by djcsdy** [comment]
Thanks @rarkins!

**Pull request merged**
