### PR TITLE
feat(gitFs): lazy fetching

### PR DESCRIPTION
**Pull request by rarkins**
Instead of shallow cloning every branch (using —no-single-branch), we now clone only the default branch and lazy fetch the others as needed.

### CODE REVIEW

**Review by viceice — APPROVED** [review]
LGTM

**Review by viceice — APPROVED** [review]

**Comment by ViceIce** [comment]
I think we have one problem. when renovate should update multiple branches.

We should check this at `setBaseBranch` and try to fetch base branch if not exists locally.

**Comment by rarkins** [comment]
@ViceIce yes, we could call branchExists() because that should trigger the fetch

**Comment by rarkins** [comment]
I've tested this with multiple baseBranches and it seems to work

**Comment by ViceIce** [comment]
Ok, I'll look at it tomorrow morning

**Review by viceice — APPROVED** [review]
LGTM

**Pull request merged**
