### PR TITLE
refactor(internal): refactor local presets

### PR DESCRIPTION
**Pull request by viceice**
In preparation to support more local platforms.

This pr is just moving functions around and convert the internal preset api to object

### CODE REVIEW

**Comment by rarkins** [comment]
@viceice I don't understand why functions like `fetchJSONFile` should fall under `local/`. I think it makes more sense for `local/` to call `github/` instead of vice versa. What's your thinking on that?

**Comment by viceice** [comment]
Yes, my first idea was, the preset folder is growing to big, so add sub directories. As I finished I thought too, that local is not the right name. 🤔

**Comment by viceice** [comment]
@rarkins @JamieMagee Refactored another time, now each platform has it's own sub folder

**Review by viceice — COMMENTED** [review]
LGTM

**Pull request merged**
