### PR TITLE
fix(vulnerabilities): do not force exact patch version for NuGet datasource

### PR DESCRIPTION
**Pull request by Churro**
## Changes

PR #26150 added support for NuGet version ranges and thereby unlocked the possibility to also use them as version constraints in vulnerability fix PRs.

## Context

- https://github.com/renovatebot/renovate/pull/29666

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

Test repos:
* GitHub alerts: https://github.com/renovate-demo/26150-nuget-github/pull/2
* OSV: https://github.com/renovate-demo/26150-nuget-osv/pull/1

### CODE REVIEW

**Comment by rarkins** [comment]
Does Nuget versioning support this syntax?

**Comment by Churro** [comment]
> Does Nuget versioning support this syntax?

Yes, there is also a test for exactly the same range format used in this PR:
https://github.com/renovatebot/renovate/blob/f1831856416829e21b9c73f3d17f6bedfd274b21/lib/modules/versioning/nuget/parser.spec.ts#L157-L165

**Comment by rarkins** [comment]
Great. Have you been able to verify that this works "end to end" in a real repo?

**Comment by Churro** [comment]
> Great. Have you been able to verify that this works "end to end" in a real repo?

Yes, therefore I've linked two test repos (see above)

**Comment by rarkins** [comment]
Sorry, I should have checked more closely (on mobile, it was hidden by default)

**Review by rarkins — APPROVED** [review]

**Pull request merged**
