### PR TITLE
docs: use one sentence per line

### LINKED ISSUE #7545: Refactor the documentation to use one line per sentence
**What would you like Renovate to be able to do?**

Contributing to the documentation is not very pleasant for me,  due to the way the Markdown files are formatted.

**Current style:**

```markdown
Beginning of paragraph sentence. This sentence really should be on its own line, but I'm making it extra long for extra effect, look at me I can type a long sentence. Now here is another sentence to make the line extra extra long.

Beginning of paragraph sentence. Let's make another long line for dramatic reasons. Now where was I on this line, the softwrap is making this hard to see. If only there was a better way to format this text...
```

**Proposed style:**

```markdown
Here is the starting sentence for this paragraph.
This sentence also belongs to the paragraph.
Here's another sentence that belongs to the paragraph.
Notice how lines are separated visually.
This also helps when dealing with line based changes in Git.

Let's start a new paragraph, notice how it is separated by a newline?
Here is another sentence that belongs to the new paragraph.
As an added bonus, it also nudges writers to write shorter and simpler sentences, if I keep on going with my sentence, it starts to look very odd, maybe I should shorten or simplify this sentence, this sentence is getting ridiculous now, but let's write some more, what harm could it do? What's that noise?! Is that a møøse I hear out thër?

The writers guild regrets that you had to read that abomination of a sentence.
We have taken cørrective mësures to ensure this wøn't happen again.
We've dispatched our team of grammar møøses to remedy this issue.

Here's a sentence that starts a new paragraph.
This line belongs to this paragraph also.
I really like this style of formatting text, it looks really clean!
```

**Did you already have any implementation ideas?**

Go through the documentation and change the files so that they all conform to the proposed style.
There are no user facing changes, the docs will look the same on their end.

**Are there any workarounds or alternative ideas you've tried to avoid needing this feature?**

Turn on soft-wrap in the editor when working on the documentation.
This still makes it hard to see where sentences begin and end, so it's not really a good solution for me.
I also noticed that searching for a specific string becomes very confusing when lines are overly long.

**Is this a feature you'd be interested in implementing yourself?**

Yes, you don't have to do anything but review the final result. I will do the manual labor for you. :smile: :wink:

### PR DESCRIPTION
**Pull request by HonkingGoose**
## Changes:

- Use the one sentence per line pattern.
- Make changes to improve flow of some sentences.

## Context:

Closes #7545 

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] Unit tests + ran on a real repository

### CODE REVIEW

**Comment by HonkingGoose** [comment]
I don't understand why the Prettier bot is complaining, I ran the Prettier `lint-fix` command, and the files are not excluded in https://github.com/renovatebot/renovate/blob/cdaf3e9097303a94873ba745498165d7f665549d/.prettierignore#L1-L20

**Comment by HonkingGoose** [comment]
Note all of this work was manual, and it was a good thing I did it by hand, because I found some weird formatting, that a automated script would not have found. :smile:

**Comment by rarkins** [comment]
I've suspended Prettifier for now, pending feedback from https://github.com/kevgo/prettifier/issues/617

I think the bot is unable to push to forks, and it comments instead. I don't know why it's claiming the formatting is *wrong* though when it's not (maybe can't read our prettier config?).

**Comment by JamieMagee** [comment]
> Note all of this work was manual, and it was a good thing I did it by hand, because I found some weird formatting, that a automated script would not have found.

Impressive!

I think this is a bit too big to review, so I'm going to approve and trust you on this one :+1:

**Review by JamieMagee — APPROVED** [review]

**Comment by HonkingGoose** [comment]
I did not edit the GitHub issue templates yet, I don't know if they should or should not use one sentence per line.

The benefit of doing it would be that we're consistent throughout.
The drawback could be that the issue template comments take up more screen real estate when a user is editing the issue template to create a new issue.

**Comment by rarkins** [comment]
I prefer to keep the design of the issue and PR templates to be optimised for contributors and not for ease of editing/diffing by us. ie as you've done

**Comment by kevgo** [comment]
Prettifier maintainer here. Apologies for the issues with Prettifier. I'm investigating the issue.

Unrelated to that, a suggestion for this pull request: instead of introducing custom formatting rules like "one sentence per line" that are hard to enforce programmatically and lead to inconsistencies and bikeshed debates, may I suggest enabling Prettier's [proseWrap option](https://prettier.io/docs/en/options.html#prose-wrap)? That's often good enough as a solution in my experience 🙂

**Comment by HonkingGoose** [comment]
> Unrelated to that, a suggestion for this pull request: instead of introducing custom formatting rules like "one sentence per line" that are hard to enforce programmatically and lead to inconsistencies and bikeshed debates, may I suggest enabling Prettier's [proseWrap option](https://prettier.io/docs/en/options.html#prose-wrap)? That's often good enough as a solution in my experience slightly_smiling_face

I agree with you that this should be dealt with in a programmatic way, and we're discussing making a Prettier plugin that fixes the problem automatically, see the last comments on https://github.com/renovatebot/renovate/issues/7545 to follow that discussion.

I don't like the `proseWrap` option, because it doesn't fix my original issue with newlines not being in a logical place.
If all else fails, it still might be a good idea to use the `proseWrap` option, but I still think we should try to fix the "real" problem. :smile:

**Pull request merged**
