### PR TITLE
feat: drop Node.js v10 support

### PR DESCRIPTION
**Pull request by rarkins**
BREAKING CHANGE: Support for Node 10 is dropped

### CODE REVIEW

**Comment by JamieMagee** [comment]
Do we need to specify the LTS version of v12 i.e. `12.13.0`. And do we need to exclude v13 which goes EOL in 2 weeks? If the answer to both of those is no, we can simplify this to `>=12.0.0`

**Comment by rarkins** [comment]
@JamieMagee first we might need to answer "what does the engines field really mean?" in this project. If it means which versions we want to "support" (test in CI against, resolve issues against, etc) then I prefer to support only LTS versions. If instead it means "compatibility", then it can be wider. But do we want to encourage users to use probably-compatible versions that we don't want issues raised against?

**Comment by JamieMagee** [comment]
@rarkins Sorry, I dropped the ball on this, and now `^12.13.0` is coming back to bite me. This change only allows Node 12, but not 13 or 14.

I would be okay with `>=12.13.0` (Or maybe even `>=12`). I don't think it happens often that users come in with bugs that are the result of an unsupported version of Node.

Just as long as I can continue using Node 14 :smile:

**Comment by rarkins** [comment]
Ok, I’m fine with a PR. Let’s keep engines simple (`>=12`) but make sure we note somewhere else in our readme or docs that we only debug against node 12 LTS

**Pull request merged**
