### PR TITLE
fix: complete git author for GitLab platform (#4932)

### LINKED ISSUE #4932: Wrong git author when using GitLab platform
**What Renovate type are you using?**

Self-hosted

**Describe the bug**

The info log outputs:

```
INFO: Using platform gitAuthor: foo@example.org
INFO: Setting git author (repository=some/repository)
       "gitAuthor": {"name": null, "email": "foo@example.org"}
```

In the end we have a user `null` making the commits.

**Did you see anything helpful in debug logs?**

The info log already provides enough information.

**To Reproduce**

Use self-hosted renovate with GitLab integration.

**Additional context**

To me it looks like a simple change in `lib/platform/gitlab/index.ts:63` can solve the problem:

Before:

```typescript
gitAuthor = user.email;
```

After (something similar as in `lib/platform/github/index.ts:118`):

```typescript
gitAuthor = `${user.name} <${user.email}>`;
```

### PR DESCRIPTION
**Pull request by Trainmaster**
Fixes incomplete git author for GitLab platform. The if/else check as noted in #4932 isn't necessary because both fields `user.name` and `user.email` are required (see https://docs.gitlab.com/ce/api/users.html#user-creation).

Closes #4932

### CODE REVIEW

**Comment by rarkins** [comment]
@Trainmaster thanks for this PR. Can you run `yarn prettier-fix` locally and then check that `yarn test` passes?

**Comment by Trainmaster** [comment]
@rarkins I fixed the lint issue. But I have some issues running the tests locally

```
Test Suites: 2 failed, 236 passed, 238 total
Tests:       95 failed, 2316 passed, 2411 total
Snapshots:   78 failed, 828 passed, 906 total
```

Here one of the failing tests:

```
● workers/repository/process/lookup › .lookupUpdates() › upgrades .x major ranges without pinning

    expect(received).toMatchSnapshot()

    Snapshot name: `workers/repository/process/lookup .lookupUpdates() upgrades .x major ranges without pinning 1`

    - Snapshot
    + Received

    @@ -3,12 +3,12 @@
          "canBeUnpublished": false,
          "fromVersion": "0.9.7",
          "isRange": true,
          "isSingleVersion": false,
          "newMajor": 1,
    -     "newMinor": 4,
    +     "newMinor": 5,
          "newValue": "1.x",
    -     "releaseTimestamp": "2015-05-17T04:25:07.299Z",
    -     "toVersion": "1.4.1",
    +     "releaseTimestamp": "2017-10-19T17:55:37.072Z",
    +     "toVersion": "1.5.1",
          "updateType": "major",
        },
      ]

      425 |         .get('/q')
      426 |         .reply(200, qJson);
    > 427 |       expect((await lookup.lookupUpdates(config)).updates).toMatchSnapshot();
          |                                                            ^
      428 |     });
      429 |     it('upgrades .x minor ranges without pinning', async () => {
      430 |       config.rangeStrategy = 'replace';

      at Object.it (test/workers/repository/process/lookup/index.spec.js:427:60)
```

**Comment by rarkins** [comment]
@Trainmaster any chance you're running Node v13?

**Comment by Trainmaster** [comment]
@rarkins I tried it with `v13.3.0` and `v10.15.0`.

**Comment by rarkins** [comment]
v13 is known to not work, but v10 should be fine. I guess we should have an issue to track it if you're unable to get it to work

**Pull request merged**
