### PR TITLE
fix: do not interpret value as version during flattening

### LINKED ISSUE #14302: Renovate fails to create changelog when using Node codenames
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

latest

### Please select which platform you are using if self-hosting.

gitlab.com

### If you're self-hosting Renovate, tell us what version of the platform you run.

_No response_

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Renovate fails to generate a changelog when upgrading the digest of a Node image using the codename:

```
 "err": {
             "message": "Invalid Version: fermium",
             "stack": "TypeError: Invalid Version: fermium\n    at new SemVer (/renovate/node_modules/semver/classes/semver.js:38:13)\n    at compare (/renovate/node_modules/semver/functions/compare.js:3:32)\n    at Object.eq [as equals] (/renovate/node_modules/semver/functions/eq.js:2:29)\n    at getChangeLogJSON (/renovate/lib/workers/pr/changelog/index.ts:30:17)\n    at embedChangelog (/renovate/lib/workers/repository/changelog/index.ts:8:43)\n    at /renovate/node_modules/p-map/index.js:57:28"
           },
```

I made a reproduction repository at https://gitlab.com/fgreinacher/renovate-node-codename-changelog

### Relevant debug logs

<details><summary>Logs</summary>

```
 "loggerErrors": [
         {
           "name": "renovate",
           "level": 50,
           "logContext": "E96TMqabNV3o0BvCNubCb",
           "repository": "fgreinacher/renovate-node-codename-changelog",
           "config": {
             "detectGlobalManagerConfig": false,
             "detectHostRulesFromEnv": false,
             "postUpgradeTasks": {
               "commands": [],
               "fileFilters": [],
               "executionMode": "update"
             },
             "onboardingBranch": "renovate/configure",
             "onboardingCommitMessage": null,
             "onboardingConfigFileName": "renovate.json",
             "onboardingNoDeps": false,
             "onboardingPrTitle": "Configure Renovate",
             "productLinks": {
               "documentation": "https://docs.renovatebot.com/",
               "help": "https://github.com/renovatebot/renovate/discussions",
               "homepage": "https://github.com/renovatebot/renovate"
             },
             "deepExtract": false,
             "draftPR": false,
             "printConfig": false,
             "composerIgnorePlatformReqs": [],
             "logContext": null,
             "dependencyDashboard": true,
             "dependencyDashboardApproval": false,
             "dependencyDashboardAutoclose": false,
             "dependencyDashboardTitle": "Dependency Dashboard",
             "dependencyDashboardHeader": "This issue provides visibility into Renovate updates and their statuses. [Learn more](https://docs.renovatebot.com/key-concepts/dashboard/)",
             "dependencyDashboardFooter": null,
             "dependencyDashboardLabels": null,
             "configWarningReuseIssue": true,
             "timezone": null,
             "schedule": ["at any time"],
             "updateNotScheduled": true,
             "persistRepoData": false,
             "ignorePlugins": false,
             "ignoreScripts": false,
             "platform": "gitlab",
             "endpoint": "https://gitlab.com/api/v4/",
             "npmrc": null,
             "npmrcMerge": false,
             "npmToken": null,
             "updateLockFiles": true,
             "skipInstalls": null,
             "useBaseBranchConfig": "none",
             "gitAuthor": "Florian Greinacher <post@floriangreinacher.de>",
             "excludeCommitPaths": [],
             "aliases": {},
             "defaultRegistryUrls": null,
             "registryUrls": null,
             "extractVersion": null,
             "versioning": "node",
             "azureWorkItemId": 0,
             "azureAutoApprove": false,
             "pinDigests": true,
             "separateMajorMinor": true,
             "separateMinorPatch": false,
             "rangeStrategy": "bump",
             "branchPrefix": "renovate/",
             "bumpVersion": null,
             "semanticCommits": "disabled",
             "semanticCommitType": "chore",
             "semanticCommitScope": "deps",
             "rollbackPrs": false,
             "recreateClosed": false,
             "rebaseWhen": "auto",
             "rebaseLabel": "rebase",
             "stopUpdatingLabel": "stop-updating",
             "stabilityDays": 0,
             "internalChecksFilter": "none",
             "prCreation": "immediate",
             "prNotPendingHours": 25,
             "prHourlyLimit": 2,
             "prConcurrentLimit": 10,
             "branchConcurrentLimit": null,
             "prPriority": 0,
             "bbUseDefaultReviewers": true,
             "automerge": false,
             "automergeType": "pr",
             "automergeStrategy": "auto",
             "automergeComment": "automergeComment",
             "ignoreTests": false,
             "transitiveRemediation": false,
             "branchName": "renovate/node-fermium",
             "additionalBranchPrefix": "",
             "branchTopic": "{{{depNameSanitized}}}-{{{currentValue}}}",
             "commitMessage": "{{{commitMessagePrefix}}} {{{commitMessageAction}}} {{{commitMessageTopic}}} {{{commitMessageExtra}}} {{{commitMessageSuffix}}}",
             "commitBody": null,
             "commitBodyTable": false,
             "commitMessagePrefix": null,
             "commitMessageAction": "Update",
             "commitMessageTopic": "Node.js",
             "commitMessageExtra": "to {{newDigestShort}}",
             "commitMessageSuffix": null,
             "prBodyTemplate": "{{{header}}}{{{table}}}{{{notes}}}{{{changelogs}}}{{{configDescription}}}{{{controls}}}{{{footer}}}",
             "prTitle": null,
             "prHeader": null,
             "prFooter": "This PR has been generated by [Renovate Bot](https://github.com/renovatebot/renovate).",
             "hashedBranchLength": null,
             "groupName": null,
             "groupSlug": null,
             "group": {
               "branchTopic": "{{{groupSlug}}}",
               "commitMessageTopic": "{{{groupName}}}",
               "commitMessageExtra": ""
             },
             "labels": [],
             "addLabels": [],
             "assignees": [],
             "assigneesFromCodeOwners": false,
             "assigneesSampleSize": null,
             "assignAutomerge": false,
             "reviewers": [],
             "reviewersFromCodeOwners": false,
             "filterUnavailableUsers": false,
             "confidential": false,
             "reviewersSampleSize": null,
             "additionalReviewers": [],
             "postUpdateOptions": [],
             "constraints": {},
             "prBodyDefinitions": {
               "Package": "{{{depNameLinked}}}",
               "Type": "{{{depType}}}",
               "Update": "{{{updateType}}}",
               "Current value": "{{{currentValue}}}",
               "New value": "{{{newValue}}}",
               "Change": "`{{{displayFrom}}}` -> `{{{displayTo}}}`",
               "Pending": "{{{displayPending}}}",
               "References": "{{{references}}}",
               "Package file": "{{{packageFile}}}"
             },
             "prBodyColumns": ["Package", "Type", "Update", "Change", "Pending"],
             "prBodyNotes": [],
             "suppressNotifications": ["deprecationWarningIssues"],
             "pruneStaleBranches": true,
             "unicodeEmoji": true,
             "gitLabIgnoreApprovals": false,
             "fetchReleaseNotes": true,
             "cloneSubmodules": false,
             "ignorePrAuthor": false,
             "updatePinnedDependencies": true,
             "writeDiscoveredRepos": null,
             "platformAutomerge": false,
             "userStrings": {
               "ignoreTopic": "Renovate Ignore Notification",
               "ignoreMajor": "As this PR has been closed unmerged, Renovate will ignore this upgrade and you will not receive PRs for *any* future {{{newMajor}}}.x releases. However, if you upgrade to {{{newMajor}}}.x manually then Renovate will reenable minor and patch updates automatically.",
               "ignoreDigest": "As this PR has been closed unmerged, Renovate will ignore this upgrade and you will not receive PRs for the `{{{depName}}}` `{{{newDigestShort}}}` update again.",
               "ignoreOther": "As this PR has been closed unmerged, Renovate will now ignore this update ({{{newValue}}}). You will still receive a PR once a newer version is released, so if you wish to permanently ignore this dependency, please add it to the `ignoreDeps` array of your renovate config."
             },
             "repository": "fgreinacher/renovate-node-codename-changelog",
             "errors": [],
             "warnings": [],
             "branchList": [],
             "defaultBranch": "main",
             "isFork": false,
             "baseBranch": "main",
             "repoIsOnboarded": true,
             "$schema": "https://docs.renovatebot.com/renovate-schema.json",
             "renovateJsonPresent": true,
             "dependencyDashboardChecks": {},
             "dependencyDashboardIssue": 2,
             "dependencyDashboardRebaseAllOpen": false,
             "language": "docker",
             "manager": "gitlabci",
             "packageFile": ".gitlab-ci.yml",
             "parentDir": "",
             "packageFileDir": "",
             "depName": "node",
             "currentValue": "fermium",
             "currentDigest": "sha256:50d4540794db9bdbd423a5823c4d840fc2ba0b9c82d71b059ff34b4aeb3e328f",
             "replaceString": "node:fermium@sha256:50d4540794db9bdbd423a5823c4d840fc2ba0b9c82d71b059ff34b4aeb3e328f",
             "autoReplaceStringTemplate": "{{depName}}{{#if newValue}}:{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
             "datasource": "docker",
             "depType": "image",
             "depIndex": 0,
             "sourceUrl": "https://github.com/nodejs/node",
             "currentVersion": "14.0.0",
             "isSingleVersion": false,
             "updateType": "digest",
             "newValue": "fermium",
             "newDigest": "sha256:b2c75df8c9706156c38b4f1f678d00e11cb2bfda09fc4ab6e36ec17ac9163865",
             "newVersion": "fermium",
             "isDigest": true,
             "depNameSanitized": "node",
             "sourceRepoSlug": "nodejs-node",
             "sourceRepo": "nodejs/node",
             "sourceRepoOrg": "nodejs",
             "sourceRepoName": "node",
             "baseDeps": [
               {
                 "depName": "node",
                 "currentValue": "fermium",
                 "currentDigest": "sha256:50d4540794db9bdbd423a5823c4d840fc2ba0b9c82d71b059ff34b4aeb3e328f",
                 "replaceString": "node:fermium@sha256:50d4540794db9bdbd423a5823c4d840fc2ba0b9c82d71b059ff34b4aeb3e328f",
                 "autoReplaceStringTemplate": "{{depName}}{{#if newValue}}:{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
                 "datasource": "docker",
                 "depType": "image",
                 "depIndex": 0,
                 "updates": [
                   {
                     "bucket": "major",
                     "newVersion": "16.14.0",
                     "newValue": "gallium",
                     "newMajor": 16,
                     "newMinor": 14,
                     "updateType": "major",
                     "isRange": true,
                     "newDigest": "sha256:fd86131ddf8e0faa8ba7a3e49b6bf571745946e663e4065f3bff0a07204c1dde",
                     "branchName": "renovate/node-16.x"
                   },
                   {
                     "updateType": "digest",
                     "newValue": "fermium",
                     "newDigest": "sha256:b2c75df8c9706156c38b4f1f678d00e11cb2bfda09fc4ab6e36ec17ac9163865",
                     "branchName": "renovate/node-fermium"
                   }
                 ],
                 "warnings": [],
                 "versioning": "node",
                 "sourceUrl": "https://github.com/nodejs/node",
                 "currentVersion": "14.0.0",
                 "isSingleVersion": false
               }
             ]
           },
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

### PR DESCRIPTION
**Pull request by fgreinacher**
## Changes

When no new version is is available during flattening (e.g. when doing a digest update), Renovate currently falls back to treat ting the new value as version.

This can cause problems down the line, when other modules expect the version to a valid version. e.g. during changelog retrieval.

See https://github.com/renovatebot/renovate/issues/14302#issuecomment-1044749015 for some more context.

This PR removes the fallback. No test cases seem to rely on the existing logic, but there might of course be people that rely on this somehow. I cannot fully estimate how big of a problem that is though.

Alternatively we could also adapt downstream modules (e.g. changelog creation) to be resilient against invalid versions, but that seemed a bit dirty to me.

## Context

Fixes #14302

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — COMMENTED** [review]
Not sure if we break some people with this. 🤔

**Comment by fgreinacher** [comment]
> Not sure if we break some people with this. 🤔

Me neither. As mentioned we could also skip changelog creation when source or target versions are malformed.

**Comment by fgreinacher** [comment]
@viceice @rarkins Sorry to bother you, but this is blocking is us a little bit. As mentioned above I see two options:

1. Do not interpret value as version (this PR).
2. Make changelog creation a bit more defensive. 

I'm fine with both, `1` seems to be the cleaner option, but would introduce a behavior change that might break folks.

**Comment by rarkins** [comment]
OK, let's go with this approach

**Review by rarkins — APPROVED** [review]

**Pull request merged**
