### PR TITLE
feat(config): Add Shopify App Bridge monorepo

### PR DESCRIPTION
**Pull request by aaronadamsCA**
## Changes:

Adds the Shopify App Bridge monorepo group.

This is a closed source monorepo that includes the following public packages, which are commonly used in tandem and should be upgraded in lockstep:

- https://www.npmjs.com/package/@shopify/app-bridge
- https://www.npmjs.com/package/@shopify/app-bridge-react
- https://www.npmjs.com/package/@shopify/app-bridge-utils

## Context:

I'm using this grouping locally, and wanted to contribute it back to the project.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by viceice** [comment]
The sourcecode is private 😕

**Comment by aaronadamsCA** [comment]
Yes, I'm not sure why; it seems odd that they don't open up the repo.

The packages are public and get 50K+ weekly downloads, so I figured the config would still add value for other Renovate users.

But if you don't add public packages from private repos, I completely understand, and I can just keep it as part of my local config.

**Comment by rarkins** [comment]
@aaronadamsCA  It looks like maintainers don't have access rights to update this PR so you are going to need to keep updating it from main until it merges.

**Comment by aaronadamsCA** [comment]
> @aaronadamsCA It looks like maintainers don't have access rights to update this PR so you are going to need to keep updating it from main until it merges.

Refiled as #10280 from my personal repo, so that "edits from maintainers" could be enabled.

**Pull request closed without merging**
