### PR TITLE
fix(config): migrate requireConfig=false

### LINKED ISSUE #15638: Regression in v32.62.0: all repositories disabled
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.62.0

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

Gitlab latest 

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

Apparently there was a change around `requireConfig` and the migration ended up disabling all my repos!

I have `requireConfig: false` and this is migrated to `requireConfig: 'required' `

Cheers,
David 

### Relevant debug logs

<details><summary>Logs</summary>

```
WARN: Config needs migrating
       "originalConfig": {
         "platform": "gitlab",
         "endpoint": "https://gitlab.stordata.fr/api/v4/",
         "token": "***********",
         "repositories": [
           "stordata/cmdb",
           "stordata/collectors",
           "stordata/rest2cegid",
           "stordata/rest2zapi",
           "stordata/vsphere-soapify",
           "stordata/supersecret",
           "stordata/spoolx",
           "stordata/eslint-config-stordata",
           "stordata/renovate-bot"
         ],
         "requireConfig": false,
         "onboarding": false,
         "enabledManagers": ["npm"],
         "extends": ["config:base", ":disableDigestUpdates"],
         "packageRules": [
           {
             "matchUpdateTypes": ["minor", "patch"],
             "matchCurrentVersion": "!/^0/",
             "automerge": true
           },
           {"matchDepTypes": ["devDependencies"], "groupName": "dev"},
           {"matchPackageNames": ["angular-i18n"], "groupName": "angular1 monorepo"}
         ],
         "ignoreDeps": ["puppeteer-core"],
         "gitAuthor": "Elliot Alderson <teamdenbas@stordata.fr>",
         "prConcurrentLimit": 1
       },
       "migratedConfig": {
         "platform": "gitlab",
         "endpoint": "https://gitlab.stordata.fr/api/v4/",
         "token": "***********",
         "repositories": [
           "stordata/cmdb",
           "stordata/collectors",
           "stordata/rest2cegid",
           "stordata/rest2zapi",
           "stordata/vsphere-soapify",
           "stordata/supersecret",
           "stordata/spoolx",
           "stordata/eslint-config-stordata",
           "stordata/renovate-bot"
         ],
         "requireConfig": "required",
         "onboarding": false,
         "enabledManagers": ["npm"],
         "extends": ["config:base", ":disableDigestUpdates"],
         "packageRules": [
           {
             "matchUpdateTypes": ["minor", "patch"],
             "matchCurrentVersion": "!/^0/",
             "automerge": true
           },
           {"matchDepTypes": ["devDependencies"], "groupName": "dev"},
           {"matchPackageNames": ["angular-i18n"], "groupName": "angular1 monorepo"}
         ],
         "ignoreDeps": ["puppeteer-core"],
         "gitAuthor": "Elliot Alderson <teamdenbas@stordata.fr>",
         "prConcurrentLimit": 1
       }
 WARN: env config dryRun property has been changed to full
 INFO: Repository started (repository=stordata/cmdb)
       "renovateVersion": "32.62.0"
 INFO: Repository is disabled - skipping (repository=stordata/cmdb)
 INFO: Repository finished (repository=stordata/cmdb)
       "durationMs": 7512
 INFO: Repository started (repository=stordata/renovate-bot)
       "renovateVersion": "32.62.0"
 INFO: Repository is disabled - skipping (repository=stordata/renovate-bot)
 INFO: Repository finished (repository=stordata/renovate-bot)
       "durationMs": 19[42](https://gitlab.stordata.fr/stordata/renovate-bot/-/jobs/232817#L42)
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

### PR DESCRIPTION
**Pull request by rarkins**
Closes #15638

## Changes

Fixes requireConfig migration

## Context

Closes #15638

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — APPROVED** [review]
🤔

**Comment by viceice** [comment]
could you validate that a string was passed to migration?

**Comment by pere3** [comment]
seems like this commit broke an ability to set this from config.js file - merging with any (false/'ignored'/'optional') is always results in it set as 'required' in merged config

```
13:11:40   WARN: Config needs migrating
13:11:40         "originalConfig": {
13:11:40           "platform": "gitea",
13:11:40           "endpoint": "https://xxx/api/v1/",
13:11:40           "prBodyTemplate": "{{{table}}}{{{changelogs}}}",
13:11:40           "commitMessage": "{{{commitMessagePrefix}}} {{{commitMessageAction}}}",
13:11:40           "lockFileMaintenance": {
13:11:40             "enabled": true,
13:11:40             "schedule": null,
13:11:40             "commitMessage": "{{{commitMessagePrefix}}} {{{commitMessageAction}}}"
13:11:40           },
13:11:40           "dependencyDashboard": false,
13:11:40           "onboarding": false,
13:11:40           "requireConfig": "ignored",
13:11:40           "enabledManagers": ["poetry", "npm", "nuget"],
13:11:40           "rangeStrategy": "bump",
13:11:40           "gitAuthor": "Renovate Bot <bot@renovateapp.com>",
```
->
```
13:11:40         "migratedConfig": {
13:11:40           "platform": "gitea",
13:11:40           "endpoint": "https://xxx/api/v1/",
13:11:40           "prBodyTemplate": "{{{table}}}{{{changelogs}}}",
13:11:40           "commitMessage": "{{{commitMessagePrefix}}} {{{commitMessageAction}}}",
13:11:40           "lockFileMaintenance": {
13:11:40             "enabled": true,
13:11:40             "schedule": null,
13:11:40             "commitMessage": "{{{commitMessagePrefix}}} {{{commitMessageAction}}}"
13:11:40           },
13:11:40           "dependencyDashboard": false,
13:11:40           "onboarding": false,
13:11:40           "requireConfig": "required",
13:11:40           "enabledManagers": ["poetry", "npm", "nuget"],
13:11:40           "rangeStrategy": "bump",
13:11:40           "gitAuthor": "Renovate Bot <bot@renovateapp.com>",
```

**Comment by pere3** [comment]
was able to rewrite it value through bash env RENOVATE_REQUIRE_CONFIG with the same 'ignored' value, but documentation clearly states that it can be done through config.js as well https://docs.renovatebot.com/self-hosted-configuration/#requireconfig

p.s. using docker image with digest dc3eb7dea168d5eccb70345c4d70c240106b977a8de0083c5c9000dac476936d

**Comment by pere3** [comment]
with requireConfig set to false - resulting merge is the same "required":
```
12:52:04   WARN: Config needs migrating
12:52:04         "originalConfig": {
12:52:04           "platform": "gitea",
12:52:04           "endpoint": "https://xxx/api/v1/",
12:52:04           "prBodyTemplate": "{{{table}}}{{{changelogs}}}",
12:52:04           "commitMessage": "{{{commitMessagePrefix}}} {{{commitMessageAction}}}",
12:52:04           "lockFileMaintenance": {
12:52:04             "enabled": true,
12:52:04             "schedule": null,
12:52:04             "commitMessage": "{{{commitMessagePrefix}}} {{{commitMessageAction}}}"
12:52:04           },
12:52:04           "dependencyDashboard": false,
12:52:04           "onboarding": false,
12:52:04           "requireConfig": false,
12:52:04           "enabledManagers": ["poetry", "npm", "nuget"],
12:52:04           "rangeStrategy": "bump",
12:52:04           "gitAuthor": "Renovate Bot <bot@renovateapp.com>",
```
->
```
12:52:04         "migratedConfig": {
12:52:04           "platform": "gitea",
12:52:04           "endpoint": "https://xxx/api/v1/",
12:52:04           "prBodyTemplate": "{{{table}}}{{{changelogs}}}",
12:52:04           "commitMessage": "{{{commitMessagePrefix}}} {{{commitMessageAction}}}",
12:52:04           "lockFileMaintenance": {
12:52:04             "enabled": true,
12:52:04             "schedule": null,
12:52:04             "commitMessage": "{{{commitMessagePrefix}}} {{{commitMessageAction}}}"
12:52:04           },
12:52:04           "dependencyDashboard": false,
12:52:04           "onboarding": false,
12:52:04           "requireConfig": "required",
12:52:04           "enabledManagers": ["poetry", "npm", "nuget"],
12:52:04           "rangeStrategy": "bump",
12:52:04           "gitAuthor": "Renovate Bot <bot@renovateapp.com>",
```

**Comment by rarkins** [comment]
@pere3 which version of Renovate were you running?L when this happened?

**Comment by rarkins** [comment]
Which is which version? I think you're possibly wasting your own time and ours by commenting on a fix for the issue which you experienced. The problem you're describing was FIXED by this PR, not caused by it.

**Comment by pere3** [comment]
version is 32.62.0, in this version setting requireConfig in any given option inside config.js - does always results in merged config having this option as 'required'
but doing same set through RENOVATE_REQUIRE_CONFIG setting works


i found an issue https://github.com/renovatebot/renovate/issues/15638 - it's still relevant on 32.62.0

**Comment by pere3** [comment]
sorry, i found that i'm using an older version here, 32.63.1 is fixed one

**Pull request merged**
