### PR TITLE
feat(vsts): abandon pr after delete branch

### LINKED ISSUE #2082: VSTS - PR not abandoned
#### This is a:

- [x] Bug report (non-security related)
- [ ] Feature request
- [ ] I'm not sure which of those it is

#### I'm using:

- [ ] The Renovate GitHub App
- [ ] Self-hosted GitHub
- [ ] Self-hosted GitLab
- [x] Self-hosted VSTS

#### Please describe the issue:

When renovate delete a renovate branch (because the dep was resolved somewhere else) it should also abandon the PR.

I will have a look later

### PR DESCRIPTION
**Pull request by jycouet**
After deleting a branch, for VSTS we abandon the PR

Closes https://github.com/renovateapp/renovate/issues/2082

### CODE REVIEW

**Comment by jycouet** [comment]
What should we do about `has same API for github and vsts` @rarkins ?
I added one vsts api because VSTS doesn't delete "empty" PRs.

**Comment by rarkins** [comment]
@jycouet is this change necessary due to Renovate's branch cleanup feature? i.e. https://github.com/renovateapp/renovate/blob/603b77799b22fcb2864013fab1b6ecff517ffa59/lib/workers/repository/finalise/prune.js#L43-L52

If you look at that code, it's *meant* to rename and close the associated PR, which is what I think you want? Maybe we can address the problem differently.

**Comment by jycouet** [comment]
@rarkins yes I though about this, but the function is just `platform.updatePr`, where you update the title. 
That is why we need a second step to really close the pr.

`platform.updatePr` is maybe used somewhere else just to update the title...

I le tyou decide how to proceed :)

**Comment by rarkins** [comment]
@jycouet I have refactored this a little:
- abandonPr is no longer a public function
- abandonPr is called by deleteBranch

Can you take a look and test it out?

Also, I see a lot of unrelated formatting changes in the VSTS index.js, which makes it harder to review. Can you either take them out or move them to a separate chore PR, so that this one is cleaner?

**Review by rarkins — CHANGES_REQUESTED** [review]
Fix prettier formatting (`yarn && yarn prettier`)
Update tests
Verify deleteBranch -> abandonPr is working

**Comment by rarkins** [comment]
@jycouet what would you like to do with this PR?

**Comment by jycouet** [comment]
Hi,

Sorry, I have no access to a laptop for quite long... 
I would have like to proceed... But since all tests are not fully working on my windows setup, it's hard to finalize. 🙄

So in the end I let you decide 👍

**Comment by rarkins** [comment]
Let’s fix the windows tests first then. Unless you can test the PR changes I can’t merge it

**Comment by jycouet** [comment]
As far as I remember the feature is working.
Windows failing tests is a bigger issue, not linked to this pr. It's again about \n\r in snapshot

**Review by rarkins — APPROVED** [review]

**Pull request merged**
