### PR TITLE
refactor(platform): Change PlatformId from enum to union type

### PR DESCRIPTION
**Pull request by zharinov**
## Changes:

- Replace `PlatformId` enum with strings union type

## Context:

- Ref: #13743

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by zharinov** [comment]
But first we need to narrow `hostType` field from string to `HostType` union...

**Comment by rarkins** [comment]
@zharinov next steps for this?

**Comment by zharinov** [comment]
> @zharinov next steps for this?

Now I'm wondering how to leverage zod library to define enums. Some of them are used as `hostType`, which is `string`. But we may want to make `HostType` enum, which would combined from datasource or manager `id`s. Then we may want to validate its values received from the user input. But though we may accomplish this with Zod, I doubt we would be able to use `import type { HostType }`. So, maybe instead would like to define `HostType` as plain TypeScript enum, and then generate validators using `ts-to-zod` utility when we'll be ready.

**Comment by zharinov** [comment]
As you see, maybe the next step is to close this for now and re-evaluate our overall approach.

**Pull request closed without merging**
