### PR TITLE
feat(gradle): use java image for docker mode

### PR DESCRIPTION
**Pull request by viceice**
## Changes:

- `gradle/deep` and `gradle-wrapper` managers are now using `java` docker image.
- moved some code to `gradle-wrapper` because `gradle/deep` will be removed in future
- fixed `fs` usages to use our fs wrapper

## Context:

ref #6364

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by viceice** [comment]
Will prepare real test repos to check if it works as expected

**Comment by viceice** [comment]
https://github.com/viceice-tests/gradle/pulls

**Comment by rarkins** [comment]
For "deep" gradle, will it work if no gradlew is present?

**Comment by viceice** [comment]
> For "deep" gradle, will it work if no gradlew is present?

Not yet, will add a precommand to dynamically install gradle if no gradlew is found

**Comment by viceice** [comment]
Ready for review 🎉

**Review by rarkins — APPROVED** [review]

**Pull request merged**
