### PR TITLE
feat(cargo): Use centralized docker execution

### PR DESCRIPTION
**Pull request by zharinov**
ref #2863

### CODE REVIEW

**Review by viceice — DISMISSED** [review]

**Comment by zharinov** [comment]
Ready for review

**Review by viceice — DISMISSED** [review]

**Comment by rarkins** [comment]
Can we have a separate PR first that moves binarySource awareness from manager to util? Ie it’s initialised globally like localDir is and then we lass docker options every time, for the util function to make the decision.

**Comment by ViceIce** [comment]
So always pass docker options and exec will decide to use it.

**Comment by rarkins** [comment]
- [ ] Test against a real repo needing PRs

**Comment by zharinov** [comment]
Equivalent for both branches: https://github.com/zharinov/indy-sdk/pulls

**Comment by rarkins** [comment]
>Equivalent for both branches: https://github.com/zharinov/indy-sdk/pulls

@zharinov I don’t see lock files there

**Comment by zharinov** [comment]
> @zharinov I don’t see lock files there

And for good reason. Fix PR is coming soon 👌

**Comment by zharinov** [comment]
Ready for review

**Pull request merged**
