### PR TITLE
feat(platform): Use uniform platformAutomerge option

### PR DESCRIPTION
**Pull request by zharinov**
## Changes:

Use `platformAutomerge` option instead of `azureAutoComplete` and `gitLabAutomerge `.

## Context:

Prerequisite for #12045
Ref: #8386

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by rarkins — CHANGES_REQUESTED** [review]

**Review by HonkingGoose — CHANGES_REQUESTED** [review]

**Review by HonkingGoose — CHANGES_REQUESTED** [review]

**Review by viceice — CHANGES_REQUESTED** [review]

**Comment by zharinov** [comment]
As a spin-off task, we may also want to uniform migration code across different config sources, i.e. use same code once config is obtained from CLI and environment.

**Comment by viceice** [comment]
> As a spin-off task, we may also want to uniform migration code across different config sources, i.e. use same code once config is obtained from CLI and environment.

I think env will already be migrated.

**Comment by zharinov** [comment]
> I think env will already be migrated.

Problems may arise because we're iterating over `getConfig()` result. Maybe, the whole idea of uniform migration not worth the struggle.

**Review by rarkins — CHANGES_REQUESTED** [review]

**Comment by rarkins** [comment]
It just occurred to me that if we make this a breaking change then we don't need to migrate the CLI/env. But should we keep it now it's here?

**Review by rarkins — APPROVED** [review]

**Review by viceice — APPROVED** [review]

**Pull request merged**
