### PR TITLE
feat(maven): Lookup for additional info for latest stable version

### LINKED ISSUE #4617: Renovate tries to wrongly download maven SNAPSHOTs
**What Renovate type are you using?**
self-hosted renovate

**Describe the bug**
Executing with `maven` manager I see multiple errors related with SNAPSHOT not found. I checked with my `artifactory` instance and those SNAPSHOTs are not there, so it's the expected error. Anyway it's surprising that Renovate tries to retrieve information about SNAPSHOTs if `ignoreUnstable=true`

**Did you see anything helpful in debug logs?**
The logs are clearly showing a warning, which is what put me on the issue
```
 WARN: Dependency lookup unauthorized. Please add authentication with a hostRule (repository=bplatform/infra)
       "pkgUrl": {}
```
Note: The `unathorized` message is caused by a bug in artifactory. When using virtual repositories is wrongly identifying 404 (see https://www.jfrog.com/jira/browse/RTFACT-6509)

**Expected behavior**
SNAPSHOTs should not be retrieved if are not going to be used

### PR DESCRIPTION
**Pull request by zharinov**
Hopefully closes #4617

### CODE REVIEW

**Comment by rarkins** [comment]
Any risk that this breaks something?

**Comment by zharinov** [comment]
Minimal, since `getLatestStableVersion` is being used only for additional info retrieval (source url, scm and homepage)

**Comment by zharinov** [comment]
Just let me test it in couple sample repos

**Comment by zharinov** [comment]
As expected, it performs simlilar to master except it takes meta-info from latest stable, not just latest.

**Pull request merged**
