### PR TITLE
fix(helm-values): set docker versioning

### PR DESCRIPTION
**Pull request by viceice**
## Changes:

Add the docker language to `helm-values` manager,  so the `docker` versioning will be auto aqssigned to deps.

## Context:

renovatebot/config-help#990

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] Unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
Does this manager also reference non-Docker types too? If so then is this really the best approach?

**Comment by viceice** [comment]
> Does this manager also reference non-Docker types too? If so then is this really the best approach?

No, currently only docker images.

**Comment by rarkins** [comment]
FWIW I would like to remove the "language" construct. It doesn't work for managers which support multiple datasources/versioning types, so we may as well use an approach that's common across all.

**Review by rarkins — APPROVED** [review]

**Comment by viceice** [comment]
> FWIW I would like to remove the "language" construct. It doesn't work for managers which support multiple datasources/versioning types, so we may as well use an approach that's common across all.

I can remove the language and assign docker versioning explicit

**Review by rarkins — CHANGES_REQUESTED** [review]
Use explicit versioning instead of language

**Review by rarkins — APPROVED** [review]

**Pull request merged**
