### PR TITLE
ci: v8 coverage

### PR DESCRIPTION
**Pull request by viceice**
## Changes:
Use new v8 coverage collector, which uses ~20% less memory. But v8 is a little slower (~20% on 4 jest worker)

## Context:

depends on #8929

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by viceice** [comment]
Requires coverage comment conversions

https://github.com/istanbuljs/v8-to-istanbul#ignoring-uncovered-lines

**Comment by viceice** [comment]
Before fixing more coverage comments i'll like to have some feedback if we want to go this way.

**Comment by rarkins** [comment]
Advantages of switching to v8 coverage:
- Less memory use
- "The future"?

Disadvantages of switching to v8:
- Runs slower for us
- Needs porting of its ignore statements (one-off cost)

@bcoe anything else you recommend we take into consideration?

At this point we don't really have a constraint of CPU/minutes, even though less is always nicer. We do seem to have hit memory problems, both:
- Actions CI tests failing due to apparent OOM. Is it now under enough control that either solution works fine?
- Running `yarn test` in codespaces ran out of memory too. Hasn't been re-tested recently

**Comment by bcoe** [comment]
@rarkins my guess is that the instrumentation is significantly faster than Istanbul (which is the default setting for Jest), _but_ Istanbul caches instrumentation heavily, whereas using V8's coverage you'll take a constant hit on performance because I believe it disables some compiler optimizations.

So advantages of using v8:

1. would expect it to be faster if you're running many files few times (if you're running the same file under test 1000s of times, the caching will probably start to help you in Istanbul).
2. I would expect memory to be less of an issue for the v8 coverage -- the implementation under the hood just adds additional byte code operations to code, vs., Istanbul which significantly increases the size of source files -- so, I would be curious to know where the OOM is occurring.
3. the v8 coverage is a little ahead of Istanbul in supporting ESM, although I think there's work to add support for ESM to Istanbul.


Question, how much slower is the v8 based approach running?

**Comment by viceice** [comment]
@bcoe v8 coverage is ~20% slower than istanbul when using 4 worker locally, see pr description

**Comment by viceice** [comment]
Now i see ~10% shorter runtime with v8, because when using istanbul my pc is going to swap on 8 worker because it will use all my 16GB assigned to wsl v2 😱  It's using 4GB swap then, which is also full. 😕

**Comment by viceice** [comment]
I'm closing this for now, as we managed to reduce our memory footprint and v8 coverage isn't working very well yet. Maybe we can retry when node v16 becomes lts.

**Pull request closed without merging**
