### PR TITLE
fix(gitlab): Restore auth for versions older than 12.2

### PR DESCRIPTION
**Pull request by julienp**
Follow up to https://github.com/renovatebot/renovate/pull/7131 to use the Private-token header when the token looks like a Personal Access Token.

### CODE REVIEW

**Comment by julienp** [comment]
Sending both headers doesn't seem to work, as it seems to always check for Private-token first, and this fails if it's an OAuth token.

GitLab relies on the fact that PATs are 20 characters long to disambiguate, so we can try to do the same here. This works for me on gitlab.org, but I don't have an old gitlab installation to test if this also works there.

**Review by viceice — APPROVED** [review]

**Comment by bytestream** [comment]
I believe this PR broke npm registry authentication on self-hosted GitLab 13.3.2:
```
hostRules: [
        {
            hostType: "npm",
            domainName: "gitlab.vendor.com",
            token: process.env.GITLAB_TOKEN
        }
    ],
```

Where `GITLAB_TOKEN` is a 20 character personal access token.

What previously worked fine prior to this release now returns `Response code 401 (Unauthorized)` when accessing npm modules belonging to private repositories.

I've only just noticed this and back tracked through CI jobs as we're only the latest version of GitLab and Renovate.

I don't understand why this PR would affect the above host rule?

**Comment by bytestream** [comment]
Nevermind it's something else in `v23`, noticed the log says: `"renovateVersion": "23.14.3"`

**Comment by viceice** [comment]
@bytestream please open a new issue for that

**Pull request merged**
