### PR TITLE
fix: update dependency vso-node-api to v6.3.2

### PR DESCRIPTION
**Pull request by jycouet**
This Pull Request updates dependency [vso-node-api](https://github.com/Microsoft/vso-node-api) from `v6.2.8-preview` to `v6.3.2`

---

This PR has been generated by [Renovate Bot](https://renovateapp.com).

### CODE REVIEW

**Comment by jycouet** [comment]
I don't know from where is coming this: `FATAL: Renovate fatal error: a`.
Do you know @rarkins ?

**Comment by rarkins** [comment]
I think there’s one deliberate fatal error that is logging only and not an actual test failure. But this branch had a couple of test failures to when I looked

**Comment by jycouet** [comment]
@rarkins Is it better?

**Comment by rarkins** [comment]
@jycouet thanks for looking at it so quickly! Nice to be on a stable release now for VSTS.

**Pull request merged**
