### PR TITLE
feat: Make this repository available for pre-commit

### PR DESCRIPTION
**Pull request by killermoehre**
## Changes:

A configuration for [pre-commit](https://pre-commit.com/) is added.

Right now this is blocked by https://github.com/renovatebot/renovate/issues/12810.

## Context:

See the discussion at https://github.com/renovatebot/renovate/discussions/10973.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
I deleted #12810 because I thought it was a spam issue. Can you create a discussion instead, with more details?

**Review by viceice — CHANGES_REQUESTED** [review]
I don't think this will work as is. AS this project needs two steps to get it working

- install deps via `yarn`
- compile typescript code

Otherwise the command will simply fail. There is maybe an option, when we run the validator via `ts-node`, so no compile step required.
But this still needs to install deps via `yarn`

**Comment by viceice** [comment]
Nope, this won't work as is: https://pre-commit.com/#node

**Comment by killermoehre** [comment]
I started a discussion at https://github.com/renovatebot/renovate/discussions/12823.

**Pull request closed without merging**
