### PR TITLE
docs: fix aws-machine-image datasource usage

### LINKED ISSUE #14999: Readme of datasource aws-machine-image is wrong
### Describe the bug

The readme at https://github.com/renovatebot/renovate/blob/main/lib/modules/datasource/aws-machine-image/readme.md is wrong:
- instead of `<packageName>` you need to use `<lookupName>` 
- instead of `\\n` you need to use `\n` 

### Relevant debug logs

<details><summary>Logs</summary>

before fixing
```
       "lookupName": "ami_id",
       "err": {
         "message": "Unexpected token a in JSON at position 0",
         "stack": "SyntaxError: Unexpected token a in JSON at position 0\n    at JSON.parse (<anonymous>)\n    at AwsMachineImageDataSource.getSortedAwsMachineImages (/usr/src/app/node_modules/renovate/lib/datasource/aws-machine-image/index.ts:51:21)\n    at callback (/usr/src/app/node_modules/renovate/lib/util/cache/package/decorator.ts:51:34)\n    at /usr/src/app/node_modules/renovate/lib/util/cache/package/decorator.ts:133:26\n    at AwsMachineImageDataSource.getReleases (/usr/src/app/node_modules/renovate/lib/datasource/aws-machine-image/index.ts:104:20)\n    at /usr/src/app/node_modules/renovate/lib/util/cache/package/decorator.ts:133:20\n    at fetchReleases (/usr/src/app/node_modules/renovate/lib/datasource/index.ts:264:13)\n    at getPkgReleases (/usr/src/app/node_modules/renovate/lib/datasource/index.ts:316:7)\n    at lookupUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/lookup/index.ts:76:32)\n    at fetchDepUpdates (/usr/src/app/node_modules/renovate/lib/workers/repository/process/fetch.ts:41:13)\n    at /usr/src/app/node_modules/p-map/index.js:57:22"
       }
```
</details>

### Have you created a minimal reproduction repository?

No reproduction repository

### PR DESCRIPTION
**Pull request by philicious**
## Changes

closes #14999 

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by philicious** [comment]
@rarkins here were are with a PR :)

**Comment by rarkins** [comment]
Thanks. Looking at this, I'm guessing that the extra escaping came because this example was copy pasted from a renovate.json, where you do need this type of escaping. Are you also using this with config.js? I assume you've verified it now working with the proposed changes?

**Comment by rarkins** [comment]
Cc @markussiebert

**Comment by philicious** [comment]
yep, I also guesses its a copy/paste issue. Especially after talking to OP author (he's a colleague of mine but different team) and he himself uses it the same way.

yes I do use it in`config.js` and have a working version

**Comment by rarkins** [comment]
Thanks for the confirmation!

**Review by rarkins — APPROVED** [review]

**Pull request merged**
