### PR TITLE
fix(bitbucket): Use HTTP GET method instead of HEAD

### PR DESCRIPTION
**Pull request by maxbrunet**
## Changes

I wanted to optimized since we do not need a response body, but this means error responses do not have a body either which can be useful for troubleshooting, for example: 

```json
{"type": "error", "error": {"message": "You do not have access to view this workspace."}}
```

## Context

Follow up to #13274. Related to #14402.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by viceice** [comment]
Don't like this.

**Comment by maxbrunet** [comment]
@viceice could you detail your concerns, please?

When there is an error, the response is dump in the logs. With `HEAD`, we have things like endpoint, headers, HTTP status, but no body explaining the error.

The payload for a working request is not very large and I assume it would be garbage collected as soon as the call returns since we still do not store it in a variable

I personally have been able to troubleshoot without, but I think it may be useful to others

**Review by rarkins — APPROVED** [review]

**Comment by viceice** [comment]
> @viceice could you elaborate your concerns, please?
> 
> When there is an error, the response is dumped in the logs. With `HEAD`, we have things like endpoint, headers, HTTP status, but no body explaining the error.
> 
> The payload for a working request is not very large and I assume it would be marked for garbage collection as soon as the call returns since we still do not store it in a variable
> 
> I personally have been able to troubleshoot without, but I think it may be useful to others

I think bitbucket cloud has defined the different status code, which also makre clarifícation about the error.
I the error is because of missing permissions, we should document that and add apropriate logging.

**Comment by rarkins** [comment]
How often is this API called? Only selectively after updating a PR due to reviewers fails?

**Comment by viceice** [comment]
> How often is this API called? Only selectively after updating a PR due to reviewers fails?

Yes, for all reviewers when PR creation / update fails.

**Comment by rarkins** [comment]
But that won't happen very often, will it? That's why I don't really see a problem with using `GET`

**Comment by viceice** [comment]
🤷‍♂️ if it fails on one repo, it will probably fail on every PR on every run.

Feel free to merge, i won't block this. 🙃 It's just my feeling.

**Pull request merged**
