### PR TITLE
fix: filter status checks when counting

### LINKED ISSUE #7800: Don't treat renovate/stability-days as passing status check
If the only passing status check is renovate/stability-days then we should consider that as *zero* passing status checks and therefore still "pending". Original:

@andrewgies17 in my instance I use an external CI pipeline (Jenkins) which reports to GitLab. The Jenkins jobs sometimes take a while to start and if the stability days status check gets applied first, the MR can be merged before the Jenkins job has started. It would be useful if there was an option to only apply the stability days status check if there is already a passing pipeline.

_Originally posted by @grit96 in https://github.com/renovatebot/renovate/issues/5743#issuecomment-732796687_

### PR DESCRIPTION
**Pull request by geraintwhite**
## Changes:

Excludes `renovate/*` status checks when counting successful checks.

Platforms:

- [x] GitLab
- [x] GitHub
- [x] Azure
- [x] Bitbucket
- [ ] Bitbucket server
- [ ] Gitea

## Context:

Closes #7800

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added unit tests, or
- [ ] Unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
@grit96 is this waiting for the two remaining platforms before reviewing?

**Comment by grit96** [comment]
@rarkins no, I wasn't sure how to implement for the two remaining platforms.

**Comment by rarkins** [comment]
Important question first: do we want to filter out our own checks completely, or only if they're passing?

e.g. if a branch had 2 passing checks but 1 failing renovate/artifacts check, we don't want to remove our failed check and call the branch passing.

**Review by rarkins — CHANGES_REQUESTED** [review]
Only filter out *passing* `renovate/*` status checks. They should still count towards pending and failed.

**Comment by rarkins** [comment]
And I think we unfortunately need to make this opt-in via config. There could be people who use prCreation=not-pending and simply have a renovate/stability-days status check.

**Pull request closed without merging**
