### PR TITLE
fix(repo-cache): pass relative paths to fs layer

### PR DESCRIPTION
**Pull request by viceice**
## Changes
fs layer will add the cache path for us

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by secustor — COMMENTED** [review]
Couldn't this potentially breaking for users which self hosting? 

E.g. the explicitly putting the Renovate cache on a path which is then saved/mounted to be persisted.

outside of that LGTM

**Comment by viceice** [comment]
the FS layer will do the exactly same.

it will prepend the cache path if the current path is relative.

https://github.com/renovatebot/renovate/blob/c39aa7e5b1880d992251221f3eb2258d95536e1d/lib/util/fs/index.ts#L281

https://github.com/renovatebot/renovate/blob/c39aa7e5b1880d992251221f3eb2258d95536e1d/lib/util/fs/util.ts#L16-L23

**Comment by rarkins** [comment]
Which scenario is this fixing?

**Comment by viceice** [comment]
not really a fix, just remove unnecessary code.

**Review by rarkins — APPROVED** [review]

**Pull request merged**
