### PR TITLE
feat(pip): support hash updating

### LINKED ISSUE #2444: feat(pip_requirements): support hashes
**What Renovate type are you using?**
Renovate GitHub App (I think)

**Describe the bug**
See https://github.com/mozilla-services/tecken/pull/1040

I have [a project with renovate](https://github.com/mozilla-services/tecken/blob/47c06d8f49cd7953d6f6683ceb566083da71d1ea/renovate.json) and by default Python support should be enabled but PRs on the `requirements.txt` is not being created. 
The [`requirements.txt`](https://github.com/mozilla-services/tecken/blob/master/requirements.txt) definitely has a format that both `pip` and `hashin` supports. Nothing weird there. 

**To Reproduce**
See above. :)

**Expected behavior**
More PRs for outdated Python packages in the the `requirements.txt`

**Additional context**
Again; https://github.com/mozilla-services/tecken/pull/1040#issuecomment-416963459

### PR DESCRIPTION
**Pull request by rarkins**
Closes #2444

### CODE REVIEW

**Comment by caphrim007** [comment]
@rarkins this PR appears to do what is intended per the results you showed in the linked-to issue. However, when I try to run this via the VSCode docs, I repeatedly get the following

```
DEBUG: Failed to update requirements/constraints.txt file (repository=org/repo, branch=renovate/regex-2020.x)
       "err": {
         "killed": false,
         "code": 127,
         "signal": null,
         "cmd": "hashin regex==2020.6.8 -r requirements/constraints.txt",
         "stdout": "",
         "stderr": "/bin/sh: 1: hashin: not found\n",
         "message": "Command failed: hashin regex==2020.6.8 -r requirements/constraints.txt\n/bin/sh: 1: hashin: not found\n",
         "stack": "Error: Command failed: hashin regex==2020.6.8 -r requirements/constraints.txt\n/bin/sh: 1: hashin: not found\n\n    at ChildProcess.exithandler (child_process.js:303:12)\n    at ChildProcess.emit (events.js:310:20)\n    at ChildProcess.EventEmitter.emit (domain.js:482:12)\n    at maybeClose (internal/child_process.js:1021:16)\n    at Socket.<anonymous> (internal/child_process.js:443:11)\n    at Socket.emit (events.js:310:20)\n    at Socket.EventEmitter.emit (domain.js:482:12)\n    at Pipe.<anonymous> (net.js:672:12)"
       }
```

I'm running the latest renovate/python image locally. I also tried building a new image with the inclusion of hashin, however I see in the Typescript that this shouldnt be necessary.

**Comment by caphrim007** [comment]
manually installed python-pip in the devcontainer and I can verify that this patch does what I would expect it to do.

Is the inclusion of the docker command in this PR something that would affect self-hosted solutions?

**Comment by rarkins** [comment]
What exactly are you running? Either you need to have hashin installed locally or you need to run with binarySource=docker. Once this feature is published we will need to add hashin to our “full” Docker image too.

**Comment by caphrim007** [comment]
I was just working within the container provided by the `.devcontainer` under the "VS Code Remote Development" steps found here 

https://github.com/renovatebot/renovate/blob/master/docs/development/local-development.md

Regardless, after a little shuffling, I was able to verify that the PR here works.

**Comment by rarkins** [comment]
OK great. That container is not intended to have all third party binaries pre-installed, otherwise it would be huge and inconvenient for people developing. Glad you could get it working.

**Comment by caphrim007** [comment]
hi @rarkins, anything that I can do to assist in nudging this forward? Thanks.

**Comment by rarkins** [comment]
Hopefully just needs some test additions to bring coverage back up to 100%

**Pull request merged**
