### PR TITLE
feat(docker): Use opencontainers labels to find repository source

### LINKED ISSUE #2395: Docker release notes
1) datasource returns GitHub source repo
2) unify docker Pr body template with default

### PR DESCRIPTION
**Pull request by mikebryant**
Closes #2395

### CODE REVIEW

**Comment by mikebryant** [comment]
This is something of a work in progress, I'm not really familiar with javascript.

It was able to successfully generate some release notes on my test repo though: https://github.com/mikebryant/renovate-test-docker/pull/7

**Comment by mikebryant** [comment]
Yes, you could definitely separate out the splitting out of the `getManifest` function into a separate PR.

I can do that now.

**Comment by mikebryant** [comment]
On the logic, yes, that's correct. I chose the latest tag so this will handle the case where the repository url changes.

**Comment by mikebryant** [comment]
And can split out the refactoring to use the library instead of the implementation in this repo

**Comment by mikebryant** [comment]
@rarkins I've pushed #2908 with the first refactor

**Comment by mikebryant** [comment]
I've reworked this to be based off #2931

**Comment by mikebryant** [comment]
@rarkins Manifest parsing and label extraction is now working for my test repo: https://github.com/mikebryant/renovate-test-docker/pull/7

You can see the weave release notes now show up.

I got a bit stuck looking at tests and mocking etc, so I've just done manual testing for now. I've tried to include relevant error checking.

**Comment by mikebryant** [comment]
Would appreciate help getting this across the line :)

**Comment by rarkins** [comment]
@mikebryant thanks, I’ll take a look

**Comment by rarkins** [comment]
Todo:
- [ ] Confirm if current unsorted tags is ok. And if not then shall we use "latest"?
- [ ] Add test with successful manifest parsing
- [ ] Cache sourceUrl results (24 hours maybe)

**Comment by mikebryant** [comment]
I would think sorting the tags and taking the newest might be the way to go?

`latest` isn't viable for a lot of our images - we deliberately don't publish `latest` as the docker registry is configured to disallow tag updates.

**Comment by rarkins** [comment]
@mikebryant do you have an example Docker package that has a source URL defined in its labels? In the Pull Request you referenced in https://github.com/renovatebot/renovate/pull/2907#issuecomment-445068438, it doesn't seem to have one.

**Comment by mikebryant** [comment]
It looks like it does to me?
```
m@lt31253:~$ docker pull weaveworks/weave:2.5.0
m@lt31253:~$ docker inspect weaveworks/weave:2.5.0 | grep org.opencont
                "LABEL org.opencontainers.image.revision=6e3f8a1c7a0ae8c011f7e28e6e06e6164396d03e org.label-schema.vcs-ref=6e3f8a1c7a0ae8c011f7e28e6e06e6164396d03e"
                "org.opencontainers.image.description": "Weave Net creates a virtual network that connects Docker containers across multiple hosts and enables their automatic discovery",
                "org.opencontainers.image.revision": "6e3f8a1c7a0ae8c011f7e28e6e06e6164396d03e",
                "org.opencontainers.image.source": "https://github.com/weaveworks/weave",
                "org.opencontainers.image.title": "Weave Net",
                "org.opencontainers.image.url": "https://weave.works",
                "org.opencontainers.image.vendor": "Weaveworks",
                "org.opencontainers.image.description": "Weave Net creates a virtual network that connects Docker containers across multiple hosts and enables their automatic discovery",
                "org.opencontainers.image.revision": "6e3f8a1c7a0ae8c011f7e28e6e06e6164396d03e",
                "org.opencontainers.image.source": "https://github.com/weaveworks/weave",
                "org.opencontainers.image.title": "Weave Net",
                "org.opencontainers.image.url": "https://weave.works",
                "org.opencontainers.image.vendor": "Weaveworks",
```

**Pull request merged**
