### PR TITLE
feat(npm): support binarySource=install for pnpm

### PR DESCRIPTION
**Pull request by rarkins**
## Changes:

Refactors pnpm tool installation to support binarySource=install

## Context:

Part of #13683

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [x] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
@viceice fails with this permissions problem:

```
DEBUG: rawExec err (repository=renovate-reproductions/monosample, branch=renovate/typeorm-0.x)
       "err": {
         "killed": false,
         "code": 1,
         "signal": null,
         "cmd": "docker run --rm --name=renovate_node --label=renovate_child -v \"/tmp/renovate/repos/github/renovate-reproductions/monosample\":\"/tmp/renovate/repos/github/renovate-reproductions/monosample\" -v \"/tmp/renovate/cache\":\"/tmp/renovate/cache\" -e NPM_CONFIG_CACHE -e npm_config_store -e ARTIFACTORY_TOKEN -w \"/tmp/renovate/repos/github/renovate-reproductions/monosample\" docker.io/renovate/node bash -l -c \"install-tool pnpm 6.27.2 && pnpm install --recursive --lockfile-only --ignore-scripts --ignore-pnpmfile\"",
         "stdout": "Installing tool pnpm v6.27.2
/home/ubuntu/.npm-global/bin/pnpm -> /home/ubuntu/.npm-global/lib/node_modules/pnpm/bin/pnpm.cjs
/home/ubuntu/.npm-global/bin/pnpx -> /home/ubuntu/.npm-global/lib/node_modules/pnpm/bin/pnpx.cjs
+ pnpm@6.27.2
added 1 package in 1.578s
6.27.2
",
         "stderr": "npm WARN using --force I sure hope you know what you are doing.
rm: cannot remove '/root/.cache': Permission denied
",
         "message": "Command failed: docker run --rm --name=renovate_node --label=renovate_child -v \"/tmp/renovate/repos/github/renovate-reproductions/monosample\":\"/tmp/renovate/repos/github/renovate-reproductions/monosample\" -v \"/tmp/renovate/cache\":\"/tmp/renovate/cache\" -e NPM_CONFIG_CACHE -e npm_config_store -e ARTIFACTORY_TOKEN -w \"/tmp/renovate/repos/github/renovate-reproductions/monosample\" docker.io/renovate/node bash -l -c \"install-tool pnpm 6.27.2 && pnpm install --recursive --lockfile-only --ignore-scripts --ignore-pnpmfile\"
npm WARN using --force I sure hope you know what you are doing.
rm: cannot remove '/root/.cache': Permission denied
",
         "stack": "Error: Command failed: docker run --rm --name=renovate_node --label=renovate_child -v \"/tmp/renovate/repos/github/renovate-reproductions/monosample\":\"/tmp/renovate/repos/github/renovate-reproductions/monosample\" -v \"/tmp/renovate/cache\":\"/tmp/renovate/cache\" -e NPM_CONFIG_CACHE -e npm_config_store -e ARTIFACTORY_TOKEN -w \"/tmp/renovate/repos/github/renovate-reproductions/monosample\" docker.io/renovate/node bash -l -c \"install-tool pnpm 6.27.2 && pnpm install --recursive --lockfile-only --ignore-scripts --ignore-pnpmfile\"
npm WARN using --force I sure hope you know what you are doing.
rm: cannot remove '/root/.cache': Permission denied

    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:390:28)
    at ChildProcess.emit (node:domain:475:12)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)"
       }
```

**Comment by viceice** [comment]
🤦‍♂️

**Comment by viceice** [comment]
Will fix it

**Comment by rarkins** [comment]
Seems to work now with binarySource=docker

**Review by viceice — APPROVED** [review]

**Pull request merged**
