### PR TITLE
feat(emoji): Adds support for configuring emoji types

### LINKED ISSUE #3799: Replace emoji short codes with unicode representation
Emoji shortcodes don't render in all instances, specifically in emails. Additionally, they're mostly to help humans in typing emoji, without having to find the exact Unicode character.

I would like to replace the emoji shortcodes, with the actual Unicode code point. so `:vertical_traffic_light:` becomes `🚦`, `:recycle:` becomes `♻️`.

Thoughts?

### PR DESCRIPTION
**Pull request by JamieMagee**
Closes #3799

### CODE REVIEW

**Comment by rarkins** [comment]
Whether to emoji or not should be a global/platform-wide setting, right? So maybe we can set it once in lib/util/emoji.js during global worker init after parsing config and then we don't need to parse `config` to it ever call. What do you think?

**Comment by JamieMagee** [comment]
Yeah, a much better idea. I was (perhaps) not on top of my game on Friday night :smile:

**Comment by ViceIce** [comment]
Maybe we should open an issue for next major version.

There we can track config changes to flip, eg `unicodeEmoji=true`

**Comment by ViceIce** [comment]
@JamieMagee this pr needs deconflicting

**Comment by JamieMagee** [comment]
@ViceIce I've updated my branch with the latest master

**Review by viceice — COMMENTED** [review]
LGTM

**Review by viceice — APPROVED** [review]
LGTM 🙈

**Comment by ViceIce** [comment]
@rarkins can we merge this? should not harm, because feature is disabled by default.

**Pull request merged**
