### PR TITLE
fix(pr): don’t mention failing checks for automerge

### PR DESCRIPTION
**Pull request by rarkins**
## Changes

Removes logic which note that automerge is disabled due to failing checks.

## Context

I noticed that this is causing "flip flopping" of PR content everytime it's rebased, and therefore it's not worth it.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — DISMISSED** [review]
do we ensure a comment in this case?

**Comment by rarkins** [comment]
> do we ensure a comment in this case?

No, and I don't think that would work (would also cause noise). Should be obvious enough that Automerge doesn't work unless checks pass?

**Comment by viceice** [comment]
> > do we ensure a comment in this case?
> 
> No, and I don't think that would work (would also cause noise). Should be obvious enough that Automerge doesn't work unless checks pass?

ok, what about other branch protections?

**Comment by rarkins** [comment]
We don't warn about them today in the Pr but can maybe use comments in future

**Review by viceice — APPROVED** [review]

**Pull request merged**
