### PR TITLE
feat: add fontsource group preset

### PR DESCRIPTION
**Pull request by walkafwalka**
## Changes:

Adds Fontsource as a group preset.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added unit tests, or
- [ ] No new tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — COMMENTED** [review]
Isn't this a monorepo?

**Comment by HonkingGoose** [comment]
> Isn't this a monorepo?

Yes. Quote from the `fontsource/fontsource` repository README:

> An updating monorepo full of self-hostable Open Source fonts bundled into individual NPM packages!

See the README here: https://github.com/fontsource/fontsource#fontsource

**Comment by HonkingGoose** [comment]
Do we need to add `fontsource` to the list of monorepos in [lib/config/presets/internal/monorepo.ts](https://github.com/renovatebot/renovate/blob/main/lib/config/presets/internal/monorepo.ts)?

**Comment by viceice** [comment]
> Do we need to add `fontsource` to the list of monorepos in [lib/config/presets/internal/monorepo.ts](https://github.com/renovatebot/renovate/blob/main/lib/config/presets/internal/monorepo.ts)?

Yes 🙃

**Comment by HonkingGoose** [comment]
I'll go make a PR for that then, and close this PR.

**Comment by HonkingGoose** [comment]
Hi @walkafwalka, it turns out that we don't want to put the `fontsource` repository in a group but in a monorepo. Even though we don't use your pull request, I still want to thank you for opening it, and trying to make Renovate bot better! 😄 ❤️

**Comment by walkafwalka** [comment]
@viceice @HonkingGoose, I feel like I sneezed, and my PR was given feedback, corrected, implemented correctly, and released. The thanks are mine to give!

**Pull request closed without merging**
