### PR TITLE
feat(package-rules): warn for depName fallback

### PR DESCRIPTION
**Pull request by rarkins**
## Changes

Log warning when depName fallback is used in packageRules

## Documentation (please check one with an [x])

- [x] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
@nabeelsaabna do you want to first check the hosted app for these types of info messages which are our fault? Or merge, upgrade, and fix warnings as we find them?

**Review by viceice — APPROVED** [review]

**Comment by nabeelsaabna** [comment]
> @nabeelsaabna do you want to first check the hosted app for these types of info messages which are our fault? Or merge, upgrade, and fix warnings as we find them?

What do you mean by "which are our fault" ?
Isn't this a user configuration?

**Comment by rarkins** [comment]
> What do you mean by "which are our fault" ? Isn't this a user configuration?

There might be some built-in preset packageRules which cause a high volume of these messages, such as matchPackageNames=node

**Comment by viceice** [comment]
we should validate our internal presets and ensure there's no warning log call?

**Comment by rarkins** [comment]
> we should validate our internal presets and ensure there's no warning log call?

Not too easy to do - requires not just resolution but also data to test against. Also, _any_ rule with matchPackageNames could in theory trigger a warning with the right inputs. The question is whether it's common instead of convoluted use cases

**Comment by nabeelsaabna** [comment]
overall there are ~6% of repositories with the message `Use matchDepNames instead of matchPackageNames`
I checked few and it look manual user configurations

On a different note, maybe its time to print/capture shallow config

**Comment by rarkins** [comment]
6% seems pretty high for manual, can you share some examples (which aren't confidential) so I can understand better?

**Comment by nabeelsaabna** [comment]
3952 unique repositories in the last 7 days, will check for more details

**Comment by rarkins** [comment]
@nabeelsaabna I was wondering if any of our workarounds might hit this, e.g. the depName is 'node' or 'java' but the packageName is not

**Comment by rarkins** [comment]
Related: we are going to remove the depName fallback in v38, which will be released soon

**Comment by rarkins** [comment]
@nabeelsaabna should we merge and put it live?

**Comment by nabeelsaabna** [comment]
Yes.
we can do that

**Review by nabeelsaabna — APPROVED** [review]

**Pull request merged**
