### PR TITLE
fix: disable sourcemaps

### PR DESCRIPTION
**Pull request by viceice**
removes the map files (disabled generation)

### CODE REVIEW

**Comment by JamieMagee** [comment]
@ViceIce are sourcemaps not essential for debugging? I would be inclined to keep them in, or have a `tsconfig.dev.json` file.

**Comment by ViceIce** [comment]
@JamieMagee It's currently not required. see [here](https://medium.com/@dupski/debug-typescript-in-vs-code-without-compiling-using-ts-node-9d1f4f9a94a) for vscode debugging

**Comment by ViceIce** [comment]
ts-node enables sourcemaps automatically, see [here](https://github.com/TypeStrong/ts-node/blob/master/src/index.ts#L114-L124)

**Comment by rarkins** [comment]
I use VSCode for development but Chrome for debugging currently. Anyone here use VSCode for both already?

**Comment by ViceIce** [comment]
I am using vscode for debugging with following `.vscode/launch.json`

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "debug",
      "program": "${workspaceFolder}\\lib\\renovate.ts",
      "env": { "LOG_LEVEL": "debug" },
      "console": "externalTerminal",
      "internalConsoleOptions": "neverOpen",
      "runtimeArgs": ["--nolazy", "--preserve-symlinks", "-r", "ts-node/register"],
      "protocol": "inspector"
    }
  ]
}
```

**Comment by JamieMagee** [comment]
@ViceIce I had no idea that ts-node enabled that.

I'm using vscode for development and debugging as well. If we're all using vscode, should we add a `.vscode` folder to the repo with some good defaults to help new contributors to get up and running quickly?

**Comment by ViceIce** [comment]
an additional optimization for vscode: [Skipping uninteresting code](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_skipping-uninteresting-code-node-chrome)
``` json
"skipFiles": [
     "<node_internals>/**/*.js"
   ]
```

**Pull request merged**
