### PR TITLE
feat(internal): cached datasource lookups

### PR DESCRIPTION
**Pull request by rarkins**
This PR simplifies the `cdnjs` datasource while abstracting away the task of caching. Also removes unnecessary getDigest.

I took away some of the "safety" and null checks because I think this datasource should throw a DatasourceError for all errors except 404.

The important thing here is abstracting away the caching - I want to add this to all datasources if possible.

### CODE REVIEW

**Comment by viceice** [comment]
Have some improvements for types, will do them later, currently on mobile only

**Review by viceice — DISMISSED** [review]

**Comment by rarkins** [comment]
I split some of the work into #5871

**Review by viceice — DISMISSED** [review]
Should have the cache a default timeout?

**Comment by rarkins** [comment]
> Should have the cache a default timeout?

yes, I'll add. Doing some more refactoring

**Comment by viceice** [comment]
I added some code docu, so ide users can see it and it would hopefully help them to use it.

**Review by viceice — APPROVED** [review]
See my commit for changes.

JsDoc types can't be linked: microsoft/TypeScript#35524

**Pull request merged**
