### PR TITLE
feat(datasource/crate): add sparse registry support

### PR DESCRIPTION
**Pull request by samrogerson**
## Changes

Implements support for Cargo [sparse registries](https://rust-lang.github.io/rfcs/2789-sparse-index.html).

Sparse registry metadata requests are made over http, so we can make use of `hostRules.matchHost` to provide credentials to private repositories.

When working with JFrog Artifactory w/ anonymous login disabled, this requires Cargo nightly for `-Z registry-auth` (see [rust/rfc-3139](https://rust-lang.github.io/rfcs/3139-cargo-alternative-registry-auth.html)) when fetching `index/config.json`.

## Context

Cargo supports sparse registries as of 1.68, released on March 9th.

See also,

- https://github.com/renovatebot/renovate/discussions/18872

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [x] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by rarkins** [comment]
@rbtcollins @Turbo87 could you review?

**Comment by Turbo87** [comment]
currently on vacation, but I might be able to take a look next week.

**Comment by rbtcollins** [comment]
I've put it on my todo, not sure how long it will take to get to it, please don't block on me.

**Comment by samrogerson** [comment]
looking at the failed tests

**Comment by rarkins** [comment]
Here's the coverage issue:
image

**Comment by samrogerson** [comment]
The `isSparseRegistry` has a `new URL(...)` which throws so we never hit the capture case later on.

I can't run tests locally (jest workers get killed from timeout) so took me a moment or two to figure it out.

**Comment by viceice** [comment]
> The `isSparseRegistry` has a `new URL(...)` which throws so we never hit the capture case later on.
> 
> I can't run tests locally (jest workers get killed from timeout) so took me a moment or two to figure it out.

pass the relative path to datasource to jest. so you only run those tests. then check `coverage/index.html` for coverage issues inside that datasource.

**Comment by samrogerson** [comment]
I've found a transient issue, locally, with fetching `index/config.json`. Looking into it

**Review by Turbo87 — APPROVED** [review]
LGTM on first glance, but I don't have much experience with 3rd party registries, so take this with a grain of salt 😉

**Review by rarkins — APPROVED** [review]

**Pull request merged**
