### PR TITLE
fix: renovate not creating PRs for some python dependencies

### LINKED ISSUE #3418: renovatebot blind to new releases of some python module dependencies
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**

Never sends a PR to update [this line](https://github.com/mesosphere/dcos-commons/blob/7dc1a18/frozen_requirements.txt#L91) even though it does send PRs for plenty of other dependencies in this file ([example](https://github.com/mesosphere/dcos-commons/pull/2984), and this version is so old that it's not even available on PyPI anymore.

**Did you see anything helpful in debug logs?**
It seems that it does not see any releases for this dependency on PyPI. The log contains:
```
{ "depName": "pygobject", "currentValue": "==3.26.1", "lineNumber": 90, "datasource": "pypi", "updates": [], "warnings": [], "sourceUrl": null, "homepage": "https://pygobject.readthedocs.io", "releases": [] }, 
```

**To Reproduce**

1.  Create repository with the aforementioned line in `requirements.txt`
2.  Configure renovatebot

**Expected behavior**
PRs should be sent to update the aforementioned dependency.

**Additional context**
Could the root cause be that the letter case does not match? The module name is in camel case on https://pypi.org/project/PyGObject/#history

### PR DESCRIPTION
**Pull request by rishabh1403**
If the dependency version is missing in list of releases fetched, renovate wasn't creating a PR.

Solution-
Fixed the current version even if it's not in list of releases
Closes #3418

### CODE REVIEW

**Comment by rarkins** [comment]
How different is `isSingleVersion` and `isVersion` in each of our version schemes? I want to make sure we don't accidentally change the logic for some other use cases.

**Comment by rishabh1403** [comment]
> How different is `isSingleVersion` and `isVersion` in each of our version schemes? I want to make sure we don't accidentally change the logic for some other use cases.

`isSingleVersion` is internally checking `isVersion` with an `or` operator, so if `isVersion` is true, the condition will still pass, making it consistent

```js
const isSingleVersion = constraint =>
  isVersion(constraint) ||
  (constraint.startsWith('==') && isVersion(constraint.substring(2).trim()));
```

and at other places `isSingleVersion` is aliased to `isVersion` itself

```js
module.exports = {
  equals,
  getMajor,
  getMinor,
  getPatch,
  isCompatible: isVersion,
  isGreaterThan,
  isSingleVersion: isVersion,
  isStable,
  isValid: isVersion,
  isVersion,
  matches,
  maxSatisfyingVersion,
  minSatisfyingVersion: maxSatisfyingVersion,
  getNewValue,
  sortVersions: compare,
};
```
@rarkins

**Review by rarkins — CHANGES_REQUESTED** [review]
@rishabh1403 I refactored it a little, now needs coverage updated

**Comment by rishabh1403** [comment]
@rarkins Please review

**Pull request merged**
