### PR TITLE
refactor(composer): Obtain COMPOSER_AUTH only from "hostRules"

### PR DESCRIPTION
**Pull request by zharinov**
Ref: #6932, #5653, #6907

Potentially destructive PR. It works for github `token` auth. Though we have at least one report of successful execution, I don't know yet how to test with `http-basic` myself.

### CODE REVIEW

**Comment by maksimru** [comment]
@zharinov it seems breaking PR
completely stopped to work with composer private packages, works perfect with older version of renovatebot
```json
"artifactErrors": [
         {
           "lockFile": "composer.lock",
           "stderr": "Command failed: composer update zendframework/zend-diactoros --with-dependencies --ignore-platform-reqs --no-ansi --no-interaction --no-scripts --no-autoloader\nLoading composer repositories with package information\n\n                                                                                                                        \n  [Composer\\Downloader\\TransportException]                                                                              \n  The 'https://zzzz.yyyy.com/artifactory/api/composer/php-local/packages.json' URL required authentication.  \n  You must be using the interactive console to authenticate                                                             \n                                                                                                                        \n\nupdate [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...\n\n"
         }
]
```

**Comment by zharinov** [comment]
@maksimru Thanks for reporting. 

Can you please tell the key by which you identify the host? E.g.:
`{ "hostName": "xxx", "username": ..., "password": ... }`, or
`{ "domainName": "xxx", "username": ..., "password": ... }`, etc.

**Comment by zharinov** [comment]
After this PR, we support only these two, now I think we need add more with hotfix

**Comment by maksimru** [comment]
@zharinov 
```
{
    "hostType": "packagist",
    "baseUrl": "https://artifactory.yyyyyyy.com/artifactory/api/composer/",
    "username": "zzzzz",
    "password": "xxxx"
 }
```

**Comment by zharinov** [comment]
Ok, now I see. For quickest possible fix, `"hostName": "artifactory.yyyyyyy.com"` should help. For less quick fix, you can just wait for #7084 being merged.

**Pull request merged**
