### PR TITLE
fix(config)!: Use `depNameSanitized` in branch name for vulnerability alerts

### PR DESCRIPTION
**Pull request by takac**
## Changes

Use the santaised dep name for branch creation, this ensure that the branch does not have special characters which could cause issues with other services.

`go-golang-org/x/net-vulnerability` should be `go-golang-org-x-net-vulnerability`

## Context

We discovered this issue after the branch name was picked up by a downstream build and caused an error due to the unexpected `/`.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — DISMISSED** [review]

**Comment by rarkins** [comment]
This looks like the right thing to do, but the question is about disruption to users. Any existing Remediation PR with a special character will be autoclosed and recreated.

**Review by viceice — COMMENTED** [review]
that's true. 🤔 make it a feature bump instead of a fix?

**Comment by rarkins** [comment]
I don't think that part matters. I do consider it a fix!

**Comment by viceice** [comment]
sure, let's do a fix with major bump

**Review by rarkins — CHANGES_REQUESTED** [review]
Hold for next major release

**Review by rarkins — APPROVED** [review]

**Review by viceice — APPROVED** [review]

**Pull request merged**
