### PR TITLE
feat: Track `ExternalHostError` instances

### PR DESCRIPTION
**Pull request by zharinov**
## Changes

During repository processing, all unhandled `ExternalHostError` will be collected and logged with `debug` level.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by viceice — DISMISSED** [review]

**Review by rarkins — COMMENTED** [review]
So this only dismisses the timer of the host error makes it up to the repository a key reason?

**Review by rarkins — COMMENTED** [review]
What if there's multiple errors?

**Comment by zharinov** [comment]
> What if there's multiple errors?

We'll see which unhandled errors are reasonable to be unhandled, and maybe also find the one that's unhandled by mistake.

**Comment by zharinov** [comment]
Though, I think we can filter out some cases already

**Review by viceice — DISMISSED** [review]

**Comment by zharinov** [comment]
Good point, fixing it

**Review by viceice — DISMISSED** [review]

**Comment by zharinov** [comment]
Need to change the approach: logger has repository-specific context that can be changed when timeout is fire. Instead, we need to aggregate errors in the `WeakSet` and flush them on repo init/finalize

**Review by viceice — DISMISSED** [review]

**Comment by rarkins** [comment]
I ran against a large repo which had had npmjs timeouts in the past: https://github.com/renovate-reproductions/silverback-mono

I also added this host rule in my config.js:
```
{
    matchHost: 'https://registry.npmjs.org',
    timeout: 100
  }
```

It triggers a lot of external host errors as anticipated, including aggregate errors. But it completed without any pending errors.

**Comment by zharinov** [comment]
Maybe these my tracking PRs are useless then 🤷‍♂️

**Pull request closed without merging**
