### PR TITLE
feat: Allow gomod manager to set git ssh config for projects that use it.

### PR DESCRIPTION
**Pull request by MovieStoreGuy**
## Changes:

This PR allows for the gomod manager to set git config to connect via ssh if that authType is set.
This means that private repo access doesn't require tokens to be stored within config.

## Context:

A lot of the repos I work on are private and hosted on bitbucket cloud which gomod has not current support for providing access to those private repos beyond the aspect of mutating the environment that renovate runs in.

This change allows for renovate to make those changes to git config to allow for access to be made via config instead of pre script hack.

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [x] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Comment by viceice** [comment]
Blocked by #10750

**Comment by MovieStoreGuy** [comment]
Hmm, Not sure how this is blocked by the change @viceice? 

Would you mind explaining?

**Comment by viceice** [comment]
#10750 is nearly done and will conflicting this changes, so please wait until we've done the other pr.

**Comment by viceice** [comment]
This changes only work for self-hosted renovate, and the other will work on hosted github app, so we prefer the other pr before this one.

Next time please open a discussion before open a feature pr, so we can discuss things and you don't have to refactor /redo too much things later.

**Comment by MovieStoreGuy** [comment]
I haven't actively worked on this for some time, I am going to close it.

**Pull request closed without merging**
