### PR TITLE
feat: sign npm package

### LINKED ISSUE #19170: Sign our own npm package
### What would you like Renovate to be able to do?

We should look into signing our packages. It's probably a good idea to figure out signing our npm package first to learn how it all works. We can expand signing to our other projects/build artifacts later.

### If you have any ideas on how this should be implemented, please tell us here.

GitHub has a blog [^blog] about using Sigstore on GitHub Actions to sign a build. The key benefit seems to be that with Sigstore you don't have to manage a private key, they call this "keyless signing". It sounds like this all makes signing easier to setup and maintain. 😄 

The Sigstore project is now released under General Availability, and GitHub says it's stable to start using now.

I've copy/pasted the most relevant part of the blog below for reference:

> **Sigstore and GitHub Actions, today**
> 
> The first thing people do to secure their builds is to sign them, so you can detect if it’s been tampered with between when the build finished and when you’re about to run it. This often requires managing a private key, including generating it correctly, keeping it a secret, and rotating it over time. At best this is a hassle, and at worst it’s a roadblock for folks who don’t have experience in this area. As a result, builds aren’t signed nearly as often as they should be.
> 
> When you’re building in a cloud CI/CD provider that [supports OIDC tokens, like GitHub Actions](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect), Sigstore can generate a signing certificate for your build _without_ having to maintain a private key. Sigstore calls this [keyless signing](https://github.com/sigstore/cosign/blob/main/KEYLESS.md), and it’s a fantastic example of lowering the barrier to entry so more projects can sign their builds. In fact, this keyless signing is already in use for [Kubernetes](https://kubernetes.io/blog/2022/05/03/kubernetes-1-24-release-announcement/#signing-release-artifacts) as well as [CPython](https://www.python.org/download/sigstore/) releases.
> 
> To illustrate how to do this, last year we wrote about [how to use Sigstore’s cosign to sign container images built in GitHub Actions](https://github.blog/2021-12-06-safeguard-container-signing-capability-actions/). While cosign sign assumes your build is a container image, you can also use cosign sign-blob on any type of build output.
> 
> These are all things you could already do with Sigstore on GitHub Actions, but general availability is an exciting milestone in terms of maturity: the components have all reached a 1.0+ release, the APIs are stable, and the public servers now have a SLO and a 24/7 on-call rotation. This release is a collaboration across several organizations, and GitHub has directly supported it by contributing to both the development of the Sigstore code as well as the on-call rotation for the servers.

I'll let you maintainers figure out how this all works, and let you set up signing. 😉 

[^blog]: https://github.blog/2022-10-25-why-were-excited-about-the-sigstore-general-availability/

### Is this a feature you are interested in implementing yourself?

No

### PR DESCRIPTION
**Pull request by JamieMagee**
## Changes

Sign Renovate packages when published

## Context

https://github.blog/2023-04-19-introducing-npm-package-provenance/
- closes #19170

## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [x] No documentation update is required

## How I've tested my work (please select one)

I have verified these changes via:

- [x] Code inspection only, or
- [ ] Newly added/modified unit tests, or
- [ ] No unit tests but ran on a real repository, or
- [ ] Both unit tests + ran on a real repository

### CODE REVIEW

**Review by secustor — APPROVED** [review]

**Review by viceice — APPROVED** [review]
are you sure this works with semantic release and will not blocked by npmjs?

**Comment by JamieMagee** [comment]
> are you sure this works with semantic release and will not blocked by npmjs?

semantic release uses npm directly to publish[^1] so it should work. And this feature is in public preview, so no configuration required. I just published [`@jamiemagee/provenance`][1] from [GitHub actions][2] with no configuration.

[^1]: https://github.com/semantic-release/npm/blob/9aa8c5e7874e4d550da395ffca4a4626dd001d2a/lib/publish.js#L23-L27

[1]: https://www.npmjs.com/package/@jamiemagee/provenance
[2]: https://github.com/JamieMagee/jamie-provenance/actions/runs/4746162226/jobs/8429437626

**Comment by JamieMagee** [comment]
I'm going ahead with the merge, and will closely monitor the package publish.

**Comment by travi** [comment]
excited to see you adopting this so quickly. i can confirm that setting either in the `.npmrc`, like you have, or setting in `publishConfig` within the `package.json` both work as intended with semantic-release

**Comment by rarkins** [comment]
The publish failed:

```
npm notice 
npm notice Publishing to https://registry.npmjs.org/ with tag latest and default access
npm ERR! code EUSAGE
npm ERR! Automatic provenance generation not supported outside of GitHub Actions

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2023-04-19T19_35_38_672Z-debug-0.log
Error: Process completed with exit code 1.
```

**Comment by JamieMagee** [comment]
@rarkins fixed in #21612 already

**Pull request merged**
